import { assertAuditChain, assertEventSequence, canonicalJson, locationOracle } from "../oracles/index.mjs";
import {
  audit, boot, byId, caseResult, createRequest, defineCase, expectError, identity, issueLowGrant,
  noSecrets, requireStatus, resources, snapshot, waitRisk, waitSnapshot,
} from "./helpers.mjs";

const c01 = defineCase("C-01", "AS-F-WORK-EVENT-AUDIT", "Create due examples of every V1 Work kind, observe claim and lease fields, drain success and terminal failures, and inspect retained records after all production roles restart.", "Work states, attempts, lease ownership and terminal flags obey the published shape, attempts increase monotonically, terminal records remain observable and drain decisions use terminal rather than deleting history.", ["all V1 Work kinds", "Workers", "dispatcher", "verification snapshot"], async (ctx) => {
  const family = ctx.fixtures.workEventAudit(); const { api } = await boot(ctx, { family }); const flow = await requestAndGrant(ctx, api.baseUrl, family, "work", { requestedTtlSeconds: 5 }); await ctx.sleep(5_200); await ctx.observeLocation(api.baseUrl, family.locationBody(2), { key: ctx.key("location") }); await ctx.revokeDevice(api.baseUrl, family.device.deviceId, { expectedEpoch: 0, reason: "work fixture" }, { key: ctx.key("revoke") }); const before = await snapshot(ctx, api.baseUrl); ctx.ok(before.work.some(({ state, terminal }) => state === "PENDING" && !terminal), "pending Work visible"); const receiver = await ctx.receiver(); const workers = [await ctx.startWorker(), await ctx.startWorker()]; const dispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url }); const drained = await waitSnapshot(ctx, api.baseUrl, (state) => state.work.every(({ terminal }) => terminal) ? state : undefined, { label: "V1 Work drain", timeoutMs: 300_000, processes: [...workers, dispatcher] }); for (const item of drained.work) { ctx.ok(["PENDING", "LEASED", "SUCCEEDED", "FAILED", "CANCELLED"].includes(item.state), `${item.workId} state`); ctx.ok(Number.isSafeInteger(item.attempt) && item.attempt >= 0, `${item.workId} attempt`); ctx.equal(item.terminal, ["SUCCEEDED", "FAILED", "CANCELLED"].includes(item.state), `${item.workId} terminal`); ctx.equal(item.state === "LEASED", item.leaseOwner !== null && item.leaseToken !== null && item.leaseExpiresAt !== null, `${item.workId} lease fields`); } ctx.ok(drained.work.some(({ aggregateId }) => aggregateId === flow.accessRequestId), "Risk Work retained"); return caseResult(ctx, { workKinds: [...new Set(drained.work.map(({ kind }) => kind))], retained: drained.work.length });
});

const c02 = defineCase("C-02", "AS-F-WORK-EVENT-AUDIT", "Hold a due Risk Work immediately after the published worker.claimed barrier, SIGKILL its owner, wait for lease expiry and let a replacement Worker reclaim it.", "Replacement observes the same Work identity at attempt plus one, the killed owner has no open transaction or stale commit, and one immutable RiskDecision, Audit and Event effect is produced.", ["worker.claimed barrier", "SIGKILL", "lease expiry", "replacement Worker"], async (ctx) => {
  const family = ctx.fixtures.workEventAudit(); const { api } = await boot(ctx, { family }); const created = await createRequest(ctx, api.baseUrl, family, "claimed"); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && point === "worker.claimed" }); const owner = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const claim = await barrier.waitFor(({ json }) => json.point === "worker.claimed", { processes: [owner] }); const claimed = await snapshot(ctx, api.baseUrl); const first = claimed.work.find(({ workId }) => workId === claim.json.workId); ctx.ok(first && first.state === "LEASED", "claimed Work persisted"); await ctx.kill(owner); await ctx.sleep(3_300); const replacement = await ctx.startWorker(); const done = await waitSnapshot(ctx, api.baseUrl, (state) => state.work.find(({ workId }) => workId === claim.json.workId)?.terminal ? state : undefined, { label: "claimed Work replacement", processes: [replacement] }); hold = false; barrier.releaseAll(); const final = await snapshot(ctx, api.baseUrl); const recovered = final.work.find(({ workId }) => workId === claim.json.workId); ctx.ok(recovered.attempt >= first.attempt + 1, "attempt incremented"); ctx.equal(resources(final, "riskDecisions").filter(({ accessRequestId }) => accessRequestId === created.accessRequestId).length, 1, "one RiskDecision", { hardCapIds: ["WORK_FENCING", "TRANSACTIONAL_EVIDENCE"] }); audit(ctx, final); return caseResult(ctx, { workId: claim.json.workId, firstAttempt: first.attempt, finalAttempt: recovered.attempt });
});

const c03 = defineCase("C-03", "AS-F-WORK-EVENT-AUDIT", "Hold Risk Work at the published worker.before-effect barrier, SIGKILL the Worker before any business effect, and start a replacement after lease expiry.", "The pre-effect snapshot has no partial Decision, Audit or Event for the request; replacement performs the complete transition once and terminal Work, authority and evidence agree.", ["worker.before-effect barrier", "SIGKILL", "verification snapshot", "replacement Worker"], async (ctx) => {
  const family = ctx.fixtures.workEventAudit(); const { api } = await boot(ctx, { family }); const created = await createRequest(ctx, api.baseUrl, family, "before-effect"); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && point === "worker.before-effect" }); const owner = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const entry = await barrier.waitFor(({ json }) => json.point === "worker.before-effect", { processes: [owner] }); const before = await snapshot(ctx, api.baseUrl); ctx.equal(resources(before, "riskDecisions").filter(({ accessRequestId }) => accessRequestId === created.accessRequestId).length, 0, "no partial Decision"); await ctx.kill(owner); await ctx.sleep(3_300); const replacement = await ctx.startWorker(); const completed = await waitSnapshot(ctx, api.baseUrl, (state) => resources(state, "riskDecisions").filter(({ accessRequestId }) => accessRequestId === created.accessRequestId).length === 1 && state.work.find(({ workId }) => workId === entry.json.workId)?.terminal ? state : undefined, { label: "before-effect recovery", processes: [replacement] }); hold = false; barrier.releaseAll(); ctx.equal(resources(completed, "riskDecisions").filter(({ accessRequestId }) => accessRequestId === created.accessRequestId).length, 1, "one complete Decision", { hardCapIds: ["WORK_FENCING"] }); audit(ctx, completed); return caseResult(ctx, { workId: entry.json.workId, decisionId: resources(completed, "riskDecisions").find(({ accessRequestId }) => accessRequestId === created.accessRequestId).riskDecisionId });
});

const c04 = defineCase("C-04", "AS-F-WORK-EVENT-AUDIT", "Pause Worker A after a persisted claim until its lease expires, let Worker B reclaim and complete, then release A with its stale fencing token.", "Only B's attempt and result remain authoritative; A cannot write terminal state or duplicate Decision, Audit, Event or other security effect after its lease expires.", ["worker.claimed barrier", "lease fencing", "two Workers", "verification snapshot"], async (ctx) => {
  const family = ctx.fixtures.workEventAudit(); const { api } = await boot(ctx, { family }); const created = await createRequest(ctx, api.baseUrl, family, "fencing"); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && point === "worker.claimed" }); const stale = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const entry = await barrier.waitFor(({ json }) => json.point === "worker.claimed", { processes: [stale] }); const leased = await snapshot(ctx, api.baseUrl); const first = leased.work.find(({ workId }) => workId === entry.json.workId); await ctx.sleep(3_300); const winner = await ctx.startWorker(); const completed = await waitSnapshot(ctx, api.baseUrl, (state) => state.work.find(({ workId }) => workId === entry.json.workId)?.terminal ? state : undefined, { label: "lease reclaim", processes: [winner] }); hold = false; barrier.releaseAll(); await ctx.sleep(500); const final = await snapshot(ctx, api.baseUrl); ctx.equal(final.work.find(({ workId }) => workId === entry.json.workId), completed.work.find(({ workId }) => workId === entry.json.workId), "stale owner cannot rewrite Work", { hardCapIds: ["WORK_FENCING"] }); ctx.ok(final.work.find(({ workId }) => workId === entry.json.workId).attempt >= first.attempt + 1, "replacement attempt increments"); ctx.equal(resources(final, "riskDecisions").filter(({ accessRequestId }) => accessRequestId === created.accessRequestId).length, 1, "one Decision effect"); ctx.equal(canonicalJson(final.events), canonicalJson(completed.events), "stale owner no Event"); return caseResult(ctx, { workId: entry.json.workId, winningAttempt: final.work.find(({ workId }) => workId === entry.json.workId).attempt });
});

const c05 = defineCase("C-05", "AS-F-LOCATION", "Trigger a bounded-late projection rebuild, kill Workers at both published claim and before-effect barriers, and replay with multiple replacements.", "Every observation is retained, terminal Work converges and the final DeviceLocation equals the offline ordering oracle with no repeated risk flag or missing sequence.", ["location HTTP", "worker barriers", "SIGKILL", "location oracle"], async (ctx) => {
  const family = ctx.fixtures.location(); const { api } = await boot(ctx, { family }); const bodies = [family.locationBody(4, { observedAt: family.at({ minutes: 1 }) }), family.locationBody(2, { observedAt: family.at({ minutes: -5 }) }), family.locationBody(3, { observedAt: family.at({ minutes: -1 }) })]; for (const [index, body] of bodies.entries()) requireStatus(ctx, await ctx.observeLocation(api.baseUrl, body, { key: ctx.key(`late:${index}`) }), 200, `location ${index}`); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && ["worker.claimed", "worker.before-effect"].includes(point) }); const first = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); await barrier.waitFor(({ json }) => json.point === "worker.claimed", { processes: [first] }); await ctx.kill(first); await ctx.sleep(3_300); const second = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); await barrier.waitFor(({ json }) => json.point === "worker.before-effect", { processes: [second] }); await ctx.kill(second); await ctx.sleep(3_300); hold = false; barrier.releaseAll(); const replacements = [await ctx.startWorker(), await ctx.startWorker()]; const state = await waitSnapshot(ctx, api.baseUrl, (value) => value.work.filter(({ kind }) => kind === "LOCATION_REPLAY").every(({ terminal }) => terminal) ? value : undefined, { label: "location recovery", processes: replacements }); const observations = resources(state, "locationObservations").filter(({ deviceId }) => deviceId === family.device.deviceId); const expected = locationOracle(observations, { maxTravelKph: family.riskModelRevision.maxTravelKph }); const actual = byId(state, "deviceLocations", "deviceId", family.device.deviceId); for (const key of ["lastSequence", "watermarkObservedAt", "longitude", "latitude", "region", "riskFlags"]) ctx.equal(actual[key], expected.projection[key], `recovered ${key}`); ctx.equal(new Set(actual.riskFlags).size, actual.riskFlags.length, "no duplicate flags"); return caseResult(ctx, { observations: observations.length, projectionRevision: actual.revision });
});

const c06 = defineCase("C-06", "AS-F-WORK-EVENT-AUDIT", "Commit a revocation fence for an active grant, kill the propagation Worker after claim, verify immediate API fail-closed behavior, then drain propagation and expiry Work with replacements.", "Authority becomes inactive at the fence transaction rather than Worker completion; replacement Workers converge dependent state, preserve terminal history and never resurrect obsolete authority.", ["grant lifecycle", "revocation Work", "worker.claimed barrier", "two APIs"], async (ctx) => {
  const family = ctx.fixtures.workEventAudit(); const { apis } = await boot(ctx, { family, apiCount: 2 }); const flow = await requestAndGrant(ctx, apis[0].baseUrl, family, "recovery"); const revoke = await ctx.revokePrincipal(apis[0].baseUrl, family.requester.principalId, { expectedEpoch: 0, reason: "security fence" }, { key: ctx.key("principal-revoke") }); requireStatus(ctx, revoke, 200, "principal revoke"); const immediate = await ctx.checkGrant(apis[1].baseUrl, flow.grantId); requireStatus(ctx, immediate, 200, "post-commit check"); ctx.equal(immediate.json.active, false, "commit immediately fail closed", { hardCapIds: ["REVOCATION_FAIL_CLOSED"] }); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && point === "worker.claimed" }); const owner = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const claim = await barrier.waitFor(({ json }) => json.point === "worker.claimed", { processes: [owner] }); await ctx.kill(owner); await ctx.sleep(3_300); hold = false; const replacements = [await ctx.startWorker(), await ctx.startWorker()]; barrier.releaseAll(); const state = await waitSnapshot(ctx, apis[0].baseUrl, (value) => value.work.find(({ workId }) => workId === claim.json.workId)?.terminal && value.work.filter(({ terminal }) => !terminal).length === 0 ? value : undefined, { label: "revocation drain", timeoutMs: 300_000, processes: replacements }); ctx.ok(resources(state, "accessGrants").filter(({ principalId }) => principalId === family.requester.principalId).every(({ state: value }) => value !== "ACTIVE"), "dependent grants converged"); return caseResult(ctx, { grantId: flow.grantId, recoveredWorkId: claim.json.workId });
});

const c07 = defineCase("C-07", "AS-F-WORK-EVENT-AUDIT", "Let a receiver persist one complete webhook response, hold the dispatcher at response-received, SIGKILL it, return failures and disconnects, then allow a replacement acknowledgement.", "Every retry preserves the exact event identity, semantic body and aggregate order with bounded attempts; no second logical Event or raw token is emitted after an unknown acknowledgement.", ["webhook receiver", "dispatcher.response-received barrier", "SIGKILL", "replacement dispatcher"], async (ctx) => {
  const family = ctx.fixtures.workEventAudit(); const { api } = await boot(ctx, { family }); const created = await ctx.createSession(api.baseUrl, family.sessionBody(), { key: ctx.key("event-source") }); requireStatus(ctx, created, 200, "event-producing mutation"); let receiverMode = "success"; const receiver = await ctx.receiver({ behavior: () => receiverMode === "success" ? { status: 204 } : receiverMode === "failure" ? { status: 500 } : { disconnect: true } }); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "dispatcher" && point === "dispatcher.response-received" }); const dispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url, env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const barrierEntry = await barrier.waitFor(({ json }) => json.point === "dispatcher.response-received", { processes: [dispatcher] }); const first = await ctx.waitFor(() => receiver.ledger[0], { label: "first webhook", processes: [dispatcher] }); await ctx.kill(dispatcher); receiverMode = "failure"; const failing = await ctx.startDispatcher({ webhookUrl: receiver.url }); await ctx.waitFor(() => receiver.ledger.length >= 2 ? receiver.ledger[1] : undefined, { label: "500 webhook retry", processes: [failing] }); await ctx.stop(failing); receiverMode = "disconnect"; const disconnecting = await ctx.startDispatcher({ webhookUrl: receiver.url }); await ctx.waitFor(() => receiver.ledger.length >= 3 ? receiver.ledger[2] : undefined, { label: "disconnected webhook retry", processes: [disconnecting] }); await ctx.kill(disconnecting); receiverMode = "success"; hold = false; barrier.releaseAll(); const replacement = await ctx.startDispatcher({ webhookUrl: receiver.url }); const delivered = await ctx.waitFor(() => receiver.ledger.find((entry) => entry.acknowledged && entry.attempt > first.attempt), { label: "replacement webhook ACK", timeoutMs: 120_000, processes: [replacement] }); ctx.equal(delivered.raw, first.raw, "webhook body stable", { hardCapIds: ["TRANSACTIONAL_EVIDENCE"] }); const eventId = findValue(delivered.json, "eventId"); ctx.equal(typeof eventId, "string", "webhook event identity"); const state = await snapshot(ctx, api.baseUrl); ctx.equal(state.events.filter(({ eventId: id }) => id === eventId).length, 1, "one logical Event"); noSecrets(ctx, { headers: delivered.headers, body: delivered.json }, [created.json.refreshToken]); return caseResult(ctx, { eventId, attempts: receiver.ledger.length, workId: barrierEntry.json.workId });
});

const c08 = defineCase("C-08", "AS-F-WORK-EVENT-AUDIT", "Execute concurrent successful security mutations and deterministic rollback failures for multiple tenants, then kill and replace a dispatcher after response receipt.", "Business state, tenant Audit entries, Domain Events and Work share transaction outcomes; failed mutations append none, Audit and Event sequences are contiguous, ordering survives delivery recovery and all evidence is secret-free.", ["two APIs", "Audit oracle", "Event ordering", "dispatcher barrier"], async (ctx) => {
  const family = ctx.fixtures.workEventAudit(); const { apis } = await boot(ctx, { family, apiCount: 2 }); const before = await snapshot(ctx, apis[0].baseUrl); const successes = await Promise.all([ctx.createSession(apis[0].baseUrl, family.sessionBody(), { key: ctx.key("session-a") }), ctx.createSession(apis[1].baseUrl, family.sessionBody(), { key: ctx.key("session-b") }), ctx.publishPolicy(apis[0].baseUrl, family.policyBundle.policyBundleId, { expectedRevision: 1, effectiveFrom: family.at({ minutes: 1 }), rules: family.policyRules(2) }, { key: ctx.key("policy") })]); successes.forEach((response, index) => requireStatus(ctx, response, 200, `success ${index}`)); const committed = await snapshot(ctx, apis[0].baseUrl); const receiver = await ctx.receiver(); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "dispatcher" && point === "dispatcher.response-received" }); const dispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url, env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); await barrier.waitFor(({ json }) => json.point === "dispatcher.response-received", { processes: [dispatcher] }); await ctx.kill(dispatcher); hold = false; barrier.releaseAll(); const replacementDispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url }); await ctx.waitFor(() => receiver.ledger.some(({ acknowledged }) => acknowledged) ? receiver.ledger : undefined, { label: "transactional Event redelivery", processes: [replacementDispatcher] }); const failed = await ctx.publishPolicy(apis[1].baseUrl, family.policyBundle.policyBundleId, { expectedRevision: 1, effectiveFrom: family.at({ minutes: 2 }), rules: family.policyRules(3) }, { key: ctx.key("stale-policy") }); ctx.equal(failed.status, 409, "stale policy rejected"); const afterFailure = await snapshot(ctx, apis[1].baseUrl); ctx.equal(canonicalJson(afterFailure.events), canonicalJson(committed.events), "rollback appends no Event"); ctx.equal(canonicalJson(resources(afterFailure, "auditEntries")), canonicalJson(resources(committed, "auditEntries")), "rollback appends no Audit"); ctx.assert("Audit chains", () => assertAuditChain(resources(afterFailure, "auditEntries"))); ctx.assert("Event sequences", () => assertEventSequence(afterFailure.events)); noSecrets(ctx, afterFailure, successes.map(({ json }) => json?.refreshToken)); ctx.ok(afterFailure.events.length >= before.events.length, "successful transitions retain Events"); return caseResult(ctx, { auditEntries: resources(afterFailure, "auditEntries").length, events: afterFailure.events.length });
});

async function requestAndGrant(ctx, baseUrl, family, label, requestOverrides = {}) { const created = await createRequest(ctx, baseUrl, family, label, requestOverrides); const worker = await ctx.startWorker(); const state = await waitRisk(ctx, baseUrl, created.accessRequestId, [worker]); const grant = await issueLowGrant(ctx, baseUrl, created.accessRequestId, state, { key: ctx.key(`${label}:grant`) }); return { ...created, ...grant }; }
function findValue(value, key) { if (!value || typeof value !== "object") return undefined; if (Object.hasOwn(value, key)) return value[key]; for (const child of Object.values(value)) { const found = findValue(child, key); if (found !== undefined) return found; } }

export const C_CASES = Object.freeze([c01, c02, c03, c04, c05, c06, c07, c08]);
