import assert from "node:assert/strict";
import { createWriteStream } from "node:fs";
import { once } from "node:events";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { CaseExcluded, CaseFailure } from "../lib/execution.mjs";
import { assertEventSequence, assertManifest, assertSorted, canonicalJson, csvBytes, jsonlBytes, manifestBytes, percentile, planShards, rangeOracle, sectionOracle, sha256 } from "../oracles/index.mjs";

const builds = new Map();
export const EXPORT_KEYS = Object.freeze(["exportId", "subjectId", "scope", "format", "datasetRevision", "state", "object", "retentionUntil", "createdAt", "readyAt", "sequence"]);
export const SHARDED_EXPORT_KEYS = Object.freeze([...EXPORT_KEYS, "manifest", "shards"]);
export const SECTION_KEYS = Object.freeze(["exportId", "name", "recordCount", "firstRecordId", "lastRecordId", "digest", "state"]);
export const GRANT_KEYS = Object.freeze(["grantId", "exportId", "expiresAt", "revokedAt", "createdAt"]);
export const SHARDED_GRANT_KEYS = Object.freeze(["grantId", "exportId", "target", "shardId", "expiresAt", "revokedAt", "createdAt"]);
export const PROOF_KEYS = Object.freeze(["exportId", "objectSha256", "reason", "deletedAt", "proofDigest"]);
export const SHARD_KEYS = Object.freeze(["shardId", "exportId", "ordinal", "section", "range", "recordCount", "state", "object"]);
export const MANIFEST_KEYS = Object.freeze(["manifestId", "exportId", "canonicalDigest", "object", "shards", "createdAt"]);
export const SUBJECT_KEYS = Object.freeze(["subjectId", "name", "currentDatasetRevision"]);
export const REVISION_SUMMARY_KEYS = Object.freeze(["subjectId", "revision", "committedAt", "recordCount", "recordsDigest"]);
export const WORK_KEYS = Object.freeze(["workId", "kind", "aggregateId", "state", "terminal", "attempt", "leaseOwner", "leaseExpiresAt"]);
export const EVENT_KEYS = Object.freeze(["eventId", "aggregateId", "sequence", "type", "occurredAt", "schemaVersion", "payload"]);
export const FINAL_RESOURCE_KEYS = Object.freeze(["subjects", "datasetRevisionSummaries", "exports", "exportSections", "downloadGrants", "deletionProofs", "exportShards", "exportManifests", "shardedDownloadGrants"]);
export const V1_RESOURCE_KEYS = Object.freeze(FINAL_RESOURCE_KEYS.slice(0, 6));

export function defineCase({ id, fixtureFamily, action, oracle, run }) {
  if (!/^[A-E]-\d{2}$/u.test(id) || !/^EV-F-/u.test(fixtureFamily ?? "") || typeof action !== "string" || action.length < 24 || typeof oracle !== "string" || oracle.length < 24 || typeof run !== "function" || run.length < 1) throw new TypeError("invalid ExportVault case definition");
  return Object.freeze({ taskId: "exportvault", id, fixtureFamily, action, oracle, run });
}
export function guardedCase(definition, hardCapIds = []) { return defineCase({ ...definition, async run(ctx) { try { return await definition.run(ctx); } catch (error) { if (error && typeof error === "object") error.hardCapIds = [...new Set([...(error.hardCapIds ?? []), ...hardCapIds])]; throw error; } } }); }
export function exactKeys(value, keys, label) { assert.ok(value && typeof value === "object" && !Array.isArray(value), `${label} must be an object`); assert.deepEqual(Object.keys(value).sort(), [...keys].sort(), `${label} fields`); return value; }
export function expectStatus(ctx, response, status, label, options = {}) { ctx.equal(response.status, status, `${label} status`, options); return response.json; }
export function expectSuccess(ctx, response, label, status = 200, options = {}) { const value = expectStatus(ctx, response, status, label, options); ctx.ok(value && typeof value === "object", `${label} JSON`, options); return value; }
export function expectError(ctx, response, status, code, label, options = {}) { expectStatus(ctx, response, status, label, options); exactKeys(response.json, ["error"], `${label} envelope`); exactKeys(response.json.error, ["code", "message", "details"], `${label} error`); ctx.equal(response.json.error.code, code, `${label} code`, options); return response.json.error; }

export function assertExport(value, { sharded = false } = {}) {
  exactKeys(value, sharded ? SHARDED_EXPORT_KEYS : EXPORT_KEYS, sharded ? "sharded Export" : "legacy Export");
  assert.match(value.exportId, /^[0-9a-f-]{36}$/u); assert.match(value.subjectId, /^[0-9a-f-]{36}$/u); assert.ok(Array.isArray(value.scope) && value.scope.length >= 1 && value.scope.length <= 20); assert.deepEqual(value.scope, [...new Set(value.scope)].sort()); assert.ok(["JSONL", "CSV"].includes(value.format)); assert.ok(Number.isSafeInteger(value.datasetRevision) && value.datasetRevision > 0); assert.ok(["REQUESTED", "GENERATING", "READY", "EXPIRED", "CANCELLED", "FAILED"].includes(value.state)); assert.ok(Number.isSafeInteger(value.sequence) && value.sequence > 0);
  if (value.object !== null) { exactKeys(value.object, ["sha256", "size", "mediaType"], "Export object"); assert.match(value.object.sha256, /^[0-9a-f]{64}$/u); assert.ok(Number.isSafeInteger(value.object.size) && value.object.size >= 0); }
  if (sharded) { assert.equal(value.object, null); assert.ok(Array.isArray(value.shards)); value.shards.forEach(assertShard); if (value.manifest !== null) assertExportManifest(value.manifest); }
  return value;
}
export function assertSection(value) { exactKeys(value, SECTION_KEYS, "ExportSection"); assert.ok(Number.isSafeInteger(value.recordCount) && value.recordCount >= 0); assert.match(value.digest, /^[0-9a-f]{64}$/u); assert.ok(["PENDING", "WRITTEN", "VERIFIED"].includes(value.state)); return value; }
export function assertGrant(value, { sharded = false } = {}) { exactKeys(value, sharded ? SHARDED_GRANT_KEYS : GRANT_KEYS, sharded ? "ShardedDownloadGrant" : "DownloadGrant"); if (sharded) { assert.ok(["MANIFEST", "SHARD"].includes(value.target)); assert.equal(value.target === "MANIFEST", value.shardId === null); } return value; }
export function assertProof(value) { exactKeys(value, PROOF_KEYS, "DeletionProof"); assert.ok(["EXPIRED", "CANCELLED"].includes(value.reason)); assert.match(value.objectSha256, /^[0-9a-f]{64}$/u); assert.match(value.proofDigest, /^[0-9a-f]{64}$/u); return value; }
export function assertShard(value) { exactKeys(value, SHARD_KEYS, "ExportShard"); exactKeys(value.range, ["afterRecordId", "throughRecordId"], "ExportShard range"); assert.ok(Number.isSafeInteger(value.ordinal) && value.ordinal >= 0); assert.ok(Number.isSafeInteger(value.recordCount) && value.recordCount >= 0 && value.recordCount <= 100000); assert.equal(value.range.throughRecordId === null, value.recordCount === 0); assert.ok(["PENDING", "GENERATING", "VERIFIED", "FAILED", "CANCELLED"].includes(value.state)); if (value.object !== null) exactKeys(value.object, ["sha256", "size", "mediaType"], "Shard object"); return value; }
export function assertExportManifest(value) { exactKeys(value, MANIFEST_KEYS, "ExportManifest"); exactKeys(value.object, ["sha256", "size", "mediaType"], "Manifest object"); assert.match(value.canonicalDigest, /^[0-9a-f]{64}$/u); assert.deepEqual(value.shards, [...value.shards].sort((a, b) => a.ordinal - b.ordinal)); for (const item of value.shards) exactKeys(item, ["shardId", "ordinal", "section", "range", "recordCount", "sha256", "size", "mediaType"], "Manifest shard member"); return value; }

async function build(ctx, workspace) { const target = ctx.forWorkspace(workspace); if (!builds.has(target.workspace)) builds.set(target.workspace, target.npm("build")); await builds.get(target.workspace); }
export async function materializeSeed(ctx, fixture, label = ctx.caseId.toLowerCase(), workspace = ctx.workspace) {
  const root = ctx.tempPath(`fixture-${label}`); const assets = resolve(root, "assets"); await mkdir(assets, { recursive: true });
  for (const [name, bytes] of Object.entries(fixture.assets ?? {})) { const path = resolve(assets, name); await mkdir(dirname(path), { recursive: true }); await writeFile(path, bytes); }
  const path = resolve(root, "seed.json"); await writeFile(path, `${JSON.stringify(fixture.seed)}\n`, { mode: 0o600 }); await ctx.forWorkspace(workspace).seedFile(path); ctx.mark("seed-imported", { fixtureFamily: fixture.fixtureFamily, seedVersion: fixture.seed.seedVersion }); return path;
}
export async function prepare(ctx, options = {}) { const workspace = options.workspace ?? ctx.workspace; const target = ctx.forWorkspace(workspace); if (options.build !== false) await build(ctx, workspace); if (options.migrate !== false) await target.migrate(); if (options.fixture) await materializeSeed(ctx, options.fixture, options.label, workspace); else if (options.seed) await target.seed(options.seed); ctx.mark("candidate-prepared", { workspace: target.workspace, seeded: Boolean(options.fixture ?? options.seed) }); return target; }
export async function startPreparedApi(ctx, options = {}) { return (await prepare(ctx, options)).startApi(options.api ?? {}); }

export async function createExport(ctx, baseUrl, body, options = {}) { const response = await ctx.mutate(baseUrl, "/api/v1/exports", options.key ?? ctx.key(`export:${body.subjectId}:${body.scope.join(",")}:${body.format}`), body, { contractExpectation: options.contractExpectation }); if (options.allowFailure) return response; return assertExport(expectSuccess(ctx, response, options.label ?? "create Export", 202, options.assertionOptions), { sharded: options.sharded }); }
export async function getExport(ctx, baseUrl, exportId, options = {}) { const value = expectSuccess(ctx, await ctx.request(baseUrl, `/api/v1/exports/${exportId}`), options.label ?? "get Export"); return assertExport(value, { sharded: options.sharded }); }
export async function cancelExport(ctx, baseUrl, exportId, reason = "user-request", options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/exports/${exportId}/cancel`, options.key ?? ctx.key(`cancel:${exportId}`), { reason }); if (options.allowFailure) return response; return assertExport(expectSuccess(ctx, response, options.label ?? "cancel Export"), { sharded: options.sharded }); }
export async function createGrant(ctx, baseUrl, exportId, body, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/exports/${exportId}/download-grants`, options.key ?? ctx.key(`grant:${exportId}:${body.target ?? "legacy"}:${body.shardId ?? "object"}`), body); if (options.allowFailure) return response; return assertGrant(expectSuccess(ctx, response, options.label ?? "create Download Grant"), { sharded: options.sharded }); }
export async function revokeGrant(ctx, baseUrl, grantId, reason = "owner-request", options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/download-grants/${grantId}/revoke`, options.key ?? ctx.key(`revoke:${grantId}`), { reason }); if (options.allowFailure) return response; return assertGrant(expectSuccess(ctx, response, options.label ?? "revoke Download Grant"), { sharded: options.sharded }); }
export async function downloadGrant(ctx, baseUrl, grantId, options = {}) { return ctx.request(baseUrl, `/api/v1/download-grants/${grantId}/content`, { method: options.method ?? "GET", headers: options.headers, binary: true, timeoutMs: options.timeoutMs ?? 30_000 }); }
export async function getSections(ctx, baseUrl, exportId) { const value = expectSuccess(ctx, await ctx.request(baseUrl, `/api/v1/exports/${exportId}/sections`), "list Export sections"); exactKeys(value, ["items"], "sections response"); value.items.forEach(assertSection); return value.items; }
export async function getEvents(ctx, baseUrl, aggregateId) { const value = expectSuccess(ctx, await ctx.request(baseUrl, `/api/v1/domain-events?aggregateId=${aggregateId}&afterSequence=0&limit=100`), "list Domain Events"); const items = value.items ?? value; assert.ok(Array.isArray(items)); items.forEach((event) => exactKeys(event, EVENT_KEYS, "Domain Event")); assertEventSequence(items); return items; }

export async function waitForExport(ctx, baseUrl, exportId, states, processes = [], options = {}) { const expected = new Set(Array.isArray(states) ? states : [states]); return ctx.waitFor(async () => { const response = await ctx.request(baseUrl, `/api/v1/exports/${exportId}`); return response.status === 200 && expected.has(response.json?.state) ? response.json : false; }, { timeoutMs: options.timeoutMs ?? 180_000, intervalMs: 100, label: `Export ${exportId} state ${[...expected].join("/")}`, processes }); }
export async function waitForDrain(ctx, baseUrl, options = {}) { return ctx.waitFor(async () => { const snapshot = await ctx.snapshot(baseUrl, { timeoutMs: options.requestTimeoutMs }); return snapshot.work.filter(options.predicate ?? (() => true)).every(({ terminal }) => terminal) ? snapshot : false; }, { timeoutMs: options.timeoutMs ?? 180_000, intervalMs: 100, label: options.label ?? "Export Work drain", processes: options.processes }); }
export async function generateExport(ctx, api, body, options = {}) { const created = await createExport(ctx, api.baseUrl, body, options); const workers = options.workers ?? [await ctx.startWorker()]; const ready = await waitForExport(ctx, api.baseUrl, created.exportId, "READY", workers, { timeoutMs: options.timeoutMs }); return { created, ready, workers }; }

function resource(snapshot, name) { const value = snapshot?.resources?.[name]; assert.ok(Array.isArray(value), `snapshot resource ${name}`); return value; }
export function assertSnapshot(ctx, snapshot, { final = true } = {}) {
  exactKeys(snapshot, ["asOf", "resources", "work", "events"], "verification snapshot"); ctx.equal(Object.keys(snapshot.resources).sort(), [...(final ? FINAL_RESOURCE_KEYS : V1_RESOURCE_KEYS)].sort(), `${final ? "FINAL" : "V1"} resource union`, { hardCapIds: ["PUBLICATION_ATOMICITY"] });
  resource(snapshot, "subjects").forEach((item) => exactKeys(item, SUBJECT_KEYS, "ExportSubject")); resource(snapshot, "datasetRevisionSummaries").forEach((item) => exactKeys(item, REVISION_SUMMARY_KEYS, "DatasetRevisionSummary")); resource(snapshot, "exports").forEach((item) => assertExport(item, { sharded: Object.hasOwn(item, "shards") })); resource(snapshot, "exportSections").forEach(assertSection); resource(snapshot, "downloadGrants").forEach((item) => assertGrant(item)); resource(snapshot, "deletionProofs").forEach(assertProof);
  assertSorted(resource(snapshot, "subjects"), ["subjectId"]); assertSorted(resource(snapshot, "datasetRevisionSummaries"), ["subjectId", "revision"]); assertSorted(resource(snapshot, "exports"), ["exportId"]); assertSorted(resource(snapshot, "exportSections"), ["exportId", "name"]); assertSorted(resource(snapshot, "downloadGrants"), ["grantId"]); assertSorted(resource(snapshot, "deletionProofs"), ["exportId", "objectSha256"]);
  if (final) { resource(snapshot, "exportShards").forEach(assertShard); resource(snapshot, "exportManifests").forEach(assertExportManifest); resource(snapshot, "shardedDownloadGrants").forEach((item) => assertGrant(item, { sharded: true })); assertSorted(resource(snapshot, "exportShards"), ["exportId", "ordinal", "shardId"]); assertSorted(resource(snapshot, "exportManifests"), ["exportId", "manifestId"]); assertSorted(resource(snapshot, "shardedDownloadGrants"), ["grantId"]); }
  for (const work of snapshot.work) { exactKeys(work, WORK_KEYS, "Work"); assert.ok(["EXPORT_GENERATION", "EXPORT_CLEANUP"].includes(work.kind)); assert.equal(work.terminal, ["SUCCEEDED", "FAILED", "CANCELLED"].includes(work.state)); assert.equal(work.state === "LEASED", work.leaseOwner !== null && work.leaseExpiresAt !== null); }
  for (const event of snapshot.events) { exactKeys(event, EVENT_KEYS, "Domain Event"); assert.deepEqual(event.payload, {}); }
  assertSorted(snapshot.work, ["workId"]); assertSorted(snapshot.events, ["aggregateId", "sequence", "eventId"]); assertEventSequence(snapshot.events); ctx.ok(!/(?:adminToken|leaseToken|idempotencyKey|authorization|postgres(?:ql)?:\/\/|\/(?:Users|home|tmp)\/)/iu.test(canonicalJson(snapshot)), "snapshot omits tokens, credentials, and private paths", { hardCapIds: ["PUBLICATION_ATOMICITY"] }); return snapshot;
}

export async function crashWorkerAt(ctx, baseUrl, point, workPredicate = () => true) { const barrier = await ctx.barrier({ hold: (payload) => payload.point === point }); const worker = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const found = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(baseUrl); const work = snapshot.work.find((item) => item.state === "LEASED" && workPredicate(item)); return work ? { snapshot, work } : false; }, { timeoutMs: 180_000, label: `${point} leased Work`, processes: [worker] }); const entry = await barrier.waitFor(({ json }) => json?.point === point && json?.workId === found.work.workId, { timeoutMs: 180_000, processes: [worker] }); ctx.equal(Object.keys(entry.json).sort(), ["aggregateId", "attempt", "leaseTokenHash", "point", "processRole", "schemaVersion", "workId"].sort(), "barrier payload exact keys"); await ctx.kill(worker); return { barrier, entry, ...found }; }
export async function crashDispatcherAfterResponse(ctx, receiver) { const barrier = await ctx.barrier({ hold: (payload) => payload.point === "dispatcher.response-received" }); const dispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url, env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const entry = await barrier.waitFor(({ json }) => json?.point === "dispatcher.response-received", { timeoutMs: 120_000, processes: [dispatcher] }); await ctx.kill(dispatcher); return { barrier, dispatcher, entry }; }

export async function launchBrowser(ctx, baseUrl, viewport = { width: 1280, height: 800 }) { const chromium = await ctx.loadChromium(); const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH ?? "/usr/bin/chromium", args: ["--no-sandbox"] }); ctx.defer(() => browser.close()); const browserContext = await browser.newContext({ viewport }); const page = await browserContext.newPage(); await page.goto(baseUrl, { waitUntil: "domcontentloaded", timeout: 30_000 }); return { browser, browserContext, page }; }
async function firstVisible(locator) { for (let index = 0; index < await locator.count(); index += 1) { const item = locator.nth(index); if (await item.isVisible().catch(() => false)) return item; } }
export async function fillField(page, labels, value) { for (const label of labels) { const item = await firstVisible(page.getByLabel(label)); if (item) { await item.fill(String(value)); return; } } throw new Error(`missing labelled field ${labels.join("/")}`); }
export async function clickControl(page, names) { for (const name of names) for (const role of ["button", "link", "option", "tab"]) { const item = await firstVisible(page.getByRole(role, { name })); if (item) { await item.click(); return; } } throw new Error(`missing visible control ${names.join("/")}`); }
export async function chooseOption(page, labels, value) { for (const label of labels) { const item = await firstVisible(page.getByLabel(label)); if (item) { await item.selectOption({ label: value }).catch(() => item.selectOption(value)); return; } } throw new Error(`missing select ${labels.join("/")}`); }
export async function checkField(page, labels, checked = true) { for (const label of labels) { const item = await firstVisible(page.getByLabel(label)); if (item) { if (checked) await item.check(); else await item.uncheck(); return; } } throw new Error(`missing checkbox ${labels.join("/")}`); }

export async function runWindow({ clients, warmupSeconds = 0, measureSeconds, operation }) { const execute = async (seconds, collect) => { const latencies = []; let completed = 0; let verifiedBytes = 0; const statuses = new Map(); const deadline = performance.now() + seconds * 1000; await Promise.all(Array.from({ length: clients }, async (_, client) => { while (performance.now() < deadline) { const index = completed++; const started = performance.now(); const result = await operation(index, client); if (collect) { latencies.push(performance.now() - started); statuses.set(result.status, (statuses.get(result.status) ?? 0) + 1); verifiedBytes += result.verifiedBytes ?? 0; } } })); return { completed, verifiedBytes, latencies, statuses }; }; if (warmupSeconds) await execute(warmupSeconds, false); const started = performance.now(); const measured = await execute(measureSeconds, true); const durationSeconds = (performance.now() - started) / 1000; return { ...measured, durationSeconds, mibPerSecond: measured.verifiedBytes / 1048576 / durationSeconds, p95Ms: percentile(measured.latencies, 0.95) }; }
export function finalEvidence(ctx, values = {}) { return ctx.pass({ evidence: [{ kind: "exportvault-case-summary", ...values }] }); }
export function candidateFailure(message, failureCodeSuffix = "ASSERTION_FAILED", hardCapIds = []) { throw new CaseFailure(message, { failureCodeSuffix, hardCapIds }); }

function integerUuid(kind, index) { const prefix = kind.toString(16).padStart(8, "0"); return `${prefix}-0000-4000-8000-${index.toString(16).padStart(12, "0")}`; }
async function writeChunk(stream, value) { if (!stream.write(value)) await once(stream, "drain"); }
export async function writePerformanceSeed(ctx) {
  const root = ctx.tempPath("exportvault-perf-seed"); const assets = resolve(root, "assets"); await mkdir(assets, { recursive: true }); const shared = Buffer.alloc(64 * 1024 * 1024, 0x45); await writeFile(resolve(assets, "live-shared.bin"), shared); const sharedObject = { sha256: sha256(shared), size: shared.length, mediaType: "application/x-ndjson" };
  const path = resolve(root, "seed.json"); const stream = createWriteStream(path, { encoding: "utf8", mode: 0o600 }); await writeChunk(stream, '{"schemaVersion":1,"seedVersion":"perf-v1","subjects":[');
  for (let subject = 1; subject <= 100; subject += 1) { if (subject > 1) await writeChunk(stream, ","); await writeChunk(stream, JSON.stringify({ subjectId: integerUuid(1, subject), name: `Perf Subject ${subject}`, currentDatasetRevision: 1 })); }
  await writeChunk(stream, '],"datasetRevisions":[');
  for (let subject = 1; subject <= 100; subject += 1) { if (subject > 1) await writeChunk(stream, ","); await writeChunk(stream, JSON.stringify({ subjectId: integerUuid(1, subject), revision: 1, committedAt: "2019-01-01T00:00:00.000Z", records: [] }).slice(0, -2)); if (subject === 1) { const scopes = ["profile", "activity", "orders", "files"]; let ordinal = 0; for (const scope of scopes) for (let index = 0; index < 1_250_000; index += 1) { if (ordinal++ > 0) await writeChunk(stream, ","); await writeChunk(stream, JSON.stringify({ recordId: integerUuid(scopes.indexOf(scope) + 2, index + 1), scope, data: { ordinal: index, scope } })); } } await writeChunk(stream, "]}"); }
  await writeChunk(stream, '],"exports":[');
  for (let index = 1; index <= 11000; index += 1) { if (index > 1) await writeChunk(stream, ","); const expired = index <= 10000; let object = sharedObject; let assetPath = "assets/live-shared.bin"; if (expired) { const body = Buffer.from(`expired-${String(index).padStart(5, "0")}`); assetPath = `assets/expired-${String(index).padStart(5, "0")}.bin`; await writeFile(resolve(root, assetPath), body); object = { sha256: sha256(body), size: body.length, mediaType: "application/x-ndjson" }; } const retentionUntil = expired ? "2020-01-02T00:00:00.000Z" : "2040-01-02T00:00:00.000Z"; const createdAt = expired ? "2020-01-01T00:00:00.000Z" : "2040-01-01T00:00:00.000Z"; await writeChunk(stream, JSON.stringify({ exportId: integerUuid(20, index), subjectId: integerUuid(1, ((index - 1) % 100) + 1), scope: ["profile"], format: "JSONL", datasetRevision: 1, state: "READY", object, retentionUntil, createdAt, readyAt: new Date(Date.parse(createdAt) + 60_000).toISOString(), sequence: 1, assetPath })); }
  await writeChunk(stream, "]}"); stream.end(); await once(stream, "finish"); return { path, sharedBytes: shared, sharedObject };
}

export { assertManifest, canonicalJson, csvBytes, jsonlBytes, manifestBytes, planShards, rangeOracle, sectionOracle, sha256 };
