import {
  activateSubscription, assertDeniedEverywhere, assertGrantIntervals, assertPoolClosure, assertSnapshot, assignSeat,
  cancelSubscription, changePlan, checkEntitlement, crashClaimedWork, createPool, createRefund, createRevision, defineCase,
  expectError, finalEvidence, getSubscription, prepare, providerEvent, publishRevision, reconcileRefund, waitForDrain,
  waitForSubscription,
} from "./helpers.mjs";

const LEASE_EXPIRY_MS = 3_300;

async function sleep(milliseconds) { await new Promise((resolve) => setTimeout(resolve, milliseconds)); }

function startBody(fixture, subjectId, kind) {
  return { tenantId: fixture.tenant.tenantId, subjectId, planRevisionId: fixture.revisions.basicV1.planRevisionId, startMode: "TRIAL", providerRequestId: `start-${subjectId}`, ...(kind ? { subscriptionKind: kind } : {}) };
}

async function assertRecoveredWork(ctx, snapshot, aggregateId, label) {
  const work = snapshot.work.filter((item) => item.aggregateId === aggregateId); ctx.ok(work.length > 0, `${label} Work retained`); ctx.ok(work.every(({ terminal }) => terminal), `${label} Work reaches terminal`); ctx.ok(work.some(({ attempt }) => Number.isSafeInteger(attempt) && attempt >= 2), `${label} lease takeover increments attempt`, { hardCapIds: ["STALE_WORK_OR_LOST_WORK"] });
}

const R01 = defineCase({
  id: "RECOVERY-01", fixtureFamily: "EH-F-RECOVERY-PLAN-WORK",
  action: "Kill workers after claiming activation, plan-change, and expiry Work, wait for lease expiry, introduce newer authority, and run replacements to drain.",
  oracle: "Every persisted Work remains observable and terminal, each Grant and fence transition occurs once, and an expired owner cannot apply stale plan authority or revive terminal access.",
  async run(ctx) {
    const fixture = ctx.fixtures.recovery(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()];
    const pending = await ctx.mutate(apis[0].baseUrl, "/api/v1/subscriptions", ctx.key("activation"), startBody(fixture, "recover-activation")); ctx.equal(pending.status, 200, "activation request accepted"); const activationId = pending.json.subscriptionId; await crashClaimedWork(ctx, apis[0].baseUrl, ({ aggregateId }) => aggregateId === activationId); await sleep(LEASE_EXPIRY_MS); let replacement = await target.startWorker(); const activated = await waitForSubscription(ctx, apis[1].baseUrl, activationId, ["TRIALING", "ACTIVE"], [replacement]); let snapshot = await waitForDrain(ctx, apis[0].baseUrl, { predicate: ({ aggregateId }) => aggregateId === activationId, processes: [replacement] }); await assertRecoveredWork(ctx, snapshot, activationId, "activation"); ctx.ok(snapshot.resources.entitlementGrants.some(({ subscriptionId, validUntil }) => subscriptionId === activationId && validUntil === null), "activation has open Grant");
    await ctx.stop(replacement); const change = await changePlan(ctx, apis[0].baseUrl, activationId, { toPlanRevisionId: fixture.revisions.proV1.planRevisionId, expectedSequence: activated.sequence }, { key: ctx.key("change") }); ctx.equal(change.kind, "UPGRADE", "recovery plan change is immediate"); await crashClaimedWork(ctx, apis[0].baseUrl, ({ aggregateId }) => aggregateId === activationId); const latest = await getSubscription(ctx, apis[1].baseUrl, activationId); const terminal = await cancelSubscription(ctx, apis[1].baseUrl, activationId, latest.sequence, { key: ctx.key("newer-cancel") }); await sleep(LEASE_EXPIRY_MS); replacement = await target.startWorker(); snapshot = await waitForDrain(ctx, apis[0].baseUrl, { predicate: ({ aggregateId }) => aggregateId === activationId, processes: [replacement] }); const afterStaleChange = await getSubscription(ctx, apis[1].baseUrl, activationId); ctx.equal(afterStaleChange.state, "CANCELLED", "newer cancel defeats claimed stale change", { hardCapIds: ["STALE_WORK_OR_LOST_WORK"] }); ctx.equal(afterStaleChange.revocationVersion, terminal.revocationVersion, "stale Work cannot advance or regress final fence"); assertGrantIntervals(snapshot.resources.entitlementGrants.filter(({ subscriptionId }) => subscriptionId === activationId)); ctx.ok(snapshot.resources.entitlementGrants.filter(({ subscriptionId }) => subscriptionId === activationId).every(({ validUntil }) => validUntil !== null), "terminal Subscription retains no open Grant");
    await ctx.stop(replacement); const expire = await ctx.mutate(apis[0].baseUrl, "/api/v1/admin/expire-due", ctx.key("expire-due"), {}); ctx.equal(expire.status, 200, "expire-due accepted"); await crashClaimedWork(ctx, apis[0].baseUrl, ({ aggregateId }) => aggregateId === fixture.due.subscriptionId); await sleep(LEASE_EXPIRY_MS); replacement = await target.startWorker(); const expired = await waitForSubscription(ctx, apis[1].baseUrl, fixture.due.subscriptionId, "EXPIRED", [replacement]); snapshot = await waitForDrain(ctx, apis[0].baseUrl, { predicate: ({ aggregateId }) => aggregateId === fixture.due.subscriptionId, processes: [replacement] }); await assertRecoveredWork(ctx, snapshot, fixture.due.subscriptionId, "expiry"); await assertDeniedEverywhere(ctx, apis, { tenantId: fixture.tenant.tenantId, subjectId: fixture.due.subjectId, feature: "reports", knownRevocationVersion: 0 }, expired.revocationVersion, [replacement]); assertSnapshot(ctx, snapshot);
    return finalEvidence(ctx, { activationId, cancelledAtVersion: terminal.revocationVersion, expiredId: expired.subscriptionId });
  },
});

const R02 = defineCase({
  id: "RECOVERY-02", fixtureFamily: "EH-F-RECOVERY-REFUND",
  action: "Persist an UNKNOWN refund, request reconcile, kill its claimed Worker, wait for lease takeover, and submit duplicate and reordered provider outcomes.",
  oracle: "The same Refund and providerRequest identity converges once, unresolved reservation is retained until final resolution, and stale ownership cannot duplicate ledger or fence effects.",
  async run(ctx) {
    const fixture = ctx.fixtures.recovery(); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi(); const refund = await createRefund(ctx, api.baseUrl, fixture.active.subscriptionId, { amountMinor: 1000, currency: "USD", providerRequestId: "recovery-unknown" }, { key: ctx.key("refund") }); const unknownBody = { providerEventId: "recovery-unknown-event", providerRequestId: refund.providerRequestId, kind: "REFUND", outcome: "UNKNOWN", occurredAt: ctx.at() }; await providerEvent(ctx, api.baseUrl, unknownBody, { key: ctx.key("unknown-event") }); await reconcileRefund(ctx, api.baseUrl, refund.refundId, {}, { key: ctx.key("reconcile") }); await crashClaimedWork(ctx, api.baseUrl, ({ aggregateId }) => aggregateId === refund.refundId); const reserved = await ctx.snapshot(api.baseUrl); const current = reserved.resources.refunds.find(({ refundId }) => refundId === refund.refundId); ctx.ok(["REQUESTED", "UNKNOWN"].includes(current.state), "claimed reconcile retains unresolved Refund"); const excess = await createRefund(ctx, api.baseUrl, fixture.active.subscriptionId, { amountMinor: 1, currency: "USD", providerRequestId: "recovery-excess" }, { allowFailure: true, key: ctx.key("excess") }); expectError(ctx, excess, 409, "REFUND_LIMIT_EXCEEDED", "UNKNOWN remains reserved during lease loss", { hardCapIds: ["REFUND_CONSERVATION"] }); await providerEvent(ctx, api.baseUrl, { ...unknownBody, providerEventId: "recovery-final-event", outcome: "SUCCEEDED", occurredAt: ctx.at({ seconds: 1 }) }, { key: ctx.key("final-event") }); await providerEvent(ctx, api.baseUrl, unknownBody, { key: ctx.key("unknown-event") }); await sleep(LEASE_EXPIRY_MS); const replacement = await target.startWorker(); const final = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(api.baseUrl); return snapshot.resources.refunds.find(({ refundId }) => refundId === refund.refundId)?.state === "SUCCEEDED" && snapshot.work.filter(({ aggregateId }) => aggregateId === refund.refundId).every(({ terminal }) => terminal) ? snapshot : false; }, { timeoutMs: 120_000, label: "recovered refund reconciliation", processes: [replacement] }); const refunds = final.resources.refunds.filter(({ providerRequestId }) => providerRequestId === refund.providerRequestId); ctx.equal(refunds.length, 1, "one providerRequest creates one Refund", { hardCapIds: ["STALE_WORK_OR_LOST_WORK"] }); ctx.equal(refunds[0].refundId, refund.refundId, "reconcile retains original Refund identity"); ctx.equal(final.resources.providerEvents.filter(({ providerEventId }) => providerEventId === unknownBody.providerEventId).length, 1, "duplicate callback retains one ProviderEvent"); await assertRecoveredWork(ctx, final, refund.refundId, "refund reconcile"); const subscription = final.resources.subscriptions.find(({ subscriptionId }) => subscriptionId === fixture.active.subscriptionId); ctx.equal(subscription.state, "REFUNDED", "full recovered refund closes Subscription");
    return finalEvidence(ctx, { refundId: refund.refundId, providerRequestId: refund.providerRequestId, state: refunds[0].state });
  },
});

const R03 = defineCase({
  id: "RECOVERY-03", fixtureFamily: "EH-F-RECOVERY-POOL",
  action: "Fill an organization Pool, cancel its Subscription, kill the claimed Pool revoke Worker, race another seat mutation, and recover all seats after lease expiry.",
  oracle: "Pool, Seat history, Grants, fences, and Work close together; every subject fails closed, replacements drain, and stale ownership cannot omit or double-revoke a seat.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const activated = await activateSubscription(ctx, apis[0], { tenantId: fixture.tenant.tenantId, subjectId: "pool-owner", planRevisionId: fixture.revisions.proV1.planRevisionId, startMode: "TRIAL", providerRequestId: "pool-owner-start", subscriptionKind: "ORGANIZATION" }, { key: ctx.key("org") }); for (const worker of activated.workers) await ctx.stop(worker); const pool = await createPool(ctx, apis[0].baseUrl, { tenantId: fixture.tenant.tenantId, subscriptionId: activated.active.subscriptionId, feature: "reports", seatLimit: 5 }, { key: ctx.key("pool") }); let version = 0; const subjects = Array.from({ length: 5 }, (_, index) => `pool-subject-${index}`); for (const subjectId of subjects) { const result = await assignSeat(ctx, apis[version % 2].baseUrl, pool.poolId, { subjectId, expectedPoolVersion: version }, { key: ctx.key(`seat:${subjectId}`) }); version = result.pool.version; }
    const lowerDraft = await createRevision(ctx, apis[0].baseUrl, fixture.plans.proPlan.planId, { priceMinor: 5000, currency: "USD", interval: "MONTH", features: { reports: 3, exports: 1 }, trialDays: 14, graceDays: 3, refundDays: 7 }, { key: ctx.key("recovery-lower") }); const lower = await publishRevision(ctx, apis[0].baseUrl, lowerDraft.planRevisionId, { key: ctx.key("publish-recovery-lower") }); const beforeChange = await getSubscription(ctx, apis[0].baseUrl, activated.active.subscriptionId); await changePlan(ctx, apis[0].baseUrl, beforeChange.subscriptionId, { toPlanRevisionId: lower.planRevisionId, expectedSequence: beforeChange.sequence }, { key: ctx.key("recovery-limit-change") }); await crashClaimedWork(ctx, apis[0].baseUrl, ({ aggregateId }) => aggregateId === pool.poolId); await sleep(LEASE_EXPIRY_MS); let replacements = [await target.startWorker()]; const reconciled = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(apis[0].baseUrl); const currentPool = snapshot.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); return currentPool?.state === "OVER_LIMIT" && currentPool.seatLimit === 3 && snapshot.work.filter(({ aggregateId }) => aggregateId === pool.poolId).every(({ terminal }) => terminal) ? snapshot : false; }, { timeoutMs: 120_000, label: "Pool reconcile takeover", processes: replacements }); ctx.equal(reconciled.resources.seatAssignments.filter(({ poolId, state }) => poolId === pool.poolId && state === "ACTIVE").length, 5, "recovered reconciliation never arbitrarily evicts"); await assertRecoveredWork(ctx, reconciled, pool.poolId, "Pool reconcile"); for (const worker of replacements) await ctx.stop(worker);
    const current = await getSubscription(ctx, apis[0].baseUrl, activated.active.subscriptionId); await cancelSubscription(ctx, apis[0].baseUrl, current.subscriptionId, current.sequence, { key: ctx.key("cancel") }); await crashClaimedWork(ctx, apis[0].baseUrl, ({ aggregateId }) => aggregateId === pool.poolId); const raced = await assignSeat(ctx, apis[1].baseUrl, pool.poolId, { subjectId: "late-seat", expectedPoolVersion: version }, { allowFailure: true, key: ctx.key("late-seat") }); ctx.ok(raced.status === 409, "terminal contention rejects later assignment"); await sleep(LEASE_EXPIRY_MS); replacements = await Promise.all([target.startWorker(), target.startWorker()]); const final = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(apis[0].baseUrl); const currentPool = snapshot.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); const assignments = snapshot.resources.seatAssignments.filter(({ poolId }) => poolId === pool.poolId); return currentPool?.state === "REVOKED" && assignments.length === subjects.length && assignments.every(({ state }) => state !== "ACTIVE") && snapshot.work.filter(({ aggregateId }) => aggregateId === pool.poolId).every(({ terminal }) => terminal) ? snapshot : false; }, { timeoutMs: 120_000, label: "Pool all-seat recovery", processes: replacements }); const finalPool = final.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); const history = final.resources.seatAssignments.filter(({ poolId }) => poolId === pool.poolId); assertPoolClosure(finalPool, history); ctx.equal(new Set(history.map(({ subjectId }) => subjectId)).size, subjects.length, "recovery neither loses nor duplicates Seat history", { hardCapIds: ["STALE_WORK_OR_LOST_WORK"] }); for (const subjectId of subjects) { const view = await checkEntitlement(ctx, apis[subjects.indexOf(subjectId) % 2].baseUrl, { tenantId: fixture.tenant.tenantId, subjectId, feature: "reports", knownRevocationVersion: 0 }); ctx.equal(view.state, "DISABLED", `${subjectId} fails closed after Pool revoke`, { hardCapIds: ["REVOCATION_FAIL_CLOSED"] }); } await assertRecoveredWork(ctx, final, pool.poolId, "Pool revoke");
    return finalEvidence(ctx, { poolId: pool.poolId, seatsClosed: history.length, state: finalPool.state });
  },
});

const R04 = defineCase({
  id: "RECOVERY-04", fixtureFamily: "EH-F-RECOVERY-OUTBOX",
  action: "Cancel a Subscription, hold the dispatcher after the receiver response, SIGKILL it, restart delivery, and query stale fence versions in reverse order on two APIs.",
  oracle: "Retry preserves event identity and byte body, aggregate sequences stay contiguous, every API denies within two seconds, and older versions never restore access.",
  async run(ctx) {
    const fixture = ctx.fixtures.recovery(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const current = await getSubscription(ctx, apis[0].baseUrl, fixture.active.subscriptionId); const cancelled = await cancelSubscription(ctx, apis[0].baseUrl, current.subscriptionId, current.sequence, { key: ctx.key("cancel") }); await assertDeniedEverywhere(ctx, apis, { tenantId: fixture.tenant.tenantId, subjectId: fixture.active.subjectId, feature: "reports", knownRevocationVersion: 0 }, cancelled.revocationVersion);
    const receiver = await ctx.receiver({ behavior: () => ({ status: 204 }) }); const barrier = await ctx.barrier({ hold: ({ processRole, point }) => processRole === "dispatcher" && point === "dispatcher.response-received" }); const dispatcher = await target.startDispatcher({ webhookUrl: receiver.url, env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const held = await barrier.waitFor(({ json }) => json?.processRole === "dispatcher" && json?.point === "dispatcher.response-received", { timeoutMs: 120_000, processes: [dispatcher] }); await ctx.kill(dispatcher); ctx.ok(receiver.ledger.length >= 1, "receiver obtained complete first body before dispatcher kill"); const first = receiver.ledger.find(({ raw }) => raw.length > 0); ctx.ok(first && first.json?.eventId, "delivered event has public eventId"); await sleep(LEASE_EXPIRY_MS); const replacement = await target.startDispatcher({ webhookUrl: receiver.url }); const retry = await ctx.waitFor(() => receiver.ledger.find((entry) => entry !== first && entry.json?.eventId === first.json.eventId), { timeoutMs: 120_000, label: "outbox retry after unknown ACK", processes: [replacement] }); ctx.equal(retry.raw, first.raw, "outbox retry body is byte-identical", { hardCapIds: ["STALE_WORK_OR_LOST_WORK"] }); ctx.equal(retry.json.eventId, first.json.eventId, "outbox retry preserves event identity"); ctx.equal(held.json.aggregateId, first.json.aggregateId, "barrier and payload aggregate agree");
    const versions = [cancelled.revocationVersion, 0, Math.max(0, cancelled.revocationVersion - 1), 0]; const views = await Promise.all(versions.map((knownRevocationVersion, index) => checkEntitlement(ctx, apis[index % 2].baseUrl, { tenantId: fixture.tenant.tenantId, subjectId: fixture.active.subjectId, feature: "reports", knownRevocationVersion }))); ctx.ok(views.every(({ state, revocationVersion }) => state === "DISABLED" && revocationVersion >= cancelled.revocationVersion), "reverse known-fence order cannot re-enable", { hardCapIds: ["REVOCATION_FAIL_CLOSED"] }); const snapshot = assertSnapshot(ctx, await waitForDrain(ctx, apis[0].baseUrl, { processes: [replacement] })); const ownEvents = snapshot.events.filter(({ aggregateId }) => aggregateId === first.json.aggregateId); ctx.ok(ownEvents.length > 0, "aggregate event history retained");
    return finalEvidence(ctx, { eventId: first.json.eventId, deliveryAttempts: receiver.ledger.filter(({ json }) => json?.eventId === first.json.eventId).length, revocationVersion: cancelled.revocationVersion });
  },
});

export const C_CASES = Object.freeze([R01, R02, R03, R04]);
