import {
  VIEW_KEYS, assertGrantIntervals, assertSnapshot,
  createSubscription, defineCase, exactKeys, finalEvidence, prepare, providerEvent, requireV1, runWindow,
  waitForDrain, waitForSubscription, writeFormalSeed,
} from "./helpers.mjs";
import { canonicalJson, percentile } from "../oracles/index.mjs";

const LEASE_EXPIRY_MS = 3_300;

async function sleep(milliseconds) { await new Promise((resolve) => setTimeout(resolve, milliseconds)); }

function formalSubject(index) { return `formal-subject-${index}`; }

function formalSubscriptionId(index) { return `0000000a-0000-4000-8000-${(index + 1).toString(16).padStart(12, "0")}`; }

const O01 = defineCase({
  id: "OPERATE-01", fixtureFamily: "EH-F-OPERATE-DECISION-READ",
  action: "Load the exact one-hundred-thousand-subject seed and run 128 clients for sixty seconds with the frozen eighty/twenty enabled and stale-disabled mix.",
  oracle: "Throughput is at least 1500 per second, p95 at most 100ms, every EntitlementView is exact, no stale allow or 5xx occurs, and the complete snapshot remains invariant.",
  async run(ctx) {
    const fixture = ctx.fixtures.operate(); const formal = await writeFormalSeed(ctx, "entitlement-decision-read"); const target = await prepare(ctx); await target.seedFile(formal.path); const api = await target.startApi(); let staleAllows = 0; let unexpected = 0;
    const result = await runWindow({ clients: 128, seconds: 60, operation: async (index) => { const subjectIndex = index % formal.count; const disabled = subjectIndex % 5 === 0; const query = new URLSearchParams({ tenantId: formal.tenantId, subjectId: formalSubject(subjectIndex), feature: disabled ? "exports" : "reports", knownRevocationVersion: disabled ? "0" : "1" }); const response = await ctx.request(api.baseUrl, `/api/v1/entitlements/check?${query}`, { timeoutMs: 2_000 }); if (response.status !== 200) unexpected += 1; else { exactKeys(response.json, VIEW_KEYS, "formal EntitlementView"); const expected = disabled ? "DISABLED" : "ENABLED"; if (response.json.state !== expected) { if (disabled && response.json.state === "ENABLED") staleAllows += 1; else unexpected += 1; } } return response; } });
    ctx.ok(result.throughput >= 1_500, `decision throughput ${result.throughput.toFixed(1)} >= 1500`, { hardCapIds: ["REVOCATION_FAIL_CLOSED"] }); ctx.ok(result.p95Ms <= 100, `decision p95 ${result.p95Ms.toFixed(1)}ms <= 100ms`); ctx.equal(staleAllows, 0, "zero stale-fence allows", { hardCapIds: ["REVOCATION_FAIL_CLOSED"] }); ctx.equal(unexpected, 0, "zero unexpected responses or 5xx"); ctx.equal([...result.statuses.entries()], [[200, result.completed]], "all formal checks return 200");
    const snapshot = assertSnapshot(ctx, await ctx.snapshot(api.baseUrl, { timeoutMs: 120_000 })); ctx.equal(snapshot.resources.subscriptions.length, formal.count, "full one-hundred-thousand Subscription population retained"); ctx.equal(snapshot.resources.entitlementGrants.length, formal.count, "full Grant population retained"); ctx.equal(snapshot.resources.revocationFences.length, formal.count, "full fence population retained"); ctx.equal(snapshot.work.filter(({ terminal }) => !terminal).length, 0, "no pending Work after decision-only load");
    return finalEvidence(ctx, { operations: result.completed, throughput: result.throughput, p95Ms: result.p95Ms, staleAllows });
  },
});

const O02 = defineCase({
  id: "OPERATE-02", fixtureFamily: "EH-F-OPERATE-LIFECYCLE",
  action: "Load exactly twenty thousand subscriptions, issue the full upgrade, downgrade, cancel and refund operation mix through two APIs at concurrency sixty-four, then fully reconcile.",
  oracle: "Mutation throughput is at least 100 per second with p95 at most 750ms, and complete reconciliation finds no overlapping Grant, excess Refund, duplicate identity, or fence regression.",
  async run(ctx) {
    const formal = await writeFormalSeed(ctx, "upgrade-refund-race"); const target = await prepare(ctx); await target.seedFile(formal.path); const apis = [await target.startApi(), await target.startApi()]; const indexes = Array.from({ length: formal.count }, (_, index) => index); const started = performance.now(); const results = await ctx.concurrent(indexes, 64, async (index) => { const baseUrl = apis[index % 2].baseUrl; const subscriptionId = formalSubscriptionId(index); if (index % 4 === 0) return ctx.mutate(baseUrl, `/api/v1/subscriptions/${subscriptionId}/change-plan`, ctx.key(`perf-upgrade:${index}`), { toPlanRevisionId: formal.proRevisionId, expectedSequence: 1 }); if (index % 4 === 1) return ctx.mutate(baseUrl, `/api/v1/subscriptions/${subscriptionId}/change-plan`, ctx.key(`perf-downgrade:${index}`), { toPlanRevisionId: formal.basicRevisionId, expectedSequence: 1 }); if (index % 4 === 2) return ctx.mutate(baseUrl, `/api/v1/subscriptions/${subscriptionId}/cancel`, ctx.key(`perf-cancel:${index}`), { expectedSequence: 1 }); return ctx.mutate(baseUrl, `/api/v1/subscriptions/${subscriptionId}/refunds`, ctx.key(`perf-refund:${index}`), { amountMinor: 500, currency: "USD", providerRequestId: `perf-refund-${index}` }); }); const durationSeconds = (performance.now() - started) / 1_000; const p95Ms = percentile(results.map(({ durationMs }) => durationMs), 0.95); const throughput = results.length / durationSeconds; ctx.ok(results.every(({ status }) => status === 200), "all twenty-thousand lifecycle operations succeed"); ctx.ok(throughput >= 100, `lifecycle throughput ${throughput.toFixed(1)} >= 100`); ctx.ok(p95Ms <= 750, `lifecycle p95 ${p95Ms.toFixed(1)}ms <= 750ms`);
    const refundIndexes = indexes.filter((index) => index % 4 === 3); await ctx.concurrent(refundIndexes, 64, (index) => providerEvent(ctx, apis[index % 2].baseUrl, { providerEventId: `perf-refund-event-${index}`, providerRequestId: `perf-refund-${index}`, kind: "REFUND", outcome: "SUCCEEDED", occurredAt: ctx.at({ seconds: index }) }, { key: ctx.key(`perf-refund-event:${index}`) })); const upgradeIds = new Set(indexes.filter((index) => index % 4 === 0).map(formalSubscriptionId)); const workers = await Promise.all([target.startWorker(), target.startWorker()]); const settled = await ctx.waitFor(async () => { const value = await ctx.snapshot(apis[0].baseUrl, { timeoutMs: 120_000 }); const upgradesApplied = value.resources.subscriptions.filter((_, index) => index % 4 === 0).every(({ planRevisionId }) => planRevisionId === formal.proRevisionId); const cancelsApplied = value.resources.subscriptions.filter((_, index) => index % 4 === 2).every(({ state }) => state === "CANCELLED"); const refundsApplied = value.resources.refunds.length === refundIndexes.length && value.resources.refunds.every(({ state }) => state === "SUCCEEDED"); const eligibleWorkDrained = value.work.filter(({ aggregateId, kind }) => kind !== "PLAN_CHANGE_APPLY" || upgradeIds.has(aggregateId)).every(({ terminal }) => terminal); return upgradesApplied && cancelsApplied && refundsApplied && eligibleWorkDrained ? value : false; }, { timeoutMs: 180_000, intervalMs: 250, label: "twenty-thousand lifecycle reconciliation", processes: workers }); const snapshot = assertSnapshot(ctx, settled); ctx.equal(snapshot.resources.subscriptions.length, formal.count, "full lifecycle population retained"); ctx.ok(snapshot.resources.subscriptions.filter((_, index) => index % 4 === 0).every(({ planRevisionId }) => planRevisionId === formal.proRevisionId), "every immediate upgrade applies"); ctx.ok(snapshot.resources.subscriptions.filter((_, index) => index % 4 === 2).every(({ state }) => state === "CANCELLED"), "every cancel reaches terminal"); ctx.equal(snapshot.resources.planChanges.filter(({ kind, state }) => kind === "DOWNGRADE" && state === "SCHEDULED").length, formal.count / 4, "every downgrade remains one authoritative schedule"); ctx.equal(snapshot.resources.refunds.length, refundIndexes.length, "one Refund per refund operation"); ctx.equal(new Set(snapshot.resources.refunds.map(({ providerRequestId }) => providerRequestId)).size, refundIndexes.length, "Refund provider identities are unique"); ctx.ok(snapshot.resources.refunds.every(({ state }) => state === "SUCCEEDED"), "every provider-confirmed Refund resolves"); assertGrantIntervals(snapshot.resources.entitlementGrants); ctx.ok(snapshot.resources.refunds.every(({ amountMinor }) => amountMinor === 500), "frozen operation mix is not diluted");
    return finalEvidence(ctx, { operations: results.length, throughput, p95Ms, refunds: refundIndexes.length });
  },
});

const O03 = defineCase({
  id: "OPERATE-03", fixtureFamily: "EH-F-OPERATE-EXPIRY-RECOVERY",
  action: "Load fifty thousand due subscriptions, kill two distinct claimed Workers, wait for lease expiry, recover with four replacements within ninety seconds, and check every subject on both APIs.",
  oracle: "All Work drains, every Subscription and Grant closes once, every one of one-hundred-thousand access checks denies, and no stale owner, missing subject, or regressed fence survives.",
  async run(ctx) {
    const formal = await writeFormalSeed(ctx, "expiry-revocation-recovery"); const target = await prepare(ctx); await target.seedFile(formal.path); const apis = [await target.startApi(), await target.startApi()]; const expire = await ctx.mutate(apis[0].baseUrl, "/api/v1/admin/expire-due", ctx.key("formal-expire-due"), {}); ctx.equal(expire.status, 200, "formal expire-due accepted"); const barrier = await ctx.barrier({ hold: ({ processRole, point }) => processRole === "worker" && point === "worker.claimed" }); const env = { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token }; const doomed = await Promise.all([target.startWorker({ env }), target.startWorker({ env })]); const first = await barrier.waitFor(({ json }) => json?.point === "worker.claimed", { timeoutMs: 120_000, processes: doomed }); const second = await barrier.waitFor(({ json }) => json?.point === "worker.claimed" && json.workId !== first.json.workId, { timeoutMs: 120_000, processes: doomed }); ctx.ok(first.json.workId !== second.json.workId, "two workers claim distinct expiry Work"); const killedAt = performance.now(); await Promise.all(doomed.map((worker) => ctx.kill(worker))); await sleep(LEASE_EXPIRY_MS); const replacements = await Promise.all(Array.from({ length: 4 }, () => target.startWorker())); const drained = await waitForDrain(ctx, apis[0].baseUrl, { predicate: ({ kind }) => kind === "SUBSCRIPTION_EXPIRE", timeoutMs: 90_000, processes: replacements, label: "fifty-thousand expiry recovery" }); const recoverySeconds = (performance.now() - killedAt) / 1_000; ctx.ok(recoverySeconds <= 90, `expiry backlog recovery ${recoverySeconds.toFixed(1)}s <= 90s`, { hardCapIds: ["STALE_WORK_OR_LOST_WORK"] }); ctx.equal(drained.resources.subscriptions.filter(({ state }) => state === "EXPIRED").length, formal.count, "all fifty-thousand subscriptions expire"); ctx.ok(drained.resources.entitlementGrants.every(({ validUntil }) => validUntil !== null), "all fifty-thousand Grants close");
    const subjects = Array.from({ length: formal.count }, (_, index) => index); let failures = 0; await ctx.concurrent(subjects, 256, async (index) => { const queries = apis.map(async (api) => { const query = new URLSearchParams({ tenantId: formal.tenantId, subjectId: formalSubject(index), feature: "reports", knownRevocationVersion: "0" }); const response = await ctx.request(api.baseUrl, `/api/v1/entitlements/check?${query}`, { timeoutMs: 2_000 }); if (response.status !== 200 || response.json?.state !== "DISABLED" || response.json.revocationVersion < 2) failures += 1; }); await Promise.all(queries); }); ctx.equal(failures, 0, "every expired subject denies on both APIs", { hardCapIds: ["REVOCATION_FAIL_CLOSED", "STALE_WORK_OR_LOST_WORK"] }); const snapshot = assertSnapshot(ctx, await ctx.snapshot(apis[1].baseUrl, { timeoutMs: 120_000 })); ctx.equal(snapshot.resources.revocationFences.length, formal.count, "full recovered fence population retained"); ctx.ok(snapshot.work.filter(({ kind }) => kind === "SUBSCRIPTION_EXPIRE").every(({ terminal }) => terminal), "expiry Work fully terminal");
    return finalEvidence(ctx, { expired: formal.count, accessChecks: formal.count * apis.length, recoverySeconds });
  },
});

const O04 = defineCase({
  id: "OPERATE-04", fixtureFamily: "EH-F-V1-FINAL-MIGRATION",
  action: "Create a frozen V1 checkpoint with individual subscriptions, UNKNOWN refund, pending Work, Event and saved replay, upgrade twice, then submit same, conflicting, unknown-member and invalid-reference seeds.",
  oracle: "FINAL preserves every V1 identity, wire, term, Grant, refund reservation, fence, Work, Event and replay while Pools stay empty and every invalid seed rejects atomically.",
  async run(ctx) {
    const fixture = ctx.fixtures.v1Final(); const v1Workspace = requireV1(ctx); const v1 = ctx.forWorkspace(v1Workspace); await v1.npm("build"); await v1.migrate(); await v1.seed(fixture.seed); const v1Api = await v1.startApi(); const originalRevision = fixture.seed.planRevisions.find(({ planId, state }) => planId === fixture.seed.plans[0].planId && state === "PUBLISHED") ?? fixture.seed.planRevisions[0]; const replayBody = { tenantId: fixture.tenant.tenantId, subjectId: "v1-omitted-kind", planRevisionId: originalRevision.planRevisionId, startMode: "TRIAL", providerRequestId: "v1-omitted-kind" }; const replay = await createSubscription(ctx, v1Api.baseUrl, replayBody, { key: fixture.savedReplayKey }); exactKeys(replay, SUBSCRIPTION_WIRE, "V1 saved Subscription replay"); const historyWorker = await v1.startWorker(); await waitForSubscription(ctx, v1Api.baseUrl, replay.subscriptionId, ["TRIALING", "ACTIVE"], [historyWorker]); await ctx.stop(historyWorker); await createSubscription(ctx, v1Api.baseUrl, { ...replayBody, subjectId: "v1-in-flight", providerRequestId: "v1-in-flight" }, { key: ctx.key("v1-in-flight") }); const before = assertSnapshot(ctx, await ctx.snapshot(v1Api.baseUrl), { final: false }); ctx.ok(before.work.some(({ terminal }) => !terminal), "V1 checkpoint contains in-flight Work"); ctx.ok(before.events.length > 0, "V1 checkpoint contains DomainEvent history"); await ctx.stop(v1Api);
    const finalTarget = ctx.forWorkspace(ctx.workspace); await finalTarget.npm("build"); await finalTarget.migrate(); await finalTarget.migrate(); const api = await finalTarget.startApi(); const upgraded = assertSnapshot(ctx, await ctx.snapshot(api.baseUrl)); const beforeResources = Object.fromEntries(Object.keys(before.resources).map((name) => [name, before.resources[name]])); ctx.equal(canonicalJson(Object.fromEntries(Object.keys(beforeResources).map((name) => [name, upgraded.resources[name]]))), canonicalJson(beforeResources), "FINAL migration preserves every V1 resource exactly", { hardCapIds: ["MIGRATION_COMPATIBILITY"] }); ctx.equal(upgraded.events, before.events, "FINAL migration preserves V1 Events"); ctx.equal(upgraded.work, before.work, "FINAL migration preserves V1 Work and leases"); ctx.equal(upgraded.resources.entitlementPools, [], "migration synthesizes no Pool"); ctx.equal(upgraded.resources.seatAssignments, [], "migration synthesizes no SeatAssignment"); const finalReplay = await createSubscription(ctx, api.baseUrl, replayBody, { key: fixture.savedReplayKey }); ctx.equal(finalReplay, replay, "FINAL returns the byte-semantic saved V1 response", { hardCapIds: ["MIGRATION_COMPATIBILITY"] });
    const beforeSeeds = await ctx.snapshot(api.baseUrl); const same = await finalTarget.seed(fixture.seed, { allowFailure: true }); ctx.equal(same.exitCode, 0, "same seed version and digest is a no-op"); const afterSame = await ctx.snapshot(api.baseUrl); ctx.equal(afterSame.resources, beforeSeeds.resources, "same seed changes no resources"); ctx.equal(afterSame.work, beforeSeeds.work, "same seed changes no Work"); ctx.equal(afterSame.events, beforeSeeds.events, "same seed changes no Event");
    const conflict = structuredClone(fixture.seed); conflict.tenants[0].name = "Conflicting Digest"; const conflictResult = await finalTarget.seed(conflict, { allowFailure: true }); ctx.ok(conflictResult.exitCode !== 0, "same seedVersion with changed digest rejects"); const unknown = { ...structuredClone(fixture.seed), seedVersion: `${fixture.seed.seedVersion}-unknown`, privateRows: [] }; const unknownResult = await finalTarget.seed(unknown, { allowFailure: true }); ctx.ok(unknownResult.exitCode !== 0, "unknown seed member rejects"); const invalid = structuredClone(fixture.seed); invalid.seedVersion = `${fixture.seed.seedVersion}-invalid-ref`; invalid.subscriptions[0].planRevisionId = ctx.uuid("missing-plan-revision"); const invalidResult = await finalTarget.seed(invalid, { allowFailure: true }); ctx.ok(invalidResult.exitCode !== 0, "invalid reference graph rejects"); const afterInvalid = await ctx.snapshot(api.baseUrl); ctx.equal(afterInvalid.resources, beforeSeeds.resources, "all invalid seeds are transactionally side-effect free", { hardCapIds: ["MIGRATION_COMPATIBILITY"] }); ctx.equal(afterInvalid.work, beforeSeeds.work, "invalid seeds create no Work"); ctx.equal(afterInvalid.events, beforeSeeds.events, "invalid seeds create no Event");
    return finalEvidence(ctx, { v1Subscriptions: before.resources.subscriptions.length, v1Work: before.work.length, v1Events: before.events.length, pools: 0 });
  },
});

const SUBSCRIPTION_WIRE = Object.freeze(["subscriptionId", "tenantId", "subjectId", "planRevisionId", "state", "periodStart", "periodEnd", "trialEndsAt", "cancelAtPeriodEnd", "pendingPlanRevisionId", "revocationVersion", "createdAt", "terminalAt", "sequence"]);

export const E_CASES = Object.freeze([O01, O02, O03, O04]);
