import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";

import { assignmentBucket,canonical,contentionSeed,createFixtureFactory,documentDigest,performanceContract,performanceSeed,v1Seed } from "../lib/fixtures.mjs";
import { assertSnapshot,percentile } from "../lib/oracle.mjs";

const options={evaluationSeed:"opaque-evaluation-seed",caseId:"REV-04",baseTime:"2035-06-01T12:00:00.000Z"};
test("fixtures are deterministic and V1 seed is closed",()=>{const left=createFixtureFactory(options),right=createFixtureFactory(options),seed=v1Seed(left,"fixture");assert.equal(left.uuid("x"),right.uuid("x"));assert.equal(left.key("x"),right.key("x"));assert.deepEqual(Object.keys(seed).sort(),["applications","auditEntries","clientObservations","configRevisions","environments","invalidations","releases","schemaVersion","seedVersion","tenants"]);assert.equal(seed.schemaVersion,1);assert.equal(seed.configRevisions[0].documentDigest,documentDigest(seed.configRevisions[0].document));});
test("canonical digest and assignment use an independent unsigned first-64-bit oracle",()=>{assert.equal(canonical({z:[1,"1"],a:{y:true,x:null}}),'{"a":{"x":null,"y":true},"z":[1,"1"]}');const input={tenantId:"t",applicationId:"a",environmentId:"e",releaseId:"r",audienceSalt:"s",clientId:"c"},bytes=createHash("sha256").update("t:a:e:r:s:c").digest(),expected=Number(bytes.readBigUInt64BE(0)%10_000n);assert.equal(assignmentBucket(input),expected);assert.notEqual(documentDigest({array:[1,2]}),documentDigest({array:[2,1]}));assert.equal(documentDigest({b:1,a:2}),documentDigest({a:2,b:1}));});
test("formal performance fixtures cannot silently scale",()=>{assert.deepEqual(performanceContract(),{fetch:{clientCount:50_000,concurrency:128,durationSeconds:60,currentEtagPercent:80,stalePercent:20,targetPerSecond:800,p95Ms:150},contention:{environmentCount:100,apiCount:2,concurrency:64,attempts:10_000,targetPerSecond:100,p95Ms:500},invalidation:{count:100_000,killedWorkers:2,replacementWorkers:4,maximumSeconds:90,convergenceSeconds:5}});const fetch=performanceSeed(createFixtureFactory(options),{environmentCount:1,clientCount:50_000}),contention=contentionSeed(createFixtureFactory(options),{environmentCount:100});assert.equal(fetch.seed.clientObservations.length,50_000);assert.equal(contention.catalogs.length,100);assert.equal(contention.seed.environments.length,300);assert.equal(percentile([9,1,3,7],0.95),9);});
test("empty FINAL snapshot enforces the exact ConfigOrbit union",()=>{assert.equal(assertSnapshot({asOf:"2035-06-01T12:00:00.000Z",resources:{tenants:[],applications:[],environments:[],configRevisions:[],releases:[],clientObservations:[],invalidations:[],auditEntries:[],promotionTrains:[],promotionStages:[]},work:[],events:[]}),true);});
