import test from 'node:test';
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import { runInNewContext } from 'node:vm';
import * as browserHelpers from '../src/task-evaluator-v2/browser.mjs';
import { performUsageUi, performCorrectionUi } from '../evaluators/transfer/metersettle/v2/cases/ui.mjs';

test('UI observation distinguishes missing request, unanswered request and network rejection, without orphan listeners', async () => {
  assert.equal(typeof browserHelpers.captureBrowserAction, 'function');
  const page = new EventEmitter();
  const request = { method: () => 'POST', url: () => 'http://test/api/action?token=PRIVATE', failure: () => ({ errorText: 'net::ERR_FAILED' }) };
  for (const [action, code] of [
    [async () => {}, 'EVALUATOR_UI_NO_MATCHING_REQUEST'],
    [async () => page.emit('request', request), 'EVALUATOR_UI_RESPONSE_TIMEOUT'],
  ]) {
    await assert.rejects(browserHelpers.captureBrowserAction(page, () => true, action, { timeoutMs: 20 }), e =>
      e.code === code && e.origin === 'evaluator' && !JSON.stringify(e.details).includes('PRIVATE'));
    assert.deepEqual(page.eventNames(), []);
  }
  const observed = await browserHelpers.captureBrowserAction(page, () => true, async () => {
    page.emit('request', request); page.emit('requestfailed', request);
  });
  assert.equal(observed.request, request); assert.equal(observed.failure, 'net::ERR_FAILED');
  assert.deepEqual(page.eventNames(), []);
  const failure = new TypeError('author mistake');
  await assert.rejects(browserHelpers.captureBrowserAction(page, () => true, async () => { throw failure; }), e => e === failure);
  assert.deepEqual(page.eventNames(), []);
});

test('actual UI drivers accept alternate semantic layouts and generated identifiers', { skip: !process.env.FRONTAL_TEST_CHROMIUM }, async t => {
  const { chromium } = await import('playwright-core');
  const browser = await chromium.launch({ executablePath: process.env.FRONTAL_TEST_CHROMIUM, headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage({ timezoneId: 'UTC' }); page.setDefaultTimeout(500);
  await page.route('http://fixture/**', r => r.fulfill({ status: 202, contentType: 'application/json', body: '{}' }));
  await page.goto('http://fixture/');
  await t.test('usage read section does not collide with usage mutation; generated event ID is observed', async () => {
    await page.setContent(`<section><h2>Meter usage</h2><button>Load usage</button></section>
      <section><h2>Usage batch</h2><form onsubmit="event.preventDefault();fetch('/api/v1/usage-batches',{method:'POST',body:JSON.stringify({tenantId:this.tenant.value,events:[{eventId:'generated-event',meterId:this.meter.value,occurredAt:new Date(this.time.value).toISOString(),quantity:Number(this.quantity.value)}]})})">
      <label>Tenant<input name=tenant></label><label>Meter<input name=meter></label><label>Occurred at<input name=time type=datetime-local></label><label>Quantity<input name=quantity></label><button>Accept usage</button></form></section>`);
    const family = { tenant: { tenantId: 't' }, meters: [{ meterId: 'm' }], events: [{ eventId: 'seed', meterId: 'm', occurredAt: '2035-01-01T00:00:00.000Z', quantity: 2 }] };
    const body = await performUsageUi(page, family);
    assert.equal(body.events[0].eventId, 'generated-event'); assert.equal(body.events[0].quantity, 1);
    await page.locator('form').evaluate(form => {
      form.onsubmit = event => { event.preventDefault(); fetch('/api/v1/usage-batches', { method: 'POST',
        body: JSON.stringify({ tenantId: 't', events: [{ eventId: 'generated-wrong', meterId: 'm', quantity: 999,
          occurredAt: '2035-01-01T00:00:00.000Z' }] }) }); };
    });
    await assert.rejects(performUsageUi(page, family), e => e.origin === 'candidate' && /quantity/.test(e.message),
      'accepting UI-generated IDs must not accept different requested business data');
  });
  await t.test('correction ID and timestamp may be generated by UI, but requested business values must be preserved', async () => {
    await page.setContent(`<section><h2>Correction</h2><form onsubmit="event.preventDefault();fetch('/api/v1/correction-batches',{method:'POST',body:JSON.stringify({tenantId:this.tenant.value,corrections:[{correctionId:'generated-correction',sourceEventId:this.source.value,quantityDelta:Number(this.delta.value),reason:this.reason.value,occurredAt:new Date().toISOString()}]})})">
      <label>Tenant<input name=tenant></label><label>Source event<input name=source></label><label>Quantity delta<input name=delta></label><label>Reason<input name=reason></label><button>Create correction</button></form></section>`);
    const correction = await performCorrectionUi(page, 't', { correctionId: 'not-required-ui-input', sourceEventId: 'e', quantityDelta: 2, reason: 'repair', occurredAt: '2035-01-01T00:00:00.000Z' });
    assert.equal(correction.correctionId, 'generated-correction'); assert.equal(correction.quantityDelta, 2);
  });
  await t.test('actual Flag history navigation never clicks Create Revision; tab and inline layouts work', async () => {
    const source = ts.createSourceFile('d.mjs', readFileSync(new URL('../evaluators/transfer/flagfoundry/v2/cases/d.mjs', import.meta.url), 'utf8'), ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
    const declaration = source.statements.find(n => ts.isFunctionDeclaration(n) && n.name?.text === 'navigateVisible').getText(source);
    const { navigateVisible } = runInNewContext(declaration + ';({navigateVisible})', { ...browserHelpers });
    await page.setContent('<button disabled>Create Revision</button><button role=tab onclick="this.textContent=\'opened\'">History</button>');
    await navigateVisible(page, /revision|history/i);
    assert.equal(await page.getByRole('tab', { name: 'opened' }).count(), 1);
    await page.setContent('<button disabled>Create Revision</button><section><h2>Revision history</h2></section>');
    await navigateVisible(page, /revision|history/i);
    await page.setContent('<button>View revision A</button><button>View revision B</button>');
    await assert.rejects(navigateVisible(page, /revision/i), e => e.code === 'EVALUATOR_UI_TARGET_AMBIGUOUS');
  });
  await t.test('actual Flag creation scopes duplicate Project ID and Key labels to its business form', async () => {
    const source = ts.createSourceFile('d.mjs', readFileSync(new URL('../evaluators/transfer/flagfoundry/v2/cases/d.mjs', import.meta.url), 'utf8'), ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
    const names = ['uiCreateFlag', 'fill', 'enter', 'click', 'visible'];
    const code = source.statements.filter(n => ts.isFunctionDeclaration(n) && names.includes(n.name?.text)).map(n => n.getText(source)).join('\n');
    const { uiCreateFlag } = runInNewContext(code + ';({uiCreateFlag})', { ...browserHelpers });
    await page.setContent(`<section><h2>Create Flag</h2><form onsubmit="event.preventDefault();this.dataset.submitted='yes'">
      <label>Project ID<input></label><label>Flag key<input></label><label>Flag type<select><option>STRING</option></select></label><button>Create flag</button></form></section>
      <section><h2>Evaluation</h2><label>Project ID<input></label><label>Flag key<input></label><button>Evaluate</button></section>`);
    await uiCreateFlag(page, 'selected-project', 'selected-key', 'STRING');
    assert.equal(await page.locator('form').getAttribute('data-submitted'), 'yes');
    assert.equal(await page.getByLabel('Project ID').nth(0).inputValue(), 'selected-project');
    assert.equal(await page.getByLabel('Project ID').nth(1).inputValue(), '');
  });
});
