import {
  FINAL_RESOURCE_KEYS, acceptOffer, assertFrozenTotals, assertOffer, assertSeatConservation, assertSnapshot,
  assertWaitlist, cancelWaitlist, checkoutHold, createHold, createWaitlist, defineCase, expectError,
  finalEvidence, launchBrowser, prepare, reconcilePayment, startProviderDouble, startSeatWorker,
  visibleControl, visibleField, waitForOffer, waitForPayment,
} from "./helpers.mjs";

const PUBLIC_PATHS = Object.freeze([
  "/api/v1/tenants", "/api/v1/venues", "/api/v1/events", "/api/v1/events/{eventId}/zones", "/api/v1/events/{eventId}/seats", "/api/v1/zones/{zoneId}/price-versions", "/api/v1/price-versions/{priceVersionId}/activate", "/api/v1/events/{eventId}/on-sale", "/api/v1/events/{eventId}/availability", "/api/v1/holds", "/api/v1/holds/{holdId}", "/api/v1/holds/{holdId}/cancel", "/api/v1/holds/{holdId}/checkout", "/api/v1/orders/{orderId}", "/api/v1/payment-intents/{paymentIntentId}/reconcile", "/api/v1/provider/receipts", "/api/v1/verification-snapshot", "/api/v1/waitlist-entries", "/api/v1/waitlist-entries/{entryId}/cancel", "/api/v1/seat-offers/{offerId}", "/api/v1/seat-offers/{offerId}/accept", "/api/v1/seat-offers/{offerId}/decline",
]);

const D01 = defineCase({
  id: "D-01", fixtureFamily: "SR-F-HTTP-OPENAPI",
  action: "Parse live OpenAPI 3.1, exercise every Manager route that has a reachable resource, and submit malformed, unknown-field, boundary, missing-ID, and cross-tenant V1 and waitlist requests.",
  oracle: "Runtime and OpenAPI publish exact methods, statuses, closed resource shapes, strict media and JSON validation, stable error envelopes, and tenant isolation; rejected reads or mutations have no side effect.",
  async run(ctx) {
    const fixture = ctx.fixtures.waitlist(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi(); const openapiResponse = await ctx.request(api.baseUrl, "/openapi.json"); ctx.equal(openapiResponse.status, 200, "OpenAPI status"); ctx.ok(/^3\.1(?:\.\d+)?$/u.test(openapiResponse.json?.openapi), "OpenAPI is 3.1"); for (const path of PUBLIC_PATHS) ctx.ok(Object.hasOwn(openapiResponse.json.paths ?? {}, path), `OpenAPI publishes ${path}`); ctx.ok(Object.hasOwn(openapiResponse.json.paths["/api/v1/waitlist-entries"], "post"), "OpenAPI publishes waitlist create POST"); ctx.ok(Object.hasOwn(openapiResponse.json.paths["/api/v1/seat-offers/{offerId}/accept"], "post"), "OpenAPI publishes Offer accept POST"); ctx.ok(Object.hasOwn(openapiResponse.json.paths["/api/v1/seat-offers/{offerId}/decline"], "post"), "OpenAPI publishes Offer decline POST");
    const before = await ctx.snapshot(api.baseUrl); const unknown = await ctx.mutate(api.baseUrl, "/api/v1/waitlist-entries", ctx.key("unknown"), { ...fixture.waitlistPayload("unknown"), privateFlag: true }); expectError(ctx, unknown, 400, "INVALID_REQUEST", "unknown Waitlist field"); const invalidCount = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("count", { seatCount: 9 }), { allowFailure: true }); expectError(ctx, invalidCount, 400, "WAITLIST_INVALID", "waitlist count boundary"); const duplicateZones = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("zones", { allowedZoneIds: [fixture.zones.zoneA.zoneId, fixture.zones.zoneA.zoneId] }), { allowFailure: true }); expectError(ctx, duplicateZones, 400, "WAITLIST_INVALID", "duplicate allowed zones"); const crossTenant = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("cross", { tenantId: fixture.otherTenant.tenantId }), { allowFailure: true }); expectError(ctx, crossTenant, 400, "WAITLIST_INVALID", "cross-tenant Event"); const malformed = await ctx.request(api.baseUrl, "/api/v1/waitlist-entries", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": ctx.key("malformed") }, raw: "{" }); expectError(ctx, malformed, 400, "INVALID_REQUEST", "malformed JSON"); const unsupported = await ctx.request(api.baseUrl, "/api/v1/waitlist-entries", { method: "POST", headers: { "content-type": "text/plain", "idempotency-key": ctx.key("unsupported") }, raw: "{}" }); ctx.equal(unsupported.status, 415, "unsupported media type"); const after = await ctx.snapshot(api.baseUrl); ctx.equal(after.resources.waitlistEntries, before.resources.waitlistEntries, "rejected Manager requests create no Entry"); ctx.equal(after.resources.seatOffers, before.resources.seatOffers, "rejected Manager requests create no Offer"); ctx.equal(after.work, before.work, "rejected Manager requests create no Work");
    const entry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("public", { seatCount: 2 })); assertWaitlist(entry); const worker = await startSeatWorker(ctx, provider); const matched = await waitForOffer(ctx, api.baseUrl, entry.waitlistEntryId, [worker]); const offerResponse = await ctx.request(api.baseUrl, `/api/v1/seat-offers/${matched.offer.seatOfferId}`); ctx.equal(offerResponse.status, 200, "known Offer GET"); assertOffer(offerResponse.json); const missing = await ctx.request(api.baseUrl, `/api/v1/seat-offers/${ctx.uuid("missing-offer")}`); expectError(ctx, missing, 404, "NOT_FOUND", "missing Offer"); const accepted = await acceptOffer(ctx, api.baseUrl, matched.offer.seatOfferId); ctx.equal(accepted.offer.state, "ACCEPTED", "accept exact Offer state"); const repeated = await ctx.mutate(api.baseUrl, `/api/v1/seat-offers/${matched.offer.seatOfferId}/decline`, ctx.key("after-accept"), {}); expectError(ctx, repeated, 409, "SEAT_OFFER_TERMINAL", "decline after accept"); const final = await ctx.snapshot(api.baseUrl); assertSeatConservation(final);
    return finalEvidence(ctx, { openapiPaths: PUBLIC_PATHS.length, waitlistEntryId: entry.waitlistEntryId, seatOfferId: matched.offer.seatOfferId });
  },
});

async function browserMutation(page, controlPattern, pathPattern) { const response = page.waitForResponse((value) => value.request().method() === "POST" && pathPattern.test(new URL(value.url()).pathname), { timeout: 30_000 }); const control = await visibleControl(page, ["button", "link"], [controlPattern]); await control.click(); return response; }

const D02 = defineCase({
  id: "D-02", fixtureFamily: "SR-F-BROWSER-BOOKING",
  action: "Use production Chromium and visible accessible controls to select seeded seats, create a Hold, checkout through TIMEOUT, reconcile UNKNOWN, refresh, and compare the UI with public HTTP and Provider ledgers.",
  oracle: "The browser calls only public HTTP, displays authoritative availability, frozen price, server expiry, errors and terminal payment state after refresh, and never uses client-only ownership or mocked payment.",
  async run(ctx) {
    const fixture = ctx.fixtures.browser(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const dev = await target.startApi({ env: { PROVIDER_BASE_URL: provider.baseUrl } }); const worker = await startSeatWorker(ctx, provider); const { page } = await launchBrowser(ctx, dev.baseUrl); const observed = []; page.on("request", (request) => { const path = new URL(request.url()).pathname; if (path.startsWith("/api/")) observed.push({ method: request.method(), path }); }); ctx.ok(await page.getByText(/Main Event|SeatReserve|座位预订/iu).count() > 0, "production UI renders Event or application identity"); const seatControl = await visibleControl(page, ["button", "checkbox"], [/\bA\s*1\b|seat\s*A\s*1|座位.*A.?1/iu]); await seatControl.click(); const customer = await visibleField(page, [/customer|customer ref|客户|顾客/iu]); await customer.fill("browser-customer"); const holdResponse = await browserMutation(page, /hold|reserve|锁定|预留/iu, /^\/api\/v1\/holds$/u); ctx.equal(holdResponse.status(), 200, "UI Hold uses public endpoint"); const hold = await holdResponse.json();
    const scenario = await visibleField(page, [/provider scenario|payment scenario|支付场景|支付结果/iu]).catch(() => undefined); if (scenario) await scenario.selectOption("TIMEOUT"); const checkoutResponse = await browserMutation(page, /checkout|pay|结算|支付/iu, /^\/api\/v1\/holds\/[^/]+\/checkout$/u); ctx.equal(checkoutResponse.status(), 200, "UI checkout uses public endpoint"); const checkout = await checkoutResponse.json(); const unknown = await waitForPayment(ctx, dev.baseUrl, checkout.paymentIntent.paymentIntentId, "UNKNOWN", [worker]); await page.reload({ waitUntil: "networkidle" }); ctx.ok(await page.getByText(/unknown|pending|uncertain|未知|待确认/iu).count() > 0, "refresh shows authoritative uncertain payment"); const reconcileResponse = await browserMutation(page, /reconcile|resolve|retry status|对账|查询结果/iu, /^\/api\/v1\/payment-intents\/[^/]+\/reconcile$/u); ctx.equal(reconcileResponse.status(), 200, "UI reconcile uses public endpoint"); const settled = await waitForPayment(ctx, dev.baseUrl, checkout.paymentIntent.paymentIntentId, ["SUCCEEDED", "FAILED"], [worker]); await page.reload({ waitUntil: "networkidle" }); ctx.ok(await page.getByText(settled.payment.state === "SUCCEEDED" ? /confirmed|success|已确认|成功/iu : /cancelled|failed|取消|失败/iu).count() > 0, "refresh shows authoritative terminal payment"); ctx.ok(observed.length > 0 && observed.every(({ path }) => !/(?:internal|private|admin|verification-snapshot)/iu.test(path)), "UI calls only public non-admin routes"); ctx.equal(unknown.snapshot.resources.holds.find(({ holdId }) => holdId === hold.holdId).state, "CHECKOUT", "UI UNKNOWN retains Hold"); assertSeatConservation(settled.snapshot);
    return finalEvidence(ctx, { holdId: hold.holdId, paymentIntentId: checkout.paymentIntent.paymentIntentId, publicRequests: observed.length });
  },
});

const D03 = defineCase({
  id: "D-03", fixtureFamily: "SR-F-BROWSER-WAITLIST",
  action: "Use production Chromium to create and cancel a WaitlistEntry with visible controls, verify its public requests, and independently validate a known SeatOffer timer, frozen items, accept and decline controls where contractually reachable.",
  oracle: "Visible Manager controls reflect authoritative Entry and Offer state, exact 120-second timer and frozen price without admin data or client memory; refresh discovery is reported fail-closed because no user read seam is published.",
  async run(ctx) {
    const fixture = ctx.fixtures.browser(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const dev = await target.startApi(); const worker = await startSeatWorker(ctx, provider); const { page } = await launchBrowser(ctx, dev.baseUrl); const observed = []; page.on("request", (request) => { const path = new URL(request.url()).pathname; if (path.startsWith("/api/")) observed.push(path); }); const waitlistTab = await visibleControl(page, ["button", "link", "tab"], [/waitlist|候补|候选/iu]); await waitlistTab.click(); const customer = await visibleField(page, [/customer|customer ref|客户|顾客/iu]); await customer.fill("browser-waitlist"); const count = await visibleField(page, [/seat count|number of seats|座位数量|席位数/iu]); await count.fill("2"); const cap = await visibleField(page, [/maximum|price cap|max unit|最高价格|价格上限/iu]); await cap.fill("6000"); const expiry = await visibleField(page, [/expires|expiry|截止|到期/iu]); await expiry.fill(fixture.waitlistPayload("browser-expiry").expiresAt); const createResponse = await browserMutation(page, /join|create.*waitlist|候补|加入/iu, /^\/api\/v1\/waitlist-entries$/u); ctx.equal(createResponse.status(), 201, "UI creates Entry through public API"); const entry = await createResponse.json(); assertWaitlist(entry); const cancelResponse = await browserMutation(page, /cancel.*waitlist|leave.*waitlist|取消候补|退出候补/iu, new RegExp(`^/api/v1/waitlist-entries/${entry.waitlistEntryId}/cancel$`, "u")); ctx.equal(cancelResponse.status(), 200, "UI cancels Entry through public API"); const cancelled = await cancelResponse.json(); ctx.equal(cancelled.state, "CANCELLED", "UI renders authoritative cancellation response");
    const reachable = await createWaitlist(ctx, dev.baseUrl, fixture.waitlistPayload("known-offer", { seatCount: 2 })); const matched = await waitForOffer(ctx, dev.baseUrl, reachable.waitlistEntryId, [worker]); ctx.equal(Date.parse(matched.offer.expiresAt) - Date.parse(matched.offer.createdAt), 120_000, "known public Offer has exact timer"); ctx.equal(matched.offer.items.reduce((sum, item) => sum + item.unitAmountMinor + item.feeMinor, 0), matched.offer.totalMinor, "known public Offer frozen total"); let controlledOffer = false; const offerIdField = await visibleField(page, [/offer id|offer code|候补邀请.*id|邀请编号/iu]).catch(() => undefined); if (offerIdField) { const loadKnownOffer = async (offerId) => { await (await visibleField(page, [/offer id|offer code|候补邀请.*id|邀请编号/iu])).fill(offerId); const response = page.waitForResponse((value) => value.request().method() === "GET" && new URL(value.url()).pathname === `/api/v1/seat-offers/${offerId}`, { timeout: 30_000 }); await (await visibleControl(page, ["button", "link"], [/load.*offer|find.*offer|查看.*邀请|查询.*邀请/iu])).click(); ctx.equal((await response).status(), 200, "UI loads known Offer through public GET"); }; await loadKnownOffer(matched.offer.seatOfferId); ctx.ok(await page.getByText(/120|2:00|expires|countdown|倒计时|过期/iu).count() > 0, "UI displays Offer countdown"); const accepted = await browserMutation(page, /accept|接受/iu, new RegExp(`^/api/v1/seat-offers/${matched.offer.seatOfferId}/accept$`, "u")); ctx.equal(accepted.status(), 201, "UI accepts known Offer through public API"); const declineEntry = await createWaitlist(ctx, dev.baseUrl, fixture.waitlistPayload("known-decline", { seatCount: 1 })); const declineMatch = await waitForOffer(ctx, dev.baseUrl, declineEntry.waitlistEntryId, [worker]); await loadKnownOffer(declineMatch.offer.seatOfferId); const declined = await browserMutation(page, /decline|reject|拒绝/iu, new RegExp(`^/api/v1/seat-offers/${declineMatch.offer.seatOfferId}/decline$`, "u")); ctx.equal(declined.status(), 200, "UI declines known Offer through public API"); controlledOffer = true; }
    ctx.ok(observed.every((path) => !/(?:verification-snapshot|internal|private|admin)/iu.test(path)), "browser never consumes admin snapshot or private route"); const final = await ctx.snapshot(dev.baseUrl); assertSeatConservation(final); assertFrozenTotals(final);
    return ctx.pass({ blockedAssertions: [{ assertionId: "SR-D03-REFRESH-OFFER-DISCOVERY", blockedBy: "SPEC-GAP-SR-01", policy: "fail-closed-diagnostic" }], evidence: [{ kind: "seatreserve-case-summary", waitlistEntryId: entry.waitlistEntryId, knownSeatOfferId: matched.offer.seatOfferId, controlledOffer, publicRequests: observed.length }] });
  },
});

const D04 = defineCase({
  id: "D-04", fixtureFamily: "SR-F-FINAL-SNAPSHOT",
  action: "Create live Hold, UNKNOWN payment, WAITING Entry, ACTIVE Offer, terminal Offer and cancellation paths, then request one authorized FINAL verification snapshot.",
  oracle: "One asOf snapshot has the exact sorted FINAL resource union and retained Work and Events, independently closes every live owner and frozen total, and omits credentials, raw Provider bodies, tokens and private paths.",
  async run(ctx) {
    const fixture = ctx.fixtures.payment(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi(); const worker = await startSeatWorker(ctx, provider); const held = await createHold(ctx, api.baseUrl, fixture.holdPayload("snapshot-held", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`)])); const paymentHold = await createHold(ctx, api.baseUrl, fixture.holdPayload("snapshot-payment", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:2`)])); const checkout = await checkoutHold(ctx, api.baseUrl, paymentHold.holdId, "TIMEOUT"); await waitForPayment(ctx, api.baseUrl, checkout.paymentIntent.paymentIntentId, "UNKNOWN", [worker]); const offeredEntry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("snapshot-offer", { seatCount: 2 })); const matched = await waitForOffer(ctx, api.baseUrl, offeredEntry.waitlistEntryId, [worker]); const waitingEntry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("snapshot-wait", { seatCount: 8, maxUnitTotalMinor: 100 })); const cancelledEntry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("snapshot-cancel", { seatCount: 1, maxUnitTotalMinor: 100 })); await cancelWaitlist(ctx, api.baseUrl, cancelledEntry.waitlistEntryId); const snapshot = assertSnapshot(ctx, await ctx.snapshot(api.baseUrl)); ctx.equal(Object.keys(snapshot.resources).sort(), [...FINAL_RESOURCE_KEYS].sort(), "snapshot exact FINAL resources"); ctx.ok(snapshot.asOf.endsWith("Z"), "snapshot publishes UTC asOf"); ctx.ok(snapshot.resources.holds.some(({ holdId }) => holdId === held.holdId), "snapshot contains live Hold"); ctx.ok(snapshot.resources.paymentIntents.some(({ paymentIntentId, state }) => paymentIntentId === checkout.paymentIntent.paymentIntentId && state === "UNKNOWN"), "snapshot contains UNKNOWN Payment"); ctx.ok(snapshot.resources.seatOffers.some(({ seatOfferId, state }) => seatOfferId === matched.offer.seatOfferId && state === "ACTIVE"), "snapshot contains ACTIVE Offer"); ctx.ok(snapshot.resources.waitlistEntries.some(({ waitlistEntryId, state }) => waitlistEntryId === waitingEntry.waitlistEntryId && state === "WAITING"), "snapshot contains WAITING Entry"); assertSeatConservation(snapshot); assertFrozenTotals(snapshot);
    return finalEvidence(ctx, { asOf: snapshot.asOf, resourceCount: Object.values(snapshot.resources).reduce((sum, values) => sum + values.length, 0), workCount: snapshot.work.length, eventCount: snapshot.events.length });
  },
});

export const D_CASES = Object.freeze([D01, D02, D03, D04]);
