import assert from "node:assert/strict";

import { documentDiff, documentDigest, mergePreview } from "../oracles/index.mjs";
import {
  BRANCH_KEYS, CHANGE_KEYS, DOCUMENT_KEYS, MERGE_REQUEST_KEYS, REVISION_KEYS,
  applyChange, approveMergeRequest, assertBranch, assertDocument, assertMergeRequest, assertRevision,
  assertSnapshot, chooseOption, clickControl, createBranch, createDocument, createMergeRequest, expectError,
  fillField, finalEvidence, getJson, guardedCase, launchBrowser, mergeRequest, prepare, resource, waitForDrain,
} from "./helpers.mjs";

function dereference(openapi, schema, seen = new Set()) {
  if (!schema?.$ref) return schema;
  if (seen.has(schema.$ref)) throw new Error(`cyclic OpenAPI schema ${schema.$ref}`);
  const name = schema.$ref.split("/").at(-1);
  return dereference(openapi, openapi.components?.schemas?.[name], new Set([...seen, schema.$ref]));
}

function assertResponseSchema(openapi, path, method, status, keys) {
  const response = openapi.paths?.[path]?.[method]?.responses?.[String(status)];
  assert.ok(response, `OpenAPI misses ${status} ${method.toUpperCase()} ${path}`);
  const schema = dereference(openapi, response.content?.["application/json"]?.schema);
  assert.ok(schema, `OpenAPI misses JSON schema for ${method.toUpperCase()} ${path}`);
  assert.deepEqual(new Set(schema.required ?? []), new Set(keys), `${path} required fields`);
  assert.deepEqual(Object.keys(schema.properties ?? {}).sort(), [...keys].sort(), `${path} response fields`);
  assert.equal(schema.additionalProperties, false, `${path} response must be closed`);
}

const D01 = guardedCase({
  id: "D-01",
  fixtureFamily: "MB-F-UI-V1-EDITOR",
  action: "Use production Chromium visible controls for insert, replace, move, delete, offline replay, conflict, history and diff.",
  oracle: "Refresh and compare the rendered blocks, conflict and immutable history evidence with public HTTP and PostgreSQL snapshot state.",
  async run(ctx) {
    const target = await prepare(ctx); const api = await target.startApi(); const worker = await target.startWorker(); const a = ctx.fixtures.block("d01:a", "alpha"); const b = ctx.fixtures.block("d01:b", "beta"); const document = await createDocument(ctx, api.baseUrl, { title: "Browser V1 editor", blocks: [a, b] }); const { browserContext, page } = await launchBrowser(ctx, api.baseUrl);
    await clickControl(page, [/Browser V1 editor/u]); await page.getByText("alpha", { exact: false }).waitFor({ state: "visible" });
    const xId = ctx.uuid("d01:x"); await clickControl(page, [/Insert(?: Block)?/iu, /Add Block/iu]); await fillField(page, [/Block ID/iu, /Identifier/iu], xId).catch(() => undefined); await fillField(page, [/Text/iu, /Block text/iu], "inserted"); await browserContext.setOffline(true); await clickControl(page, [/Apply/iu, /Save/iu, /Insert/iu]); await page.getByText(/offline|retry|queued/iu).first().waitFor({ state: "visible" }); await browserContext.setOffline(false); await clickControl(page, [/Retry|Replay|Sync/iu]); await page.getByText("inserted", { exact: false }).first().waitFor({ state: "visible" });
    await clickControl(page, [/Replace/iu, /Edit Block/iu]); await chooseOption(page, [/Block/iu, /Target/iu], "beta").catch(async () => fillField(page, [/Block ID/iu, /Target/iu], b.blockId)); await fillField(page, [/Expected text/iu], "beta").catch(() => undefined); await fillField(page, [/New text/iu, /Replacement/iu], "beta-2"); await clickControl(page, [/Apply/iu, /Save/iu, /Replace/iu]); await page.getByText("beta-2", { exact: false }).waitFor({ state: "visible" });
    await clickControl(page, [/Move/iu]); await chooseOption(page, [/Block to move/iu, /Target Block/iu], "inserted").catch(async () => fillField(page, [/Block ID/iu], xId)); await chooseOption(page, [/After Block/iu, /Destination/iu], "beta-2").catch(async () => fillField(page, [/After Block ID/iu], b.blockId)); await clickControl(page, [/Apply/iu, /Move/iu]);
    await clickControl(page, [/Delete/iu]); await chooseOption(page, [/Block/iu, /Target/iu], "alpha").catch(async () => fillField(page, [/Block ID/iu, /Target/iu], a.blockId)); await fillField(page, [/Expected text/iu], "alpha").catch(() => undefined); await clickControl(page, [/Confirm/iu, /Delete/iu]);
    await clickControl(page, [/Replace/iu, /Edit Block/iu]); await chooseOption(page, [/Block/iu, /Target/iu], "beta-2").catch(async () => fillField(page, [/Block ID/iu, /Target/iu], b.blockId)); await fillField(page, [/Expected text/iu], "beta-2").catch(() => undefined); await fillField(page, [/New text/iu, /Replacement/iu], "browser-resolution"); await applyChange(ctx, api.baseUrl, document.documentId, { clientId: ctx.uuid("d01:concurrent-client"), clientSequence: 1, baseRevision: 4, operations: [{ op: "REPLACE", blockId: b.blockId, expectedText: "beta-2", newText: "server-change" }] }, { key: ctx.key("d01:concurrent-change") }); await clickControl(page, [/Apply/iu, /Save/iu, /Replace/iu]); await page.getByText(/conflict|TARGET_CHANGED/iu).first().waitFor({ state: "visible" }); await clickControl(page, [/Resolve/iu]); await fillField(page, [/Resolution text/iu, /New text/iu], "browser-resolution").catch(() => undefined); await clickControl(page, [/Apply resolution/iu, /Resolve/iu]); await page.getByText("browser-resolution", { exact: false }).first().waitFor({ state: "visible" });
    await clickControl(page, [/History/iu, /Revisions/iu]); ctx.ok(await page.getByText(/Revision\s*0/iu).isVisible(), "revision zero is visible"); await clickControl(page, [/Diff/iu]); ctx.ok(await page.getByText(/INSERT|REPLACE|MOVE|DELETE/iu).first().isVisible(), "diff evidence is visible");
    await page.reload({ waitUntil: "domcontentloaded" }); await page.getByText("browser-resolution", { exact: false }).waitFor({ state: "visible" }); const current = assertDocument(await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}`, "browser-edited Document")); ctx.equal(current.headRevision, 6, "four visible operations plus conflict resolution create six revisions"); const snapshot = await waitForDrain(ctx, api.baseUrl, { processes: [worker] }); ctx.equal(resource(snapshot, "documentRevisions").filter(({ documentId }) => documentId === document.documentId).length, 7, "browser flow persists immutable history");
    return finalEvidence(ctx, { browserRevision: current.headRevision, visibleDiff: true, offlineReplay: true, conflictResolved: true, refreshed: true });
  },
}, ["DOCUMENT_ATOMICITY"]);

const D02 = guardedCase({
  id: "D-02",
  fixtureFamily: "MB-F-UI-BRANCH-MERGE",
  action: "Use production Chromium controls to create and edit a Branch, review its preview, approve, merge and observe STALE.",
  oracle: "Compare every visible captured head, reviewer, operation, digest and terminal state with the exact public MergeRequest.",
  async run(ctx) {
    const target = await prepare(ctx); const api = await target.startApi(); const a = ctx.fixtures.block("d02:a", "main-a"); const document = await createDocument(ctx, api.baseUrl, { title: "Browser merge", blocks: [a] }); const branches = await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/branches`, "main Branch"); branches.forEach(assertBranch); const main = branches[0]; const { page } = await launchBrowser(ctx, api.baseUrl, { width: 390, height: 844 }); await clickControl(page, [/Browser merge/u]);
    await clickControl(page, [/New Branch/iu, /Create Branch/iu]); await fillField(page, [/Branch name/iu, /^Name$/u], "browser-feature"); await chooseOption(page, [/Source Branch/iu], "main").catch(() => undefined); await fillField(page, [/Source revision/iu], "0").catch(() => undefined); await clickControl(page, [/Create/iu, /Save Branch/iu]); await page.getByText("browser-feature", { exact: false }).waitFor({ state: "visible" });
    await clickControl(page, [/browser-feature/u]); await clickControl(page, [/Insert(?: Block)?/iu, /Add Block/iu]); await fillField(page, [/Text/iu, /Block text/iu], "feature block"); await clickControl(page, [/Apply/iu, /Save/iu, /Insert/iu]);
    await clickControl(page, [/New Merge Request/iu, /Create Merge Request/iu]); await chooseOption(page, [/Source Branch/iu], "browser-feature"); await chooseOption(page, [/Target Branch/iu], "main"); await fillField(page, [/Reviewer/iu], ctx.fixtures.reviewerIds[0]); await fillField(page, [/Required approvals/iu, /Approval threshold/iu], "1"); await clickControl(page, [/Create/iu, /Open Merge Request/iu]); await page.getByText(/IN_REVIEW/iu).waitFor({ state: "visible" }); ctx.ok(await page.getByText(/feature block/iu).isVisible(), "merge preview is visible");
    await clickControl(page, [/Approve/iu]); await page.getByText(/APPROVED/iu).waitFor({ state: "visible" }); await clickControl(page, [/Merge/iu]); await page.getByText(/MERGED/iu).waitFor({ state: "visible" }); await page.reload({ waitUntil: "domcontentloaded" }); await page.getByText(/MERGED/iu).waitFor({ state: "visible" });
    const allBranches = await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/branches`, "browser Branches"); const feature = allBranches.find(({ name }) => name === "browser-feature"); ctx.ok(feature, "browser created a real Branch"); let snapshot = await ctx.snapshot(api.baseUrl); const request = resource(snapshot, "mergeRequests").find(({ sourceBranchId }) => sourceBranchId === feature.branchId); assertMergeRequest(request); ctx.equal(request.targetBranchId, main.branchId, "browser targeted main"); ctx.equal(request.state, "MERGED", "browser merge persists"); ctx.equal(request.approvals.length, 1, "browser approval persists once");
    const staleBranch = await createBranch(ctx, api.baseUrl, document.documentId, { name: "stale-ui", sourceBranchId: main.branchId, sourceRevision: 1 }); const staleBlock = ctx.fixtures.block("d02:stale", "stale"); await applyChange(ctx, api.baseUrl, document.documentId, { clientId: ctx.uuid("d02:stale-client"), clientSequence: 1, baseRevision: 0, operations: [{ op: "INSERT_AFTER", afterBlockId: a.blockId, block: staleBlock }] }, { branchId: staleBranch.branchId }); let stale = await createMergeRequest(ctx, api.baseUrl, document.documentId, { sourceBranchId: staleBranch.branchId, targetBranchId: main.branchId, expectedSourceHeadRevision: 1, expectedTargetHeadRevision: 1, reviewPolicy: { reviewerIds: [ctx.fixtures.reviewerIds[1]], requiredApprovals: 1 } }); stale = await approveMergeRequest(ctx, api.baseUrl, stale.mergeRequestId, ctx.fixtures.reviewerIds[1]); await page.reload({ waitUntil: "domcontentloaded" }); await clickControl(page, [new RegExp(stale.mergeRequestId, "u"), /stale-ui/iu]); await applyChange(ctx, api.baseUrl, document.documentId, { clientId: ctx.uuid("d02:main-client"), clientSequence: 1, baseRevision: 1, operations: [{ op: "REPLACE", blockId: a.blockId, expectedText: "main-a", newText: "main-advanced" }] }); await clickControl(page, [/Merge/iu]); await page.getByText(/STALE/iu).waitFor({ state: "visible" }); snapshot = await ctx.snapshot(api.baseUrl); stale = assertMergeRequest(resource(snapshot, "mergeRequests").find(({ mergeRequestId }) => mergeRequestId === stale.mergeRequestId)); ctx.equal(stale.state, "STALE", "browser observes persisted STALE state"); ctx.ok(!resource(snapshot, "documentRevisions").some(({ mergeRequestId }) => mergeRequestId === stale.mergeRequestId), "STALE browser merge creates no target revision");
    return finalEvidence(ctx, { mergeRequestId: request.mergeRequestId, state: request.state, staleRequestId: stale.mergeRequestId, mobileViewport: true });
  },
}, ["MERGE_ATOMICITY"]);

const D03 = guardedCase({
  id: "D-03",
  fixtureFamily: "MB-F-OPENAPI-FINAL-SNAPSHOT",
  action: "Triangulate frozen OpenAPI routes and closed schemas against a live FINAL snapshot containing every Manager resource.",
  oracle: "Validate exact keys, canonical sorting, point-in-time cross references, token omission, Work and Event closure independently.",
  async run(ctx) {
    const target = await prepare(ctx); const api = await target.startApi(); const a = ctx.fixtures.block("d03:a", "a"); const document = await createDocument(ctx, api.baseUrl, { title: "Contract closure", blocks: [a] }); const branches = await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/branches`, "main Branch"); const main = assertBranch(branches[0]); const feature = await createBranch(ctx, api.baseUrl, document.documentId, { name: "contract-feature", sourceBranchId: main.branchId, sourceRevision: 0 }); const x = ctx.fixtures.block("d03:x", "x"); await applyChange(ctx, api.baseUrl, document.documentId, { clientId: ctx.uuid("d03:client"), clientSequence: 1, baseRevision: 0, operations: [{ op: "INSERT_AFTER", afterBlockId: a.blockId, block: x }] }, { branchId: feature.branchId }); let request = await createMergeRequest(ctx, api.baseUrl, document.documentId, { sourceBranchId: feature.branchId, targetBranchId: main.branchId, expectedSourceHeadRevision: 1, expectedTargetHeadRevision: 0, reviewPolicy: { reviewerIds: [ctx.fixtures.reviewerIds[0]], requiredApprovals: 1 } }); request = await approveMergeRequest(ctx, api.baseUrl, request.mergeRequestId, ctx.fixtures.reviewerIds[0]); await mergeRequest(ctx, api.baseUrl, request.mergeRequestId);
    const openapi = await getJson(ctx, api.baseUrl, "/openapi.json", "OpenAPI"); ctx.ok(/^3\.1(?:\.|$)/u.test(openapi.openapi), "OpenAPI uses version 3.1"); const requiredPaths = ["/api/v1/documents", "/api/v1/documents/{documentId}", "/api/v1/documents/{documentId}/changes", "/api/v1/documents/{documentId}/conflicts/{conflictId}/resolve", "/api/v1/documents/{documentId}/revisions/{revision}", "/api/v1/documents/{documentId}/diff", "/api/v1/documents/{documentId}/branches", "/api/v1/documents/{documentId}/branches/{branchId}/changes", "/api/v1/documents/{documentId}/branches/{branchId}/revisions/{revision}", "/api/v1/documents/{documentId}/merge-requests", "/api/v1/merge-requests/{mergeRequestId}", "/api/v1/merge-requests/{mergeRequestId}/approvals", "/api/v1/merge-requests/{mergeRequestId}/merge", "/api/v1/verification-snapshot"]; for (const path of requiredPaths) ctx.ok(openapi.paths?.[path], `OpenAPI publishes ${path}`); assertResponseSchema(openapi, "/api/v1/documents", "post", 201, DOCUMENT_KEYS); assertResponseSchema(openapi, "/api/v1/documents/{documentId}/branches", "post", 201, BRANCH_KEYS); assertResponseSchema(openapi, "/api/v1/documents/{documentId}/branches/{branchId}/changes", "post", 201, CHANGE_KEYS); assertResponseSchema(openapi, "/api/v1/documents/{documentId}/branches/{branchId}/revisions/{revision}", "get", 200, REVISION_KEYS); assertResponseSchema(openapi, "/api/v1/documents/{documentId}/merge-requests", "post", 201, MERGE_REQUEST_KEYS); assertResponseSchema(openapi, "/api/v1/merge-requests/{mergeRequestId}/approvals", "post", 200, MERGE_REQUEST_KEYS); assertResponseSchema(openapi, "/api/v1/merge-requests/{mergeRequestId}/merge", "post", 200, MERGE_REQUEST_KEYS);
    const invalidPolicy = await createMergeRequest(ctx, api.baseUrl, document.documentId, { sourceBranchId: feature.branchId, targetBranchId: main.branchId, expectedSourceHeadRevision: 1, expectedTargetHeadRevision: 1, reviewPolicy: { reviewerIds: [], requiredApprovals: 1 } }, { key: ctx.key("d03:invalid-policy"), allowFailure: true }); expectError(ctx, invalidPolicy, 400, "INVALID_REVIEW_POLICY", "invalid review policy"); const unauthenticated = await ctx.request(api.baseUrl, "/api/v1/verification-snapshot"); expectError(ctx, unauthenticated, 401, "ADMIN_AUTH_REQUIRED", "snapshot authorization");
    const snapshot = assertSnapshot(ctx, await ctx.snapshot(api.baseUrl)); const branchRevision = resource(snapshot, "documentRevisions").find(({ documentId, branchId, mergeRequestId }) => documentId === document.documentId && branchId === main.branchId && mergeRequestId === request.mergeRequestId); ctx.ok(branchRevision, "snapshot contains merged target provenance"); ctx.equal(branchRevision.canonicalDigest, request.resultDigest, "snapshot merge revision matches preview");
    return finalEvidence(ctx, { openapiPaths: requiredPaths.length, resources: Object.keys(snapshot.resources).length }, [{ assertionId: "MB-D03-TERMINAL-STATE", status: "blocked", blockedBy: "MB-GAP-01", policy: "fail-closed-diagnostic" }]);
  },
}, ["SNAPSHOT_INTEGRITY", "MERGE_ATOMICITY"]);

const D04 = guardedCase({
  id: "D-04",
  fixtureFamily: "MB-F-MERGE-LINEAGE",
  action: "Trace canonical source revisions through preview, approvals, target revision, DocumentDiff, Snapshot and Events.",
  oracle: "Reconstruct ordered MergeOperations and preview blocks independently and match every downstream public identity and digest.",
  async run(ctx) {
    const target = await prepare(ctx); const api = await target.startApi(); const worker = await target.startWorker(); const a = ctx.fixtures.block("d04:a", "a"); const b = ctx.fixtures.block("d04:b", "b"); const x = ctx.fixtures.block("d04:x", "x"); const document = await createDocument(ctx, api.baseUrl, { title: "Lineage", blocks: [a, b] }); const branches = await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/branches`, "lineage Branches"); const main = assertBranch(branches[0]); const feature = await createBranch(ctx, api.baseUrl, document.documentId, { name: "lineage-feature", sourceBranchId: main.branchId, sourceRevision: 0 }); const operations = [{ op: "INSERT_AFTER", afterBlockId: a.blockId, block: x }, { op: "REPLACE", blockId: b.blockId, expectedText: "b", newText: "b2" }];
    for (const [index, operation] of operations.entries()) await applyChange(ctx, api.baseUrl, document.documentId, { clientId: ctx.uuid("d04:client"), clientSequence: index + 1, baseRevision: index, operations: [operation] }, { branchId: feature.branchId, key: ctx.key(`d04:change:${index}`) });
    const preview = mergePreview([a, b], operations); let request = await createMergeRequest(ctx, api.baseUrl, document.documentId, { sourceBranchId: feature.branchId, targetBranchId: main.branchId, expectedSourceHeadRevision: 2, expectedTargetHeadRevision: 0, reviewPolicy: { reviewerIds: [ctx.fixtures.reviewerIds[0]], requiredApprovals: 1 } }); ctx.equal(request.mergeOperations.map(({ operation }) => operation), operations, "MergeOperations preserve exact source history"); ctx.equal(request.resultDigest, documentDigest(document.documentId, 1, preview.blocks), "preview digest uses target next revision"); request = await approveMergeRequest(ctx, api.baseUrl, request.mergeRequestId, ctx.fixtures.reviewerIds[0]); request = await mergeRequest(ctx, api.baseUrl, request.mergeRequestId);
    const targetRevision = assertRevision(await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/branches/${main.branchId}/revisions/1`, "merged target revision")); ctx.equal(targetRevision.blocks, preview.blocks, "target revision equals stored preview"); ctx.equal(targetRevision.mergeRequestId, request.mergeRequestId, "target revision preserves merge provenance"); const legacy = assertDocument(await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}`, "legacy main lineage")); ctx.equal(legacy.blocks, preview.blocks, "legacy main exposes same merged blocks"); const diff = await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/diff?fromRevision=0&toRevision=1`, "merged legacy diff"); ctx.equal(diff.items, documentDiff([a, b], preview.blocks), "target diff closes source operation lineage");
    const snapshot = await waitForDrain(ctx, api.baseUrl, { processes: [worker] }); const stored = resource(snapshot, "branchDocumentSnapshots").find(({ branchId, revision }) => branchId === main.branchId && revision === 1); ctx.equal(stored.canonicalDigest, request.resultDigest, "Snapshot closes merge digest lineage"); const changed = snapshot.events.find(({ aggregateId, type }) => aggregateId === document.documentId && type === "document.changed" && type); const merged = snapshot.events.find(({ aggregateId, type }) => aggregateId === request.mergeRequestId && type === "merge-request.merged" && type); ctx.ok(changed && merged, "both merge Events are durable");
    return finalEvidence(ctx, { mergeRequestId: request.mergeRequestId, targetRevision: 1, diffItems: diff.items.length });
  },
}, ["MERGE_ATOMICITY", "SNAPSHOT_INTEGRITY"]);

export const D_CASES = Object.freeze([D01, D02, D03, D04]);
