import assert from "node:assert/strict";
import { createHash, createHmac } from "node:crypto";

export function canonicalJson(value) { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`; }
export function exactKeys(value, keys, label = "value") { assert.ok(value && typeof value === "object" && !Array.isArray(value), `${label} object`); assert.deepEqual(Object.keys(value).sort(), [...keys].sort(), `${label} exact keys`); }
export function tupleSort(items, fields) { return [...items].sort((left, right) => { for (const field of fields) { const a = left[field], b = right[field]; if (a === b) continue; if (a === null) return -1; if (b === null) return 1; if (Number.isSafeInteger(a) && Number.isSafeInteger(b)) return a - b; return Buffer.from(String(a)).compare(Buffer.from(String(b))); } return Buffer.from(canonicalJson(left)).compare(Buffer.from(canonicalJson(right))); }); }
export function percentile(values, fraction) { if (!values.length) return 0; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.min(sorted.length - 1, Math.ceil(sorted.length * fraction) - 1)]; }
export function sha256(value) { return createHash("sha256").update(value).digest("hex"); }
export function hmacSha256(secret, value) { return createHmac("sha256", secret).update(value, "utf8").digest("hex"); }
export function deviceAuthLine(method, path, timestamp, keyVersion) { return `${method}|${path}|${timestamp}|${keyVersion}`; }
export function telemetryLine(reading) { return [reading.deviceId, reading.readingId, reading.sequence, reading.observedAt, reading.latitudeE6, reading.longitudeE6, reading.temperatureMilliC, reading.configVersion, reading.keyVersion].join("|"); }
export function handoffAttestationLine(handoffId, carrierId, acceptedAt, expectedChainRevision, keyVersion) { return `${handoffId}|${carrierId}|${acceptedAt}|${expectedChainRevision}|${keyVersion}`; }
export function signedDeviceHeaders({ method, path, timestamp, keyVersion, deviceId, secret }) { return { "x-device-id": deviceId, "x-device-key-version": String(keyVersion), "x-device-timestamp": timestamp, "x-device-signature": hmacSha256(secret, deviceAuthLine(method, path, timestamp, keyVersion)) }; }
export function signReading(reading, secret) { return { ...reading, signature: hmacSha256(secret, telemetryLine(reading)) }; }

export function projectReadings(readings, { minimum = 2_000, maximum = 8_000, sites = [], initialLegOrdinal = 0 } = {}) {
  const ordered = [...readings].sort((left, right) => left.sequence - right.sequence || Buffer.from(left.readingId).compare(Buffer.from(right.readingId))); let lastSequence = 0, last, currentLegOrdinal = initialLegOrdinal, currentSiteId = null, runOut = 0, runIn = 0, open;
  const excursions = [];
  for (const reading of ordered) {
    lastSequence = Math.max(lastSequence, reading.sequence); last = reading;
    const siteIndex = sites.findIndex((site) => site.latitudeE6 === reading.latitudeE6 && site.longitudeE6 === reading.longitudeE6); if (siteIndex >= 0 && siteIndex >= currentLegOrdinal) { currentLegOrdinal = siteIndex; currentSiteId = sites[siteIndex].siteId; }
    const outside = reading.temperatureMilliC < minimum || reading.temperatureMilliC > maximum;
    if (outside) { runOut += 1; runIn = 0; if (runOut === 3 && !open) { const first = ordered[ordered.indexOf(reading) - 2]; open = { kind: "TEMPERATURE", state: "OPEN", firstSequence: first.sequence, lastSequence: reading.sequence, minimumObservedMilliC: Math.min(...ordered.slice(ordered.indexOf(reading) - 2, ordered.indexOf(reading) + 1).map((item) => item.temperatureMilliC)), maximumObservedMilliC: Math.max(...ordered.slice(ordered.indexOf(reading) - 2, ordered.indexOf(reading) + 1).map((item) => item.temperatureMilliC)) }; excursions.push(open); } else if (open) { open.lastSequence = reading.sequence; open.minimumObservedMilliC = Math.min(open.minimumObservedMilliC, reading.temperatureMilliC); open.maximumObservedMilliC = Math.max(open.maximumObservedMilliC, reading.temperatureMilliC); } }
    else { runIn += 1; runOut = 0; if (open && open.state !== "RESOLVED" && runIn === 3) open.state = "RESOLVED"; }
  }
  return { lastSequence, lastObservedAt: last?.observedAt ?? null, lastLatitudeE6: last?.latitudeE6 ?? null, lastLongitudeE6: last?.longitudeE6 ?? null, lastTemperatureMilliC: last?.temperatureMilliC ?? null, currentSiteId, currentLegOrdinal, excursions };
}
export function validateCustodySteps(steps, shipment, sites) { assert.ok(steps.length >= 1); let carrier = shipment.carrierId, lastWindowEnd = "", lastSiteIndex = -1; for (const [ordinal, step] of steps.entries()) { assert.equal(step.fromCarrierId, carrier, `handoff ${ordinal} connected carrier`); assert.notEqual(step.toCarrierId, step.fromCarrierId); assert.ok(step.windowStart < step.windowEnd && (!lastWindowEnd || step.windowStart >= lastWindowEnd), `handoff ${ordinal} window`); const index = sites.findIndex(({ siteId }) => siteId === step.siteId); assert.ok(index >= lastSiteIndex, `handoff ${ordinal} monotonic site`); carrier = step.toCarrierId; lastWindowEnd = step.windowEnd; lastSiteIndex = index; } return true; }
export function frozenRecallSet(shipments, tenantId, lot) { return shipments.filter((item) => item.tenantId === tenantId && item.productLotCode === lot && item.state !== "CANCELLED").map(({ shipmentId }) => shipmentId).sort((a, b) => Buffer.from(a).compare(Buffer.from(b))); }
export function assertEventSequence(events) { const groups = new Map(); for (const event of events) { const values = groups.get(event.aggregateId) ?? []; values.push(event); groups.set(event.aggregateId, values); } for (const values of groups.values()) { values.sort((a, b) => a.sequence - b.sequence); values.forEach((event, index) => assert.equal(event.sequence, index + 1, `contiguous Event sequence for ${event.aggregateId}`)); assert.equal(new Set(values.map(({ eventId }) => eventId)).size, values.length); } return true; }
export function assertNoSecrets(value, secrets = []) { const encoded = JSON.stringify(value); assert.equal(/"(?:secret|authorization|attestation|[^"]*Token)"\s*:/iu.test(encoded), false, "public evidence omits secret field names"); function visit(item, key = "") { if (!item || typeof item !== "object") { if (/signature$/iu.test(key) && typeof item === "string") assert.equal(/^[0-9a-f]{64}$/u.test(item), false, `${key} raw signature redacted`); return; } for (const [childKey, child] of Object.entries(item)) visit(child, childKey); } visit(value); for (const secret of secrets.filter(Boolean)) assert.equal(encoded.includes(secret), false, "public evidence omits secret material"); return true; }
export function assertWork(work) { const identities = new Set(); for (const item of work) { assert.equal(typeof item.workId, "string"); assert.equal(identities.has(item.workId), false); identities.add(item.workId); assert.equal(typeof item.kind, "string"); assert.equal(typeof item.aggregateId, "string"); assert.ok(Number.isSafeInteger(item.attempt) && item.attempt >= 0); assert.equal(typeof item.terminal, "boolean"); if (item.terminal) assert.notEqual(item.state, "LEASED"); } return true; }
export function assertNotificationIdentity(deliveries, receiverEntries) { const byEvent = new Map(); for (const delivery of deliveries) { const existing = byEvent.get(`${delivery.notificationPolicyId}:${delivery.eventId}`); if (existing) assert.equal(existing, delivery.notificationDeliveryId); else byEvent.set(`${delivery.notificationPolicyId}:${delivery.eventId}`, delivery.notificationDeliveryId); } for (const group of Map.groupBy(receiverEntries, (entry) => entry.headers["x-coldchain-event-id"]).values()) { assert.ok(group[0]?.headers["x-coldchain-event-id"]); const body = canonicalJson(group[0].json); assert.ok(group.every((entry) => canonicalJson(entry.json) === body), "retry semantic body stable"); } return true; }
