import { releaseDeclaration } from "../lib/fixtures.mjs";
import { assertReferenceClosure,canonical } from "../lib/oracle.mjs";
import { boot,caseResult,createRelease,createUpload,defineCase,eventsFor,expectError,findVersion,putSequential,snapshot,stableSemantic,uploadReleaseMembers,waitSnapshot,waitUpload,workFor } from "./helpers.mjs";

const RACE01=defineCase("RACE-01","unknown complete response and concurrent replay","Drop one committed complete response then replay the same key across two APIs","Saved status/body, single Work, single ArtifactVersion and single event effect remain stable",["response shield","two APIs","durable idempotency"],async(ctx)=>{
  const{apis}=await boot(ctx,{apiCount:2}),bytes=ctx.fixtures.bytes("race-01",2*1024*1024),created=await createUpload(ctx,apis[0].baseUrl,"race-01",bytes,{packageName:"race-complete",version:"1"});await putSequential(ctx,apis[0].baseUrl,created.upload.uploadId,bytes);const key=ctx.key("unknown-complete"),shield=await ctx.responseShield(apis[0].baseUrl);shield.dropNextMutation();await ctx.completeUpload(shield.baseUrl,created.upload.uploadId,{key}).catch(()=>undefined);await ctx.waitFor(()=>shield.captures.find(({dropped})=>dropped),{label:"dropped complete response"});
  const replays=await Promise.all(Array.from({length:20},(_,index)=>ctx.completeUpload(apis[index%2].baseUrl,created.upload.uploadId,{key})));const first=stableSemantic(ctx,replays,"complete replay",{hardCapIds:["IDEMPOTENCY_CORRECTNESS"]});ctx.equal("replayed complete status",first.status,202);const conflict=await ctx.mutate(apis[1].baseUrl,`/api/v1/upload-sessions/${created.upload.uploadId}/complete`,key,{unexpected:true},{contractExpectation:"invalid"});expectError(ctx,conflict,409,"IDEMPOTENCY_CONFLICT",{hardCapIds:["IDEMPOTENCY_CORRECTNESS"]});
  const worker=await ctx.startWorker();await waitUpload(ctx,apis[0].baseUrl,created.upload.uploadId,"COMMITTED",{processes:[worker]});await ctx.stop(worker);const state=await snapshot(ctx,apis[0].baseUrl);ctx.equal("one verification Work",workFor(state,"ARTIFACT_VERIFICATION",created.upload.uploadId).length,1,{hardCapIds:["IDEMPOTENCY_CORRECTNESS"]});ctx.equal("one ArtifactVersion",state.resources.artifactVersions.length,1,{hardCapIds:["IDEMPOTENCY_CORRECTNESS"]});ctx.equal("one BlobReference",state.resources.blobReferences.length,1,{hardCapIds:["IDEMPOTENCY_CORRECTNESS"]});ctx.equal("one upload.completed event",state.events.filter(({type})=>type==="upload.completed").length,1);return caseResult(ctx,{replayCount:replays.length});
});

const RACE02=defineCase("RACE-02","cross-layer package/version reservation race","Race standalone V1 upload creation against Manager Release creation on separate APIs","Exactly one package/version authority wins and every public surface agrees",["two APIs","database uniqueness","UI/snapshot"],async(ctx)=>{
  const{apis}=await boot(ctx,{apiCount:2}),bytes=ctx.fixtures.bytes("race-02",2048),packageName="cross-layer",version="same",uploadBody={packageName,version,mediaType:"application/octet-stream",expectedSize:bytes.length,expectedSha256:(await import("../lib/fixtures.mjs")).sha256(bytes)},releaseBody=releaseDeclaration(ctx.fixtures,"race-02",[{platform:"linux",bytes}]);releaseBody.packageName=packageName;releaseBody.version=version;
  const[startUpload,startRelease]=await Promise.all([ctx.createUpload(apis[0].baseUrl,uploadBody,{key:ctx.key("v1-race")}),ctx.createRelease(apis[1].baseUrl,releaseBody,{key:ctx.key("release-race")})]),successes=[startUpload.status===201,startRelease.status===200];ctx.equal("one reservation succeeds",successes.filter(Boolean).length,1,{hardCapIds:["DOMAIN_ATOMICITY"]});const loser=startUpload.status===201?startRelease:startUpload;expectError(ctx,loser,409,"RELEASE_VERSION_EXISTS",{hardCapIds:["DOMAIN_ATOMICITY"]});const openapi=await ctx.readOpenApi(apis[0].baseUrl);ctx.ok("OpenAPI publishes both competing create routes",Object.hasOwn(openapi.paths,"/api/v1/upload-sessions")&&Object.hasOwn(openapi.paths,"/api/v1/releases"));const state=await snapshot(ctx,apis[0].baseUrl);ctx.equal("snapshot has one reservation authority",state.resources.uploadSessions.length,1,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.ok("winner is represented exactly once",state.resources.releases.length+(state.resources.uploadSessions.some((item)=>!Object.hasOwn(item,"releaseId"))?1:0)===1);await ctx.withPage(apis[0],{width:1280,height:800},async(page)=>{await page.goto("/",{waitUntil:"networkidle"});ctx.ok("UI renders one real authority workflow",await page.locator("a,button,input,select").count()>0);});return caseResult(ctx,{winner:startUpload.status===201?"v1":"release"});
});

async function fencedVerification(ctx,point,index){await ctx.resetDatabase();await ctx.migrate();const api=await ctx.startApi(),bytes=ctx.fixtures.bytes(`race-03-${index}`,1024*1024),created=await createUpload(ctx,api.baseUrl,`race-03-${index}`,bytes,{packageName:`fence-${index}`,version:"1"});await putSequential(ctx,api.baseUrl,created.upload.uploadId,bytes);await ctx.completeUpload(api.baseUrl,created.upload.uploadId);const barrier=ctx.workerBarrier(point,({aggregateId})=>aggregateId===created.upload.uploadId),stale=await ctx.startWorkerAtBarrier(barrier),held=await barrier.waitFor((entry)=>entry.json.aggregateId===created.upload.uploadId,{timeoutMs:30_000,processes:[stale]});await ctx.kill(stale);ctx.ok(`${point} process was held`,held&&!held.released);await ctx.sleep(3_200);const replacement=await ctx.startWorker();await waitUpload(ctx,api.baseUrl,created.upload.uploadId,"COMMITTED",{timeoutMs:60_000,processes:[replacement]});await ctx.stop(replacement);const state=await snapshot(ctx,api.baseUrl),work=workFor(state,"ARTIFACT_VERIFICATION",created.upload.uploadId)[0];ctx.equal(`${point} one Version`,state.resources.artifactVersions.length,1,{hardCapIds:["WORK_RECOVERY_CORRECTNESS"]});ctx.equal(`${point} one Reference`,state.resources.blobReferences.length,1,{hardCapIds:["WORK_RECOVERY_CORRECTNESS"]});ctx.equal(`${point} one terminal verification Work`,workFor(state,"ARTIFACT_VERIFICATION",created.upload.uploadId).filter(({terminal})=>terminal).length,1,{hardCapIds:["WORK_RECOVERY_CORRECTNESS"]});ctx.ok(`${point} replacement increments attempt`,work.attempt>held.json.attempt,undefined,{hardCapIds:["WORK_RECOVERY_CORRECTNESS"]});ctx.assert(`${point} reference closure`,()=>assertReferenceClosure(state));return{point,attempt:work.attempt,staleAttempt:held.json.attempt};}

const RACE03=defineCase("RACE-03","three verification fencing seams","SIGKILL stale workers at claimed, effect-complete and before-commit, then reclaim after lease expiry","Each isolated crash produces one terminal effect and no stale commit",["worker.claimed","worker.effect-complete","worker.before-commit","SIGKILL"],async(ctx)=>{
  const results=[];for(const[point,index]of[["worker.claimed",1],["worker.effect-complete",2],["worker.before-commit",3]])results.push(await fencedVerification(ctx,point,index));return caseResult(ctx,{seams:results});
});

const RACE04=defineCase("RACE-04","dispatcher unknown acknowledgement","Commit an Artifact, hold dispatcher after receiver response, SIGKILL and restart","Every retry preserves Event identity, semantic body, headers and aggregate sequence",["dispatcher.response-received","receiver ledger","SIGKILL"],async(ctx)=>{
  const{api}=await boot(ctx),receiver=await ctx.receiver(()=>({status:204})),bytes=ctx.fixtures.bytes("race-04",4096),created=await createUpload(ctx,api.baseUrl,"race-04",bytes,{packageName:"dispatch-race",version:"1"});await putSequential(ctx,api.baseUrl,created.upload.uploadId,bytes);await ctx.completeUpload(api.baseUrl,created.upload.uploadId);const worker=await ctx.startWorker();await waitUpload(ctx,api.baseUrl,created.upload.uploadId,"COMMITTED",{processes:[worker]});await ctx.stop(worker);const state=await snapshot(ctx,api.baseUrl),expected=state.events[0];ctx.ok("committed transition has Event",expected);
  const barrier=ctx.dispatcherBarrier(({aggregateId})=>aggregateId===expected.aggregateId),first=await ctx.startDispatcherAtBarrier(receiver,barrier),held=await barrier.waitFor((entry)=>entry.json.aggregateId===expected.aggregateId,{timeoutMs:30_000,processes:[first]});await ctx.kill(first);ctx.ok("dispatcher killed after receiver response",held&&!held.released);const replacement=await ctx.startDispatcher({webhookUrl:receiver.url});await ctx.waitFor(()=>receiver.ledger.length>=2,{label:"dispatcher retry delivery",timeoutMs:30_000,processes:[replacement]});await ctx.stop(replacement);const attempts=receiver.ledger.filter(({json})=>json?.eventId===expected.eventId);ctx.ok("same Event is retried",attempts.length>=2,{hardCapIds:["EVENT_CORRECTNESS"]});ctx.equal("semantic bodies stable",new Set(attempts.map(({json})=>canonical(json))).size,1,{hardCapIds:["EVENT_CORRECTNESS"]});ctx.equal("event id header stable",new Set(attempts.map(({headers})=>headers["x-artifactvault-event-id"])).size,1);ctx.equal("event type header stable",new Set(attempts.map(({headers})=>headers["x-artifactvault-event-type"])).size,1);ctx.equal("payload remains empty",attempts[0].json.payload,{});return caseResult(ctx,{eventId:expected.eventId,deliveryAttempts:attempts.length});
});

export const RACE_CASES=Object.freeze([RACE01,RACE02,RACE03,RACE04]);
