import { releaseDeclaration } from "../lib/fixtures.mjs";
import { assertReferenceClosure,assertRelease,assertReleaseDetail,manifestFor } from "../lib/oracle.mjs";
import { boot,caseResult,commitStandalone,createRelease,defineCase,exactBinary,exerciseReleaseUi,expectError,findRelease,findVersion,publishReadyRelease,putSequential,snapshot,uploadReleaseMembers,waitSnapshot,waitUpload } from "./helpers.mjs";

function releaseFixture(ctx,label,platforms=["linux","darwin","windows"]){const members=platforms.map((platform,index)=>({platform,bytes:ctx.fixtures.bytes(`${label}:${platform}`,(index+1)*1024+17),mediaType:"application/octet-stream"}));return{members,bytesByPlatform:Object.fromEntries(members.map(({platform,bytes})=>[platform,bytes])),declaration:releaseDeclaration(ctx.fixtures,label,members)};}

const RELEASE01=defineCase("RELEASE-01","three independently verified members","Verify Release members one at a time without publishing","Every pre-publish snapshot has zero member Versions and References and a null manifest",["worker","snapshot","Release detail"],async(ctx)=>{
  const{api}=await boot(ctx),fixture=releaseFixture(ctx,"release-01"),created=await createRelease(ctx,api.baseUrl,fixture.declaration),worker=await ctx.startWorker();
  for(const artifact of created.release.artifacts){await putSequential(ctx,api.baseUrl,artifact.uploadId,fixture.bytesByPlatform[artifact.platform]);await ctx.completeUpload(api.baseUrl,artifact.uploadId);const settled=await waitUpload(ctx,api.baseUrl,artifact.uploadId,"VERIFIED",{processes:[worker]});ctx.equal("member becomes VERIFIED",settled.upload.state,"VERIFIED");ctx.equal("verified member has no ArtifactVersion",settled.upload.artifactVersionId,null,{hardCapIds:["DOMAIN_ATOMICITY"]});const state=await snapshot(ctx,api.baseUrl);ctx.equal("no early ArtifactVersion",state.resources.artifactVersions.length,0,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("no early BlobReference",state.resources.blobReferences.length,0,{hardCapIds:["DOMAIN_ATOMICITY"]});const detail=await ctx.getRelease(api.baseUrl,fixture.declaration.packageName,fixture.declaration.version);ctx.assert("DRAFT detail exact",()=>assertReleaseDetail(detail.json));ctx.equal("manifest remains null",detail.json.manifest,null);}
  await ctx.stop(worker);return caseResult(ctx,{releaseId:created.release.releaseId,verifiedMembers:3});
});

const RELEASE02=defineCase("RELEASE-02","reverse-ordered three-platform Release","Verify windows, linux and darwin members then publish once","Independent canonical manifest oracle matches and publication appears atomically",["public HTTP","snapshot before/after"],async(ctx)=>{
  const{api}=await boot(ctx),fixture=releaseFixture(ctx,"release-02",["windows","linux","darwin"]),created=await createRelease(ctx,api.baseUrl,fixture.declaration);await uploadReleaseMembers(ctx,api.baseUrl,created.release,fixture.bytesByPlatform);const before=await snapshot(ctx,api.baseUrl);ctx.equal("pre-publish has no Versions",before.resources.artifactVersions.length,0,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("pre-publish has no References",before.resources.blobReferences.length,0,{hardCapIds:["DOMAIN_ATOMICITY"]});
  const published=await publishReadyRelease(ctx,api.baseUrl,created.release),detail=await ctx.getRelease(api.baseUrl,fixture.declaration.packageName,fixture.declaration.version);ctx.assert("published ReleaseDetail exact",()=>assertReleaseDetail(detail.json));const expected=manifestFor(fixture.declaration.packageName,fixture.declaration.version,fixture.members.map(({platform,bytes,mediaType})=>({platform,sha256:ctx.fixtures?fixture.declaration.artifacts.find((item)=>item.platform===platform).expectedSha256:"",size:bytes.length,mediaType})));ctx.equal("canonical member order",detail.json.manifest.artifacts,expected.artifacts);ctx.equal("canonical manifest digest",detail.json.manifest.manifestSha256,expected.manifestSha256,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("Release digest agrees",published.published.manifestSha256,expected.manifestSha256);
  const after=await snapshot(ctx,api.baseUrl);ctx.equal("all three Versions publish",after.resources.artifactVersions.length,3,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("all three References publish",after.resources.blobReferences.length,3,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("all member sessions COMMITTED",after.resources.uploadSessions.map(({state})=>state),["COMMITTED","COMMITTED","COMMITTED"]);ctx.assert("reference closure",()=>assertReferenceClosure(after));return caseResult(ctx,{manifestSha256:expected.manifestSha256});
});

const RELEASE03=defineCase("RELEASE-03","mixed good and failed member Release","Drive one member VERIFIED, one digest REJECTED, reject publish, then retry the failed platform","DRAFT Release leaks no Version/Reference and retry preserves the good member Blob identity",["worker","retry API","snapshot"],async(ctx)=>{
  const{api}=await boot(ctx),fixture=releaseFixture(ctx,"release-03",["good","bad","spare"]),created=await createRelease(ctx,api.baseUrl,fixture.declaration),worker=await ctx.startWorker(),[good,bad,spare]=created.release.artifacts;
  await putSequential(ctx,api.baseUrl,good.uploadId,fixture.bytesByPlatform.good);await ctx.completeUpload(api.baseUrl,good.uploadId);await waitUpload(ctx,api.baseUrl,good.uploadId,"VERIFIED",{processes:[worker]});const beforeGood=await ctx.getRelease(api.baseUrl,fixture.declaration.packageName,fixture.declaration.version),goodBlob=beforeGood.json.release.artifacts.find(({platform})=>platform==="good").blob;
  const wrong=Buffer.from(fixture.bytesByPlatform.bad);wrong[0]^=255;await putSequential(ctx,api.baseUrl,bad.uploadId,wrong);await ctx.completeUpload(api.baseUrl,bad.uploadId);const rejected=await waitUpload(ctx,api.baseUrl,bad.uploadId,"REJECTED",{processes:[worker]});ctx.equal("failed member digest rejected",rejected.verificationResult.outcome,"DIGEST_MISMATCH");expectError(ctx,await ctx.publishRelease(api.baseUrl,created.release.releaseId),409,"RELEASE_NOT_READY",{hardCapIds:["DOMAIN_ATOMICITY"]});const blocked=await snapshot(ctx,api.baseUrl);ctx.equal("failed Release creates no Versions",blocked.resources.artifactVersions.length,0,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("failed Release creates no References",blocked.resources.blobReferences.length,0,{hardCapIds:["DOMAIN_ATOMICITY"]});
  const abandoned=await waitUpload(ctx,api.baseUrl,spare.uploadId,"ABANDONED",{timeoutMs:3_700_000,processes:[worker],intervalMs:500});ctx.equal("inactive member reaches ABANDONED",abandoned.upload.state,"ABANDONED");const retry=await ctx.retryRelease(api.baseUrl,created.release.releaseId,"bad");ctx.equal("retry status",retry.status,200);const retried=retry.json.release??retry.json;ctx.assert("retry response is exact Release",()=>assertRelease(retried));const replacement=retried.artifacts.find(({platform})=>platform==="bad");ctx.ok("retry creates replacement UploadSession",replacement.uploadId!==bad.uploadId);ctx.equal("verified good Blob stable",retried.artifacts.find(({platform})=>platform==="good").blob,goodBlob);const spareRetry=await ctx.retryRelease(api.baseUrl,created.release.releaseId,"spare");ctx.equal("abandoned member retry status",spareRetry.status,200);await ctx.stop(worker);const after=await snapshot(ctx,api.baseUrl);ctx.equal("retry only adds replacement sessions",after.resources.artifactVersions.length,0,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("retry still has no References",after.resources.blobReferences.length,0,{hardCapIds:["DOMAIN_ATOMICITY"]});return caseResult(ctx,{releaseId:created.release.releaseId,replacementUploadId:replacement.uploadId});
});

const RELEASE04=defineCase("RELEASE-04","published multi-platform Release","Validate OpenAPI routes, download three platforms including dedup, exercise desktop and mobile UI","API, OpenAPI, UI and FINAL snapshot resolve one committed authority",["OpenAPI 3.1","Chromium","snapshot"],async(ctx)=>{
  const{api}=await boot(ctx),shared=ctx.fixtures.bytes("release-04-shared",2048),unique=ctx.fixtures.bytes("release-04-unique",1536),members=[{platform:"linux",bytes:shared},{platform:"darwin",bytes:shared},{platform:"windows",bytes:unique}],fixture={members,bytesByPlatform:Object.fromEntries(members.map(({platform,bytes})=>[platform,bytes])),declaration:releaseDeclaration(ctx.fixtures,"release-04",members)},created=await createRelease(ctx,api.baseUrl,fixture.declaration);await uploadReleaseMembers(ctx,api.baseUrl,created.release,fixture.bytesByPlatform);await publishReadyRelease(ctx,api.baseUrl,created.release);
  const openapi=await ctx.readOpenApi(api.baseUrl);ctx.equal("OpenAPI 3.1",openapi.openapi,"3.1.0");for(const path of["/api/v1/releases","/api/v1/releases/{releaseId}/artifacts/{platform}/retry","/api/v1/releases/{releaseId}/publish","/api/v1/packages/{packageName}/releases/{version}","/api/v1/packages/{packageName}/releases/{version}/artifacts/{platform}/content"])ctx.ok(`OpenAPI publishes ${path}`,Object.hasOwn(openapi.paths,path));
  for(const{platform,bytes}of members)exactBinary(ctx,await ctx.getReleaseContent(api.baseUrl,fixture.declaration.packageName,fixture.declaration.version,platform),bytes,`${platform} download`);expectError(ctx,await ctx.getContent(api.baseUrl,fixture.declaration.packageName,fixture.declaration.version),409,"PLATFORM_REQUIRED");expectError(ctx,await ctx.getReleaseContent(api.baseUrl,fixture.declaration.packageName,fixture.declaration.version,"missing"),404,"RELEASE_PLATFORM_NOT_FOUND");const state=await snapshot(ctx,api.baseUrl);ctx.equal("two equal members deduplicate",state.resources.blobs.length,2);ctx.equal("three references protect content",state.resources.blobReferences.length,3);ctx.assert("reference closure",()=>assertReferenceClosure(state));
  await exerciseReleaseUi(ctx,api,{packageName:fixture.declaration.packageName,version:fixture.declaration.version,platforms:members.map(({platform})=>platform)});await ctx.withPage(api,{width:390,height:844},async(page)=>{await page.goto("/",{waitUntil:"networkidle"});ctx.ok("mobile UI exposes visible interactive controls",await page.locator("button, a, input, select").count()>0);});return caseResult(ctx,{releaseId:created.release.releaseId,platforms:members.length});
});

const RELEASE05=defineCase("RELEASE-05","referenced and unreferenced verified Blobs","Hold a GC worker at claimed and add a committed reference before release","Grace plus second-check keeps referenced content readable and never collects a protected Blob",["worker.claimed barrier","SIGKILL-safe Work","snapshot"],async(ctx)=>{
  const{api}=await boot(ctx),protectedBytes=ctx.fixtures.bytes("release-05-protected",4096),committed=await commitStandalone(ctx,api.baseUrl,"release-05-protected",protectedBytes,{packageName:"gc-protected",version:"1"}),fixture=releaseFixture(ctx,"release-05-orphan",["candidate"]),created=await createRelease(ctx,api.baseUrl,fixture.declaration);await uploadReleaseMembers(ctx,api.baseUrl,created.release,fixture.bytesByPlatform);const before=await snapshot(ctx,api.baseUrl),orphan=before.resources.blobs.find(({referenceCount,state})=>referenceCount===0&&["VERIFIED","ORPHANED"].includes(state)),gcWork=before.work.find(({kind,aggregateId,terminal})=>kind==="BLOB_GC"&&aggregateId===created.release.artifacts[0].uploadId&&!terminal)??before.work.find(({kind,terminal})=>kind==="BLOB_GC"&&!terminal);ctx.ok("verified unreferenced Blob is observable",orphan);ctx.ok("durable GC Work exists",gcWork);ctx.ok("committed Blob has reference",before.resources.blobs.some(({sha256:digest,referenceCount})=>digest===committed.version.blob.sha256&&referenceCount===1));
  await ctx.sleep(600_100);const barrier=ctx.workerBarrier("worker.claimed",({workId})=>workId===gcWork.workId),stale=await ctx.startWorkerAtBarrier(barrier),held=await barrier.waitFor((entry)=>entry.json.workId===gcWork.workId,{timeoutMs:30_000,processes:[stale]});await publishReadyRelease(ctx,api.baseUrl,created.release);await ctx.kill(stale);ctx.ok("GC was held after claim while reference committed",held&&!held.released);await ctx.sleep(3_200);const replacement=await ctx.startWorker();await waitSnapshot(ctx,api.baseUrl,(state)=>state.work.find(({workId})=>workId===gcWork.workId)?.terminal===true,{label:"stale GC replacement terminal",timeoutMs:60_000,processes:[replacement]});await ctx.stop(replacement);exactBinary(ctx,await ctx.getContent(api.baseUrl,"gc-protected","1"),protectedBytes,"preexisting protected Blob");exactBinary(ctx,await ctx.getReleaseContent(api.baseUrl,fixture.declaration.packageName,fixture.declaration.version,"candidate"),fixture.bytesByPlatform.candidate,"concurrently referenced Blob");const after=await snapshot(ctx,api.baseUrl);ctx.ok("newly referenced digest retained",after.resources.blobs.some(({sha256:digest})=>digest===orphan.sha256),undefined,{hardCapIds:["DOMAIN_ATOMICITY","WORK_RECOVERY_CORRECTNESS"]});ctx.assert("reference closure after stale GC",()=>assertReferenceClosure(after));return caseResult(ctx,{protectedDigest:committed.version.blob.sha256,secondCheckedDigest:orphan.sha256});
});

export const RELEASE_CASES=Object.freeze([RELEASE01,RELEASE02,RELEASE03,RELEASE04,RELEASE05]);
