import { releaseDeclaration,sha256 } from "../lib/fixtures.mjs";
import { assertArtifactVersion,assertChunkReceipt,assertReferenceClosure,assertUploadSession } from "../lib/oracle.mjs";
import { boot,caseResult,commitStandalone,completeAndVerify,createUpload,defineCase,exactBinary,expectError,findUpload,findVersion,putSequential,snapshot,waitUpload } from "./helpers.mjs";

const STREAM01=defineCase("STREAM-01","9 MiB deterministic stream","PUT sequential ranges, replay the first range exactly, and complete","Offsets, receipts, Work and committed content independently reconcile",["public HTTP","snapshot"],async(ctx)=>{
  const{api}=await boot(ctx),bytes=ctx.fixtures.bytes("stream-01",9*1024*1024),created=await createUpload(ctx,api.baseUrl,"stream-01",bytes),first=bytes.subarray(0,8*1024*1024),tail=bytes.subarray(8*1024*1024),key=ctx.key("first-range");
  const receipt=await ctx.putChunk(api.baseUrl,created.upload.uploadId,first,0,bytes.length,{key});ctx.equal("first range status",receipt.status,200);ctx.assert("first receipt exact",()=>assertChunkReceipt(receipt.json));ctx.equal("first nextOffset",receipt.json.nextOffset,first.length);
  const replay=await ctx.putChunk(api.baseUrl,created.upload.uploadId,first,0,bytes.length,{key:ctx.key("range-replay")});ctx.equal("replay status",replay.status,200);ctx.equal("replay marked",replay.json.replayed,true);ctx.equal("replay offset stable",replay.json.nextOffset,first.length);
  const final=await ctx.putChunk(api.baseUrl,created.upload.uploadId,tail,first.length,bytes.length);ctx.equal("final chunk status",final.status,200);ctx.equal("final offset",final.json.nextOffset,bytes.length);
  const settled=await completeAndVerify(ctx,api.baseUrl,created.upload.uploadId);ctx.equal("upload committed",settled.upload.state,"COMMITTED");const state=await snapshot(ctx,api.baseUrl);ctx.equal("one ArtifactVersion",state.resources.artifactVersions.length,1,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("one Blob Reference",state.resources.blobReferences.length,1,{hardCapIds:["DOMAIN_ATOMICITY"]});return caseResult(ctx,{uploadId:created.upload.uploadId,digest:sha256(bytes)});
});

const STREAM02=defineCase("STREAM-02","atomic range rejection fixture","Issue gap, overlap, out-of-range and different-byte replay before a legal continuation","Every rejection leaves offset, bytes, Work, Events and resources unchanged",["public HTTP","point-in-time snapshot"],async(ctx)=>{
  const{api}=await boot(ctx),bytes=ctx.fixtures.bytes("stream-02",3*1024*1024),created=await createUpload(ctx,api.baseUrl,"stream-02",bytes),first=bytes.subarray(0,1024*1024);await ctx.putChunk(api.baseUrl,created.upload.uploadId,first,0,bytes.length);
  const before=await snapshot(ctx,api.baseUrl),variants=[
    await ctx.putChunk(api.baseUrl,created.upload.uploadId,bytes.subarray(1024*1024,1024*1024+8),1024*1024+1,bytes.length),
    await ctx.putChunk(api.baseUrl,created.upload.uploadId,bytes.subarray(0,8),4,bytes.length),
    await ctx.putChunk(api.baseUrl,created.upload.uploadId,Buffer.alloc(8,bytes[0]^255),0,bytes.length),
    await ctx.request(api.baseUrl,`/api/v1/upload-sessions/${created.upload.uploadId}/chunks`,{method:"PUT",raw:Buffer.alloc(1),headers:{"idempotency-key":ctx.key("bad-total"),"content-type":"application/octet-stream","content-range":`bytes ${bytes.length}-${bytes.length}/${bytes.length}`}}),
  ];
  for(const response of variants)expectError(ctx,response,409,"UPLOAD_RANGE_CONFLICT",{hardCapIds:["DOMAIN_ATOMICITY"]});const after=await snapshot(ctx,api.baseUrl);ctx.equal("rejections preserve offset",findUpload(after,created.upload.uploadId).nextOffset,first.length,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("rejections preserve durable projections",{versions:after.resources.artifactVersions,refs:after.resources.blobReferences,events:after.events,work:after.work},{versions:before.resources.artifactVersions,refs:before.resources.blobReferences,events:before.events,work:before.work},{hardCapIds:["DOMAIN_ATOMICITY"]});
  for(let start=first.length;start<bytes.length;start+=1024*1024){const chunk=bytes.subarray(start,Math.min(start+1024*1024,bytes.length)),response=await ctx.putChunk(api.baseUrl,created.upload.uploadId,chunk,start,bytes.length);ctx.equal("legal continuation succeeds",response.status,200);}const settled=await completeAndVerify(ctx,api.baseUrl,created.upload.uploadId);ctx.equal("legal continuation still commits",settled.upload.state,"COMMITTED");return caseResult(ctx,{rejections:variants.length});
});

const STREAM03=defineCase("STREAM-03","96 MiB verifier and negative declarations","Stream a large valid upload plus incomplete and wrong-digest uploads through the public worker","Only the exact stream commits; failures expose terminal evidence without Version or Reference",["worker process","snapshot","RSS observation"],async(ctx)=>{
  const{api}=await boot(ctx),large=ctx.fixtures.bytes("stream-03-large",96*1024*1024),worker=await ctx.startWorker(),valid=await createUpload(ctx,api.baseUrl,"stream-03-valid",large);await putSequential(ctx,api.baseUrl,valid.upload.uploadId,large);const validDone=await completeAndVerify(ctx,api.baseUrl,valid.upload.uploadId,{worker,keepWorker:true,timeoutMs:180_000});ctx.equal("96 MiB stream commits",validDone.upload.state,"COMMITTED",{hardCapIds:["DOMAIN_ATOMICITY"]});
  const incompleteBytes=ctx.fixtures.bytes("stream-03-short",1024),incomplete=await createUpload(ctx,api.baseUrl,"stream-03-incomplete",Buffer.alloc(2048),{expectedSha256:sha256(Buffer.alloc(2048))});await ctx.putChunk(api.baseUrl,incomplete.upload.uploadId,incompleteBytes,0,2048);expectError(ctx,await ctx.completeUpload(api.baseUrl,incomplete.upload.uploadId),409,"UPLOAD_INCOMPLETE",{hardCapIds:["DOMAIN_ATOMICITY"]});
  const wrong=ctx.fixtures.bytes("stream-03-wrong",2*1024*1024),wrongDecl=await createUpload(ctx,api.baseUrl,"stream-03-digest",wrong,{expectedSha256:"0".repeat(64)});await putSequential(ctx,api.baseUrl,wrongDecl.upload.uploadId,wrong);const rejected=await completeAndVerify(ctx,api.baseUrl,wrongDecl.upload.uploadId,{worker,keepWorker:true,states:"REJECTED"});ctx.equal("digest mismatch outcome",rejected.verificationResult.outcome,"DIGEST_MISMATCH",{hardCapIds:["DOMAIN_ATOMICITY"]});await ctx.stop(worker);
  const state=await snapshot(ctx,api.baseUrl);ctx.equal("only valid ArtifactVersion commits",state.resources.artifactVersions.length,1,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("only valid BlobReference commits",state.resources.blobReferences.length,1,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.ok("large content remains stream-readable",findVersion(state,valid.declaration.packageName,valid.declaration.version));return caseResult(ctx,{verifiedBytes:large.length});
});

const STREAM04=defineCase("STREAM-04","two packages with identical bytes","Commit equal bytes through independent upload sessions","Snapshot contains one content-addressed Blob and two durable references; both downloads match",["public HTTP","snapshot"],async(ctx)=>{
  const{api}=await boot(ctx),bytes=ctx.fixtures.bytes("shared-blob",4*1024*1024),first=await commitStandalone(ctx,api.baseUrl,"stream-04-a",bytes,{packageName:"dedup-a",version:"1"}),second=await commitStandalone(ctx,api.baseUrl,"stream-04-b",bytes,{packageName:"dedup-b",version:"1"});const state=await snapshot(ctx,api.baseUrl);ctx.equal("equal bytes deduplicate to one Blob",state.resources.blobs.length,1,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.equal("two committed ownership edges",state.resources.blobReferences.length,2,{hardCapIds:["DOMAIN_ATOMICITY"]});ctx.assert("reference count closes",()=>assertReferenceClosure(state));ctx.equal("both versions share digest",first.version.blob.sha256,second.version.blob.sha256);exactBinary(ctx,await ctx.getContent(api.baseUrl,"dedup-a","1"),bytes,"first package");exactBinary(ctx,await ctx.getContent(api.baseUrl,"dedup-b","1"),bytes,"second package");return caseResult(ctx,{blobSha256:first.version.blob.sha256,referenceCount:2});
});

const STREAM05=defineCase("STREAM-05","immutable 4 MiB version","Read full, first, middle, tail and invalid ranges, then race a conflicting version","ETag, Content-Range, bytes and immutable Version identity remain exact",["public raw content","two API processes","snapshot"],async(ctx)=>{
  const{apis,api}=await boot(ctx,{apiCount:2}),bytes=ctx.fixtures.bytes("stream-05",4*1024*1024),committed=await commitStandalone(ctx,api.baseUrl,"stream-05",bytes,{packageName:"immutable",version:"v1"});const full=await ctx.getContent(api.baseUrl,"immutable","v1");exactBinary(ctx,full,bytes);const etag=full.headers.get("etag");ctx.ok("digest ETag published",etag?.includes(committed.version.blob.sha256));
  for(const[start,end]of[[0,31],[1024,2047],[bytes.length-29,bytes.length-1]]){const response=await ctx.getContent(api.baseUrl,"immutable","v1",{headers:{range:`bytes=${start}-${end}`}});ctx.equal("range status",response.status,206);ctx.equal("range bytes",response.body,bytes.subarray(start,end+1));ctx.equal("range ETag stable",response.headers.get("etag"),etag);ctx.equal("Content-Range exact",response.headers.get("content-range"),`bytes ${start}-${end}/${bytes.length}`);}
  const invalid=await ctx.getContent(api.baseUrl,"immutable","v1",{headers:{range:`bytes=${bytes.length}-${bytes.length+1}`}});ctx.equal("unsatisfiable range",invalid.status,416);const conflictBytes=ctx.fixtures.bytes("stream-05-conflict",1024),races=await Promise.all(apis.map((process,index)=>ctx.createUpload(process.baseUrl,{packageName:"immutable",version:"v1",mediaType:"application/octet-stream",expectedSize:conflictBytes.length,expectedSha256:sha256(conflictBytes)},{key:ctx.key(`conflict-${index}`)})));ctx.ok("committed version reservation rejects every replacement",races.every((response)=>response.status===409));races.forEach((response)=>expectError(ctx,response,409,"PACKAGE_VERSION_EXISTS"));const after=await ctx.getVersion(api.baseUrl,"immutable","v1");ctx.assert("ArtifactVersion remains exact",()=>assertArtifactVersion(after.json));ctx.equal("ArtifactVersion identity immutable",after.json,committed.version,{hardCapIds:["DOMAIN_ATOMICITY"]});return caseResult(ctx,{etag});
});

export const STREAM_CASES=Object.freeze([STREAM01,STREAM02,STREAM03,STREAM04,STREAM05]);
