import { ref, obj, arr, one, nil, str, text, bool, int, count, positive, range, uuid, time, sha, en, page, id, T, auth, admin, key, q, paging, commands, environmentVariables, op, commonSchemas, snapshot, seedSchema, infra, observe, basicSmoke, seedSmoke, commonNotes, manager, digest } from '../learning/helpers-a2.mjs';

const ascii = { type: 'string', minLength: 1, maxLength: 64, pattern: '^[\\x00-\\x7f]+$' };
const value = one(str, bool), flagType = en('STRING', 'BOOLEAN');
const clause = obj({ attribute: ascii, operator: en('EQUALS', 'IN'), value: one(str, arr(str)) });
const variant = obj({ key: ascii, value, allocationBasisPoints: int });
const rule = obj({ ruleId: uuid, clauses: arr(clause), variantKey: ascii });
const revision = obj({ revisionId: uuid, flagId: uuid, environment: ascii, revision: positive, flagType, defaultVariant: ascii, variants: arr(variant), rules: arr(ref('FlagRule')), state: en('COMPILING', 'READY', 'ACTIVE', 'REJECTED', 'SUPERSEDED'), snapshotDigest: nil(sha), createdAt: time, activatedAt: nil(time), sequence: positive });
const evaluation = obj({ projectId: uuid, flagId: uuid, flagKey: ascii, environment: ascii, subjectKey: str, variantKey: ascii, value, revisionId: uuid, snapshotDigest: sha, reason: en('DEFAULT', 'RULE', 'PERCENTAGE'), matchedRuleId: nil(uuid) });
const rolloutInputStep = obj({ candidateExposureBasisPoints: int, minimumEvaluationCount: int, maximumFailureBasisPoints: int, observationSeconds: int });
const outcomeInput = obj({ outcomeId: str, stepIndex: int, subjectKey: str, snapshotDigest: sha, outcome: en('SUCCESS', 'FAILURE') });
const schemas = {
  ...commonSchemas(['FLAG_COMPILATION', 'ROLLOUT_DEADLINE'], ['flag.compilation-started', 'flag.revision-rejected', 'flag.revision-activated', 'flag.revision-superseded']),
  Project: obj({ projectId: uuid, name: str }),
  Environment: obj({ projectId: uuid, name: ascii, contextAttributes: arr(ascii), schemaRevision: positive }),
  Flag: obj({ flagId: uuid, projectId: uuid, key: ascii, flagType, createdAt: time }),
  SeedFlag: obj({ flagId: uuid, projectId: uuid, key: ascii, flagType }),
  FlagRule: rule, FlagRevision: revision,
  FlagSnapshot: obj({ snapshotVersion: { const: 1 }, projectId: uuid, flagId: uuid, flagKey: ascii, environment: ascii, revisionId: uuid, revision: positive, flagType, defaultVariant: ascii, variants: arr(variant), rules: arr(ref('FlagRule')), contextAttributes: arr(ascii), contextSchemaRevision: positive }),
  Evaluation: one(evaluation, obj({ ...evaluation.properties, rolloutId: nil(uuid), stepIndex: nil(int) })),
  FlagRevisionDiff: obj({ flagId: uuid, environment: ascii, fromRevision: positive, toRevision: positive, defaultVariantChanged: bool, addedVariantKeys: arr(ascii), removedVariantKeys: arr(ascii), changedVariantKeys: arr(ascii), variantOrderChanged: bool, addedRuleIds: arr(uuid), removedRuleIds: arr(uuid), changedRuleIds: arr(uuid), ruleOrderChanged: bool }),
  CompilationFinding: obj({ code: str, path: str, message: str }),
  ProgressiveRollout: obj({ rolloutId: uuid, flagId: uuid, environment: ascii, priorRevisionId: uuid, candidateRevisionId: uuid, state: en('RUNNING', 'COMPLETED', 'ROLLED_BACK', 'STALE'), currentStepIndex: int, steps: arr(obj({ stepIndex: int, ...rolloutInputStep.properties, successCount: count, failureCount: count, state: en('PENDING', 'OBSERVING', 'PASSED', 'FAILED'), startedAt: nil(time), observationDeadlineAt: nil(time), completedAt: nil(time) })), createdAt: time, terminalAt: nil(time) }),
  EvaluationOutcome: obj({ ...outcomeInput.properties, rolloutId: uuid, reportedAt: time }),
};
schemas.VerificationSnapshot = snapshot({ projects: 'Project', environments: 'Environment', flags: 'Flag', flagRevisions: 'FlagRevision', flagSnapshots: 'FlagSnapshot', progressiveRollouts: 'ProgressiveRollout', evaluationOutcomes: 'EvaluationOutcome' });
const project = { projectId: id(201), name: 'Public decision project' };
const environment = { projectId: id(201), name: 'production', contextAttributes: ['region', 'subjectKey', 'tier'], schemaRevision: 1 };
const flag = { flagId: id(202), projectId: id(201), key: 'welcome', flagType: 'STRING' };
const variants = [{ key: 'standard', value: 'Welcome', allocationBasisPoints: 10000 }];
const publicSnapshot = { snapshotVersion: 1, projectId: id(201), flagId: id(202), flagKey: 'welcome', environment: 'production', revisionId: id(203), revision: 1, flagType: 'STRING', defaultVariant: 'standard', variants, rules: [], contextAttributes: environment.contextAttributes, contextSchemaRevision: 1 };
const active = { revisionId: id(203), flagId: id(202), environment: 'production', revision: 1, flagType: 'STRING', defaultVariant: 'standard', variants, rules: [], state: 'ACTIVE', snapshotDigest: digest(publicSnapshot), createdAt: T, activatedAt: T, sequence: 1 };
const revisionBody = obj({ environment: ascii, flagType, defaultVariant: ascii, variants: arr(variant), rules: arr(ref('FlagRule')), expectedActiveRevision: nil(positive) });
const errors = Object.fromEntries([400, 401, 404, 409, 415, 500].map(status => [status, ref('Error')]));
const operations = [
  ...infra(), ...observe(),
  op('list-revisions', 'GET', '/api/v1/flag-revisions', 200, page(ref('FlagRevision')), undefined, { query: { limit: 50 } }, { parameters: paging }),
  op('get-revision', 'GET', '/api/v1/flag-revisions/:revisionId', 200, ref('FlagRevision'), undefined, { params: { revisionId: id(203) } }),
  op('compilation-findings', 'GET', '/api/v1/flag-revisions/:revisionId/findings', 200, arr(ref('CompilationFinding')), undefined, { params: { revisionId: id(203) } }, { source: 'V2 public observation clarification (contract notes), original CompilationFinding and stale-compilation requirements' }),
  op('update-context-schema', 'POST', '/api/v1/projects/:projectId/environments/:environment/context-schema', 200, ref('Environment'), obj({ contextAttributes: arr(ascii, { uniqueItems: true }) }), { params: { projectId: id(201), environment: 'production' }, body: { contextAttributes: ['region', 'subjectKey', 'tier'] }, headers: auth }, { parameters: admin, source: 'V2 public observation clarification (contract notes), original captured Environment context schema invariant' }),
  op('create-flag', 'POST', '/api/v1/flags', 201, ref('Flag'), obj({ projectId: uuid, key: ascii, flagType }), { body: { projectId: id(201), key: 'public-created-flag', flagType: 'BOOLEAN' } }),
  op('create-revision', 'POST', '/api/v1/flags/:flagId/revisions', 202, ref('FlagRevision'), revisionBody, { params: { flagId: id(202) }, body: { environment: 'production', flagType: 'STRING', defaultVariant: 'standard', variants, rules: [], expectedActiveRevision: 1 } }),
  op('activate-revision', 'POST', '/api/v1/flag-revisions/:revisionId/activate', 200, ref('FlagRevision'), obj({ expectedActiveRevision: nil(positive) }), { params: { revisionId: id(204) }, body: { expectedActiveRevision: 1 } }),
  op('evaluate', 'POST', '/api/v1/evaluations', 200, ref('Evaluation'), obj({ projectId: uuid, flagKey: ascii, environment: ascii, context: { type: 'object', propertyNames: ascii, additionalProperties: str }, snapshotDigest: sha }, ['projectId', 'flagKey', 'environment', 'context']), { body: { projectId: id(201), flagKey: 'welcome', environment: 'production', context: { subjectKey: 'public-subject', region: 'us', tier: 'pro' } } }),
  op('revision-diff', 'GET', '/api/v1/flags/:flagId/revisions/:revision/diff', 200, ref('FlagRevisionDiff'), undefined, { params: { flagId: id(202), revision: 2 }, query: { against: 1, environment: 'production' } }, { parameters: [q('against', positive, true), q('environment', ascii)] }),
  op('flag-revisions', 'GET', '/api/v1/flags/:flagId/revisions', 200, page(ref('FlagRevision')), undefined, { params: { flagId: id(202) }, query: { environment: 'production', limit: 50 } }, { parameters: [q('environment', ascii, true), ...paging] }),
  op('progressive-activate', 'POST', '/api/v1/flag-revisions/:revisionId/progressive-activate', 202, ref('ProgressiveRollout'), obj({ expectedActiveRevision: nil(positive), steps: arr(rolloutInputStep) }), { params: { revisionId: id(204) }, body: { expectedActiveRevision: 1, steps: [{ candidateExposureBasisPoints: 10000, minimumEvaluationCount: 1, maximumFailureBasisPoints: 0, observationSeconds: 60 }] } }, { source: manager }),
  op('outcome-batch', 'POST', '/api/v1/progressive-rollouts/:rolloutId/outcome-batches', 200, obj({ acceptedIds: arr(str), duplicateIds: arr(str) }), obj({ outcomes: arr(outcomeInput) }), { params: { rolloutId: id(205) }, body: { outcomes: [{ outcomeId: 'public-outcome', stepIndex: 0, subjectKey: 'public-subject', snapshotDigest: active.snapshotDigest, outcome: 'SUCCESS' }] } }, { source: manager }),
  op('get-rollout', 'GET', '/api/v1/progressive-rollouts/:rolloutId', 200, ref('ProgressiveRollout'), undefined, { params: { rolloutId: id(205) } }, { source: manager }),
].map(operation => ({ ...operation, errors, parameters: operation.parameters.map(parameter => parameter.in === 'path' && ['revision', 'environment'].includes(parameter.name) ? { ...parameter, schema: parameter.name === 'revision' ? positive : ascii } : parameter), ...(operation.id === 'production-ui' && { response: { type: 'string', contentMediaType: 'text/html' } }) }));

export default {
  taskId: 'flagfoundry', title: 'FlagFoundry', httpHost: '127.0.0.1', commands, environmentVariables,
  policyRevision: 'flagfoundry-public-observation-v2',
  transportErrors: { auth: { status: 401, code: 'ADMIN_AUTH_REQUIRED' }, unknownField: { status: 400, code: 'UNKNOWN_FIELD' } }, schemas, operations,
  seed: { command: ['npm', 'run', 'db:seed', '--', '--file', '${SEED_PATH}'], replay: true, schema: seedSchema({ projects: 'Project', environments: 'Environment', flags: 'SeedFlag', activeRevisions: { ...revision, properties: { ...revision.properties, state: { const: 'ACTIVE' }, snapshotDigest: sha, activatedAt: time } } }), example: { schemaVersion: 1, seedVersion: 'flagfoundry-public-v2-1', projects: [project], environments: [environment], flags: [flag], activeRevisions: [active] } },
  smoke: [...basicSmoke, seedSmoke({ projects: [project], flags: [flag], flagRevisions: [active], flagSnapshots: [publicSnapshot] }),
    { operationId: 'evaluate', body: { projectId: id(201), flagKey: 'welcome', environment: 'production', context: { subjectKey: 'public-read-subject' } }, headers: key('seed-evaluation'), expectStatus: 200, expectBody: { flagId: id(202), revisionId: id(203), value: 'Welcome', snapshotDigest: active.snapshotDigest } },
    { operationId: 'create-flag', body: { projectId: id(201), key: 'public-independent-flag', flagType: 'BOOLEAN' }, headers: key('new-flag'), expectStatus: 201, capture: { flagId: ['flagId'] } },
    { operationId: 'verification-snapshot', headers: auth, expectStatus: 200, expectContains: [{ path: ['resources', 'flags'], match: { flagId: '${flagId}', projectId: id(201), key: 'public-independent-flag', flagType: 'BOOLEAN' } }] },
    { operationId: 'compilation-findings', params: { revisionId: id(203) }, expectStatus: 200, expectBody: [] },
    { operationId: 'update-context-schema', params: { projectId: id(201), environment: 'production' }, headers: { ...auth, ...key('schema-noop') }, body: { contextAttributes: environment.contextAttributes }, expectStatus: 200, expectBody: environment }],
  notes: [...commonNotes,
    'Author-confirmed business policy flagfoundry-rollout-authority-v1: while a progressive rollout is RUNNING, its captured prior revision remains the sole ACTIVE revision and its captured candidate remains READY with activatedAt null. The official active pointer and expectedActiveRevision compare-and-set still refer to the prior revision, including a final cohort at 10000 exposure while observations remain incomplete.',
    'The RUNNING rollout alone authorizes evaluation of its captured READY candidate Snapshot according to the published cohort bucket; this is the explicit Manager exception to the V1 invariant that an inactive revision cannot be evaluated. Non-selected, unrelated READY, REJECTED and stale revisions gain no evaluation authority. Every progressive Evaluation still names its rolloutId and current stepIndex.',
    'Only the transaction that passes all rollout steps marks the rollout COMPLETED, supersedes the prior revision and makes the candidate the sole ACTIVE revision. Candidate activatedAt is that completion transaction timestamp, equal to rollout terminalAt; immutable prior and candidate Snapshot contents and digests do not change. A failed threshold or deadline instead marks the rollout ROLLED_BACK without activating the candidate: prior remains ACTIVE, candidate remains READY with activatedAt null, and subsequent fresh evaluations use the prior Snapshot.',
    'The confirmed authority rule applies at the observed RUNNING or terminal transition, not as a permanent condition on historical terminal rollout rows. A later legitimate activation may supersede that active revision. A concurrent immediate activation makes a RUNNING rollout STALE and owns the new active pointer; old rollout work cannot restore its prior. Saved V1 replies and seeded history remain unchanged.',
    'Author clarification flagfoundry-public-observation-v2 preserves flagfoundry-rollout-authority-v1 and all original business requirements. ASCII 1..64 means U+0000 through U+007F inclusive, length 1..64, case-sensitive, with no trimming or visible-character-only restriction. This is distinct from the visible-ASCII Idempotency-Key header rule.',
    'GET /api/v1/flag-revisions/:revisionId/findings returns the complete CompilationFinding array, sorted by path then code using UTF-8 byte order, without a wrapper or pagination. It is a read-only durable explanation of that Compilation result, not another snapshot resource key. Unknown revision returns 404 NOT_FOUND. COMPILING and successfully compiled revisions return []; a REJECTED revision has one or more nonempty code/path/message findings explaining the rejected rule or captured prerequisite. Findings use JSON Pointer paths into the revision request and remain stable after completion; no new error-code enum is imposed on findings.',
    'POST /api/v1/projects/:projectId/environments/:environment/context-schema is an ADMIN_TOKEN mutation using the ordinary durable Idempotency-Key contract. Body is exactly {contextAttributes:[ASCII name]}; names must be sorted unique and unsorted names return 400 INVALID_REQUEST. It updates only an existing Environment and returns its exact Environment shape; missing Project/Environment returns 404 NOT_FOUND. A changed attribute list increments schemaRevision by one in the same transaction; an identical list is a no-op and replay never increments again. Existing Snapshots and captured Compilation inputs remain immutable. This publishes the mutation needed to observe the original captured-schema invariant, not an automatic activation, a schema-edit workflow, or a new event. A READY revision compiled against an older schema cannot activate (409 ACTIVE_REVISION_CHANGED); an unfinished stale Compilation becomes REJECTED with explanatory findings. The existing active Snapshot remains authority until a valid new activation.',
    'For fresh legacy /activate requests, the Manager one-Step 10000/zero-observation description is semantic equivalence to immediate activation: keep the exact old FlagRevision response and create no new ProgressiveRollout, EvaluationOutcome, or ROLLOUT_DEADLINE Work. Existing RUNNING rollouts may become STALE as already required. Imported history and saved legacy replay bodies acquire no synthetic rollout rows or activations.',
    'An Outcome for a well-formed but wrong Snapshot digest in its otherwise current open rollout Step returns 409 SNAPSHOT_MISMATCH. Wrong current Step or superseded authority retains 409 ROLLOUT_STALE; deadline precedence retains 409 OUTCOME_WINDOW_CLOSED. A failed member rejects the complete batch with no accepted IDs, counter increments, or side effects. outcomeId is the original unrestricted JSON string: do not impose an unpublished UUID, nonempty, ASCII, or maximum-length requirement.',
    'V2 public wire clarification: outcome batches return the closed object {acceptedIds:[string],duplicateIds:[string]}, each preserving input order. These are the outcomeId values accepted or replayed, not counters or private record identifiers.',
    'V2 public wire clarification: revision-diff requires against (positive integer). Optional environment disambiguates per-environment revision numbers; omitting it is valid only when exactly one Environment contains both revisions. Ambiguous requests return 400 INVALID_REQUEST, never compare revisions across Environments. Flag-specific revision lists require environment.',
    'V2 compatibility clarification: ordinary and saved legacy Evaluation responses retain the original shape; evaluations participating in a progressive activation include both rolloutId and stepIndex. If an implementation includes the two fields outside a rollout they are both null. The union allows old replay bodies, never an extra wrapper.',
    'The Evaluation context is an explicitly open map of published ASCII attribute names to string values; subjectKey is the intrinsic required bucketing input and need not also occur in contextAttributes. Other supplied keys must occur in the captured Environment attribute whitelist. Missing nonempty subjectKey uses MISSING_SUBJECT_KEY and a non-intrinsic unknown attribute uses INVALID_FLAG_RULE. Rules, variant type agreement, allocation totals and progressive-step bounds retain the business errors published in README/Manager.',
    'The V1 seed keeps only projects, environments, flags and activeRevisions. The linked public example has one exact RFC 8785 Snapshot digest. Seed flags have no createdAt field; their public createdAt is the earliest imported revision createdAt, or the import transaction time if none exists, and replay never changes it. No rollout or outcome state may be seeded.',
  ],
};
