const { fillUiContext, navigateReadView } = await import(new URL("browser.mjs", process.env.FRONTAL_V2_SHARED_ROOT_URL ?? new URL("../../../../../src/task-evaluator-v2/", import.meta.url)));
import { candidateAssert as assert } from "../lib/execution.mjs";

import {
  assertEvaluation, assertFlag, assertFlagRevision, assertOpenApiDocument, assertProgressiveRollout,
  assertPublicError, assertSnapshot, canonicalJson, exactKeys, snapshotDigest, snapshotFromRevision,
  assertRolloutAuthority, expectedRolloutEvaluation, assertExpectedEvaluation,
} from "../oracles/index.mjs";
import { CaseExcluded } from "../lib/execution.mjs";

export function defineCase(id, fixtureFamily, action, oracle, seams, run) { return Object.freeze({ id, taskId: "flagfoundry", fixtureFamily, action, oracle, seams: Object.freeze([...seams]), run }); }
export function caseResult(ctx, details = {}, diagnostics = []) { return ctx.pass({ evidence: [{ taskId: "flagfoundry", caseId: ctx.caseId, ...details }], ...(diagnostics.length ? { diagnostics } : {}) }); }
export function blocked(assertionId, blockedBy) { return { assertionId, blockedBy }; }

export function requireStatus(ctx, response, expected, label = "request", options = {}) { const statuses = Array.isArray(expected) ? expected : [expected]; ctx.ok(statuses.includes(response.status), `${label} expected ${statuses.join("/")}, got ${response.status}: ${response.text}`, options); return response.json; }
export function expectError(ctx, response, status, code, options = {}) { ctx.assert(`${code} exact public error`, () => assertPublicError(response, status, code), options); return response; }

export async function boot(ctx, options = {}) {
  if (options.install) await ctx.command("npm", ["install", "--no-audit", "--no-fund"], { timeoutMs: 300_000 });
  if (options.migrate !== false) await ctx.migrate({ timeoutMs: 180_000 });
  if (options.build) await ctx.npm("build", [], { timeoutMs: 300_000 });
  const family = options.family ?? ctx.fixtures.flag(); if (options.seed !== false) await ctx.seed(options.seed ?? family.seed, { timeoutMs: 180_000 });
  const apis = []; for (let index = 0; index < (options.apiCount ?? 1); index += 1) apis.push(await ctx.startApi({ healthTimeoutMs: 60_000 })); return { family, apis, api: apis[0] };
}

export async function snapshot(ctx, baseUrl, options = {}) { const value = await ctx.snapshot(baseUrl, options); ctx.assert("exact point-in-time FlagFoundry snapshot", () => assertSnapshot(value, { final: options.final ?? true }), options.assertionOptions); return value; }
export async function checkRolloutAuthority(ctx, baseUrl, rolloutId, { expectedState, bodies = [], assertionOptions = { hardCapIds: ['ROLLOUT_AUTHORITY'] } } = {}) {
  const value = await snapshot(ctx, baseUrl);
  ctx.assert('confirmed rollout active authority', () => assertRolloutAuthority(value, rolloutId, { expectedState }), assertionOptions);
  for (const body of bodies) {
    const response = await ctx.evaluateFlag(baseUrl, body);
    requireStatus(ctx, response, 200, 'fresh rollout authority Evaluation', assertionOptions);
    ctx.assert('rollout Evaluation shape', () => assertEvaluation(response.json), assertionOptions);
    assertExpectedEvaluation(ctx, response.json, expectedRolloutEvaluation(value, rolloutId, body), 'rollout routing agrees with the public active authority', assertionOptions);
  }
  return value;
}
export async function waitSnapshot(ctx, baseUrl, predicate, options = {}) { return ctx.waitFor(async () => { const value = await ctx.snapshot(baseUrl, { timeoutMs: options.requestTimeoutMs }); return predicate(value) ? value : undefined; }, { timeoutMs: options.timeoutMs ?? 180_000, intervalMs: options.intervalMs ?? 100, label: options.label ?? "FlagFoundry durable state", processes: options.processes ?? [] }); }

export function flagBody(projectId, key, flagType = "STRING") { return { projectId, key, flagType }; }
export function outcomeBody(outcomes) { return { outcomes: outcomes.map(({ outcomeId, stepIndex, subjectKey, snapshotDigest: digest, outcome }) => ({ outcomeId, stepIndex, subjectKey, snapshotDigest: digest, outcome })) }; }
export function progressiveBody(expectedActiveRevision, steps) { return { expectedActiveRevision, steps: steps.map(({ candidateExposureBasisPoints, minimumEvaluationCount, maximumFailureBasisPoints, observationSeconds }) => ({ candidateExposureBasisPoints, minimumEvaluationCount, maximumFailureBasisPoints, observationSeconds })) }; }

export async function createFlag(ctx, baseUrl, body, options = {}) { const response = await ctx.createFlag(baseUrl, body, { key: options.key ?? ctx.key(`flag:${body.projectId}:${body.key}`) }); requireStatus(ctx, response, 201, options.label ?? "create Flag", options.assertionOptions); ctx.assert("exact Flag response", () => assertFlag(response.json)); return response; }
export async function createRevision(ctx, baseUrl, flagId, body, options = {}) { const response = await ctx.createRevision(baseUrl, flagId, body, { key: options.key ?? ctx.key(`revision:${flagId}:${options.label ?? "draft"}`) }); requireStatus(ctx, response, 202, options.label ?? "create Flag Revision", options.assertionOptions); ctx.assert("exact COMPILING FlagRevision", () => assertFlagRevision(response.json)); ctx.equal(response.json.state, "COMPILING", "new revision state"); return response; }
export async function compileRevision(ctx, baseUrl, revisionId, options = {}) { const workers = []; for (let index = 0; index < (options.workerCount ?? 2); index += 1) workers.push(await ctx.startWorker(options.workerOptions ?? {})); const state = await waitSnapshot(ctx, baseUrl, (value) => { const revision = value.resources.flagRevisions.find((item) => item.revisionId === revisionId); return revision && ["READY", "REJECTED"].includes(revision.state) && value.work.filter(({ aggregateId }) => aggregateId === revisionId).every(({ terminal }) => terminal) ? value : undefined; }, { label: options.label ?? `compile ${revisionId}`, timeoutMs: options.timeoutMs, processes: workers }); return { state, revision: state.resources.flagRevisions.find((item) => item.revisionId === revisionId), artifact: state.resources.flagSnapshots.find((item) => item.revisionId === revisionId), workers };
}
export async function createReadyCandidate(ctx, baseUrl, family, options = {}) { const response = await createRevision(ctx, baseUrl, options.flag?.flagId ?? family.stringFlag.flagId, options.body ?? family.revisionBody(options.flag ?? family.stringFlag, options.label ?? "candidate", options.overrides), { key: options.key, label: options.label }); const compiled = await compileRevision(ctx, baseUrl, response.json.revisionId, options); ctx.equal(compiled.revision.state, "READY", `${options.label ?? "candidate"} READY`); ctx.ok(compiled.artifact, "READY revision has Snapshot"); ctx.equal(compiled.revision.snapshotDigest, snapshotDigest(compiled.artifact), "candidate digest independent oracle", { failureCodeSuffix: "DIGEST_MISMATCH", hardCapIds: ["FLAG_AUTHORITY"] }); if (["B-07", "C-02", "C-03", "C-04", "C-06", "C-08"].includes(ctx.caseId)) await Promise.all(compiled.workers.map(worker => ctx.stop(worker))); return { response, ...compiled }; }
export async function activate(ctx, baseUrl, revisionId, expectedActiveRevision, options = {}) { const response = await ctx.activateRevision(baseUrl, revisionId, expectedActiveRevision, { key: options.key ?? ctx.key(`activate:${revisionId}`) }); requireStatus(ctx, response, 200, options.label ?? "activate revision", options.assertionOptions); ctx.assert("exact activation FlagRevision", () => assertFlagRevision(response.json)); return response; }
export async function progressiveActivate(ctx, baseUrl, revisionId, expectedActiveRevision, steps, options = {}) { const response = await ctx.progressiveActivate(baseUrl, revisionId, progressiveBody(expectedActiveRevision, steps), { key: options.key ?? ctx.key(`progressive:${revisionId}`) }); requireStatus(ctx, response, 202, options.label ?? "progressive activation", options.assertionOptions); ctx.assert("exact ProgressiveRollout", () => assertProgressiveRollout(response.json)); return response; }
export async function submitOutcomes(ctx, baseUrl, rolloutId, outcomes, options = {}) { const response = await ctx.outcomeBatch(baseUrl, rolloutId, outcomeBody(outcomes), { key: options.key ?? ctx.key(`outcomes:${rolloutId}:${outcomes.map(({ outcomeId }) => outcomeId).join(":")}`) }); requireStatus(ctx, response, 200, options.label ?? "outcome batch", options.assertionOptions); exactKeys(response.json, ["acceptedIds", "duplicateIds"], "Outcome batch response"); return response; }

export function exactIdSets(ctx, response, accepted, duplicate, label = "ID sets") { ctx.equal(new Set(response.json.acceptedIds), new Set(accepted), `${label} accepted`); ctx.equal(new Set(response.json.duplicateIds), new Set(duplicate), `${label} duplicate`); ctx.equal(response.json.acceptedIds.length, new Set(response.json.acceptedIds).size, `${label} accepted unique`); ctx.equal(response.json.duplicateIds.length, new Set(response.json.duplicateIds).size, `${label} duplicate unique`); }
export function stableSemantic(ctx, responses, label, options = {}) { ctx.ok(responses.length > 0, `${label} responses`); ctx.equal(new Set(responses.map(({ status }) => status)).size, 1, `${label} status`, options); ctx.equal(new Set(responses.map(({ json }) => canonicalJson(json))).size, 1, `${label} body`, options); return responses[0]; }
export function revisionFor(state, revisionId) { return state.resources.flagRevisions.find((item) => item.revisionId === revisionId); }
export function artifactFor(state, revisionId) { return state.resources.flagSnapshots.find((item) => item.revisionId === revisionId); }
export function deriveSnapshot(family, revision, flag = family.stringFlag, environment = family.environment) { return snapshotFromRevision(revision, flag, flag.projectId, environment); }
export function assertEvaluationResponse(ctx, response, expected, options = {}) { requireStatus(ctx, response, 200, options.label ?? "Evaluation"); ctx.assert("exact Evaluation", () => assertEvaluation(response.json, { final: options.final ?? true })); ctx.equal(response.json, expected, options.label ?? "independent Evaluation", options.assertionOptions); return response; }
export function openApi(ctx, document, options = {}) { ctx.assert("independent OpenAPI 3.1 contract", () => assertOpenApiDocument(document, options)); return document; }
export function requireV1Workspace(ctx) { if (!ctx.v1Workspace) throw new CaseExcluded("missing_v1_checkpoint"); return ctx.forWorkspace(ctx.v1Workspace); }
export async function publishedGate(ctx, script, timeoutMs = 900_000) { const result = await ctx.npm(script, [], { timeoutMs }); ctx.equal(result.exitCode, 0, `${script} exit`); ctx.ok(result.durationMs > 0, `${script} ran`); return result; }
export async function launchBrowser(ctx, api, options = {}) { const chromium = await ctx.loadChromium(); const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/usr/bin/chromium", headless: true }); ctx.defer(() => browser.close()); const page = await browser.newPage({ viewport: options.viewport ?? { width: 1280, height: 900 } }); await page.goto(api.baseUrl, { waitUntil: "networkidle" }); await fillUiContext(page, [[/admin.*token/i, ctx.adminToken]]); await navigateReadView(page, /snapshot/i) || await navigateReadView(page, /^refresh$/i); await page.waitForLoadState("networkidle"); return { browser, page }; }
export async function crashAtBarrier(ctx, baseUrl, point, options = {}) { let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point: actual }) => hold && processRole === "worker" && actual === point }); const worker = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const entry = await barrier.waitFor(({ json }) => json.point === point, { timeoutMs: 90_000, processes: [worker] }); const before = await ctx.snapshot(baseUrl); await ctx.kill(worker); hold = false; await ctx.sleep(options.leaseWaitMs ?? 3_300); const replacement = await ctx.startWorker(); const after = await waitSnapshot(ctx, baseUrl, (value) => value.work.some(({ workId, terminal }) => workId === entry.json.workId && terminal) ? value : undefined, { label: `${point} replacement`, timeoutMs: options.timeoutMs, processes: [replacement] }); return { barrier, entry, before, after, worker, replacement }; }
export function assertNoSecret(value, sentinels = []) { const text = typeof value === "string" ? value : canonicalJson(value); for (const secret of sentinels) if (secret) assert.equal(text.includes(secret), false); assert.equal(/(?:idempotency|barrier|lease)[_-]?token/i.test(text), false); return true; }
