import { assertStatement, assertWork, percentile } from "../oracles/index.mjs";
import {
  boot, caseResult, correctionBody, expectError, requireStatus, requireV1Workspace, snapshot,
  stableSemantic, usageBody, waitSnapshot,
} from "./helpers.mjs";
import { closedLoopWindow, performanceBatch, writePerformanceSeed } from "./perf.mjs";

const e01 = define(
  "E-01", "F-MIGRATION populated V1 history fixture",
  "Create real V1 open and finalized Statements, late rejection and Work history, then migrate the same database with FINAL",
  "Base revision one, lines, events and timestamps remain unchanged and only the new Correction endpoint can revise history",
  ["V1 public commands", "FINAL public commands", "same PostgreSQL database", "verification snapshot"],
  async (ctx) => {
    const family = ctx.fixtures.migration(); const v1 = requireV1Workspace(ctx); await v1.migrate(); await v1.seed(family.seed); const v1Api = await v1.startApi(); requireStatus(ctx, await ctx.advanceWatermark(v1Api.baseUrl, family.tenant.tenantId, "2035-01-01T00:00:00.000Z", { key: ctx.key("e01-v1-watermark") }), 200, "V1 Watermark"); const worker = await v1.startWorker(); const before = await waitSnapshot(ctx, v1Api.baseUrl, (state) => state.work.length && state.work.every(({ terminal }) => terminal) ? state : undefined, { label: "V1 finalized history", processes: [worker] }); const late = ctx.fixtures.event(1100, { occurredAt: "2034-12-31T23:59:59.999Z" }); expectError(ctx, await ctx.usageBatch(v1Api.baseUrl, usageBody(family.tenant.tenantId, [late]), { key: ctx.key("e01-late") }), 409, "LATE_USAGE_EVENT"); const v1Final = await snapshot(ctx, v1Api.baseUrl, { final: false }); await ctx.stop(worker); await ctx.stop(v1Api);
    await ctx.migrate(); const finalApi = await ctx.startApi(); const final = await snapshot(ctx, finalApi.baseUrl); for (const old of v1Final.resources.statements) { const migrated = final.resources.statements.find(({ statementId }) => statementId === old.statementId); ctx.equal(ctx.canonical(migrated), ctx.canonical(old), `${old.statementId} base JSON preserved`, { failureCodeSuffix: "STATEMENT_HISTORY_CHANGED", hardCapIds: ["MIGRATION_COMPATIBILITY"] }); ctx.equal(migrated.revision, 1, "migrated base revision one"); } for (const event of v1Final.events) ctx.ok(final.events.some((item) => item.eventId === event.eventId && ctx.canonical(item) === ctx.canonical(event)), `${event.eventId} event preserved`);
    expectError(ctx, await ctx.usageBatch(finalApi.baseUrl, usageBody(family.tenant.tenantId, [late]), { key: ctx.key("e01-late-final") }), 409, "LATE_USAGE_EVENT"); const source = family.events.find(({ occurredAt }) => occurredAt < "2035-01-01T00:00:00.000Z"); const correction = ctx.fixtures.correction(20, source, { correctionId: "e01-only-correction" }); requireStatus(ctx, await ctx.correctionBatch(finalApi.baseUrl, correctionBody(family.tenant.tenantId, [correction]), { key: ctx.key("e01-correction") }), 200, "FINAL correction endpoint");
    return caseResult(ctx, { v1Statements: v1Final.resources.statements.length, preservedEvents: v1Final.events.length });
  },
);

const e02 = define(
  "E-02", "F-MIGRATION saved replay and delivery identity fixture",
  "Persist a V1 unknown-response idempotent result and delivered/undelivered Events, migrate, replay and restart Dispatcher",
  "Original status, semantic body, event IDs, body and sequence survive and FINAL detail fields never rewrite saved V1 responses",
  ["V1 response shield", "V1/FINAL API", "webhook receiver", "verification snapshot"],
  async (ctx) => {
    const family = ctx.fixtures.migration(); const v1 = requireV1Workspace(ctx); await v1.migrate(); await v1.seed(family.seed); const api = await v1.startApi(); let allowAck = false; const receiver = await ctx.receiver({ behavior: (_entry, ledger) => ledger.length === 1 || allowAck ? { status: 204 } : { status: 500 } }); const dispatcher = await v1.startDispatcher({ webhookUrl: receiver.url });
    const firstEvent = ctx.fixtures.event(1200); requireStatus(ctx, await ctx.usageBatch(api.baseUrl, usageBody(family.tenant.tenantId, [firstEvent]), { key: ctx.key("e02-delivered") }), 202, "delivered V1 batch"); await ctx.waitFor(() => receiver.ledger[0]?.acknowledged, { label: "V1 delivered event", processes: [dispatcher] });
    const shield = await ctx.responseShield(api.baseUrl); const replayKey = ctx.key("e02-unknown"); const replayEvent = ctx.fixtures.event(1201); shield.dropNextMutation(); await ctx.usageBatch(shield.baseUrl, usageBody(family.tenant.tenantId, [replayEvent]), { key: replayKey }).catch(() => undefined); const capture = await ctx.waitFor(() => shield.captures.find(({ dropped }) => dropped), { label: "V1 unknown response" }); await ctx.waitFor(() => receiver.ledger.length >= 2, { label: "V1 undelivered event", processes: [dispatcher] }); await ctx.stop(dispatcher); const before = await snapshot(ctx, api.baseUrl, { final: false }); await ctx.stop(api);
    await ctx.migrate(); const finalApi = await ctx.startApi(); const replay = await ctx.usageBatch(finalApi.baseUrl, usageBody(family.tenant.tenantId, [replayEvent]), { key: replayKey }); ctx.equal(replay.status, capture.response.status, "V1 saved status after migration"); ctx.equal(ctx.canonical(replay.json), ctx.canonical(JSON.parse(capture.response.body)), "V1 saved body after migration", { failureCodeSuffix: "SAVED_REPLAY_CHANGED", hardCapIds: ["MIGRATION_COMPATIBILITY", "IDEMPOTENCY_CORRECTNESS"] }); const after = await snapshot(ctx, finalApi.baseUrl); for (const event of before.events) ctx.ok(after.events.some((item) => item.eventId === event.eventId && ctx.canonical(item) === ctx.canonical(event)), `${event.eventId} identity/body/sequence preserved`);
    allowAck = true; const replacement = await ctx.startDispatcher({ webhookUrl: receiver.url }); const redelivery = await ctx.waitFor(() => receiver.ledger.find((entry, index) => index >= 2 && entry.acknowledged), { label: "FINAL undelivered event redelivery", timeoutMs: 120_000, processes: [replacement] }); const original = receiver.ledger.find((entry) => entry.headers["x-metersettle-event-id"] === redelivery.headers["x-metersettle-event-id"]); ctx.equal(redelivery.raw, original.raw, "redelivery body stable");
    return caseResult(ctx, { savedStatus: replay.status, preservedEvents: before.events.length, deliveryAttempts: receiver.ledger.length });
  },
);

const e03 = define(
  "E-03", "F-MIGRATION live leased Work and Watermark fixture",
  "Hold a V1 worker after claim, migrate the same database while paused, let FINAL reclaim, then release the stale V1 owner",
  "Watermark and leased Work identity persist exactly and the old token cannot alter the completed base or Revision state",
  ["V1/FINAL public commands", "worker barrier", "same database", "verification snapshot"],
  async (ctx) => {
    const family = ctx.fixtures.migration(); const v1 = requireV1Workspace(ctx); await v1.migrate(); await v1.seed(family.seed); const api = await v1.startApi(); requireStatus(ctx, await ctx.advanceWatermark(api.baseUrl, family.tenant.tenantId, "2036-01-01T00:00:00.000Z", { key: ctx.key("e03-watermark") }), 200, "V1 Watermark"); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && point === "worker.claimed" }); const oldWorker = await v1.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const claim = await barrier.waitFor(({ json }) => json.point === "worker.claimed", { processes: [oldWorker] }); const before = await snapshot(ctx, api.baseUrl, { final: false }); const oldWork = before.work.find(({ workId }) => workId === claim.json.workId); await ctx.stop(api); await ctx.migrate(); const finalApi = await ctx.startApi(); const migrated = await snapshot(ctx, finalApi.baseUrl); const migratedWork = migrated.work.find(({ workId }) => workId === oldWork.workId); ctx.equal(migratedWork, oldWork, "leased Work exact across migration", { failureCodeSuffix: "WORK_MIGRATION_CHANGED", hardCapIds: ["MIGRATION_COMPATIBILITY"] }); ctx.equal(migrated.resources.tenantStates.find(({ tenantId }) => tenantId === family.tenant.tenantId).watermarkThrough, before.resources.tenantStates.find(({ tenantId }) => tenantId === family.tenant.tenantId).watermarkThrough, "Watermark exact across migration");
    await ctx.sleep(3_300); const replacement = await ctx.startWorker(); const completed = await waitSnapshot(ctx, finalApi.baseUrl, (state) => state.work.find(({ workId }) => workId === oldWork.workId)?.terminal ? state : undefined, { label: "FINAL replacement drain", processes: [replacement] }); hold = false; barrier.releaseAll(); await ctx.sleep(500); const final = await snapshot(ctx, finalApi.baseUrl); ctx.equal(ctx.canonical(final.resources.statements), ctx.canonical(completed.resources.statements), "stale V1 worker cannot mutate FINAL state", { failureCodeSuffix: "STALE_V1_COMMIT", hardCapIds: ["STALE_WORK_OR_LOST_WORK", "MIGRATION_COMPATIBILITY"] }); ctx.equal(ctx.canonical(final.events), ctx.canonical(completed.events), "stale V1 worker cannot add event");
    return caseResult(ctx, { workId: oldWork.workId, beforeAttempt: oldWork.attempt, afterAttempt: final.work.find(({ workId }) => workId === oldWork.workId).attempt });
  },
);

const e04 = define(
  "E-04", "F-PERF-V1 exact million-event HTTP fixture",
  "Run the frozen 1000-event/s ingestion and 200-read/s scenarios with exact seed, selectors, 64 clients and 10s plus 60s windows",
  "Throughput, p95, 5xx and every post-load rating invariant meet the published thresholds",
  ["fixed performance seed", "production HTTP", "64 closed-loop clients", "verification snapshot"],
  async (ctx) => {
    const catalog = await writePerformanceSeed(ctx); await ctx.migrate(); await ctx.seedFile(catalog.path, { timeoutMs: 900_000 }); const api = await ctx.startApi({ healthTimeoutMs: 60_000 });
    const executeBatch = async (prefix, index) => { const response = await ctx.usageBatch(api.baseUrl, performanceBatch(catalog, prefix, index), { key: ctx.key(`${prefix}:${index}`), timeoutMs: 10_000 }); return { status: response.status, durationMs: response.durationMs, acceptedCount: response.json?.acceptedEventIds?.length ?? 0, duplicateCount: response.json?.duplicateEventIds?.length ?? 0 }; };
    await closedLoopWindow(ctx, [null], 64, 10, 10, (_unused, index) => executeBatch("perf-warmup", index)); const measuredRun = await closedLoopWindow(ctx, [null], 64, 60, 10, (_unused, index) => executeBatch("perf-measured", index)); const successfulBatches = measuredRun.filter(({ response }) => response.status === 202 && response.acceptedCount === 100 && response.duplicateCount === 0).length; const ingestP95 = percentile(measuredRun.map(({ durationMs }) => durationMs), 0.95); const ingest5xx = measuredRun.filter(({ response }) => response.status >= 500).length; ctx.ok(successfulBatches / 60 >= 10, "ingest at least 10 successful batches/s"); ctx.ok(ingestP95 <= 400, `ingest p95 ${ingestP95}ms`); ctx.equal(ingest5xx, 0, "ingest unexpected 5xx"); const measuredReplay = await ctx.usageBatch(api.baseUrl, performanceBatch(catalog, "perf-measured", 0), { key: ctx.key("perf-measured:0"), timeoutMs: 10_000 }); requireStatus(ctx, measuredReplay, 202, "measured saved replay"); ctx.equal(measuredReplay.json.acceptedEventIds.length, 100, "measured replay returns original accepted body"); const postIngest = await snapshot(ctx, api.baseUrl, { timeoutMs: 120_000 }); ctx.equal(postIngest.resources.usageEvents.filter(({ eventId }) => eventId.startsWith("perf-measured")).length, successfulBatches * 100, "all measured events persisted once", { failureCodeSuffix: "PERF_INGEST_INVARIANT", hardCapIds: ["RATING_CONSERVATION", "IDEMPOTENCY_CORRECTNESS"] });
    await ctx.resetDatabase(); await ctx.migrate(); await ctx.seedFile(catalog.path, { timeoutMs: 900_000 }); const readApi = await ctx.startApi({ healthTimeoutMs: 60_000 }); const watermarks = await ctx.concurrent(catalog.tenants, 20, (tenant, index) => ctx.advanceWatermark(readApi.baseUrl, tenant.tenantId, "2026-01-01T00:00:00.000Z", { key: ctx.key(`perf-watermark:${index}`) })); watermarks.forEach((response) => requireStatus(ctx, response, 200, "perf Watermark")); const workers = [await ctx.startWorker(), await ctx.startWorker()]; const statements = await ctx.waitFor(async () => { const values = await allStatements(ctx, readApi.baseUrl); return values.length === 100 && values.every(({ state }) => state === "FINALIZED") ? values : undefined; }, { label: "10k-line Statement setup", timeoutMs: 300_000, intervalMs: 250, processes: workers }); const ordered = statements.sort((a, b) => Buffer.from(a.statementId).compare(Buffer.from(b.statementId)));
    const compactRead = async (statementId) => { const response = await ctx.statement(readApi.baseUrl, statementId); const value = response.json?.statement ?? response.json; const valid = response.status === 200 && value?.lines?.reduce((sum, line) => sum + line.quantity, 0) === value?.totalQuantity && value?.lines?.reduce((sum, line) => sum + line.chargeMinor, 0) === value?.totalMinor; return { status: response.status, durationMs: response.durationMs, valid }; };
    await closedLoopWindow(ctx, ordered, 64, 10, 200, (statement) => compactRead(statement.statementId)); const samples = await closedLoopWindow(ctx, ordered, 64, 60, 200, (statement) => compactRead(statement.statementId)); const successfulReads = samples.filter(({ response }) => response.status === 200 && response.valid).length; const readP95 = percentile(samples.map(({ durationMs }) => durationMs), 0.95); ctx.ok(successfulReads / 60 >= 200, "Statement reads at least 200/s"); ctx.ok(readP95 <= 150, `Statement read p95 ${readP95}ms`); ctx.equal(samples.filter(({ response }) => response.status >= 500).length, 0, "Statement read unexpected 5xx"); const postRead = await snapshot(ctx, readApi.baseUrl, { timeoutMs: 120_000 }); postRead.resources.statements.filter(({ state }) => state === "FINALIZED").forEach((statement) => ctx.assert("post-load Statement invariant", () => assertStatement(statement), { failureCodeSuffix: "PERF_READ_INVARIANT", hardCapIds: ["RATING_CONSERVATION"] }));
    return caseResult(ctx, { ingestion: { successfulBatches, throughput: successfulBatches / 60, p95Ms: ingestP95, unexpected5xx: ingest5xx }, statementRead: { successfulReads, throughput: successfulReads / 60, p95Ms: readP95, unexpected5xx: 0 } });
  },
);

const e05 = define(
  "E-05", "F-PERF-V1 exact ten-thousand-line recovery fixture",
  "Advance all fixed tenants, kill two workers at claimed, wait lease expiry and time two replacements to a proving snapshot",
  "Exactly ten thousand lines finalize once within sixty seconds with no nonterminal Work, wrong plan, leak or secret",
  ["fixed performance seed", "worker barrier", "two SIGKILLs", "replacement workers", "verification snapshot"],
  async (ctx) => {
    const catalog = await writePerformanceSeed(ctx); await ctx.migrate(); await ctx.seedFile(catalog.path, { timeoutMs: 900_000 }); const api = await ctx.startApi({ healthTimeoutMs: 60_000 }); const responses = await ctx.concurrent(catalog.tenants, 20, (tenant, index) => ctx.advanceWatermark(api.baseUrl, tenant.tenantId, "2026-01-01T00:00:00.000Z", { key: ctx.key(`recovery-watermark:${index}`) })); responses.forEach((response) => requireStatus(ctx, response, 200, "recovery Watermark")); const barrier = await ctx.barrier({ hold: ({ processRole, point }) => processRole === "worker" && point === "worker.claimed" }); const workers = [await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }), await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } })]; await ctx.waitFor(() => new Set(barrier.ledger.filter(({ json }) => json.point === "worker.claimed").map(({ json }) => json.workId)).size >= 2, { label: "two claimed Rating works", timeoutMs: 90_000, processes: workers }); await Promise.all(workers.map((worker) => ctx.kill(worker))); await ctx.sleep(3_300); const replacements = [await ctx.startWorker(), await ctx.startWorker()]; const started = performance.now(); await ctx.waitFor(async () => { const values = await allStatements(ctx, api.baseUrl); const finalized = values.filter(({ periodStart, state }) => periodStart === "2025-12-01T00:00:00.000Z" && state === "FINALIZED"); return finalized.reduce((sum, statement) => sum + statement.lines.length, 0) === 10_000 ? values : undefined; }, { label: "10k recovered lines", timeoutMs: 60_000, intervalMs: 100, processes: replacements }); const final = await snapshot(ctx, api.baseUrl, { timeoutMs: 120_000 }); const durationMs = performance.now() - started; const closed = final.resources.statements.filter(({ periodStart }) => periodStart === "2025-12-01T00:00:00.000Z"); const lines = closed.flatMap(({ lines }) => lines); ctx.ok(durationMs <= 60_000, `recovery duration ${durationMs}ms`); ctx.equal(lines.length, 10_000, "exactly 10k rated lines", { failureCodeSuffix: "PERF_RECOVERY_INVARIANT", hardCapIds: ["RATING_CONSERVATION", "STALE_WORK_OR_LOST_WORK"] }); ctx.equal(new Set(lines.map(({ eventId }) => eventId)).size, 10_000, "no duplicate or missing rated line"); ctx.equal(final.work.filter(({ kind, terminal }) => kind === "RATING" && !terminal).length, 0, "no nonterminal Rating Work"); ctx.assert("all recovery Work shapes", () => assertWork(final.work)); for (const statement of closed) ctx.assert("recovered Statement rating", () => assertStatement(statement)); const logs = replacements.map(({ logs }) => logs).join("\n"); ctx.ok(!logs.includes(ctx.adminToken) && !logs.includes(ctx.barrierToken) && !logs.includes(ctx.databaseUrl), "recovery logs contain no evaluator secrets");
    return caseResult(ctx, { durationMs: Math.round(durationMs), ratedLines: lines.length, terminalWork: final.work.length });
  },
);

async function allStatements(ctx, baseUrl) { const items = []; let cursor; for (let page = 0; page < 10_000; page += 1) { const response = await ctx.statements(baseUrl, { limit: "100", ...(cursor ? { cursor } : {}) }); requireStatus(ctx, response, 200, "Statement page"); items.push(...response.json.items); cursor = response.json.nextCursor; if (cursor === null) break; } return items; }
function define(id, fixtureFamily, action, oracle, seams, run) { return Object.freeze({ id, taskId: "metersettle", fixtureFamily, action, oracle, seams: Object.freeze(seams), run }); }

export const E_CASES = Object.freeze([e01, e02, e03, e04, e05]);
