import assert from "node:assert/strict";
import { assertEventSequence, assertNotificationIdentity, assertOneActiveDedup, assertQuorumClosure, canonicalJson, retryDelaySeconds, schedule } from "../oracles/index.mjs";
import { acknowledge, createIncident, createPolicy, diagnostic, guardedCase, legacyAcknowledge, prepare, resolveIncident, resources, semanticError, stableSnapshot, startReceivers, successful, waitSnapshot, waitStep } from "./helpers.mjs";

const B01 = guardedCase("B-01", ["INCIDENT_TERMINAL_AUTHORITY", "STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  let targetNotificationId; const targetTimes = []; const receiver = await ctx.receiver({ path: "/notifications", behavior: (entry) => { const notificationId = entry.headers["x-incidentrelay-notification-id"]; targetNotificationId ??= notificationId; if (notificationId !== targetNotificationId) return { status: 204 }; targetTimes.push(performance.now()); return targetTimes.length <= 6 ? { status: 500 } : { status: 204 }; } });
  const fixture = ctx.fixtures.notification([receiver.url, receiver.url, receiver.url]); const { api, workers } = await prepare(ctx, fixture, { workerCount: 2 });
  const policy = await createPolicy(ctx, api.baseUrl, fixture, "arithmetic", { steps: [0, 1, 60, 86_400].map((delaySeconds, stepIndex) => ({ stepIndex, delaySeconds, responderIds: [fixture.responders[stepIndex % 3].responderId], quorumRequired: 1 })), expireAfterSeconds: 86_500 }); assert.equal(policy.response.status, 200);
  const created = await createIncident(ctx, api.baseUrl, fixture, "arithmetic"); const expected = schedule(policy.policy, created.incident.createdAt); const snapshot = await ctx.snapshot(api.baseUrl); const steps = resources(snapshot).groupEscalationSteps.filter((item) => item.incidentId === created.incidentId);
  assert.deepEqual(steps.map(({ dueAt }) => dueAt), expected.map(({ dueAt }) => dueAt)); assert.equal(created.incident.expiresAt, expected[0].expiresAt);
  await ctx.waitFor(() => targetTimes.length >= 7, { timeoutMs: 80_000, processes: workers, label: "six failures and successful retry" });
  const expectedDelays = [1, 2, 3, 4, 5, 6].map(retryDelaySeconds), gaps = targetTimes.slice(1).map((time, index) => time - targetTimes[index]); assert.deepEqual(expectedDelays, [1, 2, 4, 8, 16, 32]);
  gaps.forEach((gap, index) => { const expectedMs = expectedDelays[index] * 1_000; assert.ok(gap >= expectedMs - 250 && gap <= expectedMs + 2_500, `attempt ${index + 2} receiver timing window ${gap}ms around ${expectedMs}ms`); });
  const delivered = resources(await ctx.snapshot(api.baseUrl)).notificationDeliveries.find((item) => item.notificationId === targetNotificationId); assert.equal(delivered.state, "DELIVERED"); assert.equal(delivered.attemptCount, 7); assert.equal(delivered.nextAttemptAt, null);
  ctx.mark("retry.observable-window", { attempts: targetTimes.length, gaps, expectedDelays });
  return ctx.pass({ diagnostics: [diagnostic("IR-B01-EXACT-RETRY-TIMESTAMP", "SPEC-GAP-03")] });
});

const B02 = guardedCase("B-02", ["INCIDENT_TERMINAL_AUTHORITY", "IDEMPOTENCY_CORRECTNESS"], async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.idempotency(receivers.map(({ url }) => url)); const { api, workers } = await prepare(ctx, fixture, { workerCount: 1 });
  const original = await createIncident(ctx, api.baseUrl, fixture, "lifecycle", { dedupKey: "stable-active-key" });
  const semanticReplay = await ctx.mutate(api.baseUrl, "/api/v1/incidents", ctx.key("lifecycle-semantic"), original.body); successful(semanticReplay, "active dedup replay", [200, 201]); assert.equal(semanticReplay.json.incidentId, original.incidentId);
  const conflict = await ctx.mutate(api.baseUrl, "/api/v1/incidents", ctx.key("lifecycle-conflict"), { ...original.body, details: "different" }); semanticError(conflict, 409, "INCIDENT_DEDUP_CONFLICT");
  await waitStep(ctx, api.baseUrl, original.incidentId, 0, "SENT", { processes: workers }); await legacyAcknowledge(ctx, api.baseUrl, original.incidentId, fixture.responders[0].responderId); await resolveIncident(ctx, api.baseUrl, original.incidentId, fixture.responders[0].responderId);
  const replacement = await createIncident(ctx, api.baseUrl, fixture, "replacement", { dedupKey: original.body.dedupKey }); assert.notEqual(replacement.incidentId, original.incidentId, "terminal releases active dedup key");
  const eternalReplay = await ctx.mutate(api.baseUrl, "/api/v1/incidents", ctx.key("incident:lifecycle"), original.body); assert.equal(eternalReplay.status, original.response.status); assert.equal(canonicalJson(eternalReplay.json), canonicalJson(original.incident));
  assertOneActiveDedup(resources(await ctx.snapshot(api.baseUrl)).incidents); return ctx.pass();
});

const B03 = guardedCase("B-03", ["INCIDENT_TERMINAL_AUTHORITY", "EVENT_TRANSACTIONALITY"], async (ctx) => {
  const fixture = ctx.fixtures.policy(); const { api } = await prepare(ctx, fixture); const before = stableSnapshot(await ctx.snapshot(api.baseUrl));
  const invalidPolicies = [
    [{ stepIndex: 0, delaySeconds: 0, responderIds: [ctx.uuid("missing")], quorumRequired: 1 }],
    [{ stepIndex: 0, delaySeconds: -1, responderIds: [fixture.responders[0].responderId], quorumRequired: 1 }],
    [{ stepIndex: 0, delaySeconds: 0, responderIds: [fixture.responders[0].responderId], quorumRequired: 2 }],
  ];
  for (let index = 0; index < invalidPolicies.length; index += 1) { const invalid = await createPolicy(ctx, api.baseUrl, fixture, `invalid-${index}`, { steps: invalidPolicies[index], expectSuccess: false }); semanticError(invalid.response, 400, index === 2 ? "INVALID_QUORUM_POLICY" : "INVALID_ESCALATION_POLICY"); assert.equal(stableSnapshot(await ctx.snapshot(api.baseUrl)), before, `invalid policy ${index} has zero side effect`); }
  const invalidIncident = await ctx.mutate(api.baseUrl, "/api/v1/incidents", ctx.key("bad-target"), fixture.incidentBody("bad", { serviceId: ctx.uuid("missing-service") })); semanticError(invalidIncident, 404, "NOT_FOUND"); assert.equal(stableSnapshot(await ctx.snapshot(api.baseUrl)), before, "invalid Incident is atomic"); return ctx.pass();
});

const B04 = guardedCase("B-04", ["IDEMPOTENCY_CORRECTNESS", "EVENT_TRANSACTIONALITY"], async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.idempotency(receivers.map(({ url }) => url)); const { api } = await prepare(ctx, fixture); const saved = [];
  async function loseAndReplay(baseUrl, path, key, body, status) { const shield = await ctx.responseShield(baseUrl); shield.dropNextMutation(); await assert.rejects(ctx.mutate(shield.baseUrl, path, key, body)); const capture = shield.captures.find(({ dropped }) => dropped); assert.equal(capture.response.status, status, `${path} committed before response loss`); const replay = await ctx.mutate(baseUrl, path, key, body); assert.equal(replay.status, capture.response.status); assert.equal(replay.text, capture.response.body, `${path} replay exact bytes`); saved.push({ path, key, body, status: replay.status, text: replay.text }); return replay; }
  const createBody = fixture.incidentBody("unknown-create"), createKey = ctx.key("unknown-create"); const replay = await loseAndReplay(api.baseUrl, "/api/v1/incidents", createKey, createBody, 201); const originalIncidentId = replay.json.incidentId;
  const policyBody = { expectedCurrentVersion: 1, steps: fixture.policyGroup.steps, expireAfterSeconds: fixture.policyGroup.expireAfterSeconds }, policyKey = ctx.key("unknown-policy"); await loseAndReplay(api.baseUrl, `/api/v1/services/${fixture.service.serviceId}/escalation-policies`, policyKey, policyBody, 200);
  const group = await createIncident(ctx, api.baseUrl, fixture, "unknown-group"); const workers = await Promise.all([ctx.startWorker(), ctx.startWorker()]); await waitStep(ctx, api.baseUrl, group.incidentId, 0, "SENT", { processes: workers });
  const firstAckBody = { stepIndex: 0, responderId: fixture.responders[0].responderId }, firstAckKey = ctx.key("unknown-ack"); await loseAndReplay(api.baseUrl, `/api/v1/incidents/${group.incidentId}/acknowledgements`, firstAckKey, firstAckBody, 200); await acknowledge(ctx, api.baseUrl, group.incidentId, 0, fixture.responders[1].responderId, "unknown-ack-winner");
  const resolveBody = { responderId: fixture.responders[2].responderId, resolution: "Unknown response recovery" }, resolveKey = ctx.key("unknown-resolve"); await loseAndReplay(api.baseUrl, `/api/v1/incidents/${group.incidentId}/resolve`, resolveKey, resolveBody, 200);
  await ctx.stop(api); const restarted = await ctx.startApi(); for (const item of saved) { const afterRestart = await ctx.mutate(restarted.baseUrl, item.path, item.key, item.body); assert.equal(afterRestart.status, item.status); assert.equal(afterRestart.text, item.text, `${item.path} replay survives API restart`); }
  const snapshot = await ctx.snapshot(restarted.baseUrl); assert.equal(resources(snapshot).incidents.filter((item) => item.incidentId === originalIncidentId).length, 1); assert.equal(snapshot.events.filter((item) => item.aggregateId === originalIncidentId && item.type === "incident.opened").length, 1); assert.equal(resources(snapshot).incidentAcknowledgements.filter((item) => item.incidentId === group.incidentId).length, 2); assert.equal(snapshot.events.filter((item) => item.aggregateId === group.incidentId && item.type === "incident.acknowledged").length, 1); assert.equal(snapshot.events.filter((item) => item.aggregateId === group.incidentId && item.type === "incident.resolved").length, 1); return ctx.pass();
});

const B05 = guardedCase("B-05", ["IDEMPOTENCY_CORRECTNESS"], async (ctx) => {
  const fixture = ctx.fixtures.contention(); const { apis } = await prepare(ctx, fixture, { apiCount: 2 }); const body = fixture.incidentBody("same-key"), key = ctx.key("same-key");
  const responses = await ctx.concurrent(Array.from({ length: 64 }), 64, (_, index) => ctx.mutate(apis[index % 2].baseUrl, "/api/v1/incidents", key, body)); assert.ok(responses.every((item) => item.status === 201 && item.text === responses[0].text), "same key converges exact response");
  const conflict = await ctx.mutate(apis[0].baseUrl, "/api/v1/incidents", key, { ...body, title: "other" }); semanticError(conflict, 409, "IDEMPOTENCY_CONFLICT");
  const third = await ctx.startApi(); const replay = await ctx.mutate(third.baseUrl, "/api/v1/incidents", key, body); assert.equal(replay.text, responses[0].text); const incidentId = replay.json.incidentId; const snapshot = await ctx.snapshot(third.baseUrl); assert.equal(resources(snapshot).incidents.filter((item) => item.incidentId === incidentId).length, 1); assert.equal(snapshot.work.filter((item) => item.aggregateId === incidentId).length, fixture.policyV1.steps.length + 1); return ctx.pass();
});

const B06 = guardedCase("B-06", ["INCIDENT_TERMINAL_AUTHORITY", "IDEMPOTENCY_CORRECTNESS"], async (ctx) => {
  for (let round = 0; round < 3; round += 1) {
    if (round) await ctx.resetDatabase(); const fixture = ctx.fixtures.contention(); const { apis } = await prepare(ctx, fixture, { apiCount: 2 }); const body = fixture.incidentBody(`distinct-${round}`, { dedupKey: `hot-${round}` });
    const responses = await ctx.concurrent(Array.from({ length: 64 }), 64, (_, index) => ctx.mutate(apis[index % 2].baseUrl, "/api/v1/incidents", ctx.key(`distinct:${round}:${index}`), index % 5 === 0 && round === 2 ? { ...body, title: `variant-${index}` } : body));
    const successfulResponses = responses.filter((item) => [200, 201].includes(item.status)); assert.ok(successfulResponses.length >= 1); assert.equal(new Set(successfulResponses.map((item) => item.json.incidentId)).size, 1, "identical semantics converge one active Incident"); assert.ok(responses.every((item) => [200, 201].includes(item.status) || (item.status === 409 && item.json?.error?.code === "INCIDENT_DEDUP_CONFLICT")));
    const snapshot = await ctx.snapshot(apis[0].baseUrl); assertOneActiveDedup(resources(snapshot).incidents); const winnerId = successfulResponses[0].json.incidentId; assert.equal(resources(snapshot).groupEscalationSteps.filter((item) => item.incidentId === winnerId).length + resources(snapshot).escalationSteps.filter((item) => item.incidentId === winnerId).length, fixture.policyV1.steps.length);
  }
  return ctx.pass();
});

const B07 = guardedCase("B-07", ["INCIDENT_TERMINAL_AUTHORITY", "EVENT_TRANSACTIONALITY"], async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.contention(receivers.map(({ url }) => url)); const { apis, workers } = await prepare(ctx, fixture, { apiCount: 2, workerCount: 2 });
  await createPolicy(ctx, apis[0].baseUrl, fixture, "race-policy", { steps: [{ stepIndex: 0, delaySeconds: 0, responderIds: [fixture.responders[0].responderId], quorumRequired: 1 }, { stepIndex: 1, delaySeconds: 1, responderIds: [fixture.responders[1].responderId], quorumRequired: 1 }], expireAfterSeconds: 3 });
  const created = await createIncident(ctx, apis[0].baseUrl, fixture, "ack-race"); await waitStep(ctx, apis[0].baseUrl, created.incidentId, 1, "SENT", { processes: workers, timeoutMs: 10_000 });
  const ackRace = await Promise.all([0, 1].map((responderIndex, index) => legacyAcknowledge(ctx, apis[index].baseUrl, created.incidentId, fixture.responders[responderIndex].responderId, `race-${index}`, { expectSuccess: false })));
  assert.equal(ackRace.filter((item) => item.status === 200).length, 1, "V1 has one acknowledgement winner"); assert.ok(ackRace.filter((item) => item.status !== 200).every((item) => item.status === 409));
  const winnerId = ackRace.find((item) => item.status === 200).json.acknowledgedBy; const terminal = await Promise.all([resolveIncident(ctx, apis[0].baseUrl, created.incidentId, winnerId, "resolve-race", { expectSuccess: false }), resolveIncident(ctx, apis[1].baseUrl, created.incidentId, winnerId, "resolve-race-2", { expectSuccess: false })]); assert.equal(terminal.filter((item) => item.status === 200).length, 1, "resolve commits once");
  const snapshot = await ctx.snapshot(apis[0].baseUrl); assert.equal(resources(snapshot).incidents.find((item) => item.incidentId === created.incidentId).state, "RESOLVED"); assertEventSequence(snapshot.events.filter((item) => item.aggregateId === created.incidentId));
  const expiryRace = await createIncident(ctx, apis[0].baseUrl, fixture, "expiry-race"); await waitStep(ctx, apis[0].baseUrl, expiryRace.incidentId, 1, "SENT", { processes: workers, timeoutMs: 10_000 }); const untilExpiry = Math.max(0, Date.parse(expiryRace.incident.expiresAt) - Date.now() + 5); await new Promise((resolve) => setTimeout(resolve, untilExpiry)); const lateAcks = await Promise.all(fixture.responders.slice(0, 2).map((responder, index) => legacyAcknowledge(ctx, apis[index].baseUrl, expiryRace.incidentId, responder.responderId, `expiry-${index}`, { expectSuccess: false }))); assert.ok(lateAcks.every((item) => item.status === 409 && item.json?.error?.code === "INCIDENT_NOT_ACKNOWLEDGEABLE")); const expired = await waitSnapshot(ctx, apis[0].baseUrl, (value) => resources(value).incidents.find((item) => item.incidentId === expiryRace.incidentId)?.state === "EXPIRED", { processes: workers, timeoutMs: 10_000, label: "expiry wins boundary race" }); assert.equal(expired.events.filter((item) => item.aggregateId === expiryRace.incidentId && item.type === "incident.expired").length, 1); return ctx.pass();
});

const B08 = guardedCase("B-08", ["INCIDENT_TERMINAL_AUTHORITY", "STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  let releaseFirst = false; const receivers = await startReceivers(ctx, 3, (index) => index === 0 && !releaseFirst ? { status: 500 } : { status: 204 }); const fixture = ctx.fixtures.contention(receivers.map(({ url }) => url)); const { api, workers } = await prepare(ctx, fixture, { workerCount: 2 });
  const policy = await createPolicy(ctx, api.baseUrl, fixture, "ordered", { steps: fixture.responders.map(({ responderId }, stepIndex) => ({ stepIndex, delaySeconds: stepIndex, responderIds: [responderId], quorumRequired: 1 })), expireAfterSeconds: 60 }); assert.equal(policy.response.status, 200);
  const created = await createIncident(ctx, api.baseUrl, fixture, "ordered"); await ctx.waitFor(() => receivers[0].ledger.length >= 2, { timeoutMs: 10_000, processes: workers, label: "earlier Step retries while later due" }); assert.equal(receivers[1].ledger.length, 0, "later Step cannot become a successful notification before earlier Step"); const pending = await ctx.snapshot(api.baseUrl); assert.equal(resources(pending).groupEscalationSteps.find((item) => item.incidentId === created.incidentId && item.stepIndex === 1).state, "PENDING"); releaseFirst = true; const sent = await waitSnapshot(ctx, api.baseUrl, (snapshot) => resources(snapshot).groupEscalationSteps.filter((item) => item.incidentId === created.incidentId && item.state === "SENT").length >= 2, { processes: workers, timeoutMs: 20_000, label: "ordered deliveries sent" }); const orderedSteps = resources(sent).groupEscalationSteps.filter((item) => item.incidentId === created.incidentId && item.state === "SENT").sort((a, b) => a.stepIndex - b.stepIndex); assert.ok(orderedSteps.every((item, index) => index === 0 || item.successfulDeliveryAt >= orderedSteps[index - 1].successfulDeliveryAt), "successful notifications preserve increasing step order");
  await acknowledge(ctx, api.baseUrl, created.incidentId, 0, fixture.responders[0].responderId, "terminal"); const before = receivers.reduce((sum, receiver) => sum + receiver.ledger.length, 0); await new Promise((resolve) => setTimeout(resolve, 1_200)); const after = receivers.reduce((sum, receiver) => sum + receiver.ledger.length, 0); assert.equal(after, before, "terminal commit suppresses new notification attempts"); return ctx.pass();
});

const B09 = guardedCase("B-09", ["QUORUM_AUTHORITY", "STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  for (let round = 0; round < 3; round += 1) {
    if (round) await ctx.resetDatabase(); const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.quorum(receivers.map(({ url }) => url)); const { api, workers } = await prepare(ctx, fixture, { workerCount: 2 }); await createPolicy(ctx, api.baseUrl, fixture, `quorum-${round}`); const created = await createIncident(ctx, api.baseUrl, fixture, `quorum-${round}`); const snapshot = await waitStep(ctx, api.baseUrl, created.incidentId, 0, "SENT", { processes: workers }); const step = resources(snapshot).groupEscalationSteps.find((item) => item.incidentId === created.incidentId && item.stepIndex === 0); assert.equal(step.notifications.filter(({ state }) => state === "DELIVERED").length >= step.quorumRequired, true); assertNotificationIdentity(step.notifications); const successfulAt = step.successfulDeliveryAt; await new Promise((resolve) => setTimeout(resolve, 100)); const later = resources(await ctx.snapshot(api.baseUrl)).groupEscalationSteps.find((item) => item.incidentId === created.incidentId && item.stepIndex === 0); assert.equal(later.successfulDeliveryAt, successfulAt, "later delivery cannot rewrite quorum transition time"); assert.equal(resources(snapshot).groupEscalationSteps.filter((item) => item.incidentId === created.incidentId && item.stepIndex === 0 && item.state === "SENT").length, 1);
  }
  return ctx.pass();
});

const B10 = guardedCase("B-10", ["QUORUM_AUTHORITY", "IDEMPOTENCY_CORRECTNESS", "EVENT_TRANSACTIONALITY"], async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.quorum(receivers.map(({ url }) => url)); const { apis, workers } = await prepare(ctx, fixture, { apiCount: 2, workerCount: 2 });
  const steps = [{ stepIndex: 0, delaySeconds: 0, responderIds: fixture.responders.map(({ responderId }) => responderId), quorumRequired: 2 }, { stepIndex: 1, delaySeconds: 1, responderIds: fixture.responders.slice(1).map(({ responderId }) => responderId), quorumRequired: 2 }]; await createPolicy(ctx, apis[0].baseUrl, fixture, "two-quorums", { steps, expireAfterSeconds: 60 }); const created = await createIncident(ctx, apis[0].baseUrl, fixture, "parallel-quorum"); await waitStep(ctx, apis[0].baseUrl, created.incidentId, 1, "SENT", { processes: workers, timeoutMs: 20_000 });
  await acknowledge(ctx, apis[0].baseUrl, created.incidentId, 0, fixture.responders[0].responderId, "step0-first"); await acknowledge(ctx, apis[1].baseUrl, created.incidentId, 1, fixture.responders[1].responderId, "step1-first");
  const race = await Promise.all([acknowledge(ctx, apis[0].baseUrl, created.incidentId, 0, fixture.responders[1].responderId, "step0-last", { expectSuccess: false }), acknowledge(ctx, apis[1].baseUrl, created.incidentId, 1, fixture.responders[2].responderId, "step1-last", { expectSuccess: false })]); assert.equal(race.filter((item) => item.status === 200).length, 1, "only one Step wins parallel quorum");
  const incident = resources(await ctx.snapshot(apis[0].baseUrl)).incidents.find((item) => item.incidentId === created.incidentId); assert.ok([0, 1].includes(incident.acknowledgementStepIndex)); const snapshot = await ctx.snapshot(apis[0].baseUrl); const accepted = resources(snapshot).incidentAcknowledgements.filter((item) => item.incidentId === created.incidentId); assertQuorumClosure(incident, resources(snapshot).groupEscalationSteps.filter((item) => item.incidentId === created.incidentId), accepted); assert.equal(snapshot.events.filter((item) => item.aggregateId === created.incidentId && item.type === "incident.acknowledged").length, 1);
  const duplicate = await acknowledge(ctx, apis[0].baseUrl, created.incidentId, incident.acknowledgementStepIndex, accepted.find((item) => item.stepIndex === incident.acknowledgementStepIndex).responderId, "terminal-duplicate", { key: ctx.key("terminal-duplicate-new") }); assert.equal(duplicate.json.replayed, true); assert.equal(resources(await ctx.snapshot(apis[0].baseUrl)).incidentAcknowledgements.filter((item) => item.incidentId === created.incidentId).length, accepted.length); return ctx.pass();
});

export const B_CASES = [B01, B02, B03, B04, B05, B06, B07, B08, B09, B10];
