import assert from "node:assert/strict";
import { createHash } from "node:crypto";

export function canonicalJson(value) { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value)) throw new TypeError("non-finite JSON number"); return Object.is(value, -0) ? "0" : JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`; throw new TypeError("value is not JSON"); }
export function sha256(value) { return createHash("sha256").update(value).digest("hex"); }
export function exactKeys(value, keys, label = "value") { assert.ok(value && typeof value === "object" && !Array.isArray(value), `${label} object`); assert.deepEqual(Object.keys(value).sort(), [...keys].sort(), `${label} exact keys`); return true; }
export function byteCompare(left, right) { return Buffer.from(String(left)).compare(Buffer.from(String(right))); }
export function scalarCompare(left, right) { if (left === null || right === null) return left === right ? 0 : left === null ? -1 : 1; if (typeof left === "boolean" && typeof right === "boolean") return Number(left) - Number(right); if (Number.isSafeInteger(left) && Number.isSafeInteger(right)) return left - right; return byteCompare(left, right); }
export function tupleSort(items, paths) { const read = (item, path) => path.split(".").reduce((value, key) => value?.[key], item); return [...items].sort((left, right) => { for (const path of paths) { const comparison = scalarCompare(read(left, path), read(right, path)); if (comparison) return comparison; } return byteCompare(canonicalJson(left), canonicalJson(right)); }); }
export function recursivelyOmitTokens(value) { if (Array.isArray(value)) return value.map(recursivelyOmitTokens); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value).filter(([key]) => !key.endsWith("Token")).map(([key, child]) => [key, recursivelyOmitTokens(child)])); }
export function freezePolicy(policy) { return { ...policy, steps: policy.steps.map((step) => { const responderIds = [...new Set(step.responderIds ?? [step.responderId])].sort(byteCompare); const quorumRequired = step.quorumRequired ?? 1; assert.ok(quorumRequired >= 1 && quorumRequired <= responderIds.length, "quorum outside captured responder set"); return { stepIndex: step.stepIndex, delaySeconds: step.delaySeconds, responderIds, quorumRequired }; }).sort((left, right) => left.stepIndex - right.stepIndex) }; }
export function schedule(policy, createdAt) { const created = Date.parse(createdAt); return freezePolicy(policy).steps.map((step) => ({ ...step, dueAt: new Date(created + step.delaySeconds * 1_000).toISOString(), expiresAt: new Date(created + policy.expireAfterSeconds * 1_000).toISOString() })); }
export function retryDelaySeconds(failedAttempt) { assert.ok(Number.isSafeInteger(failedAttempt) && failedAttempt >= 1); return Math.min(2 ** (failedAttempt - 1), 60); }
export function dueOrder(steps) { return [...steps].sort((left, right) => left.dueAt.localeCompare(right.dueAt) || byteCompare(left.incidentId, right.incidentId) || left.stepIndex - right.stepIndex); }
export function notificationQuorum(step, deliveries) { const eligible = new Set(step.responderIds ?? [step.responderId]); const delivered = new Set(deliveries.filter(({ state, responderId }) => state === "DELIVERED" && eligible.has(responderId)).map(({ responderId }) => responderId)); return { deliveredCount: delivered.size, sent: delivered.size >= (step.quorumRequired ?? 1) }; }
export function acknowledgementQuorum(step, acknowledgements) { const eligible = new Set(step.responderIds ?? [step.responderId]); const distinct = new Set(acknowledgements.filter(({ stepIndex, responderId }) => stepIndex === step.stepIndex && eligible.has(responderId)).map(({ responderId }) => responderId)); return { acknowledgementCount: distinct.size, reached: distinct.size >= (step.quorumRequired ?? 1) }; }
export function chooseWinner(steps, acknowledgements) { return [...steps].sort((left, right) => left.stepIndex - right.stepIndex).find((step) => acknowledgementQuorum(step, acknowledgements).reached) ?? null; }
export function chooseLegacyAcknowledge(steps, responderId) { return [...steps].filter((step) => step.state === "SENT" && (step.responderIds ?? [step.responderId]).includes(responderId)).sort((left, right) => left.stepIndex - right.stepIndex)[0] ?? null; }
export function assertOneActiveDedup(incidents) { const active = new Set(); for (const incident of incidents.filter(({ state }) => ["OPEN", "ACKNOWLEDGED"].includes(state))) { const identity = `${incident.serviceId}\0${incident.dedupKey}`; assert.ok(!active.has(identity), `duplicate active incident ${identity}`); active.add(identity); } return true; }
export function assertQuorumClosure(incident, steps, acknowledgements) { const winner = chooseWinner(steps, acknowledgements); if (incident.state === "ACKNOWLEDGED") { assert.ok(winner, "ACKNOWLEDGED Incident has no quorum winner"); assert.equal(incident.acknowledgementStepIndex, winner.stepIndex, "winner step projection"); assert.ok(steps.filter(({ state }) => state === "SENT").every(({ stepIndex }) => stepIndex === winner.stepIndex), "nonwinner SENT Step survives quorum"); } return true; }
export function assertNotificationIdentity(deliveries) { const ids = new Set(); for (const delivery of deliveries) { assert.ok(!ids.has(delivery.notificationId), `duplicate notificationId ${delivery.notificationId}`); ids.add(delivery.notificationId); if (Array.isArray(delivery.attempts)) for (const attempt of delivery.attempts) assert.equal(attempt.notificationId ?? delivery.notificationId, delivery.notificationId, "retry notification identity"); } return true; }
export function assertEventSequence(events) { const grouped = new Map(); for (const event of events) { const values = grouped.get(event.aggregateId) ?? []; values.push(event); grouped.set(event.aggregateId, values); } for (const [aggregateId, values] of grouped) { values.sort((left, right) => left.sequence - right.sequence); values.forEach((event, index) => assert.equal(event.sequence, index + 1, `${aggregateId} Event sequence`)); } return true; }
export function assertWork(work) { for (const item of work) { const leased = item.state === "LEASED"; assert.equal(item.terminal, ["SUCCEEDED", "FAILED", "CANCELLED"].includes(item.state), `${item.workId} terminal`); assert.equal(item.leaseOwner !== null, leased, `${item.workId} leaseOwner`); assert.equal(item.leaseExpiresAt !== null, leased, `${item.workId} leaseExpiresAt`); } return true; }
export function percentile(values, fraction) { if (!values.length) return 0; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.min(sorted.length - 1, Math.ceil(sorted.length * fraction) - 1)]; }
