import assert from "node:assert/strict";
import test from "node:test";

import { createFixtureFactory,performanceContract,releaseDeclaration,seedBundle,sha256 } from "../lib/fixtures.mjs";
import { assertSnapshot,canonical,manifestFor,percentile } from "../lib/oracle.mjs";

const options={evaluationSeed:"secret-evaluation-seed",caseId:"STREAM-01",baseTime:"2035-06-01T12:00:00.000Z"};
test("fixtures are deterministic and seed stays exact V1",()=>{const left=createFixtureFactory(options),right=createFixtureFactory(options),bytes=left.bytes("payload",17);assert.equal(left.uuid("x"),right.uuid("x"));assert.deepEqual(bytes,right.bytes("payload",17));const bundle=seedBundle(left,"fixture",[{packageName:"pkg",version:"1",bytes}]);assert.deepEqual(Object.keys(bundle.seed).sort(),["artifactVersions","packages","schemaVersion","seedVersion"]);assert.equal(bundle.seed.schemaVersion,1);assert.equal(bundle.seed.artifactVersions[0].expectedSha256,sha256(bytes));});
test("release canonical manifest uses UTF-8 platform order and fixed JSON",()=>{const fixtures=createFixtureFactory(options),members=[{platform:"windows",bytes:Buffer.from("w")},{platform:"darwin",bytes:Buffer.from("d")},{platform:"linux",bytes:Buffer.from("l")}],declaration=releaseDeclaration(fixtures,"r",members),expected=manifestFor(declaration.packageName,declaration.version,declaration.artifacts.map(({platform,expectedSha256,size,expectedSize,mediaType})=>({platform,sha256:expectedSha256,size:expectedSize??size,mediaType})));assert.deepEqual(expected.artifacts.map(({platform})=>platform),["darwin","linux","windows"]);assert.equal(expected.canonicalBytes.toString(),JSON.stringify(expected.artifacts));assert.equal(expected.manifestSha256,sha256(expected.canonicalBytes));});
test("formal performance constants cannot silently scale",()=>{assert.deepEqual(performanceContract(),{stream:{uploadCount:20,bytesPerUpload:67108864,chunkBytes:8388608,chunksPerUpload:8,concurrency:20,targetMiBPerSecond:120},read:{packageCount:100000,concurrency:64,warmupSeconds:10,measureSeconds:60,targetPerSecond:200,p95Ms:120},recovery:{sessionCount:32,bytesPerSession:67108864,totalBytes:2147483648,killedWorkers:2,replacementWorkers:2,maximumSeconds:90,peakRssMiB:768,deltaRssMiB:64}});assert.equal(percentile([9,1,3,7],0.95),9);assert.equal(canonical({b:1,a:2}),'{"a":2,"b":1}');});
test("empty FINAL snapshot still enforces the exact union",()=>{assert.equal(assertSnapshot({asOf:"2035-06-01T12:00:00.000Z",resources:{packages:[],uploadSessions:[],artifactVersions:[],verificationResults:[],blobs:[],blobReferences:[],releases:[]},work:[],events:[]}),true);});
