import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";

import { snapshotDigest } from "../oracles/index.mjs";

function uuid(label) { const bytes = createHash("sha256").update(`flagfoundry-perf-v1\0${label}`).digest().subarray(0, 16); bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80; const hex = bytes.toString("hex"); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`; }

export async function writePerformanceSeed(ctx) {
  const projects = Array.from({ length: 100 }, (_, index) => ({ projectId: uuid(`project:${index}`), name: `Project ${String(index).padStart(3, "0")}` })); const environments = projects.flatMap((project, projectIndex) => Array.from({ length: 3 }, (_, environmentIndex) => ({ projectId: project.projectId, name: `environment-${environmentIndex}`, contextAttributes: ["region", "tier"], schemaRevision: 1 + ((projectIndex + environmentIndex) % 7) })));
  const flags = []; const activeRevisions = []; const pairs = [];
  for (let index = 0; index < 5_000; index += 1) { const project = projects[index % projects.length]; const projectEnvironments = environments.filter(({ projectId }) => projectId === project.projectId); const environment = projectEnvironments[Math.floor(index / projects.length) % 3]; const flag = { flagId: uuid(`flag:${index}`), projectId: project.projectId, key: `perf_flag_${String(index).padStart(5, "0")}`, flagType: "STRING" }; const variants = [{ key: "control", value: "control", allocationBasisPoints: 5_000 }, { key: "candidate", value: "candidate", allocationBasisPoints: 5_000 }]; const revisionId = uuid(`revision:${index}:1`); const snapshot = { snapshotVersion: 1, projectId: flag.projectId, flagId: flag.flagId, flagKey: flag.key, environment: environment.name, revisionId, revision: 1, flagType: "STRING", defaultVariant: "control", variants, rules: [], contextAttributes: [...environment.contextAttributes], contextSchemaRevision: environment.schemaRevision }; const revision = { revisionId, flagId: flag.flagId, environment: environment.name, revision: 1, flagType: "STRING", defaultVariant: "control", variants, rules: [], state: "ACTIVE", snapshotDigest: snapshotDigest(snapshot), createdAt: "2025-12-30T00:00:00.000Z", activatedAt: "2025-12-31T00:00:00.000Z", sequence: 1 }; flags.push(flag); activeRevisions.push(revision); pairs.push({ project, environment, flag, revision, snapshot }); }
  const seed = { schemaVersion: 1, seedVersion: "perf-v1", projects, environments, flags, activeRevisions }; const path = ctx.tempPath("flagfoundry-perf-v1.json"); await writeFile(path, JSON.stringify(seed)); return { path, seed, projects, environments, flags, activeRevisions, pairs, uuid };
}

export function compilationBody(catalog, pair, ordinal) { const variants = [{ key: "control", value: `control-${ordinal}`, allocationBasisPoints: 5_000 }, { key: "candidate", value: `candidate-${ordinal}`, allocationBasisPoints: 5_000 }]; const rules = Array.from({ length: 10 }, (_, index) => ({ ruleId: catalog.uuid(`compile:${ordinal}:rule:${index}`), clauses: [{ attribute: index % 2 === 0 ? "region" : "tier", operator: "EQUALS", value: index % 2 === 0 ? `region-${index}` : `tier-${index}` }], variantKey: index % 2 === 0 ? "candidate" : "control" })); return { environment: pair.environment.name, flagType: "STRING", defaultVariant: "control", variants, rules, expectedActiveRevision: pair.revision.revision }; }
export function evaluationBody(pair, ordinal) { return { projectId: pair.project.projectId, flagKey: pair.flag.key, environment: pair.environment.name, context: { subjectKey: `perf-subject-${ordinal % 100_000}`, region: "us", tier: "pro" } }; }

export async function closedLoopWindow(ctx, values, concurrency, seconds, operation) { const items = Array.from(values); const samples = []; let ordinal = 0; const deadline = performance.now() + (seconds * 1_000); await Promise.all(Array.from({ length: concurrency }, async () => { while (performance.now() < deadline) { const index = ordinal++; const value = items[index % items.length]; const started = performance.now(); const response = await operation(value, index); samples.push({ response, durationMs: response.durationMs ?? performance.now() - started, ordinal: index }); } })); return samples; }
export async function finiteConcurrent(ctx, values, concurrency, operation) { const started = performance.now(); const responses = await ctx.concurrent(values, concurrency, operation); return { responses, durationMs: performance.now() - started }; }
export function percentile(values, ratio) { if (!values.length) return Infinity; const ordered = [...values].sort((left, right) => left - right); return ordered[Math.min(ordered.length - 1, Math.ceil(ordered.length * ratio) - 1)]; }
