import assert from "node:assert/strict";

import { makeLotFixture, makeSplitFixture } from "../fixtures/index.mjs";
import { assertCarbonLedgerOpenApi, assertLotConservation, carbonLedgerOpenApiRoutes } from "../oracles/index.mjs";
import {
  assertAllocation, assertCreditLot, assertRetirement, assertRetirementAllocationClosure, assertSnapshot, browserMutation, certificateResponse,
  clickVisible, createRetirement, defineCase, exactKeys, fillControl, finalEvidence, getAllocations, getCertificate,
  getCreditLot, identityPattern, keyboardFill, launchBrowser, listCreditLots, listRetirements, prepare,
  releaseRetirement, resources, retirementRequest, semanticError, successful, tabTo, visibleControl, visibleField,
  waitForRetired, waitForRetirement,
} from "./helpers.mjs";

function options(ctx) { return { evaluationSeed: ctx.evaluationSeed, caseId: ctx.caseId, baseTime: ctx.fixtures.baseTime }; }
function exactState(snapshot) { const { asOf: _asOf, ...value } = snapshot; return value; }
function uiText(value) { return new RegExp(String(value).replace(/[.*+?^${}()|[\]\\]/gu, "\\$&"), "u"); }
function publicTraffic(page) { const requests = []; page.on("request", (request) => { const path = new URL(request.url()).pathname; if (path.startsWith("/api/")) requests.push({ method: request.method(), path, headers: request.headers() }); }); return requests; }
async function chooseField(page, patterns, value, keyboard = false) { const field = await visibleField(page, patterns); if (keyboard) await keyboardFill(page, field, value); else await fillControl(field, value); return field; }
async function fillRetirementForm(page, fixture, quantity, { keyboard = false } = {}) {
  await chooseField(page, [/beneficiary/iu, /受益/iu], fixture.beneficiaryId, keyboard);
  await chooseField(page, [/quantity|grams/iu, /数量|克/iu], quantity, keyboard);
}
async function keyboardMutation(page, names, path) { const response = page.waitForResponse((candidate) => candidate.request().method() === "POST" && path.test(new URL(candidate.url()).pathname), { timeout: 30_000 }); const action = await visibleControl(page, ["button", "link"], names); await tabTo(page, action); await page.keyboard.press("Enter"); return response; }
async function visibleIdentity(page, value, label) { assert.ok(await page.getByText(uiText(value), { exact: false }).count() > 0, `${label} identity visible`); }
async function openCertificate(page, retirementId) { const pending = page.waitForResponse((response) => response.request().method() === "GET" && new URL(response.url()).pathname === `/api/v1/retirements/${retirementId}/certificate`, { timeout: 30_000 }); const action = await visibleControl(page, ["button", "link"], [/certificate|download/iu, /证书|下载/iu]); await action.click(); return pending; }
async function assertControlledLoading(page) { let release; const gate = new Promise((resolve) => { release = resolve; }); const pattern = /\/api\/v1\/(?:credit-lots|retirements)(?:\?|$)/u; await page.route(pattern, async (route) => { await gate; await route.continue(); }); const reload = page.reload({ waitUntil: "networkidle" }); try { await page.getByText(/loading|加载|载入/iu).first().waitFor({ state: "visible", timeout: 5_000 }); } finally { release(); await reload; await page.unroute(pattern); } }
function dueSeed(ctx) { const fixture = makeLotFixture(options(ctx), { lotCount: 4, capacities: [20, 20, 20, 20] }); const lot = fixture.creditLots[0]; const quantityGrams = 3; const retirementId = fixture.fixtures.uuid("browser-due"); lot.availableGrams -= quantityGrams; lot.reservedGrams += quantityGrams; fixture.seed.seedVersion = fixture.fixtures.seedVersion("browser-due"); fixture.seed.retirements = [{ retirementId, beneficiaryId: fixture.beneficiaryId, quantityGrams, state: "RESERVED", allocation: { creditLotId: lot.creditLotId, quantityGrams }, expiresAt: "2020-01-01T00:00:00.000Z", certificateDigest: null, createdAt: "2019-12-31T23:50:00.000Z", terminalAt: null, sequence: 1 }]; return { ...fixture, retirementId, quantityGrams }; }
async function browserCreate(ctx, page, fixture, quantity, label, keyboard = false) { await fillRetirementForm(page, fixture, quantity, { keyboard }); const response = keyboard ? await keyboardMutation(page, [/create|reserve|retire/iu, /创建|预留|注销/iu], /^\/api\/v1\/retirements$/u) : await browserMutation(page, [/create|reserve|retire/iu, /创建|预留|注销/iu], /^\/api\/v1\/retirements$/u); assert.equal(response.status(), 202, `${label} browser create`); const retirement = assertRetirement(await response.json()); await visibleIdentity(page, retirement.retirementId, label); return retirement; }

const D01 = defineCase({
  id: "D-01", fixtureFamily: "CL-F-V1-SINGLE",
  action: "Validate the production OpenAPI document with a CarbonLedger-owned closed-schema oracle while collecting live success traffic for every route family and all published error classes.",
  oracle: "Every live status, header and exact body shape agrees with OpenAPI 3.1; nullable legacy fields, FINAL allocations, certificate alternatives, errors and Bearer security cannot be hidden by permissive schemas.",
  async run(ctx) {
    const fixture = makeLotFixture(options(ctx), { lotCount: 8, capacities: Array(8).fill(20) }); const { target, api } = await prepare(ctx, { seed: fixture.seed });
    const document = successful(await ctx.request(api.baseUrl, "/openapi.json"), "OpenAPI", 200).json; ctx.ok(assertCarbonLedgerOpenApi(document), "exact OpenAPI contract"); const traffic = new Set();
    const record = (method, path, response, status) => { ctx.equal(response.status, status, `${method} ${path}`); traffic.add(`${method}:${path}`); return response; };
    const lotPage = record("get", "/api/v1/credit-lots", await ctx.request(api.baseUrl, "/api/v1/credit-lots?limit=50"), 200); exactKeys(lotPage.json, ["items", "nextCursor"], "live CreditLot page"); lotPage.json.items.forEach(assertCreditLot); assertCreditLot(record("get", "/api/v1/credit-lots/{creditLotId}", await ctx.request(api.baseUrl, `/api/v1/credit-lots/${fixture.creditLots[0].creditLotId}`), 200).json);
    const released = assertRetirement(record("post", "/api/v1/retirements", await ctx.mutate(api.baseUrl, "/api/v1/retirements", ctx.key("d01-release-create"), retirementRequest(fixture, 2)), 202).json); const retirementPage = record("get", "/api/v1/retirements", await ctx.request(api.baseUrl, "/api/v1/retirements?limit=50"), 200); exactKeys(retirementPage.json, ["items", "nextCursor"], "live Retirement page"); retirementPage.json.items.forEach(assertRetirement); assertRetirement(record("get", "/api/v1/retirements/{retirementId}", await ctx.request(api.baseUrl, `/api/v1/retirements/${released.retirementId}`), 200).json); const allocationPage = record("get", "/api/v1/retirements/{retirementId}/allocations", await ctx.request(api.baseUrl, `/api/v1/retirements/${released.retirementId}/allocations`), 200); exactKeys(allocationPage.json, ["items"], "live allocations"); allocationPage.json.items.forEach(assertAllocation); assertRetirement(record("post", "/api/v1/retirements/{retirementId}/release", await ctx.mutate(api.baseUrl, `/api/v1/retirements/${released.retirementId}/release`, ctx.key("d01-release"), { reason: "contract traffic" }), 200).json); const events = record("get", "/api/v1/domain-events", await ctx.request(api.baseUrl, `/api/v1/domain-events?aggregateId=${released.retirementId}&afterSequence=0&limit=100`), 200); exactKeys(events.json, ["items", "nextCursor"], "live Event page"); const snapshotResponse = record("get", "/api/v1/verification-snapshot", await ctx.request(api.baseUrl, "/api/v1/verification-snapshot", { headers: { authorization: `Bearer ${ctx.adminToken}` } }), 200); assertSnapshot(snapshotResponse.json);
    const certifying = await createRetirement(ctx, api.baseUrl, retirementRequest(fixture, 2), { key: ctx.key("d01-certificate") }); const pending = record("get", "/api/v1/retirements/{retirementId}/certificate", await ctx.request(api.baseUrl, `/api/v1/retirements/${certifying.retirementId}/certificate`), 202); exactKeys(pending.json, ["retirementId", "state"], "pending Certificate"); const worker = await target.startWorker(); const retired = await waitForRetirement(ctx, api.baseUrl, certifying.retirementId, "RETIRED", [worker]); const closure = assertRetirementAllocationClosure(retired.snapshot, certifying.retirementId); const certificate = record("get", "/api/v1/retirements/{retirementId}/certificate", await ctx.request(api.baseUrl, `/api/v1/retirements/${certifying.retirementId}/certificate`, { binary: true }), 200); certificateResponse(ctx, certificate, closure.retirement, closure.allocations, resources(retired.snapshot).creditLots);
    semanticError(await ctx.request(api.baseUrl, `/api/v1/credit-lots/${ctx.uuid("missing")}`), 404, "NOT_FOUND"); semanticError(await ctx.request(api.baseUrl, "/api/v1/credit-lots?limit=0"), 400, "INVALID_REQUEST"); semanticError(await ctx.request(api.baseUrl, "/api/v1/verification-snapshot", { headers: { authorization: "Bearer wrong" } }), 401, "ADMIN_AUTH_REQUIRED"); semanticError(await ctx.request(api.baseUrl, "/api/v1/retirements", { method: "POST", headers: { "content-type": "text/plain", "idempotency-key": ctx.key("media") }, raw: "{}" }), 415, "UNSUPPORTED_MEDIA_TYPE"); semanticError(await releaseRetirement(ctx, api.baseUrl, released.retirementId, "again", { allowFailure: true, key: ctx.key("release-again") }), 409, "RETIREMENT_NOT_RELEASABLE");
    const expected = Object.entries(carbonLedgerOpenApiRoutes()).flatMap(([path, methods]) => Object.keys(methods).map((method) => `${method}:${path}`)); ctx.equal([...traffic].sort(), expected.sort(), "live success for every operation"); return finalEvidence(ctx, { liveOperations: traffic.size, errorClasses: [400, 401, 404, 409, 415] });
  },
});

const D02 = defineCase({
  id: "D-02", fixtureFamily: "CL-F-BROWSER",
  action: "Drive production Chromium through visible V1 Lot browsing, Retirement creation, asynchronous RESERVED-to-RETIRED progress, exact Certificate download and a full page refresh.",
  oracle: "The browser uses public non-admin routes only; the concrete Retirement and Lot identities, UI state, snapshot quantities and canonical served Certificate bytes agree after refresh.",
  async run(ctx) {
    const fixture = makeLotFixture(options(ctx), { lotCount: 6, capacities: Array(6).fill(20) }); const { target, api } = await prepare(ctx, { seed: fixture.seed }); const worker = await target.startWorker(); const { page } = await launchBrowser(ctx, api.baseUrl); const observed = publicTraffic(page); const retirement = await browserCreate(ctx, page, fixture, 3, "V1"); const retired = await waitForRetirement(ctx, api.baseUrl, retirement.retirementId, "RETIRED", [worker]); await page.reload({ waitUntil: "networkidle" }); await visibleIdentity(page, retirement.retirementId, "refreshed Retirement"); ctx.ok(await page.getByText(/retired|completed|已注销|已完成/iu).count() > 0, "RETIRED visible"); const certificate = await openCertificate(page, retirement.retirementId); ctx.equal(certificate.status(), 200, "browser Certificate status"); const closure = assertRetirementAllocationClosure(retired.snapshot, retirement.retirementId); const publicCertificate = await getCertificate(ctx, api.baseUrl, retirement.retirementId); const verified = certificateResponse(ctx, publicCertificate, closure.retirement, closure.allocations, resources(retired.snapshot).creditLots); ctx.equal(Buffer.from(await certificate.body()), verified.bytes, "browser and API Certificate bytes"); ctx.ok(observed.length > 0 && observed.every(({ path }) => !/(?:verification-snapshot|internal|private|admin)/iu.test(path)), "browser only public routes"); return finalEvidence(ctx, { retirementId: retirement.retirementId, creditLotId: closure.allocations[0].creditLotId, certificateDigest: verified.digest });
  },
});

const D03 = defineCase({
  id: "D-03", fixtureFamily: "CL-F-BROWSER",
  action: "Use visible production UI controls to release a RESERVED Retirement, observe an independently due Retirement expire, submit an insufficient request, and recover empty, loading, stale, offline and retry states.",
  oracle: "Terminal states and conserved Lot quantities match the public snapshot, failed or offline submissions create no phantom aggregate, and every visible recoverable state returns to server-authoritative data.",
  async run(ctx) {
    const fixture = makeLotFixture(options(ctx), { lotCount: 4, capacities: [5, 5, 5, 5] }); let prepared = await prepare(ctx, { seed: fixture.seed }); let browser = await launchBrowser(ctx, prepared.api.baseUrl); ctx.ok(await browser.page.getByText(/empty|no retirement|暂无|没有/iu).count() > 0, "empty state visible"); await assertControlledLoading(browser.page); const retirement = await browserCreate(ctx, browser.page, fixture, 2, "release"); const releaseResponse = browser.page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === `/api/v1/retirements/${retirement.retirementId}/release`, { timeout: 30_000 }); await clickVisible(browser.page, "release|释放"); ctx.equal((await releaseResponse).status(), 200, "browser release"); await browser.page.reload({ waitUntil: "networkidle" }); ctx.ok(await browser.page.getByText(/released|已释放/iu).count() > 0, "release visible");
    await browser.page.goto(prepared.api.baseUrl, { waitUntil: "networkidle" }); const beforeFailure = await ctx.snapshot(prepared.api.baseUrl); await fillRetirementForm(browser.page, fixture, 9999); const conflict = await browserMutation(browser.page, [/create|reserve|retire/iu, /创建|预留|注销/iu], /^\/api\/v1\/retirements$/u); ctx.equal(conflict.status(), 409, "capacity conflict"); ctx.ok(await browser.page.getByText(/unavailable|conflict|insufficient|不足|冲突/iu).count() > 0, "conflict visible"); ctx.equal(exactState(await ctx.snapshot(prepared.api.baseUrl)), exactState(beforeFailure), "conflict creates no phantom Retirement"); await browser.page.goto(prepared.api.baseUrl, { waitUntil: "networkidle" }); const beforeOffline = await ctx.snapshot(prepared.api.baseUrl); await browser.browserContext.setOffline(true); await fillRetirementForm(browser.page, fixture, 1); await (await visibleControl(browser.page, ["button", "link"], [/create|reserve|retire/iu, /创建|预留|注销/iu])).click(); await browser.page.waitForTimeout(300); ctx.ok(await browser.page.getByText(/offline|retry|network|离线|重试|网络/iu).count() > 0, "application offline/retry state visible"); const retried = browser.page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === "/api/v1/retirements", { timeout: 30_000 }); await browser.browserContext.setOffline(false); await (await visibleControl(browser.page, ["button", "link"], [/retry|create|reserve|retire/iu, /重试|创建|预留|注销/iu])).click(); ctx.equal((await retried).status(), 202, "offline retry succeeds"); ctx.equal(resources(await ctx.snapshot(prepared.api.baseUrl)).retirements.length - resources(beforeOffline).retirements.length, 1, "offline retry creates exactly one Retirement");
    const due = dueSeed(ctx); await ctx.resetDatabase(); prepared = await prepare(ctx, { seed: due.seed }); const worker = await prepared.target.startWorker(); await waitForRetirement(ctx, prepared.api.baseUrl, due.retirementId, "EXPIRED", [worker]); browser = await launchBrowser(ctx, prepared.api.baseUrl); await visibleIdentity(browser.page, due.retirementId, "expired Retirement"); ctx.ok(await browser.page.getByText(/expired|已过期/iu).count() > 0, "expiry visible"); const snapshot = assertSnapshot(await ctx.snapshot(prepared.api.baseUrl)); assertLotConservation(resources(snapshot).creditLots); return finalEvidence(ctx, { releasedRetirementId: retirement.retirementId, expiredRetirementId: due.retirementId, recoveredOffline: true });
  },
});

const D04 = defineCase({
  id: "D-04", fixtureFamily: "CL-F-BROWSER",
  action: "Create two-, three- and twenty-Lot split Retirements through production UI, inspect every ordered allocation and provenance identity dynamically, publish v2 Certificates, and compare a released one-Lot control.",
  oracle: "The UI renders the complete variable-length allocation set and concrete IDs, v2 bytes total every immutable allocation, v1 legacy fields remain intact, and all selected Lot quantities close across HTTP and snapshot.",
  async run(ctx) {
    const counts = [2, 3, 20]; const evidence = [];
    for (const count of counts) { const fixture = makeSplitFixture(options(ctx), count); fixture.quantityGrams = count === 20 ? 39 : fixture.creditLots.slice(0, count).reduce((sum, lot) => sum + lot.availableGrams, 0) - 1; if (evidence.length) await ctx.resetDatabase(); const { target, api } = await prepare(ctx, { seed: fixture.seed }); const { page } = await launchBrowser(ctx, api.baseUrl); const retirement = await browserCreate(ctx, page, fixture, fixture.quantityGrams, `${count}-Lot`); const allocations = await getAllocations(ctx, api.baseUrl, retirement.retirementId); ctx.equal(allocations.length, count, `${count}-Lot allocation count`); for (const allocation of allocations) { await visibleIdentity(page, allocation.creditLotId, "allocation Lot"); await visibleIdentity(page, allocation.provenanceDigest, "allocation provenance"); } const worker = await target.startWorker(); const retired = await waitForRetirement(ctx, api.baseUrl, retirement.retirementId, "RETIRED", [worker]); const closure = assertRetirementAllocationClosure(retired.snapshot, retirement.retirementId); const cert = certificateResponse(ctx, await getCertificate(ctx, api.baseUrl, retirement.retirementId), closure.retirement, closure.allocations, resources(retired.snapshot).creditLots); ctx.equal(cert.parsed.certificateVersion, 2, `${count}-Lot v2 Certificate`); ctx.equal(cert.parsed.totalQuantityGrams, fixture.quantityGrams, `${count}-Lot exact total`); await page.reload({ waitUntil: "networkidle" }); await visibleIdentity(page, retirement.retirementId, `${count}-Lot retired Retirement`); ctx.ok(await page.getByText(/retired|completed|已注销|已完成/iu).count() > 0, `${count}-Lot terminal state visible`); const browserCertificate = await openCertificate(page, retirement.retirementId); ctx.equal(browserCertificate.status(), 200, `${count}-Lot UI Certificate`); ctx.equal(Buffer.from(await browserCertificate.body()), cert.bytes, `${count}-Lot browser Certificate bytes`); evidence.push({ retirementId: retirement.retirementId, allocations: count, digest: cert.digest }); }
    await ctx.resetDatabase(); const oneFixture = makeLotFixture(options(ctx), { lotCount: 4, capacities: [10, 10, 10, 10] }); const onePrepared = await prepare(ctx, { seed: oneFixture.seed }); const oneBrowser = await launchBrowser(ctx, onePrepared.api.baseUrl); const one = await browserCreate(ctx, oneBrowser.page, oneFixture, 2, "one-Lot control"); ctx.ok(one.allocation && one.allocations.length === 1, "one-Lot legacy fields remain populated"); const oneRelease = oneBrowser.page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === `/api/v1/retirements/${one.retirementId}/release`, { timeout: 30_000 }); await (await visibleControl(oneBrowser.page, ["button", "link"], [/release|释放/iu])).click(); ctx.equal((await oneRelease).status(), 200, "one-Lot UI release control"); const oneFinal = assertRetirement(successful(await ctx.request(onePrepared.api.baseUrl, `/api/v1/retirements/${one.retirementId}`), "one-Lot detail", 200).json); ctx.equal(oneFinal.state, "RELEASED", "one-Lot release persists"); return finalEvidence(ctx, { splitLifecycles: evidence, oneLotControl: one.retirementId });
  },
});

const D05 = defineCase({
  id: "D-05", fixtureFamily: "CL-F-BROWSER",
  action: "Exercise unauthorized snapshot, slow and offline browser requests, a stale cross-API mutation conflict and a retried create while auditing production bundle, DOM, storage, requests and process logs.",
  oracle: "Permission and transport failures are visible and recoverable, one semantic mutation commits at most once, and ADMIN_TOKEN, database URLs, private paths, seeds and idempotency values never reach browser assets or logs.",
  async run(ctx) {
    const fixture = makeLotFixture(options(ctx), { lotCount: 4, capacities: Array(4).fill(20) }); const { api, apis } = await prepare(ctx, { seed: fixture.seed, apiCount: 2 }); const denied = await ctx.request(api.baseUrl, "/api/v1/verification-snapshot", { headers: { authorization: "Bearer wrong" } }); semanticError(denied, 401, "ADMIN_AUTH_REQUIRED"); const { browserContext, page } = await launchBrowser(ctx, api.baseUrl); const observed = publicTraffic(page); await assertControlledLoading(page); const retirement = await browserCreate(ctx, page, fixture, 2, "stale"); await releaseRetirement(ctx, apis[1].baseUrl, retirement.retirementId, "other API", { key: ctx.key("other-api") }); const staleResponse = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === `/api/v1/retirements/${retirement.retirementId}/release`, { timeout: 30_000 }); await (await visibleControl(page, ["button", "link"], [/release|释放/iu])).click(); ctx.equal((await staleResponse).status(), 409, "stale cross-API mutation conflict"); ctx.ok(await page.getByText(/stale|conflict|released|已更新|冲突|已释放/iu).count() > 0, "stale conflict visible"); await page.reload({ waitUntil: "networkidle" }); ctx.ok(await page.getByText(/released|已释放/iu).count() > 0, "stale state refreshes from server");
    await page.goto(api.baseUrl, { waitUntil: "networkidle" }); const before = await ctx.snapshot(api.baseUrl); await browserContext.setOffline(true); await fillRetirementForm(page, fixture, 2); const offlineAction = await visibleControl(page, ["button", "link"], [/create|reserve|retire/iu, /创建|预留|注销/iu]); await offlineAction.click(); await page.waitForTimeout(300); ctx.ok(await page.getByText(/offline|retry|network|离线|重试|网络/iu).count() > 0, "offline failure visible"); const retried = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === "/api/v1/retirements", { timeout: 30_000 }); await browserContext.setOffline(false); const retryAction = await visibleControl(page, ["button", "link"], [/retry|create|reserve|retire/iu, /重试|创建|预留|注销/iu]); await retryAction.click(); ctx.equal((await retried).status(), 202, "offline mutation retries successfully"); const after = await ctx.snapshot(api.baseUrl); ctx.equal(resources(after).retirements.length - resources(before).retirements.length, 1, "retry commits exactly one mutation");
    const html = await page.content(); const scripts = await page.locator("script[src]").evaluateAll((elements) => elements.map((item) => item.src)); const bundles = await Promise.all(scripts.map(async (url) => (await fetch(url)).text())); const storage = await page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } })); const logs = [html, storage, ...bundles, ...ctx.processes.map(({ logs }) => logs ?? ""), JSON.stringify(observed)].join("\n"); ctx.ok(!logs.includes(ctx.adminToken), "ADMIN_TOKEN absent"); ctx.ok(!/(?:postgres(?:ql)?:\/\/|\/(?:Users|home|tmp)\/|seedVersion|idempotency-key[^\n]{0,80}cl-)/iu.test(logs), "secrets and private paths absent"); return finalEvidence(ctx, { retirementId: retirement.retirementId, browserRequests: observed.length, retryDelta: resources(after).retirements.length - resources(before).retirements.length });
  },
});

async function contrastAudit(page) { return page.locator("button,a,input,select,textarea").evaluateAll((elements) => elements.filter((element) => { const rect = element.getBoundingClientRect(); return rect.width > 0 && rect.height > 0; }).map((element) => { const parse = (value) => (value.match(/[\d.]+/gu) ?? []).slice(0, 3).map(Number); const luminance = (rgb) => { const values = rgb.map((channel) => { const value = channel / 255; return value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4; }); return values[0] * 0.2126 + values[1] * 0.7152 + values[2] * 0.0722; }; const style = getComputedStyle(element); const foreground = luminance(parse(style.color)); let background = parse(style.backgroundColor); if (background.length < 3 || Number(style.backgroundColor.match(/[\d.]+/gu)?.[3] ?? 1) === 0) background = parse(getComputedStyle(document.body).backgroundColor); const behind = luminance(background); return { label: element.getAttribute("aria-label") ?? element.textContent?.trim() ?? element.getAttribute("name"), ratio: (Math.max(foreground, behind) + 0.05) / (Math.min(foreground, behind) + 0.05), size: Number.parseFloat(style.fontSize) }; })); }

const D06 = defineCase({
  id: "D-06", fixtureFamily: "CL-F-BROWSER",
  action: "At 390px and 1280px, use only Tab, typing and Enter to create and release one-Lot Retirements and open split detail and Certificate download, then remove Chromium to prove the browser gate is dependency-sensitive.",
  oracle: "Every primary control is labelled, focus-visible and unobstructed, concrete identities persist, visible text meets WCAG AA contrast, and project E2E fails closed when real Chromium is unavailable.",
  async run(ctx) {
    const results = [];
    for (const viewport of [{ width: 390, height: 844 }, { width: 1280, height: 800 }]) { if (results.length) await ctx.resetDatabase(); const fixture = makeLotFixture(options(ctx), { lotCount: 6, capacities: Array(6).fill(20) }); let prepared = await prepare(ctx, { seed: fixture.seed }); let browser = await launchBrowser(ctx, prepared.api.baseUrl, viewport); const retirement = await browserCreate(ctx, browser.page, fixture, 2, `${viewport.width}px`, true); const response = await keyboardMutation(browser.page, [/release|释放/iu], new RegExp(`^/api/v1/retirements/${retirement.retirementId}/release$`, "u")); ctx.equal(response.status(), 200, `${viewport.width}px keyboard release`); const focused = await browser.page.evaluate(() => document.activeElement && ["BUTTON", "A", "INPUT", "SELECT", "TEXTAREA"].includes(document.activeElement.tagName)); ctx.ok(focused, `${viewport.width}px understandable focus`); const boxes = await browser.page.locator("button:visible,a:visible,input:visible,select:visible,textarea:visible").evaluateAll((elements) => elements.map((element) => { const box = element.getBoundingClientRect(); return { left: box.left, right: box.right, top: box.top, bottom: box.bottom, label: element.getAttribute("aria-label") ?? element.getAttribute("name") ?? element.textContent?.trim() }; })); ctx.ok(boxes.every((box) => box.label && box.left >= 0 && box.right <= viewport.width && box.top >= 0), `${viewport.width}px controls labelled and in viewport`); const contrast = await contrastAudit(browser.page); ctx.ok(contrast.length > 0 && contrast.every(({ ratio, size }) => ratio >= (size >= 24 ? 3 : 4.5)), `${viewport.width}px WCAG AA contrast`);
      await ctx.resetDatabase(); const splitFixture = makeSplitFixture(options(ctx), 3); splitFixture.quantityGrams = 6; prepared = await prepare(ctx, { seed: splitFixture.seed }); browser = await launchBrowser(ctx, prepared.api.baseUrl, viewport); const split = await browserCreate(ctx, browser.page, splitFixture, splitFixture.quantityGrams, `${viewport.width}px split`, true); const allocations = await getAllocations(ctx, prepared.api.baseUrl, split.retirementId); ctx.equal(allocations.length, 3, `${viewport.width}px split detail`); const worker = await prepared.target.startWorker(); await waitForRetirement(ctx, prepared.api.baseUrl, split.retirementId, "RETIRED", [worker]); await browser.page.reload({ waitUntil: "networkidle" }); for (const allocation of allocations) await visibleIdentity(browser.page, allocation.creditLotId, `${viewport.width}px split allocation`); const certificate = browser.page.waitForResponse((candidate) => candidate.request().method() === "GET" && new URL(candidate.url()).pathname === `/api/v1/retirements/${split.retirementId}/certificate`, { timeout: 30_000 }); const download = await visibleControl(browser.page, ["button", "link"], [/certificate|download/iu, /证书|下载/iu]); await tabTo(browser.page, download); await browser.page.keyboard.press("Enter"); ctx.equal((await certificate).status(), 200, `${viewport.width}px keyboard Certificate download`); results.push({ viewport: viewport.width, retirementId: retirement.retirementId, splitRetirementId: split.retirementId, controls: boxes.length, allocations: allocations.length }); }
    const target = ctx.forWorkspace(ctx.workspace); await assert.rejects(target.npm("test:e2e", [], { env: { CHROMIUM_PATH: ctx.tempPath("missing-chromium") }, timeoutMs: 240_000 }), "E2E must fail without Chromium"); return finalEvidence(ctx, { keyboardFlows: results, chromiumNegativeControl: true });
  },
});

const D07 = defineCase({
  id: "D-07", fixtureFamily: "CL-F-BROWSER",
  action: "Run every published project-owned test command and controlled negative dependencies for PostgreSQL, Chromium and the recovery barrier while capturing their process output and exit behavior.",
  oracle: "Unit, integration, E2E, concurrency, recovery, all and performance gates execute nonzero assertions against real dependencies; missing dependencies fail nonzero instead of skipping, swallowing errors or checking strings.",
  async run(ctx) {
    const target = ctx.forWorkspace(ctx.workspace); const scripts = ["test:unit", "test:integration", "test:e2e", "test:concurrency", "test:recovery", "test:all", "test:perf"]; const evidence = [];
    for (const script of scripts) { const result = await target.npm(script, [], { timeoutMs: script === "test:perf" ? 900_000 : 300_000 }); const output = `${result.stdout ?? ""}\n${result.stderr ?? ""}`; ctx.ok(!/(?:0 tests?|no tests? found|skipp(?:ed|ing) all)/iu.test(output), `${script} executes tests`); evidence.push({ script, outputBytes: Buffer.byteLength(output) }); }
    await assert.rejects(target.npm("test:integration", [], { env: { TEST_DATABASE_URL: "postgresql://127.0.0.1:1/unreachable", DATABASE_URL: "postgresql://127.0.0.1:1/unreachable" }, timeoutMs: 120_000 }), "integration fails without PostgreSQL"); await assert.rejects(target.npm("test:e2e", [], { env: { CHROMIUM_PATH: ctx.tempPath("missing") }, timeoutMs: 120_000 }), "E2E fails without Chromium"); await assert.rejects(target.npm("test:recovery", [], { env: { TEST_BARRIER_URL: "http://127.0.0.1:1/barrier", TEST_BARRIER_TOKEN: "controlled-invalid" }, timeoutMs: 120_000 }), "recovery fails without barrier"); return finalEvidence(ctx, { gates: evidence, dependencyControls: ["postgresql", "chromium", "barrier"] });
  },
});

const D08 = defineCase({
  id: "D-08", fixtureFamily: "CL-F-BROWSER",
  action: "Execute a frozen requirement ledger for one-Lot reserve, release, split certification and Registry history, recording concrete HTTP, OpenAPI, production UI, snapshot, Work, Event and Certificate evidence nodes.",
  oracle: "Each applicable ledger node is derived from an executed public surface and bound to the same concrete identity; a route name, file, test title or self-reported pass cannot close any requirement.",
  async run(ctx) {
    const fixture = makeSplitFixture(options(ctx), 4); fixture.quantityGrams = 7; const { target, api } = await prepare(ctx, { seed: fixture.seed }); const openapi = successful(await ctx.request(api.baseUrl, "/openapi.json"), "OpenAPI", 200); assertCarbonLedgerOpenApi(openapi.json); const { page } = await launchBrowser(ctx, api.baseUrl); const one = await browserCreate(ctx, page, fixture, 1, "ledger one-Lot"); ctx.ok(one.allocation && one.allocations.length === 1, "ledger one-Lot reserve"); const oneReleaseResponse = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === `/api/v1/retirements/${one.retirementId}/release`, { timeout: 30_000 }); await (await visibleControl(page, ["button", "link"], [/release|释放/iu])).click(); ctx.equal((await oneReleaseResponse).status(), 200, "ledger one-Lot release"); const oneReleased = assertRetirement(successful(await ctx.request(api.baseUrl, `/api/v1/retirements/${one.retirementId}`), "released one-Lot", 200).json); await page.goto(api.baseUrl, { waitUntil: "networkidle" }); const split = await browserCreate(ctx, page, fixture, fixture.quantityGrams, "ledger split"); const allocations = await getAllocations(ctx, api.baseUrl, split.retirementId); for (const allocation of allocations) await visibleIdentity(page, allocation.creditLotId, "ledger allocation"); const worker = await target.startWorker(); await waitForRetirement(ctx, api.baseUrl, split.retirementId, "RETIRED", [worker]); const closed = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(api.baseUrl); const splitState = resources(snapshot).retirements.find(({ retirementId }) => retirementId === split.retirementId)?.state; const obsoleteClosed = snapshot.work.filter(({ aggregateId }) => aggregateId === one.retirementId).every(({ terminal }) => terminal); return splitState === "RETIRED" && obsoleteClosed ? snapshot : undefined; }, { timeoutMs: 120_000, label: "ledger Work closure", processes: [worker] }); const closure = assertRetirementAllocationClosure(closed, split.retirementId); const cert = certificateResponse(ctx, await getCertificate(ctx, api.baseUrl, split.retirementId), closure.retirement, closure.allocations, resources(closed).creditLots); await page.reload({ waitUntil: "networkidle" }); await visibleIdentity(page, split.retirementId, "ledger Retirement"); const eventResponse = successful(await ctx.request(api.baseUrl, `/api/v1/domain-events?aggregateId=${split.retirementId}&afterSequence=0&limit=100`), "event history", 200); exactKeys(eventResponse.json, ["items", "nextCursor"], "event page"); const releaseEvents = successful(await ctx.request(api.baseUrl, `/api/v1/domain-events?aggregateId=${one.retirementId}&afterSequence=0&limit=100`), "release history", 200).json.items;
    const oneWork = closed.work.filter(({ aggregateId }) => aggregateId === one.retirementId); const splitWork = closed.work.filter(({ aggregateId }) => aggregateId === split.retirementId); const nodes = {
      oneLotReserveAndRelease: { http: oneReleased.state === "RELEASED", openapi: Boolean(openapi.json.paths["/api/v1/retirements"]?.post && openapi.json.paths["/api/v1/retirements/{retirementId}/release"]?.post), ui: await page.getByText(identityPattern(one.retirementId)).count() > 0, snapshot: resources(closed).retirements.some(({ retirementId, state }) => retirementId === one.retirementId && state === "RELEASED"), work: oneWork.length > 0 && oneWork.every(({ terminal }) => terminal), event: releaseEvents.some(({ aggregateId, type }) => aggregateId === one.retirementId && type === "retirement.released") },
      splitReserve: { http: split.retirementId === closure.retirement.retirementId, openapi: Boolean(openapi.json.paths["/api/v1/retirements"]?.post), ui: await page.getByText(identityPattern(split.retirementId)).count() > 0, snapshot: resources(closed).retirements.some(({ retirementId }) => retirementId === split.retirementId), work: closed.work.some(({ aggregateId }) => aggregateId === split.retirementId), event: eventResponse.json.items.some(({ aggregateId, type }) => aggregateId === split.retirementId && type === "retirement.reserved") },
      splitAllocation: { http: allocations.length === 4, openapi: Boolean(openapi.json.paths["/api/v1/retirements/{retirementId}/allocations"]?.get), ui: (await Promise.all(allocations.map(({ creditLotId }) => page.getByText(identityPattern(creditLotId)).count()))).every((count) => count > 0), snapshot: closure.allocations.length === allocations.length, certificateBytes: cert.parsed.certificateVersion === 2 && cert.parsed.allocations.length === allocations.length },
      publication: { http: cert.bytes.length > 0, openapi: Boolean(openapi.json.paths["/api/v1/retirements/{retirementId}/certificate"]?.get), ui: await page.getByText(/retired|completed|已注销|已完成/iu).count() > 0, snapshot: closure.retirement.state === "RETIRED", work: splitWork.length > 0 && splitWork.every(({ terminal }) => terminal), event: eventResponse.json.items.some(({ aggregateId, type }) => aggregateId === split.retirementId && type === "certificate.published"), certificateBytes: cert.digest === closure.retirement.certificateDigest },
    };
    for (const [requirement, applicable] of Object.entries(nodes)) ctx.ok(Object.values(applicable).every(Boolean), `${requirement} cross-layer closure`); return finalEvidence(ctx, { oneLotRetirementId: one.retirementId, splitRetirementId: split.retirementId, requirements: nodes });
  },
});

export const D_CASES = Object.freeze([D01, D02, D03, D04, D05, D06, D07, D08]);
