import assert from "node:assert/strict";
import { createHash } from "node:crypto";

import { CaseExcluded, CaseFailure } from "../lib/execution.mjs";
import { assertAllocationSet, assertEventSequence, assertLotConservation, canonicalJson, percentile } from "../oracles/index.mjs";

export const CREDIT_LOT_KEYS = Object.freeze(["creditLotId", "projectId", "vintage", "methodology", "priority", "issuedGrams", "availableGrams", "reservedGrams", "retiredGrams", "provenanceDigest"]);
export const V1_RETIREMENT_KEYS = Object.freeze(["retirementId", "beneficiaryId", "quantityGrams", "state", "allocation", "expiresAt", "certificateDigest", "createdAt", "terminalAt", "sequence"]);
export const FINAL_RETIREMENT_KEYS = Object.freeze([...V1_RETIREMENT_KEYS, "allocations"]);
export const ALLOCATION_KEYS = Object.freeze(["lotAllocationId", "retirementId", "ordinal", "creditLotId", "quantityGrams", "projectId", "vintage", "methodology", "provenanceDigest"]);
export const CERTIFICATE_KEYS = Object.freeze(["certificateVersion", "retirementId", "beneficiaryId", "quantityGrams", "creditLotId", "projectId", "vintage", "methodology", "provenanceDigest", "retiredAt"]);
export const SPLIT_CERTIFICATE_KEYS = Object.freeze(["certificateVersion", "retirementId", "beneficiaryId", "totalQuantityGrams", "allocations", "retiredAt"]);
export const SPLIT_CERTIFICATE_ALLOCATION_KEYS = Object.freeze(["ordinal", "creditLotId", "quantityGrams", "projectId", "vintage", "methodology", "provenanceDigest"]);
export const V1_RESOURCE_KEYS = Object.freeze(["projects", "beneficiaries", "creditLots", "retirements", "certificates"]);
export const FINAL_RESOURCE_KEYS = Object.freeze([...V1_RESOURCE_KEYS, "lotAllocations", "splitCertificates"].sort());
export const WORK_KINDS = Object.freeze(["CERTIFICATE_GENERATION", "RETIREMENT_EXPIRY"]);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const SHA256 = /^[0-9a-f]{64}$/u;
const UTC_TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u;
const RETIREMENT_STATES = Object.freeze(["RESERVED", "CERTIFYING", "RETIRED", "RELEASED", "EXPIRED", "FAILED"]);
const WORK_STATES = Object.freeze(["PENDING", "LEASED", "SUCCEEDED", "FAILED", "CANCELLED"]);

const HARD_CAPS = Object.freeze({
  "A-01": ["BUILD_MIGRATION_OR_BOOT"], "A-02": ["BUILD_MIGRATION_OR_BOOT", "MIGRATION_COMPATIBILITY"], "A-03": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"],
  "A-08": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "A-09": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "A-10": ["SPLIT_ATOMICITY_OR_CERTIFICATE"], "A-11": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "A-13": ["SPLIT_ATOMICITY_OR_CERTIFICATE"], "A-16": ["SPLIT_ATOMICITY_OR_CERTIFICATE"],
  "B-01": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "B-02": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "B-03": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "B-04": ["DURABLE_IDEMPOTENCY"], "B-05": ["DURABLE_IDEMPOTENCY"], "B-06": ["DURABLE_IDEMPOTENCY", "LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "B-07": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "B-08": ["SPLIT_ATOMICITY_OR_CERTIFICATE"], "B-09": ["SPLIT_ATOMICITY_OR_CERTIFICATE"], "B-10": ["SPLIT_ATOMICITY_OR_CERTIFICATE"],
  "C-01": ["STALE_WORK_OR_LOST_WORK"], "C-02": ["STALE_WORK_OR_LOST_WORK"], "C-03": ["STALE_WORK_OR_LOST_WORK", "SPLIT_ATOMICITY_OR_CERTIFICATE"], "C-04": ["STALE_WORK_OR_LOST_WORK", "SPLIT_ATOMICITY_OR_CERTIFICATE"], "C-05": ["STALE_WORK_OR_LOST_WORK"], "C-06": ["STALE_WORK_OR_LOST_WORK"], "C-07": ["EVENT_ATOMICITY_OR_IDENTITY"], "C-08": ["EVENT_ATOMICITY_OR_IDENTITY"],
  "D-02": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "D-03": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "D-04": ["SPLIT_ATOMICITY_OR_CERTIFICATE"],
  "E-01": ["MIGRATION_COMPATIBILITY"], "E-02": ["MIGRATION_COMPATIBILITY", "DURABLE_IDEMPOTENCY", "EVENT_ATOMICITY_OR_IDENTITY"], "E-03": ["MIGRATION_COMPATIBILITY", "STALE_WORK_OR_LOST_WORK"], "E-04": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "E-05": ["LOT_CONSERVATION_OR_ATOMIC_REJECTION"], "E-06": ["STALE_WORK_OR_LOST_WORK", "SPLIT_ATOMICITY_OR_CERTIFICATE"],
});

export function defineCase({ id, fixtureFamily, action, oracle, run }) {
  if (!/^[A-E]-\d{2}$/u.test(id) || !/^CL-F-/u.test(fixtureFamily ?? "") || typeof action !== "string" || action.length < 24 || typeof oracle !== "string" || oracle.length < 24 || typeof run !== "function" || run.length < 1) throw new TypeError("invalid CarbonLedger Case definition");
  const hardCaps = HARD_CAPS[id] ?? [];
  return Object.freeze({ id, taskId: "carbonledger", fixtureFamily, action, oracle, async run(ctx) { try { return await run(ctx); } catch (error) { if (error && typeof error === "object") error.hardCapIds = [...new Set([...(error.hardCapIds ?? []), ...hardCaps])]; throw error; } } });
}

export function exactKeys(value, keys, label) { assert.ok(value && typeof value === "object" && !Array.isArray(value), `${label} must be an object`); assert.deepEqual(Object.keys(value).sort(), [...keys].sort(), `${label} fields`); return value; }
function uuid(value, label) { assert.match(value, UUID, `${label} lowercase UUID`); }
function timestamp(value, label) { assert.match(value, UTC_TIMESTAMP, `${label} UTC timestamp`); assert.equal(new Date(value).toISOString(), value, `${label} valid timestamp`); }
function text(value, label) { assert.equal(typeof value, "string", `${label} string`); }
function safeInteger(value, label, { positive = false, nonnegative = false } = {}) { assert.ok(Number.isSafeInteger(value), `${label} safe integer`); if (positive) assert.ok(value > 0, `${label} positive`); if (nonnegative) assert.ok(value >= 0, `${label} nonnegative`); }
export function successful(response, label = "request", status) { if (status === undefined) assert.ok(response.status >= 200 && response.status < 300, `${label} returned ${response.status}: ${response.text}`); else assert.equal(response.status, status, `${label} status`); return response; }
export function semanticError(response, status, code, label = code) { assert.equal(response.status, status, `${label} status`); exactKeys(response.json, ["error"], `${label} envelope`); exactKeys(response.json.error, ["code", "message", "details"], `${label} error`); assert.equal(response.json.error.code, code, `${label} code`); text(response.json.error.message, `${label} message`); exactKeys(response.json.error.details, [], `${label} details`); return response.json.error; }
export function resources(snapshot) { assert.ok(snapshot?.resources && Array.isArray(snapshot.work) && Array.isArray(snapshot.events), "snapshot resources/work/events"); return snapshot.resources; }
export function assertCreditLot(value) { exactKeys(value, CREDIT_LOT_KEYS, "CreditLot"); uuid(value.creditLotId, "CreditLot.creditLotId"); uuid(value.projectId, "CreditLot.projectId"); safeInteger(value.vintage, "CreditLot.vintage"); safeInteger(value.priority, "CreditLot.priority"); text(value.methodology, "CreditLot.methodology"); assert.ok(value.methodology.length > 0, "CreditLot.methodology nonempty"); assertLotConservation([value]); assert.match(value.provenanceDigest, SHA256); return value; }
export function assertRetirement(value, { final = true } = {}) { exactKeys(value, final ? FINAL_RETIREMENT_KEYS : V1_RETIREMENT_KEYS, "Retirement"); uuid(value.retirementId, "Retirement.retirementId"); uuid(value.beneficiaryId, "Retirement.beneficiaryId"); assert.ok(RETIREMENT_STATES.includes(value.state), "published Retirement state"); safeInteger(value.quantityGrams, "Retirement.quantityGrams", { positive: true }); safeInteger(value.sequence, "Retirement.sequence", { positive: true }); timestamp(value.expiresAt, "Retirement.expiresAt"); timestamp(value.createdAt, "Retirement.createdAt"); if (["RETIRED", "RELEASED", "EXPIRED", "FAILED"].includes(value.state)) timestamp(value.terminalAt, "Retirement.terminalAt"); else assert.equal(value.terminalAt, null, "nonterminal Retirement terminalAt null"); if (value.state === "RETIRED") assert.match(value.certificateDigest, SHA256, "RETIRED certificateDigest"); else assert.equal(value.certificateDigest, null, "non-RETIRED certificateDigest null"); if (value.allocation !== null) { exactKeys(value.allocation, ["creditLotId", "quantityGrams"], "Retirement allocation"); uuid(value.allocation.creditLotId, "Retirement allocation.creditLotId"); safeInteger(value.allocation.quantityGrams, "Retirement allocation.quantityGrams", { positive: true }); } if (!final) assert.ok(value.allocation, "V1 Retirement allocation"); if (final) { assert.ok(Array.isArray(value.allocations) && value.allocations.length >= 1 && value.allocations.length <= 20, "FINAL Retirement allocations"); value.allocations.forEach((allocation, index) => { assertAllocation(allocation); assert.equal(allocation.retirementId, value.retirementId, "allocation Retirement identity"); assert.equal(allocation.ordinal, index + 1, "allocation response order"); }); if (value.allocations.length === 1) assert.deepEqual(value.allocation, { creditLotId: value.allocations[0].creditLotId, quantityGrams: value.allocations[0].quantityGrams }, "one-Lot legacy allocation"); else assert.equal(value.allocation, null, "split legacy allocation null"); } return value; }
export function assertAllocation(value) { exactKeys(value, ALLOCATION_KEYS, "LotAllocation"); for (const field of ["lotAllocationId", "retirementId", "creditLotId", "projectId"]) uuid(value[field], `LotAllocation.${field}`); safeInteger(value.ordinal, "LotAllocation.ordinal", { positive: true }); safeInteger(value.quantityGrams, "LotAllocation.quantityGrams", { positive: true }); safeInteger(value.vintage, "LotAllocation.vintage"); text(value.methodology, "LotAllocation.methodology"); assert.match(value.provenanceDigest, SHA256); return value; }
export function assertCertificate(value) { exactKeys(value, CERTIFICATE_KEYS, "Certificate"); assert.equal(value.certificateVersion, 1); for (const field of ["retirementId", "beneficiaryId", "creditLotId", "projectId"]) uuid(value[field], `Certificate.${field}`); safeInteger(value.quantityGrams, "Certificate.quantityGrams", { positive: true }); safeInteger(value.vintage, "Certificate.vintage"); text(value.methodology, "Certificate.methodology"); assert.match(value.provenanceDigest, SHA256); timestamp(value.retiredAt, "Certificate.retiredAt"); return value; }
export function assertSplitCertificate(value) { exactKeys(value, SPLIT_CERTIFICATE_KEYS, "SplitCertificate"); assert.equal(value.certificateVersion, 2); uuid(value.retirementId, "SplitCertificate.retirementId"); uuid(value.beneficiaryId, "SplitCertificate.beneficiaryId"); safeInteger(value.totalQuantityGrams, "SplitCertificate.totalQuantityGrams", { positive: true }); timestamp(value.retiredAt, "SplitCertificate.retiredAt"); assert.ok(Array.isArray(value.allocations) && value.allocations.length > 1 && value.allocations.length <= 20, "SplitCertificate allocations"); value.allocations.forEach((allocation, index) => { exactKeys(allocation, SPLIT_CERTIFICATE_ALLOCATION_KEYS, "SplitCertificate allocation"); assert.equal(allocation.ordinal, index + 1); for (const field of ["creditLotId", "projectId"]) uuid(allocation[field], `SplitCertificate allocation.${field}`); safeInteger(allocation.quantityGrams, "SplitCertificate allocation.quantityGrams", { positive: true }); safeInteger(allocation.vintage, "SplitCertificate allocation.vintage"); text(allocation.methodology, "SplitCertificate allocation.methodology"); assert.match(allocation.provenanceDigest, SHA256); }); assert.equal(value.allocations.reduce((sum, allocation) => sum + allocation.quantityGrams, 0), value.totalQuantityGrams, "SplitCertificate total"); return value; }

export async function prepare(ctx, { seed, workspace = ctx.workspace, build = true, migrate = true, apiCount = 1, workerCount = 0 } = {}) {
  const target = ctx.forWorkspace(workspace);
  if (build) await target.npm("build", [], { timeoutMs: 240_000 });
  if (migrate) await target.migrate();
  if (seed) await target.seed(seed);
  const apis = await Promise.all(Array.from({ length: apiCount }, () => target.startApi()));
  const workers = await Promise.all(Array.from({ length: workerCount }, () => target.startWorker()));
  ctx.mark("carbonledger.prepared", { apiCount, workerCount, seeded: Boolean(seed), workspace: target.workspace });
  return { target, api: apis[0], apis, workers };
}

export async function createRetirement(ctx, baseUrl, body, options = {}) {
  const response = await ctx.mutate(baseUrl, "/api/v1/retirements", options.key ?? ctx.key(`retirement:${body.beneficiaryId}:${body.quantityGrams}`), body);
  if (options.allowFailure) return response;
  successful(response, options.label ?? "create Retirement", 202);
  return assertRetirement(response.json);
}
export async function getRetirement(ctx, baseUrl, retirementId) { return assertRetirement(successful(await ctx.request(baseUrl, `/api/v1/retirements/${retirementId}`), "get Retirement", 200).json); }
export async function releaseRetirement(ctx, baseUrl, retirementId, reason, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/retirements/${retirementId}/release`, options.key ?? ctx.key(`release:${retirementId}`), { reason }); if (options.allowFailure) return response; return assertRetirement(successful(response, options.label ?? "release Retirement", 200).json); }
export async function getAllocations(ctx, baseUrl, retirementId) { const response = successful(await ctx.request(baseUrl, `/api/v1/retirements/${retirementId}/allocations`), "get allocations", 200); exactKeys(response.json, ["items"], "allocation collection"); response.json.items.forEach(assertAllocation); return response.json.items; }
export async function getCertificate(ctx, baseUrl, retirementId, { binary = true } = {}) { return ctx.request(baseUrl, `/api/v1/retirements/${retirementId}/certificate`, { binary }); }
export function retirementRequest(fixture, quantityGrams, eligibility = {}) { return { beneficiaryId: fixture.beneficiaryId, quantityGrams, eligibility }; }
export async function getCreditLot(ctx, baseUrl, creditLotId) { return assertCreditLot(successful(await ctx.request(baseUrl, `/api/v1/credit-lots/${creditLotId}`), "get Credit Lot", 200).json); }
export async function listCreditLots(ctx, baseUrl, query = {}) { const response = successful(await ctx.request(baseUrl, `/api/v1/credit-lots?${new URLSearchParams(Object.entries(query).filter(([, value]) => value !== undefined).map(([key, value]) => [key, String(value)]))}`), "list Credit Lots", 200); exactKeys(response.json, ["items", "nextCursor"], "Credit Lot page"); assert.ok(Array.isArray(response.json.items), "Credit Lot page items"); assert.ok(response.json.nextCursor === null || typeof response.json.nextCursor === "string", "Credit Lot nextCursor nullable string"); response.json.items.forEach(assertCreditLot); return response.json; }
export async function listRetirements(ctx, baseUrl, query = {}) { const response = successful(await ctx.request(baseUrl, `/api/v1/retirements?${new URLSearchParams(Object.entries(query).filter(([, value]) => value !== undefined).map(([key, value]) => [key, String(value)]))}`), "list Retirements", 200); exactKeys(response.json, ["items", "nextCursor"], "Retirement page"); assert.ok(Array.isArray(response.json.items), "Retirement page items"); assert.ok(response.json.nextCursor === null || typeof response.json.nextCursor === "string", "Retirement nextCursor nullable string"); response.json.items.forEach(assertRetirement); return response.json; }
export async function startCertificateWorker(target, options = {}) { return target.startWorker(options); }
export async function waitForRetired(ctx, target, baseUrl, retirementId, options = {}) { const worker = options.worker ?? await startCertificateWorker(target, options.workerOptions); const result = await waitForRetirement(ctx, baseUrl, retirementId, "RETIRED", [worker], options.timeoutMs); return { ...result, worker }; }
export function certificateResponse(ctx, response, retirement, allocations, lots) { successful(response, "Certificate", 200); ctx.equal(response.headers.get("content-type")?.split(";")[0], "application/json", "Certificate Content-Type"); const bytes = response.body; ctx.ok(Buffer.isBuffer(bytes) && bytes.length > 0, "Certificate bytes"); const parsed = JSON.parse(bytes.toString("utf8")); if (allocations.length === 1) assertCertificate(parsed); else assertSplitCertificate(parsed); const lotById = new Map(lots.map((lot) => [lot.creditLotId, lot])); const expected = allocations.length === 1
  ? { certificateVersion: 1, retirementId: retirement.retirementId, beneficiaryId: retirement.beneficiaryId, quantityGrams: retirement.quantityGrams, creditLotId: allocations[0].creditLotId, projectId: allocations[0].projectId, vintage: allocations[0].vintage, methodology: allocations[0].methodology, provenanceDigest: allocations[0].provenanceDigest, retiredAt: parsed.retiredAt }
  : { certificateVersion: 2, retirementId: retirement.retirementId, beneficiaryId: retirement.beneficiaryId, totalQuantityGrams: retirement.quantityGrams, allocations: allocations.map(({ ordinal, creditLotId, quantityGrams, projectId, vintage, methodology, provenanceDigest }) => ({ ordinal, creditLotId, quantityGrams, projectId, vintage, methodology, provenanceDigest })), retiredAt: parsed.retiredAt };
  ctx.equal(parsed, expected, "canonical Certificate lineage"); ctx.equal(bytes.toString("utf8"), canonicalJson(expected), "RFC 8785 Certificate bytes"); const digest = createHash("sha256").update(bytes).digest("hex"); ctx.equal(response.headers.get("etag")?.replace(/^"|"$/gu, ""), digest, "Certificate ETag"); ctx.equal(retirement.certificateDigest, digest, "Retirement certificateDigest"); for (const allocation of allocations) ctx.ok(lotById.has(allocation.creditLotId), "Certificate allocation Lot exists"); return { parsed, bytes, digest };
}

export async function waitForSnapshot(ctx, baseUrl, predicate, options = {}) { return ctx.waitFor(async () => { const snapshot = await ctx.snapshot(baseUrl); return predicate(snapshot) ? snapshot : undefined; }, { timeoutMs: options.timeoutMs ?? 120_000, intervalMs: options.intervalMs ?? 100, label: options.label ?? "CarbonLedger snapshot condition", processes: options.processes ?? [] }); }
export async function waitForRetirement(ctx, baseUrl, retirementId, state, processes = [], timeoutMs = 120_000) { const snapshot = await waitForSnapshot(ctx, baseUrl, (value) => resources(value).retirements.find((item) => item.retirementId === retirementId)?.state === state, { timeoutMs, label: `Retirement ${retirementId} ${state}`, processes }); return { snapshot, retirement: resources(snapshot).retirements.find((item) => item.retirementId === retirementId) }; }
export async function waitForWorkDrain(ctx, baseUrl, predicate, processes = [], timeoutMs = 120_000) { return waitForSnapshot(ctx, baseUrl, (snapshot) => { const selected = snapshot.work.filter(predicate); return selected.length > 0 && selected.every(({ terminal }) => terminal); }, { timeoutMs, label: "CarbonLedger Work drain", processes }); }

function scalarCompare(left, right) { if (left === null || right === null) return left === right ? 0 : left === null ? -1 : 1; if (typeof left === "boolean" && typeof right === "boolean") return Number(left) - Number(right); if (Number.isSafeInteger(left) && Number.isSafeInteger(right)) return left - right; return Buffer.from(String(left)).compare(Buffer.from(String(right))); }
function readPath(value, path) { return path.split(".").reduce((current, key) => current?.[key], value); }
function assertSorted(items, paths, label) { const sorted = [...items].sort((left, right) => { for (const path of paths) { const compared = scalarCompare(readPath(left, path), readPath(right, path)); if (compared) return compared; } return Buffer.from(canonicalJson(left)).compare(Buffer.from(canonicalJson(right))); }); assert.deepEqual(items, sorted, `${label} sort`); }
function assertWork(items) { for (const item of items) { exactKeys(item, ["workId", "kind", "aggregateId", "state", "terminal", "attempt", "leaseOwner", "leaseExpiresAt"], "Work"); uuid(item.workId, "Work.workId"); uuid(item.aggregateId, "Work.aggregateId"); assert.ok(WORK_KINDS.includes(item.kind), `published Work kind ${item.kind}`); assert.ok(WORK_STATES.includes(item.state), `published Work state ${item.state}`); safeInteger(item.attempt, "Work.attempt", { nonnegative: true }); assert.equal(item.terminal, ["SUCCEEDED", "FAILED", "CANCELLED"].includes(item.state)); if (item.state === "LEASED") { text(item.leaseOwner, "Work.leaseOwner"); assert.ok(item.leaseOwner.length > 0, "Work.leaseOwner nonempty"); timestamp(item.leaseExpiresAt, "Work.leaseExpiresAt"); } else { assert.equal(item.leaseOwner, null, "unleased Work leaseOwner null"); assert.equal(item.leaseExpiresAt, null, "unleased Work leaseExpiresAt null"); } } assertSorted(items, ["workId"], "Work"); }
function assertEvents(items) { for (const item of items) { exactKeys(item, ["eventId", "aggregateId", "sequence", "type", "occurredAt", "schemaVersion", "payload"], "DomainEvent"); uuid(item.eventId, "DomainEvent.eventId"); uuid(item.aggregateId, "DomainEvent.aggregateId"); safeInteger(item.sequence, "DomainEvent.sequence", { positive: true }); text(item.type, "DomainEvent.type"); assert.ok(item.type.length > 0, "DomainEvent.type nonempty"); timestamp(item.occurredAt, "DomainEvent.occurredAt"); assert.equal(item.schemaVersion, 1, "DomainEvent.schemaVersion"); assert.equal(canonicalJson(item.payload), "{}", "DomainEvent payload"); } assertSorted(items, ["aggregateId", "sequence", "eventId"], "DomainEvent"); assertEventSequence(items); }
function assertResourceGraph(data, { final }) {
  const projects = new Set(data.projects.map(({ projectId }) => projectId)); const beneficiaries = new Set(data.beneficiaries.map(({ beneficiaryId }) => beneficiaryId)); const lots = new Map(data.creditLots.map((lot) => [lot.creditLotId, lot])); const retirements = new Map(data.retirements.map((retirement) => [retirement.retirementId, retirement]));
  assert.equal(projects.size, data.projects.length, "unique Project identities"); assert.equal(beneficiaries.size, data.beneficiaries.length, "unique Beneficiary identities"); assert.equal(lots.size, data.creditLots.length, "unique Credit Lot identities"); assert.equal(retirements.size, data.retirements.length, "unique Retirement identities");
  for (const lot of data.creditLots) assert.ok(projects.has(lot.projectId), "Credit Lot Project exists");
  const allocationsByRetirement = new Map(); if (final) { const allocationIds = new Set(); for (const allocation of data.lotAllocations) { assert.ok(!allocationIds.has(allocation.lotAllocationId), "unique LotAllocation identity"); allocationIds.add(allocation.lotAllocationId); const retirement = retirements.get(allocation.retirementId); const lot = lots.get(allocation.creditLotId); assert.ok(retirement && lot, "LotAllocation references public resources"); assert.equal(allocation.projectId, lot.projectId, "LotAllocation Project provenance"); assert.equal(allocation.vintage, lot.vintage, "LotAllocation vintage provenance"); assert.equal(allocation.methodology, lot.methodology, "LotAllocation methodology provenance"); assert.equal(allocation.provenanceDigest, lot.provenanceDigest, "LotAllocation digest provenance"); const selected = allocationsByRetirement.get(allocation.retirementId) ?? []; selected.push(allocation); allocationsByRetirement.set(allocation.retirementId, selected); } }
  for (const retirement of data.retirements) { assert.ok(beneficiaries.has(retirement.beneficiaryId), "Retirement Beneficiary exists"); if (retirement.allocation) assert.ok(lots.has(retirement.allocation.creditLotId), "Retirement Credit Lot exists"); if (final) { const allocations = allocationsByRetirement.get(retirement.retirementId) ?? []; assert.deepEqual(retirement.allocations, allocations, "Retirement allocations equal snapshot collection"); assert.equal(allocations.reduce((sum, allocation) => sum + allocation.quantityGrams, 0), retirement.quantityGrams, "Retirement allocation conservation"); } }
  for (const certificate of data.certificates) { const retirement = retirements.get(certificate.retirementId); const lot = lots.get(certificate.creditLotId); assert.ok(retirement?.state === "RETIRED" && lot, "Certificate references RETIRED public resources"); assert.equal(certificate.beneficiaryId, retirement.beneficiaryId, "Certificate Beneficiary"); assert.equal(certificate.quantityGrams, retirement.quantityGrams, "Certificate quantity"); assert.equal(certificate.projectId, lot.projectId, "Certificate Project"); assert.equal(certificate.vintage, lot.vintage, "Certificate vintage"); assert.equal(certificate.methodology, lot.methodology, "Certificate methodology"); assert.equal(certificate.provenanceDigest, lot.provenanceDigest, "Certificate provenance"); assert.equal(createHash("sha256").update(canonicalJson(certificate)).digest("hex"), retirement.certificateDigest, "Certificate digest"); }
  if (final) for (const certificate of data.splitCertificates) { const retirement = retirements.get(certificate.retirementId); assert.ok(retirement?.state === "RETIRED", "SplitCertificate references RETIRED Retirement"); assert.equal(certificate.beneficiaryId, retirement.beneficiaryId, "SplitCertificate Beneficiary"); assert.equal(certificate.totalQuantityGrams, retirement.quantityGrams, "SplitCertificate quantity"); assert.deepEqual(certificate.allocations, retirement.allocations.map(({ ordinal, creditLotId, quantityGrams, projectId, vintage, methodology, provenanceDigest }) => ({ ordinal, creditLotId, quantityGrams, projectId, vintage, methodology, provenanceDigest })), "SplitCertificate immutable allocations"); assert.equal(createHash("sha256").update(canonicalJson(certificate)).digest("hex"), retirement.certificateDigest, "SplitCertificate digest"); }
  return retirements;
}
export function assertSnapshot(snapshot, { final = true } = {}) {
  exactKeys(snapshot, ["asOf", "resources", "work", "events"], "verification snapshot"); timestamp(snapshot.asOf, "snapshot.asOf"); const data = resources(snapshot); assert.deepEqual(Object.keys(data).sort(), final ? FINAL_RESOURCE_KEYS : [...V1_RESOURCE_KEYS].sort(), "snapshot resource keys");
  for (const value of data.projects) { exactKeys(value, ["projectId", "name"], "CarbonProject"); uuid(value.projectId, "CarbonProject.projectId"); text(value.name, "CarbonProject.name"); } for (const value of data.beneficiaries) { exactKeys(value, ["beneficiaryId", "name"], "Beneficiary"); uuid(value.beneficiaryId, "Beneficiary.beneficiaryId"); text(value.name, "Beneficiary.name"); } data.creditLots.forEach(assertCreditLot); data.retirements.forEach((value) => assertRetirement(value, { final })); data.certificates.forEach(assertCertificate); if (final) { data.lotAllocations.forEach(assertAllocation); data.splitCertificates.forEach(assertSplitCertificate); }
  const sorts = { projects: ["projectId"], beneficiaries: ["beneficiaryId"], creditLots: ["creditLotId"], retirements: ["retirementId"], certificates: ["retirementId"], lotAllocations: ["retirementId", "ordinal"], splitCertificates: ["retirementId"] }; for (const [name, paths] of Object.entries(sorts)) if (data[name]) assertSorted(data[name], paths, name);
  assertWork(snapshot.work); assertEvents(snapshot.events); const retirementIndex = assertResourceGraph(data, { final }); for (const item of [...snapshot.work, ...snapshot.events]) assert.ok(retirementIndex.has(item.aggregateId), "Work/Event aggregate exists"); const eventSequence = new Map(); for (const event of snapshot.events) eventSequence.set(event.aggregateId, Math.max(eventSequence.get(event.aggregateId) ?? 0, event.sequence)); for (const retirement of data.retirements) assert.equal(eventSequence.get(retirement.retirementId) ?? 0, retirement.sequence, "Retirement sequence matches committed Events"); assertLotConservation(data.creditLots); const serialized = canonicalJson(snapshot); assert.equal(/"[^"]*Token"\s*:/u.test(serialized), false, "snapshot recursively omits *Token fields"); assert.equal(/postgres(?:ql)?:\/\/|\/(?:Users|home|tmp)\//iu.test(serialized), false, "snapshot omits connection strings and private paths"); return snapshot;
}
export function assertRetirementAllocationClosure(snapshot, retirementId) { const data = resources(snapshot); const retirement = data.retirements.find((item) => item.retirementId === retirementId); assert.ok(retirement, "Retirement in snapshot"); const allocations = data.lotAllocations.filter((item) => item.retirementId === retirementId).sort((left, right) => left.ordinal - right.ordinal); assertAllocationSet(allocations, data.creditLots, retirement.quantityGrams); assert.deepEqual(retirement.allocations, allocations, "Retirement immutable allocations"); if (allocations.length === 1) assert.deepEqual(retirement.allocation, { creditLotId: allocations[0].creditLotId, quantityGrams: allocations[0].quantityGrams }, "one-Lot legacy allocation"); else assert.equal(retirement.allocation, null, "split legacy allocation null"); return { retirement, allocations }; }

export async function fixedLoad(ctx, { count, concurrency, request, collectResponses = false }) { const latencies = [], statuses = new Map(), responses = collectResponses ? new Array(count) : undefined; const startedAt = performance.now(); await ctx.concurrent(Array.from({ length: count }), concurrency, async (_, index) => { const started = performance.now(); const response = await request(index); latencies.push(performance.now() - started); statuses.set(response.status, (statuses.get(response.status) ?? 0) + 1); if (responses) responses[index] = response; }); const durationMs = performance.now() - startedAt; return { count, responses, durationMs, throughput: count / (durationMs / 1_000), p95: percentile(latencies, 0.95), statuses: Object.fromEntries(statuses) }; }
export function assertLoad(load, { accepted, minimumThroughput, maximumP95 }) { const acceptedCount = Object.entries(load.statuses).filter(([status]) => accepted.includes(Number(status))).reduce((sum, [, count]) => sum + count, 0); const serverErrors = Object.entries(load.statuses).filter(([status]) => Number(status) >= 500).reduce((sum, [, count]) => sum + count, 0); assert.equal(acceptedCount, load.count, "every workload operation has an accepted complete response"); assert.equal(serverErrors, 0, "unexpected 5xx"); assert.ok(load.throughput >= minimumThroughput, `throughput ${load.throughput} below ${minimumThroughput}`); assert.ok(load.p95 <= maximumP95, `p95 ${load.p95} above ${maximumP95}`); }

export async function sustainedClosedLoop({ clients, warmupMs, measureMs, operation }) {
  let ordinal = 0; const samples = []; const statuses = new Map(); const responses = [];
  async function phase(durationMs, measuring) { const name = measuring ? "measure" : "warmup"; const startedAt = performance.now(); const deadline = startedAt + durationMs; await Promise.all(Array.from({ length: clients }, async (_, client) => { while (performance.now() < deadline) { const current = ordinal += 1; const requestStarted = performance.now(); const response = await operation({ client, ordinal: current, measuring, phase: name }); if (measuring) { const latencyMs = Number.isFinite(response.durationMs) ? response.durationMs : performance.now() - requestStarted; samples.push(latencyMs); statuses.set(response.status, (statuses.get(response.status) ?? 0) + 1); response._latencyMs = latencyMs; responses.push(response); } } })); return performance.now() - startedAt; }
  const warmupElapsedMs = await phase(warmupMs, false); ordinal = 0; const measuredElapsedMs = await phase(measureMs, true); return { count: samples.length, responses, statuses, measureWindowMs: measureMs, warmupElapsedMs, measuredElapsedMs, throughput: samples.length / (measureMs / 1000), p50Ms: percentile(samples, 0.5), p95Ms: percentile(samples, 0.95), p99Ms: percentile(samples, 0.99) };
}
export function countStatus(load, predicate) { return [...load.statuses].filter(([status]) => predicate(status)).reduce((sum, [, count]) => sum + count, 0); }

export async function launchBrowser(ctx, baseUrl, viewport = { width: 1280, height: 800 }) { const chromium = await ctx.loadChromium(); const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/usr/bin/chromium", headless: true, args: ["--no-sandbox"] }); ctx.defer(() => browser.close()); const browserContext = await browser.newContext({ viewport }); const page = await browserContext.newPage(); await page.goto(baseUrl, { waitUntil: "networkidle", timeout: 30_000 }); return { browser, browserContext, page }; }
export async function fillControl(control, value) { const tag = await control.evaluate((element) => element.tagName.toLowerCase()); if (tag === "select") return control.selectOption(String(value)); const type = await control.getAttribute("type"); const text = type === "datetime-local" ? String(value).replace(/Z$/u, "").slice(0, 16) : String(value); return control.fill(text); }
export async function fillVisible(page, name, value) { const labelled = page.getByLabel(new RegExp(name, "i")).first(); if (await labelled.count()) return fillControl(labelled, value); const control = page.locator(`[name="${name}"]`).first(); assert.ok(await control.count(), `visible control ${name}`); return fillControl(control, value); }
export async function tabTo(page, control) { for (let index = 0; index < 200; index += 1) { if (await control.evaluate((element) => element === document.activeElement)) return; await page.keyboard.press("Tab"); } throw new Error("keyboard traversal could not reach visible control"); }
export async function keyboardFill(page, control, value) { const tag = await control.evaluate((element) => element.tagName.toLowerCase()); await tabTo(page, control); if (tag === "select") { await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter"); return; } const type = await control.getAttribute("type"); const text = type === "datetime-local" ? String(value).replace(/Z$/u, "").slice(0, 16) : String(value); await page.keyboard.press(process.platform === "darwin" ? "Meta+A" : "Control+A"); await page.keyboard.insertText(text); }
export async function clickVisible(page, name) { const button = page.getByRole("button", { name: new RegExp(name, "i") }).first(); assert.ok(await button.count(), `visible action ${name}`); await button.click(); }
export async function visibleControl(page, roles, names) { for (const role of roles) for (const name of names) { const values = page.getByRole(role, { name }); for (let index = 0; index < await values.count(); index += 1) if (await values.nth(index).isVisible().catch(() => false)) return values.nth(index); } throw new Error(`missing visible ${roles.join("/")} control`); }
export async function visibleField(page, names) { for (const name of names) { const values = page.getByLabel(name); for (let index = 0; index < await values.count(); index += 1) if (await values.nth(index).isVisible().catch(() => false)) return values.nth(index); } throw new Error("missing visible labelled field"); }
export async function browserMutation(page, actionNames, pathPattern) { const pending = page.waitForResponse((response) => response.request().method() === "POST" && pathPattern.test(new URL(response.url()).pathname), { timeout: 30_000 }); await (await visibleControl(page, ["button", "link"], actionNames)).click(); return pending; }
export function identityPattern(value) { return new RegExp(String(value).replace(/[.*+?^${}()|[\]\\]/gu, "\\$&"), "u"); }
export function stableSnapshot(snapshot) { const { asOf: _asOf, ...stable } = snapshot; return canonicalJson(stable); }
export function requireV1(ctx) { if (!ctx.v1Workspace) throw new CaseExcluded("missing_v1_checkpoint"); return ctx.v1Workspace; }
export function finalEvidence(ctx, values = {}) { return ctx.pass({ evidence: [{ kind: "carbonledger-case-summary", ...values }] }); }
export function candidateFailure(message, failureCodeSuffix = "ASSERTION_FAILED", hardCapIds = []) { throw new CaseFailure(message, { failureCodeSuffix, hardCapIds }); }
