import assert from "node:assert/strict";
import { access,writeFile } from "node:fs/promises";
import { consignmentBody,createFixtureFactory,performanceContract,pieceScanBody,routeCatalog,scanBody,shipmentBody,v1Seed } from "./fixtures.mjs";
import { canonical,digestProjection } from "./oracle.mjs";
const sharedUrl=process.env.FRONTAL_V2_SHARED_RUNTIME_URL??new URL("../../../../../src/task-evaluator-v2/runtime.mjs",import.meta.url).href;const shared=await import(sharedUrl);
const BARRIER_KEYS=["schemaVersion","processRole","point","workId","aggregateId","attempt","leaseTokenHash"];
function identity(_adapter,{json}){return json;}function noAdapter(value){if(value!=null)throw new Error("RouteWeave publishes no compatibility response adapter");}
export function isRouteWeaveBarrier(value){if(!value||typeof value!=="object"||Array.isArray(value)||JSON.stringify(Object.keys(value).sort())!==JSON.stringify([...BARRIER_KEYS].sort()))return false;const seam=value.processRole==="worker"?value.point==="worker.claimed":value.processRole==="dispatcher"&&value.point==="dispatcher.response-received";return value.schemaVersion===1&&seam&&typeof value.workId==="string"&&typeof value.aggregateId==="string"&&Number.isSafeInteger(value.attempt)&&value.attempt>=1&&/^[0-9a-f]{64}$/u.test(value.leaseTokenHash);}
const runtime=shared.createCaseRuntime({taskSlug:"routeweave",databasePrefix:"rw",snapshotPath:"/api/v1/verification-snapshot",createFixtureFactory,adaptCompatibilityResponse:identity,assertCompatibilityAdapter:noAdapter,validateBarrierPayload:isRouteWeaveBarrier});
class ScenarioFailure extends Error{constructor(message,options={}){super(message,{cause:options.cause});this.origin = "candidate"; this.failureCodeSuffix=options.failureCodeSuffix??"ASSERTION_FAILED";this.hardCapIds=options.hardCapIds??[];}}
class Evidence{constructor(){this.assertions=[];this.statuses=new Map();this.metrics={};}check(label,operation,options={}){try{operation();this.assertions.push({label,status:"passed"});}catch (cause) {shared.assertCandidateError(cause);this.assertions.push({label,status:"failed"});throw new ScenarioFailure(`${label}: ${cause?.message??cause}`,{...options,cause});}}finish(){return{assertions:this.assertions,statuses:Object.fromEntries([...this.statuses.entries()].sort()),metrics:this.metrics};}}
async function decorate(ctx){const evidence=new Evidence(),originalRequest=ctx.request,fixtureKey=ctx.key;let keys=0,seeds=0;ctx.evidence=evidence;ctx.key=(label)=>fixtureKey(`${label}-${keys++}`);ctx.catalog=(options={})=>routeCatalog(ctx.fixtures,options);ctx.seedFor=(version,options={})=>v1Seed(ctx.fixtures,version,options);ctx.shipmentBody=shipmentBody;ctx.consignmentBody=consignmentBody;ctx.scanBody=(catalog,type,index,overrides)=>scanBody(ctx.fixtures,catalog,type,index,overrides);ctx.pieceScanBody=(catalog,type,index,overrides)=>pieceScanBody(ctx.fixtures,catalog,type,index,overrides);ctx.performanceContract=performanceContract;ctx.assert=(label,operation,options)=>evidence.check(label,operation,options);ctx.equal=(label,actual,expected,options)=>evidence.check(label,()=>assert.deepEqual(actual,expected),options);ctx.ok=(label,condition,message,options)=>evidence.check(label,()=>assert.ok(condition,message),options);ctx.metric=(name,value)=>{evidence.metrics[name]=value;};ctx.sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));ctx.canonical=canonical;ctx.digestProjection=digestProjection;
  ctx.request=async(baseUrl,path,options={})=>{const response=await originalRequest(baseUrl,path,options);if(options.record!==false)evidence.statuses.set(String(response.status),(evidence.statuses.get(String(response.status))??0)+1);return response;};
  ctx.seed=async(value,options={})=>{const path=ctx.tempPath(`routeweave-seed-${String(++seeds).padStart(3,"0")}.json`);await writeFile(path,JSON.stringify(value));const result=await ctx.npm("db:seed",["--file",path],{workspace:options.workspace,timeoutMs:options.timeoutMs??1_800_000,allowFailure:true});if(options.expectFailure)ctx.ok("invalid seed exits nonzero",result.exitCode!==0,undefined,{failureCodeSuffix:"SEED_ACCEPTED_INVALID"});else ctx.equal("valid seed exits zero",result.exitCode,0,{failureCodeSuffix:"SEED_FAILED"});return result;};
  ctx.createTenant=(url,body,options={})=>ctx.mutate(url,"/api/v1/tenants",options.key??ctx.key("tenant"),body);ctx.createHub=(url,body,options={})=>ctx.mutate(url,"/api/v1/hubs",options.key??ctx.key("hub"),body);ctx.createCarrier=(url,body,options={})=>ctx.mutate(url,"/api/v1/carriers",options.key??ctx.key("carrier"),body);
  ctx.createShipment=(url,body,options={})=>ctx.mutate(url,"/api/v1/shipments",options.key??ctx.key("shipment"),body,{timeoutMs:options.timeoutMs});ctx.getShipment=(url,id)=>ctx.request(url,`/api/v1/shipments/${id}`);ctx.timeline=(url,id)=>ctx.request(url,`/api/v1/shipments/${id}/timeline`);
  ctx.scanShipment=(url,body,options={})=>ctx.mutate(url,"/api/v1/scan-events",options.key??ctx.key("scan"),body,{timeoutMs:options.timeoutMs});ctx.lossShipment=(url,id,body,options={})=>ctx.mutate(url,`/api/v1/shipments/${id}/loss`,options.key??ctx.key("loss"),body);ctx.foundShipment=(url,id,body,options={})=>ctx.mutate(url,`/api/v1/shipments/${id}/found`,options.key??ctx.key("found"),body);ctx.reassignShipment=(url,id,body,options={})=>ctx.mutate(url,`/api/v1/shipments/${id}/reassign`,options.key??ctx.key("reassign"),body);ctx.cancelShipment=(url,id,options={})=>ctx.mutate(url,`/api/v1/shipments/${id}/cancel`,options.key??ctx.key("cancel"),{});
  ctx.createConsignment=(url,body,options={})=>ctx.mutate(url,"/api/v1/consignments",options.key??ctx.key("consignment"),body,{timeoutMs:options.timeoutMs,contractExpectation:options.contractExpectation});ctx.getConsignment=(url,id)=>ctx.request(url,`/api/v1/consignments/${id}`);ctx.reassignConsignment=(url,id,body,options={})=>ctx.mutate(url,`/api/v1/consignments/${id}/reassign`,options.key??ctx.key("consignment-reassign"),body);ctx.cancelConsignment=(url,id,options={})=>ctx.mutate(url,`/api/v1/consignments/${id}/cancel`,options.key??ctx.key("consignment-cancel"),{});
  ctx.scanPiece=(url,id,body,options={})=>ctx.mutate(url,`/api/v1/parcel-pieces/${id}/scan-events`,options.key??ctx.key("piece-scan"),body,{timeoutMs:options.timeoutMs});ctx.lossPiece=(url,id,body,options={})=>ctx.mutate(url,`/api/v1/parcel-pieces/${id}/loss`,options.key??ctx.key("piece-loss"),body);ctx.foundPiece=(url,id,body,options={})=>ctx.mutate(url,`/api/v1/parcel-pieces/${id}/found`,options.key??ctx.key("piece-found"),body);
  ctx.workerBarrier=(predicate=()=>true)=>ctx.barrier({hold:(payload)=>payload.processRole==="worker"&&payload.point==="worker.claimed"&&predicate(payload)});ctx.dispatcherBarrier=(predicate=()=>true)=>ctx.barrier({hold:(payload)=>payload.processRole==="dispatcher"&&payload.point==="dispatcher.response-received"&&predicate(payload)});ctx.startWorkerAtBarrier=(barrier,options={})=>ctx.startWorker({...options,env:{TEST_BARRIER_URL:barrier.url,TEST_BARRIER_TOKEN:barrier.token,...options.env}});ctx.startDispatcherAtBarrier=(receiver,barrier,options={})=>ctx.startDispatcher({...options,webhookUrl:receiver.url,env:{TEST_BARRIER_URL:barrier.url,TEST_BARRIER_TOKEN:barrier.token,...options.env}});ctx.readOpenApi=async(url)=>{const response=await ctx.request(url,"/openapi.json");ctx.equal("OpenAPI returns 200",response.status,200);return response.json;};ctx.withPage=(api,viewport,operation)=>withPage(ctx,api,viewport,operation);return ctx;}
export async function createCaseContext(options){return decorate(await runtime.createCaseContext(options));}
export async function withCaseContext(options,operation){return runtime.withCaseContext(options,async(raw)=>{const ctx=await decorate(raw);if(ctx.caseId!=="E-01")await ctx.migrate();const outcome=await operation(ctx),unexpected=[...ctx.evidence.statuses].filter(([status])=>Number(status)>=500).reduce((sum,[,count])=>sum+count,0);ctx.equal("no unexpected HTTP 5xx",unexpected,0);return{...outcome,evidence:{...ctx.evidence.finish(),caseEvidence:outcome?.evidence??[]}};});}
async function chromiumExecutable(){for(const candidate of[process.env.CHROMIUM_PATH,"/usr/bin/chromium","/usr/bin/chromium-browser","/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","/Applications/Chromium.app/Contents/MacOS/Chromium"].filter(Boolean)){try{await access(candidate);return candidate;}catch{}}throw new shared.EvaluationInfrastructureError("EVALUATOR_CHROMIUM_UNAVAILABLE","EVALUATOR_CHROMIUM_UNAVAILABLE");}
async function withPage(ctx,api,viewport,operation){let chromium;try{({chromium}=await import("playwright-core"));}catch(cause){throw new shared.EvaluationInfrastructureError("EVALUATOR_PLAYWRIGHT_UNAVAILABLE","EVALUATOR_PLAYWRIGHT_UNAVAILABLE",{cause});}const browser=await chromium.launch({executablePath:await chromiumExecutable(),headless:true,args:["--no-sandbox","--disable-dev-shm-usage"]}),browserContext=await browser.newContext({viewport,baseURL:api.baseUrl}),page=await browserContext.newPage(),errors=[];page.on("pageerror",(error)=>errors.push(error.message));page.on("console",(message)=>{if(message.type()==="error"&&!/Failed to load resource.*4\d\d/iu.test(message.text()))errors.push(message.text());});try{await operation(page);ctx.equal("browser console clean",errors,[]);ctx.equal("browser no horizontal overflow",await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);}finally{await browserContext.close();await browser.close();}}
export const{CandidateResponseError,CommandError,EvaluationInfrastructureError,freePort,runCommand}=shared;
