import assert from "node:assert/strict";
import { canonicalJson, exactKeys } from "../oracles/index.mjs";
import { assertOpenApiContract } from "../oracles/openapi.mjs";
import { PUBLIC_PATHS, acknowledge, assertSnapshotShape, clickVisible, createIncident, createPolicy, defineCase, diagnostic, fillVisible, guardedCase, launchBrowser, legacyAcknowledge, prepare, resolveIncident, resources, semanticError, startReceivers, successful, timeline, visibleText, waitStep } from "./helpers.mjs";

const D01 = defineCase("D-01", async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.policy(receivers.map(({ url }) => url)); const { api, workers } = await prepare(ctx, fixture, { workerCount: 2 }); const openapiResponse = successful(await ctx.request(api.baseUrl, "/openapi.json"), "OpenAPI", [200]); const openapi = openapiResponse.json; assertOpenApiContract(openapi);
  const created = await createIncident(ctx, api.baseUrl, fixture, "live-contract"); const detail = await ctx.request(api.baseUrl, `/api/v1/incidents/${created.incidentId}`); assert.equal(detail.status, 200); assert.equal(canonicalJson(detail.json), canonicalJson(created.incident));
  const list = successful(await ctx.request(api.baseUrl, "/api/v1/incidents?limit=1"), "Incident list", [200]); exactKeys(list.json, ["items", "nextCursor"]); assert.equal(list.json.items[0].incidentId, created.incidentId);
  await waitStep(ctx, api.baseUrl, created.incidentId, 0, "SENT", { processes: workers }); const legacy = await legacyAcknowledge(ctx, api.baseUrl, created.incidentId, fixture.responders[0].responderId); assert.equal(legacy.status, 200); const resolved = await resolveIncident(ctx, api.baseUrl, created.incidentId, fixture.responders[0].responderId); assert.equal(resolved.status, 200); assert.ok((await timeline(ctx, api.baseUrl, created.incidentId)).length >= 4);
  const policy = successful(await ctx.request(api.baseUrl, `/api/v1/services/${fixture.service.serviceId}/escalation-policy`), "policy read", [200]); assert.equal(policy.json.policyId, fixture.policyV1.policyId); const events = successful(await ctx.request(api.baseUrl, `/api/v1/domain-events?aggregateId=${created.incidentId}&afterSequence=0&limit=100`), "event read", [200]); assert.ok(Array.isArray(events.json.items) && events.json.items.length >= 4);
  semanticError(await ctx.request(api.baseUrl, "/api/v1/verification-snapshot", { contractExpectation: "invalid" }), 401, "ADMIN_AUTH_REQUIRED"); semanticError(await ctx.request(api.baseUrl, "/api/v1/incidents?limit=101", { contractExpectation: "invalid" }), 400, "INVALID_REQUEST"); semanticError(await ctx.request(api.baseUrl, `/api/v1/incidents/${ctx.uuid("d01-missing")}`), 404, "NOT_FOUND"); semanticError(await ctx.request(api.baseUrl, "/api/v1/incidents", { method: "POST", headers: { "content-type": "text/plain", "idempotency-key": ctx.key("d01-media") }, raw: "{}", contractExpectation: "invalid" }), 415, "UNSUPPORTED_MEDIA_TYPE"); assertSnapshotShape(await ctx.snapshot(api.baseUrl)); return ctx.pass();
});

const D02 = defineCase("D-02", async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.browser(receivers.map(({ url }) => url)); const { api, page } = await launchBrowser(ctx, fixture, { workers: 2 });
  await fillVisible(page, "serviceId", fixture.service.serviceId); await fillVisible(page, "dedupKey", "browser-v1"); await fillVisible(page, "severity", "HIGH"); await fillVisible(page, "title", "Browser incident"); await fillVisible(page, "details", "Created through production Chromium visible controls"); await clickVisible(page, "create"); await visibleText(page, /OPEN|open/u);
  const snapshot = await ctx.snapshot(api.baseUrl); const incident = resources(snapshot).incidents.find(({ dedupKey }) => dedupKey === "browser-v1"); assert.ok(incident, "browser mutation reached PostgreSQL"); await waitStep(ctx, api.baseUrl, incident.incidentId, 0, "SENT", { timeoutMs: 20_000 }); await page.reload({ waitUntil: "networkidle" }); await visibleText(page, new RegExp(incident.incidentId, "i"));
  await fillVisible(page, "responderId", fixture.responders[0].responderId); await clickVisible(page, "acknowledge"); await visibleText(page, /ACKNOWLEDGED|acknowledged/u); await fillVisible(page, "resolution", "Resolved in browser"); await clickVisible(page, "resolve"); await visibleText(page, /RESOLVED|resolved/u); const persisted = resources(await ctx.snapshot(api.baseUrl)).incidents.find(({ incidentId }) => incidentId === incident.incidentId); assert.equal(persisted.state, "RESOLVED"); return ctx.pass();
});

const D03 = defineCase("D-03", async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.browser(receivers.map(({ url }) => url)); const { api, page } = await launchBrowser(ctx, fixture, { workers: 2 });
  await visibleText(page, /policy|escalation/u); await fillVisible(page, "expectedCurrentVersion", "1"); await fillVisible(page, "responderIds", fixture.responders.map(({ responderId }) => responderId).join(",")); await fillVisible(page, "quorumRequired", "2"); await fillVisible(page, "expireAfterSeconds", "180"); await clickVisible(page, /save|create.*policy/u); await visibleText(page, /quorum|version 2|v2/u);
  await fillVisible(page, "serviceId", fixture.service.serviceId); await fillVisible(page, "dedupKey", "browser-quorum"); await fillVisible(page, "severity", "CRITICAL"); await fillVisible(page, "title", "Browser quorum"); await fillVisible(page, "details", "Group quorum through visible controls"); await clickVisible(page, "create");
  const incident = resources(await ctx.snapshot(api.baseUrl)).incidents.find(({ dedupKey }) => dedupKey === "browser-quorum"); assert.ok(incident); await waitStep(ctx, api.baseUrl, incident.incidentId, 0, "SENT", { timeoutMs: 20_000 }); await page.reload({ waitUntil: "networkidle" }); await visibleText(page, /delivery|notification/u); await fillVisible(page, "stepIndex", "0"); await fillVisible(page, "responderId", fixture.responders[0].responderId); await clickVisible(page, /vote|acknowledge/u); await visibleText(page, /1\s*\/\s*2|1 of 2|OPEN/u); await fillVisible(page, "responderId", fixture.responders[1].responderId); await clickVisible(page, /vote|acknowledge/u); await visibleText(page, /ACKNOWLEDGED|acknowledged/u);
  const final = resources(await ctx.snapshot(api.baseUrl)).incidents.find(({ incidentId }) => incidentId === incident.incidentId); assert.equal(final.state, "ACKNOWLEDGED"); assert.equal(final.acknowledgements.length, 2); return ctx.pass();
});

const D04 = defineCase("D-04", async (ctx) => {
  const fixture = ctx.fixtures.browser(); const { api, page } = await launchBrowser(ctx, fixture, { workers: 0, dispatchers: 0 });
  await visibleText(page, /empty|no incidents|incident/u);
  let delayed = false; await page.route("**/api/v1/incidents*", async (route) => { if (route.request().method() !== "GET") return route.continue(); delayed = true; await new Promise((resolve) => setTimeout(resolve, 500)); await route.continue(); }); const reload = page.reload({ waitUntil: "domcontentloaded" }); await page.waitForTimeout(75); await visibleText(page, /loading|busy|fetching/iu); await reload; await page.waitForLoadState("networkidle"); assert.ok(delayed); await page.unroute("**/api/v1/incidents*");
  const created = await createIncident(ctx, api.baseUrl, fixture, "ui-conflict", { dedupKey: "ui-conflict" }); await fillVisible(page, "serviceId", fixture.service.serviceId); await fillVisible(page, "dedupKey", created.body.dedupKey); await fillVisible(page, "severity", created.body.severity); await fillVisible(page, "title", "different"); await fillVisible(page, "details", created.body.details); await clickVisible(page, "create"); await visibleText(page, /conflict|already|different/u);
  await page.context().setOffline(true); await page.reload().catch(() => {}); await visibleText(page, /offline|retry|network/u); await page.context().setOffline(false); await clickVisible(page, /retry|reload/u); await visibleText(page, /incident/u);
  assert.equal((await ctx.request(api.baseUrl, "/api/v1/verification-snapshot", { contractExpectation: "invalid" })).status, 401); assert.equal((await ctx.snapshot(api.baseUrl)).resources.incidents.length, 1, "UI retries create no duplicate mutation"); return ctx.pass();
});

function luminance(rgb) { const values = rgb.match(/[\d.]+/gu)?.slice(0, 3).map(Number) ?? []; return values.map((value) => { const channel = value / 255; return channel <= 0.03928 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4; }).reduce((sum, value, index) => sum + value * [0.2126, 0.7152, 0.0722][index], 0); }
const D05 = defineCase("D-05", async (ctx) => {
  const fixture = ctx.fixtures.browser(); const { page } = await launchBrowser(ctx, fixture, { workers: 0, dispatchers: 0, viewport: { width: 390, height: 844 } });
  const controls = page.locator("button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]"); const count = await controls.count(); assert.ok(count >= 5, "mobile has reachable primary controls");
  await page.keyboard.press("Tab"); for (let index = 0; index < Math.min(count, 12); index += 1) { const focused = await page.evaluate(() => document.activeElement?.tagName); assert.ok(["A", "BUTTON", "INPUT", "SELECT", "TEXTAREA"].includes(focused), "keyboard focus lands on interactive control"); await page.keyboard.press("Tab"); }
  const unlabeled = await page.locator("input:not([type=hidden]),select,textarea").evaluateAll((elements) => elements.filter((element) => !(element.getAttribute("aria-label") || element.getAttribute("aria-labelledby") || [...(element.labels ?? [])].some(label => label.textContent.trim()))).length); assert.equal(unlabeled, 0, "all form controls have accessible labels");
  const visible = page.locator("body *:visible"); const samples = await visible.evaluateAll((elements) => elements.slice(0, 200).map((element) => { const style = getComputedStyle(element); return { text: element.textContent?.trim(), color: style.color, background: style.backgroundColor, fontSize: Number.parseFloat(style.fontSize), weight: style.fontWeight }; }).filter((item) => item.text && !item.background.endsWith(", 0)")));
  for (const sample of samples) { const lighter = Math.max(luminance(sample.color), luminance(sample.background)), darker = Math.min(luminance(sample.color), luminance(sample.background)); const ratio = (lighter + 0.05) / (darker + 0.05); const large = sample.fontSize >= 24 || (sample.fontSize >= 18.66 && Number(sample.weight) >= 700); assert.ok(ratio >= (large ? 3 : 4.5), `WCAG AA contrast for ${sample.text.slice(0, 40)}`); }
  await fillVisible(page, "dedupKey", ""); await clickVisible(page, "create"); const active = await page.evaluate(() => ({ tag: document.activeElement?.tagName, name: document.activeElement?.getAttribute("name"), invalid: document.activeElement?.getAttribute("aria-invalid") })); assert.ok(active.invalid === "true" || active.name === "dedupKey", "validation focuses invalid field"); return ctx.pass();
});

const D06 = guardedCase("D-06", ["PRODUCTION_BOOT", "STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  const gates = ["test:unit", "test:integration", "test:e2e", "test:concurrency", "test:recovery"];
  for (const gate of gates) {
    const result = await ctx.npm(gate, [], { timeoutMs: 300_000 }); assert.equal(result.exitCode, 0, `${gate} exits zero`); assert.ok(result.stdout.length + result.stderr.length > 0, `${gate} executes nonempty test process`);
    const broken = await ctx.npm(gate, [], { timeoutMs: 60_000, allowFailure: true, env: { NODE_OPTIONS: "--require=/incidentrelay-evaluator/missing-required-module.cjs" } }); assert.notEqual(broken.exitCode, 0, `${gate} is sensitive to a controlled runtime dependency failure`);
  }
  const business = await startReceivers(ctx, 3); const domain = await ctx.receiver({ path: "/events" }); const fixture = ctx.fixtures.browser(business.map(({ url }) => url)); await ctx.migrate(); await ctx.seed(fixture.seed); const apiA = await ctx.startApi(), apiB = await ctx.startApi(); const dispatcher = await ctx.startDispatcher({ webhookUrl: domain.url }); const created = await createIncident(ctx, apiA.baseUrl, fixture, "gate-observer"); const barrier = await ctx.barrier({ hold: (value) => value.point === "worker.claimed" && value.aggregateId === created.incidentId }); const workerA = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const held = await barrier.waitFor((entry) => entry.json?.aggregateId === created.incidentId, { processes: [workerA] }); const workerB = await ctx.startWorker(); barrier.release(held); await waitStep(ctx, apiB.baseUrl, created.incidentId, 0, "SENT", { processes: [workerA, workerB] }); await ctx.waitFor(() => domain.ledger.length > 0, { processes: [dispatcher], label: "independent Domain receiver" }); assert.ok(business.some(({ ledger }) => ledger.length > 0), "independent business receiver crossed"); assertSnapshotShape(await ctx.snapshot(apiA.baseUrl)); return ctx.pass();
});

const D07 = defineCase("D-07", async (ctx) => {
  const business = await startReceivers(ctx, 3); const fixture = ctx.fixtures.browser(business.map(({ url }) => url)); const { api, page } = await launchBrowser(ctx, fixture, { workers: 2 }); const openapi = successful(await ctx.request(api.baseUrl, "/openapi.json"), "OpenAPI", [200]).json; for (const path of PUBLIC_PATHS) assert.ok(openapi.paths[path]);
  const policy = await createPolicy(ctx, api.baseUrl, fixture, "evidence"); const created = await createIncident(ctx, api.baseUrl, fixture, "evidence"); const sent = await waitStep(ctx, api.baseUrl, created.incidentId, 0, "SENT", { timeoutMs: 20_000 }); const step = resources(sent).groupEscalationSteps.find((item) => item.incidentId === created.incidentId && item.stepIndex === 0); await acknowledge(ctx, api.baseUrl, created.incidentId, 0, step.responderIds[0], "evidence-a"); await acknowledge(ctx, api.baseUrl, created.incidentId, 0, step.responderIds[1], "evidence-b"); await page.reload({ waitUntil: "networkidle" }); await visibleText(page, /ACKNOWLEDGED|acknowledged/u); const snapshot = await ctx.snapshot(api.baseUrl); assertSnapshotShape(snapshot); const incident = resources(snapshot).incidents.find((item) => item.incidentId === created.incidentId), selectedWork = snapshot.work.filter((item) => item.aggregateId === created.incidentId && item.kind === "ESCALATION_STEP"); const evidence = { README: Boolean(policy.policy && incident), HTTP: incident.state === "ACKNOWLEDGED", OpenAPI: Boolean(openapi.paths["/api/v1/incidents/{incidentId}/acknowledgements"]), UI: await page.getByText(/ACKNOWLEDGED|acknowledged/u).count() > 0, snapshot: resources(snapshot).incidentAcknowledgements.filter((item) => item.incidentId === created.incidentId).length === 2, Work: selectedWork.length > 0 && selectedWork.every((item) => item.terminal), Event: snapshot.events.some((item) => item.aggregateId === created.incidentId && item.type === "incident.acknowledged"), receivers: business.filter(({ ledger }) => ledger.length > 0).length >= step.quorumRequired }; assert.ok(Object.values(evidence).every(Boolean), `cross-layer requirement evidence ${canonicalJson(evidence)}`);
  ctx.mark("readme.cross-layer.closed", evidence); return ctx.pass({ diagnostics: [diagnostic("IR-D07-SPEC-GAPS", "SPEC-GAP-06")] });
});

export const D_CASES = [D01, D02, D03, D04, D05, D06, D07];
