import { performUsageUi, performWatermarkUi, performCorrectionUi, navigateVisible, clickVisible, expectVisible, accessibleName } from "./ui.mjs";
const { assertUiLoading, assertUiEvidence } = await import(new URL('browser.mjs', process.env.FRONTAL_V2_SHARED_ROOT_URL ?? new URL('../../../../../src/task-evaluator-v2/', import.meta.url)));
import { candidateAssert as assert } from "../lib/execution.mjs";
const { observeExpectedCommandFailure } = await import(new URL('runtime.mjs', process.env.FRONTAL_V2_SHARED_ROOT_URL ?? new URL('../../../../../src/task-evaluator-v2/', import.meta.url)));

import {
  assertDomainEvent, assertPublicError, assertSnapshot, assertStatement, assertUsageBatch, assertUsageEvent,
  exactKeys, semanticRevisionDetail, validateOpenApiResponse,
} from "../oracles/index.mjs";
import {
  blocked, boot, caseResult, correctionBody, expectError, finalize, ingest, launchBrowser, openApi,
  publishedGate, requireStatus, snapshot, statementDetail, statementFor, usageBody, waitSnapshot,
} from "./helpers.mjs";

const d01 = define(
  "D-01", "F-V1-RATING live OpenAPI traffic fixture",
  "Capture successes and published errors from every route family and validate them against independent OpenAPI traversal",
  "Runtime status, headers and JSON satisfy exact declared schemas rather than route presence or candidate self-validation",
  ["production OpenAPI", "public HTTP", "task-local schema validator"],
  async (ctx) => {
    const family = ctx.fixtures.correctionFamily(); const { api } = await boot(ctx, { family }); const documentResponse = await ctx.openApi(api.baseUrl); const document = requireStatus(ctx, documentResponse, 200, "OpenAPI"); openApi(ctx, document); const traffic = [];
    const capture = async (path, method, request) => { const response = await request(); traffic.push({ path, method, response }); return response; };
    await capture("/healthz", "get", () => ctx.request(api.baseUrl, "/healthz")); await capture("/openapi.json", "get", () => ctx.openApi(api.baseUrl)); const snapshotResponse = await capture("/api/v1/verification-snapshot", "get", () => ctx.request(api.baseUrl, "/api/v1/verification-snapshot", { headers: { authorization: `Bearer ${ctx.adminToken}` } })); ctx.assert("snapshot live contract", () => assertSnapshot(snapshotResponse.json));
    const usage = await capture("/api/v1/usage-batches", "post", () => ctx.usageBatch(api.baseUrl, usageBody(family.tenant.tenantId, [ctx.fixtures.event(900)]), { key: ctx.key("d01-usage") })); requireStatus(ctx, usage, 202, "usage success"); ctx.assert("UsageBatch live contract", () => assertUsageBatch(usage.json));
    const usageError = await capture("/api/v1/usage-batches", "post", () => ctx.usageBatch(api.baseUrl, { bad: true }, { key: ctx.key("d01-bad"), contractExpectation:"invalid" })); ctx.assert("usage error live contract", () => assertPublicError(usageError, 400, "UNKNOWN_FIELD")); const wm = await capture("/api/v1/tenants/{tenantId}/watermark", "post", () => ctx.advanceWatermark(api.baseUrl, family.tenant.tenantId, "2035-03-01T00:00:00.000Z", { key: ctx.key("d01-wm") })); requireStatus(ctx, wm, 200, "Watermark success");
    const workers = [await ctx.startWorker(), await ctx.startWorker()]; const finalized = await waitSnapshot(ctx, api.baseUrl, (state) => state.work.length && state.work.every(({ terminal }) => terminal) ? state : undefined, { label: "D01 finalization", processes: workers }); const base = finalized.resources.statements[0];
    const statementList = await capture("/api/v1/statements", "get", () => ctx.statements(api.baseUrl, { limit: "10" })); exactKeys(statementList.json, ["items", "nextCursor"], "Statement collection"); statementList.json.items.forEach(assertStatement); const detailResponse = await capture("/api/v1/statements/{statementId}", "get", () => ctx.statement(api.baseUrl, base.statementId)); ctx.assert("StatementDetail live contract", () => statementDetail(detailResponse.json)); const usageRead = await capture("/api/v1/meters/{meterId}/usage", "get", () => ctx.meterUsage(api.baseUrl, family.meters[0].meterId, { from: "2034-01-01T00:00:00.000Z", to: "2036-01-01T00:00:00.000Z", limit: "10" })); exactKeys(usageRead.json, ["items", "nextCursor"], "usage collection"); usageRead.json.items.forEach(assertUsageEvent); const watermarkRead = await capture("/api/v1/tenants/{tenantId}/watermark", "get", () => ctx.watermark(api.baseUrl, family.tenant.tenantId)); exactKeys(watermarkRead.json, ["tenantId", "watermarkThrough", "openPeriodStarts", "finalizedThrough"], "Watermark read"); const eventRead = await capture("/api/v1/domain-events", "get", () => ctx.domainEvents(api.baseUrl, { limit: "10" })); const eventItems = eventRead.json.items ?? eventRead.json; eventItems.forEach(assertDomainEvent);
    const correction = await capture("/api/v1/correction-batches", "post", () => ctx.correctionBatch(api.baseUrl, correctionBody(family.tenant.tenantId, [family.corrections[0]]), { key: ctx.key("d01-correction") })); requireStatus(ctx, correction, 200, "correction success"); exactKeys(correction.json, ["batchId", "acceptedCorrectionIds", "duplicateCorrectionIds"], "CorrectionBatch response"); const revisionWorker = await ctx.startWorker(); const revisionState = await waitSnapshot(ctx, api.baseUrl, (state) => state.resources.statementRevisions.some(({ state: value }) => value === "FINALIZED") ? state : undefined, { label: "D01 Revision", processes: [revisionWorker] }); const revision = revisionState.resources.statementRevisions[0]; const revisionResponse = await capture("/api/v1/statements/{statementId}/revisions/{revision}", "get", () => ctx.revision(api.baseUrl, revision.statementId, revision.revision)); ctx.assert("revision semantic live contract", () => semanticRevisionDetail(revisionResponse.json));
    for (const item of traffic) ctx.assert(`${item.method.toUpperCase()} ${item.path} live OpenAPI response`, () => validateOpenApiResponse(document, item.path, item.method, item.response));
    return caseResult(ctx, { validatedResponses: traffic.length });
  },
);

const d02 = define(
  "D-02", "F-BROWSER production V1 lifecycle fixture",
  "Use only visible semantic controls to ingest usage, advance Watermark and navigate persisted Statement, usage and event views",
  "Browser-visible state agrees with PostgreSQL-backed public state after worker completion and a full page refresh",
  ["production Chromium", "visible controls", "public UI", "verification snapshot"],
  async (ctx) => {
    const family = ctx.fixtures.browser(); const { api } = await boot(ctx, { family, seed: browserDependencySeed(family, "d02-browser"), build: true }); const { page } = await launchBrowser(ctx, api); const submitted = await performUsageUi(page, family); const submittedEventId = submitted.events[0].eventId; await expectVisible(page, /accepted|queued|usage/i); await performWatermarkUi(page, family.tenant.tenantId, "2035-03-01T00:00:00.000Z"); const workers = [await ctx.startWorker(), await ctx.startWorker()]; const state = await waitSnapshot(ctx, api.baseUrl, (value) => value.resources.statements.some(({ state: status }) => status === "FINALIZED") ? value : undefined, { label: "browser-triggered finalization", processes: workers }); const statement = state.resources.statements.find(({ state: status }) => status === "FINALIZED"); const usageEvent = state.resources.usageEvents.find(({ eventId }) => eventId === submittedEventId); const domainEvent = state.events.find(({ type }) => type === "usage.batch-accepted"); ctx.ok(usageEvent, "UI-submitted Usage Event persisted"); ctx.ok(domainEvent, "UI submission emitted a durable Domain Event");
    await page.reload({ waitUntil: "networkidle" }); await navigateVisible(page, /statement/i); await expectVisible(page, new RegExp(statement.statementId.slice(0, 8), "i")); await navigateVisible(page, /usage/i); await expectVisible(page, new RegExp(submittedEventId, "i")); await navigateVisible(page, /domain/i); await expectVisible(page, new RegExp(domainEvent.eventId.slice(0, 8), "i"));
    return caseResult(ctx, { statementId: statement.statementId, usageEventId: submittedEventId, domainEventId: domainEvent.eventId, lines: statement.lines.length });
  },
);

const d03 = define(
  "D-03", "F-BROWSER pre/post-finalization correction UI fixture",
  "Create corrections from visible UI controls for open and finalized Statements and inspect Revision progress and history",
  "Browser exposes both correction paths and persisted pending/final totals and correction IDs match the snapshot",
  ["production Chromium", "visible controls", "Rating worker", "verification snapshot"],
  async (ctx) => {
    const family = ctx.fixtures.browser(); const { api } = await boot(ctx, { family, build: true }); const { page } = await launchBrowser(ctx, api); const openCorrection = await performCorrectionUi(page, family.tenant.tenantId, family.corrections[2]); await expectVisible(page, /accepted|correction|pending/i); const beforeFinalization = await snapshot(ctx, api.baseUrl); ctx.ok(beforeFinalization.resources.correctionEvents.some(({ correctionId }) => correctionId === openCorrection.correctionId), "pre-finalization UI correction persisted"); ctx.equal(beforeFinalization.resources.statementRevisions.length, 0, "pre-finalization correction does not create a Revision");
    const baseRun = await finalize(ctx, api.baseUrl, { ...family, through: "2035-03-01T00:00:00.000Z" }); for (const worker of baseRun.workers) await ctx.stop(worker); const finalizedBase = statementFor(baseRun.snapshot, family.tenant.tenantId, "2034-12-01T00:00:00.000Z"); const correctedOpenBase = statementFor(baseRun.snapshot, family.tenant.tenantId, "2035-01-01T00:00:00.000Z"); ctx.ok(correctedOpenBase.lines.some(({ eventId, quantity }) => eventId === family.events[1].eventId && quantity === family.events[1].quantity + openCorrection.quantityDelta), "pre-finalization correction folded into base Statement");
    const finalizedCorrection = await performCorrectionUi(page, family.tenant.tenantId, family.corrections[0]); await expectVisible(page, /accepted|correction|pending/i); const worker = await ctx.startWorker(); const revised = await waitSnapshot(ctx, api.baseUrl, (state) => state.resources.statementRevisions.some(({ statementId, state: value }) => statementId === finalizedBase.statementId && value === "FINALIZED") ? state : undefined, { label: "browser correction Revision", processes: [worker] }); await page.reload({ waitUntil: "networkidle" }); await navigateVisible(page, /correction|history/i); await expectVisible(page, new RegExp(finalizedCorrection.correctionId, "i")); await expectVisible(page, new RegExp(openCorrection.correctionId, "i")); await navigateVisible(page, /revision|statement/i); const revision = revised.resources.statementRevisions.find(({ statementId }) => statementId === finalizedBase.statementId); await expectVisible(page, new RegExp(finalizedCorrection.correctionId, "i")); ctx.ok((await page.locator("body").innerText()).includes(String(revision.effectiveTotalMinor)), "UI shows persisted effective total");
    return caseResult(ctx, { statementId: finalizedBase.statementId, preFinalizationCorrectionId: openCorrection.correctionId, finalizedCorrectionId: finalizedCorrection.correctionId, revision: revision.revision });
  },
);

const d04 = define(
  "D-04", "F-BROWSER controlled UI state fixture",
  "Trigger slow, empty, invalid, conflict, offline and permission responses and retry through visible controls",
  "Each state is semantic and recoverable, retry has one mutation effect, and no admin or idempotency secret appears",
  ["production Chromium", "browser network control", "visible controls", "verification snapshot"],
  async (ctx) => {
    const family = ctx.fixtures.browser(); const { api } = await boot(ctx, { family, seed: browserDependencySeed(family, "d04-browser"), build: true }); const { page } = await launchBrowser(ctx, api); await navigateVisible(page, /statement/i); await expectVisible(page, /empty|no\b[^\n]*(?:yet|available|selected|recorded|events?|statements?)|nothing/i);
    await assertUiLoading(page, async () => { if (!await navigateVisible(page, /snapshot/i) && !await navigateVisible(page, /^refresh$/i)) await page.reload(); });
    await performUsageUi(page, family, { invalidQuantity: true }); await expectVisible(page, /invalid|required|quantity/i);
    await page.route("**/api/v1/usage-batches", (route) => route.fulfill({ status: 409, contentType: "application/json", body: JSON.stringify({ error: { code: "EVENT_ID_CONFLICT", message: "conflict", details: {} } }) }), { times: 1 }); await performUsageUi(page, family); await expectVisible(page, /conflict|already exists/i);
    await page.route("**/api/v1/**", (route) => route.fulfill({ status: 401, contentType: "application/json", body: JSON.stringify({ error: { code: "ADMIN_AUTH_REQUIRED", message: "permission", details: {} } }) }), { times: 1 }); await page.reload(); await expectVisible(page, /permission|unauthorized|sign in|access/i); await page.reload({ waitUntil: "networkidle" });
    await page.route("**/api/v1/usage-batches", (route) => route.abort(), { times: 1 }); await performUsageUi(page, family).catch(() => undefined); await expectVisible(page, /offline|network|retry/i); await clickVisible(page, /retry|try again/i); await ctx.waitFor(async () => (await ctx.snapshot(api.baseUrl)).resources.usageEvents.length === 1, { label: "offline retry persisted once" }); const state = await snapshot(ctx, api.baseUrl); ctx.equal(state.resources.usageEvents.length, 1, "retry creates one event"); const bundleAndPage = `${await page.content()}${api.logs}`; ctx.ok(!bundleAndPage.includes(ctx.adminToken), "ADMIN_TOKEN absent from UI and logs");
    return caseResult(ctx, { recoveredUsage: state.resources.usageEvents.length });
  },
);

const d05 = define(
  "D-05", "F-BROWSER keyboard, label, focus and mobile fixture",
  "Complete primary forms with keyboard at desktop and mobile widths and inspect accessible names, focus and contrast",
  "Every primary control is reachable and named, errors receive focus, and critical text satisfies WCAG AA contrast",
  ["production Chromium", "keyboard input", "computed accessibility state"],
  async (ctx) => {
    const family = ctx.fixtures.browser(); const { api } = await boot(ctx, { family, seed: browserDependencySeed(family, "d05-browser"), build: true }); const { page } = await launchBrowser(ctx, api, { viewport: { width: 390, height: 844 } }); const controls = page.locator("button:visible,input:visible,select:visible,textarea:visible,a[href]:visible"); const count = await controls.count(); ctx.ok(count > 0, "mobile UI exposes primary controls"); for (let index = 0; index < count; index += 1) { const control = controls.nth(index); const name = await control.evaluate(accessibleName); ctx.ok(name.trim().length > 0, `visible control ${index} has accessible identity`); }
    await page.keyboard.press("Tab"); ctx.ok(await page.evaluate(() => document.activeElement && document.activeElement !== document.body), "keyboard moves focus"); const submitted = await performUsageUi(page, family, { keyboard: true, eventId: "d05-keyboard-usage" }); await expectVisible(page, /accepted|queued|usage/i); await performWatermarkUi(page, family.tenant.tenantId, "2035-01-01T00:00:00.000Z", { keyboard: true }); const baseWorker = await ctx.startWorker(); const base = await waitSnapshot(ctx, api.baseUrl, (state) => state.resources.statements.some(({ state: value }) => value === "FINALIZED") ? state : undefined, { label: "keyboard V1 finalization", processes: [baseWorker] }); const correction = { ...family.corrections[0], correctionId: "d05-keyboard-correction", sourceEventId: submitted.events[0].eventId }; await performCorrectionUi(page, family.tenant.tenantId, correction, { keyboard: true }); await expectVisible(page, /accepted|correction|pending/i); const revisionWorker = await ctx.startWorker(); await waitSnapshot(ctx, api.baseUrl, (state) => state.resources.statementRevisions.some(({ state: value }) => value === "FINALIZED") ? state : undefined, { label: "keyboard correction Revision", processes: [revisionWorker] });
    await performUsageUi(page, family, { invalidQuantity: true, keyboard: true, eventId: "d05-invalid-usage" }); const error = page.locator("[role='alert'], [aria-invalid='true'], input:invalid,select:invalid,textarea:invalid").first(); await assertUiEvidence(error, "invalid quantity is announced or rejected by native form validation"); const invalid = page.locator("[aria-invalid='true'],input:invalid,select:invalid,textarea:invalid").first(); if (await invalid.count()) ctx.ok(await invalid.evaluate((element) => element === document.activeElement || element.contains(document.activeElement)), "validation focus reaches invalid field"); await page.route("**/api/v1/usage-batches", (route) => route.fulfill({ status: 401, contentType: "application/json", body: JSON.stringify({ error: { code: "ADMIN_AUTH_REQUIRED", message: "permission", details: {} } }) }), { times: 1 }); await performUsageUi(page, family, { keyboard: true, eventId: "d05-permission-usage" }); const permission = page.getByText(/permission|unauthorized|sign in|access/i).or(page.locator("[role='alert']")).first(); await assertUiEvidence(permission, "permission rejection is visible after the observed 401 response"); ctx.ok(await permission.evaluate((element) => element.getAttribute("role") === "alert" || element === document.activeElement || element.contains(document.activeElement)), "permission error is announced or focused"); ctx.ok(base.resources.statements.some(({ state }) => state === "FINALIZED"), "keyboard flow finalized a persisted Statement");
    const ratios = await page.locator("body,button,input,label,[role='alert']").evaluateAll((elements) => elements.filter((element) => { const style = getComputedStyle(element); return style.visibility !== "hidden" && style.display !== "none" && element.getBoundingClientRect().width > 0; }).map((element) => { const parse = (value) => { const values = value.match(/[\d.]+/g)?.map(Number) ?? [0, 0, 0, 0]; return { rgb: values.slice(0, 3), alpha: values[3] ?? 1 }; }; const luminance = (rgb) => { const linear = rgb.map((channel) => { const normalized = channel / 255; return normalized <= 0.03928 ? normalized / 12.92 : ((normalized + 0.055) / 1.055) ** 2.4; }); return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]; }; const style = getComputedStyle(element); let ancestor = element; let background = { rgb: [255, 255, 255], alpha: 1 }; while (ancestor) { const candidate = parse(getComputedStyle(ancestor).backgroundColor); if (candidate.alpha > 0) { background = candidate; break; } ancestor = ancestor.parentElement; } const fg = luminance(parse(style.color).rgb); const bg = luminance(background.rgb); const ratio = (Math.max(fg, bg) + 0.05) / (Math.min(fg, bg) + 0.05); const size = Number.parseFloat(style.fontSize); const bold = Number(style.fontWeight) >= 700; return { ratio, required: size >= 24 || (bold && size >= 18.66) ? 3 : 4.5 }; })); ctx.ok(ratios.every(({ ratio, required }) => Number.isFinite(ratio) && ratio >= required), "critical visible text reaches WCAG AA contrast");
    return caseResult(ctx, { visibleControls: count, measuredContrastNodes: ratios.length });
  },
);

const d06 = define(
  "D-06", "F-EMPTY project-owned public gate fixture",
  "Run every published non-performance test command against isolated PostgreSQL and real process environment",
  "Commands execute non-empty public seams, propagate failures and cover HTTP, Chromium, multi-process and barrier recovery",
  ["public npm test commands", "PostgreSQL", "Chromium", "OS processes"],
  async (ctx) => {
    await ctx.migrate(); await ctx.npm("build", [], { timeoutMs: 300_000 }); const results = [];
    for (const script of ["test:unit", "test:integration", "test:e2e", "test:concurrency", "test:recovery", "test:all"]) { const result = await publishedGate(ctx, script, 900_000); ctx.ok(`${result.stdout}${result.stderr}`.trim().length > 0, `${script} emits real execution evidence`); results.push({ script, durationMs: Math.round(result.durationMs) }); }
    const unreachable = "postgresql://invalid:invalid@127.0.0.1:1/metersettle_unreachable?connect_timeout=1"; const databaseSensitive = await observeExpectedCommandFailure(() => ctx.npm("test:integration", [], { allowFailure: true, timeoutMs: 120_000, env: { DATABASE_URL: unreachable, TEST_DATABASE_URL: unreachable } })); ctx.ok(databaseSensitive.exitCode !== 0, "integration gate fails when its PostgreSQL seam is unreachable"); const browserSensitive = await observeExpectedCommandFailure(() => ctx.npm("test:e2e", [], { allowFailure: true, timeoutMs: 120_000, env: { CHROMIUM_PATH: "/__metersettle_missing_chromium__" } })); ctx.ok(browserSensitive.exitCode !== 0, "E2E gate fails when its Chromium seam is unavailable");
    await ctx.resetDatabase(); const family = ctx.fixtures.recovery(); const { apis } = await boot(ctx, { family, apiCount: 2 }); requireStatus(ctx, await ctx.request(apis[1].baseUrl, "/healthz"), 200, "second production API"); const { page } = await launchBrowser(ctx, apis[0]); ctx.ok((await page.locator("body").innerText()).trim().length > 0, "production Chromium renders the live HTTP UI"); requireStatus(ctx, await ctx.advanceWatermark(apis[0].baseUrl, family.tenant.tenantId, family.through, { key: ctx.key("d06-watermark") }), 200, "D06 Watermark"); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && point === "worker.claimed" }); const crashed = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const claim = await barrier.waitFor(({ json }) => json.point === "worker.claimed", { processes: [crashed] }); await ctx.kill(crashed); await ctx.waitFor(() => claim.disconnected ? claim : undefined, { label: "SIGKILL disconnect at public barrier" }); hold = false; barrier.releaseAll(); await ctx.sleep(3_300); const replacement = await ctx.startWorker(); const recovered = await waitSnapshot(ctx, apis[1].baseUrl, (state) => state.work.some(({ workId, terminal }) => workId === claim.json.workId && terminal) ? state : undefined, { label: "D06 replacement worker recovery", processes: [replacement] }); const receiver = await ctx.receiver(); const dispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url }); const delivery = await ctx.waitFor(() => receiver.ledger.find(({ acknowledged }) => acknowledged), { label: "D06 dispatcher delivery", processes: [dispatcher] }); ctx.assert("D06 delivered public Domain Event", () => assertDomainEvent(delivery.json));
    return caseResult(ctx, { gates: results, sensitivity: { postgresFailure: databaseSensitive.exitCode, chromiumFailure: browserSensitive.exitCode, cleanup: { chromium: { forced: browserSensitive.leakedProcessGroup, complete: browserSensitive.cleanupComplete }, postgres: { forced: databaseSensitive.leakedProcessGroup, complete: databaseSensitive.cleanupComplete } } }, observed: { apiProcesses: apis.length, crashedAt: claim.json.point, recoveredWorkId: claim.json.workId, terminalWork: recovered.work.filter(({ terminal }) => terminal).length, deliveredEventId: delivery.json.eventId } });
  },
);

const d07 = define(
  "D-07", "F-BROWSER cross-layer requirement ledger fixture",
  "Execute a frozen README ledger through HTTP, OpenAPI, visible UI, durable snapshot, Work and Event evidence",
  "A ledger node passes only from observed execution; every applicable layer closes without relying on test names or pass counts",
  ["public HTTP", "OpenAPI", "production Chromium", "verification snapshot", "Work and Events"],
  async (ctx) => {
    const family = ctx.fixtures.browser(); const { api } = await boot(ctx, { family, build: true }); const document = requireStatus(ctx, await ctx.openApi(api.baseUrl), 200, "ledger OpenAPI"); openApi(ctx, document); const usageEvent = { ...family.events[0], eventId: "d07-ledger-usage" }; const usage = await ctx.usageBatch(api.baseUrl, usageBody(family.tenant.tenantId, [usageEvent]), { key: ctx.key("d07-usage") }); requireStatus(ctx, usage, 202, "ledger usage"); const afterUsage = await snapshot(ctx, api.baseUrl); const usageDomainEvent = afterUsage.events.find(({ type }) => type === "usage.batch-accepted"); ctx.ok(usageDomainEvent, "usage ledger has durable Domain Event evidence"); const finalization = await finalize(ctx, api.baseUrl, { ...family, through: "2035-03-01T00:00:00.000Z" }); const state = await snapshot(ctx, api.baseUrl); const statement = state.resources.statements.find(({ state: value }) => value === "FINALIZED"); const { page } = await launchBrowser(ctx, api); await navigateVisible(page, /usage/i); const usagePageText = await page.locator("body").innerText(); await expectVisible(page, new RegExp(usageEvent.eventId, "i")); await navigateVisible(page, /domain/i); await expectVisible(page, new RegExp(usageDomainEvent.eventId.slice(0, 8), "i")); await navigateVisible(page, /statement/i); const statementPageText = await page.locator("body").innerText(); await expectVisible(page, new RegExp(statement.statementId.slice(0, 8), "i")); const status = (condition) => condition ? "passing" : "failed"; const ledger = [
      { requirement: "usage ingestion", nodes: { http: status(usage.status === 202), openapi: status(Boolean(document.paths["/api/v1/usage-batches"]?.post)), ui: status(usagePageText.includes(usageEvent.eventId)), snapshot: status(state.resources.usageEvents.some(({ eventId }) => eventId === usageEvent.eventId)), event: status(state.events.some(({ eventId }) => eventId === usageDomainEvent.eventId)) } },
      { requirement: "Watermark finalization", nodes: { http: status(finalization.response.status === 200), openapi: status(Boolean(document.paths["/api/v1/tenants/{tenantId}/watermark"]?.post)), ui: status(statementPageText.includes(statement.statementId.slice(0, 8))), snapshot: status(statement.state === "FINALIZED"), work: status(state.work.length > 0 && state.work.every(({ terminal }) => terminal)), event: status(state.events.some(({ type }) => type === "statement.finalized")) } },
    ]; ctx.ok(ledger.every(({ nodes }) => Object.values(nodes).every((value) => value === "passing")), "all applicable executed cross-layer nodes pass");
    return caseResult(ctx, { ledger });
  },
);

// UI interactions are shared by all cases in ./ui.mjs.
function browserDependencySeed(family, seedVersion) { return { ...family.seed, seedVersion, usageEvents: [] }; }
function define(id, fixtureFamily, action, oracle, seams, run) { return Object.freeze({ id, taskId: "metersettle", fixtureFamily, action, oracle, seams: Object.freeze(seams), run }); }

export const D_CASES = Object.freeze([d01, d02, d03, d04, d05, d06, d07]);
