import assert from "node:assert/strict";
import { assertEventSequence, assertNotificationIdentity, assertWork, canonicalJson } from "../oracles/index.mjs";
import { acknowledge, createIncident, createPolicy, diagnostic, guardedCase, prepare, resolveIncident, resources, startReceivers, waitStep, waitTerminalWork } from "./helpers.mjs";

async function recoveryFixture(ctx, label, point, options = {}) {
  const receivers = await startReceivers(ctx, 3, options.receiverBehavior ?? (() => ({ status: 204 })));
  const fixture = ctx.fixtures.work(receivers.map(({ url }) => url)); await ctx.migrate(); await ctx.seed(fixture.seed); const api = await ctx.startApi();
  if (options.group) await createPolicy(ctx, api.baseUrl, fixture, `${label}-group`);
  const created = await createIncident(ctx, api.baseUrl, fixture, label);
  const barrier = await ctx.barrier({ hold: (value) => value.point === point && value.aggregateId === created.incidentId });
  const worker = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } });
  const held = await barrier.waitFor((entry) => entry.json?.point === point && entry.json?.aggregateId === created.incidentId, { timeoutMs: 30_000, processes: [worker] });
  return { receivers, fixture, api, created, barrier, worker, held };
}

const C01 = guardedCase("C-01", ["STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.work(receivers.map(({ url }) => url)); const { api } = await prepare(ctx, fixture); const created = await createIncident(ctx, api.baseUrl, fixture, "work-shape");
  const pending = await ctx.snapshot(api.baseUrl); const incidentWork = pending.work.filter((item) => item.aggregateId === created.incidentId); assert.equal(new Set(incidentWork.map(({ kind }) => kind)).size, 2); assert.deepEqual([...new Set(incidentWork.map(({ kind }) => kind))].sort(), ["ESCALATION_STEP", "INCIDENT_EXPIRY"]); assertWork(incidentWork); assert.ok(incidentWork.every(({ state, terminal }) => state === "PENDING" && !terminal));
  const barrier = await ctx.barrier({ hold: (value) => value.point === "worker.claimed" && value.aggregateId === created.incidentId }); const worker = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const held = await barrier.waitFor((entry) => entry.json?.aggregateId === created.incidentId, { processes: [worker] }); const leased = await ctx.snapshot(api.baseUrl); assertWork(leased.work); assert.ok(leased.work.some((item) => item.aggregateId === created.incidentId && item.state === "LEASED")); barrier.release(held);
  const terminal = await waitStep(ctx, api.baseUrl, created.incidentId, 0, "SENT", { processes: [worker] }); assertWork(terminal.work); assert.ok(terminal.work.some((item) => item.aggregateId === created.incidentId && item.kind === "ESCALATION_STEP" && item.terminal)); assert.ok(terminal.work.every((item) => ["PENDING", "LEASED", "SUCCEEDED", "FAILED", "CANCELLED"].includes(item.state))); return ctx.pass();
});

const C02 = guardedCase("C-02", ["STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  const state = await recoveryFixture(ctx, "claimed-kill", "worker.claimed"); const leased = (await ctx.snapshot(state.api.baseUrl)).work.find((item) => item.aggregateId === state.created.incidentId && item.state === "LEASED"); assert.ok(leased); await ctx.kill(state.worker); state.barrier.release(state.held); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacement = await ctx.startWorker();
  const recovered = await waitStep(ctx, state.api.baseUrl, state.created.incidentId, 0, "SENT", { processes: [replacement], timeoutMs: 20_000 }); const work = recovered.work.find((item) => item.workId === leased.workId); assert.ok(work.terminal && work.attempt > leased.attempt, "replacement reclaims with increasing attempt"); assert.equal(state.receivers[0].ledger.length, 1, "claimed death has one eventual business effect"); return ctx.pass();
});

const C03 = guardedCase("C-03", ["STALE_WORK_OR_LOST_DELIVERY", "EVENT_TRANSACTIONALITY"], async (ctx) => {
  const state = await recoveryFixture(ctx, "effect-kill", "worker.effect-complete"); assert.equal(state.receivers[0].ledger.length, 1, "receiver persisted first notification before held ACK handling"); const first = state.receivers[0].ledger[0]; await ctx.kill(state.worker); state.barrier.release(state.held); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacement = await ctx.startWorker(); const recovered = await waitStep(ctx, state.api.baseUrl, state.created.incidentId, 0, "SENT", { processes: [replacement], timeoutMs: 20_000 });
  assert.ok(state.receivers[0].ledger.length >= 2, "unknown business ACK retried"); assert.ok(state.receivers[0].ledger.every((entry) => entry.headers["x-incidentrelay-notification-id"] === first.headers["x-incidentrelay-notification-id"] && canonicalJson(entry.json) === canonicalJson(first.json)), "retry preserves notification identity and body"); const deliveries = resources(recovered).notificationDeliveries.filter((item) => item.incidentId === state.created.incidentId); assertNotificationIdentity(deliveries); assert.equal(deliveries.filter(({ state }) => state === "DELIVERED").length, 1); assert.equal(recovered.events.filter((item) => item.aggregateId === state.created.incidentId && item.type === "escalation.sent").length, 1); return ctx.pass();
});

const C04 = guardedCase("C-04", ["STALE_WORK_OR_LOST_DELIVERY", "EVENT_TRANSACTIONALITY"], async (ctx) => {
  const state = await recoveryFixture(ctx, "before-commit", "worker.before-commit", { group: true }); const before = await ctx.snapshot(state.api.baseUrl); const stepBefore = resources(before).groupEscalationSteps.find((item) => item.incidentId === state.created.incidentId && item.stepIndex === 0); assert.equal(stepBefore.state, "PENDING", "held before commit exposes no partial group transition"); const eventCount = before.events.filter((item) => item.aggregateId === state.created.incidentId).length;
  await ctx.kill(state.worker); state.barrier.release(state.held); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacement = await ctx.startWorker(); const after = await waitStep(ctx, state.api.baseUrl, state.created.incidentId, 0, "SENT", { processes: [replacement], timeoutMs: 20_000 }); const step = resources(after).groupEscalationSteps.find((item) => item.incidentId === state.created.incidentId && item.stepIndex === 0); assert.ok(step.notifications.filter(({ state }) => state === "DELIVERED").length >= step.quorumRequired); assert.equal(after.events.filter((item) => item.aggregateId === state.created.incidentId && item.type === "escalation.sent").length, 1); assert.ok(after.events.filter((item) => item.aggregateId === state.created.incidentId).length > eventCount); return ctx.pass();
});

const C05 = guardedCase("C-05", ["STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  const state = await recoveryFixture(ctx, "stale-fence", "worker.claimed"); const leased = (await ctx.snapshot(state.api.baseUrl)).work.find((item) => item.aggregateId === state.created.incidentId && item.state === "LEASED"); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacement = await ctx.startWorker(); const recovered = await waitStep(ctx, state.api.baseUrl, state.created.incidentId, 0, "SENT", { processes: [replacement], timeoutMs: 20_000 }); const beforeRelease = resources(recovered).notificationDeliveries.find((item) => item.incidentId === state.created.incidentId && item.stepIndex === 0); const eventCount = recovered.events.length; state.barrier.release(state.held); await new Promise((resolve) => setTimeout(resolve, 300)); const afterRelease = await ctx.snapshot(state.api.baseUrl); const afterDelivery = resources(afterRelease).notificationDeliveries.find((item) => item.notificationId === beforeRelease.notificationId); assert.deepEqual(afterDelivery, beforeRelease, "expired lease cannot overwrite winning delivery"); assert.equal(afterRelease.events.length, eventCount, "expired lease cannot emit event"); const finalWork = afterRelease.work.find((item) => item.workId === leased.workId); assert.ok(finalWork.terminal && finalWork.attempt > leased.attempt); await ctx.kill(state.worker); return ctx.pass();
});

const C06 = guardedCase("C-06", ["INCIDENT_TERMINAL_AUTHORITY", "STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.work(receivers.map(({ url }) => url)); await ctx.migrate(); await ctx.seed(fixture.seed); const api = await ctx.startApi(); await createPolicy(ctx, api.baseUrl, fixture, "terminal-work", { steps: [{ stepIndex: 0, delaySeconds: 0, responderIds: [fixture.responders[0].responderId], quorumRequired: 1 }, { stepIndex: 1, delaySeconds: 1, responderIds: [fixture.responders[1].responderId], quorumRequired: 1 }], expireAfterSeconds: 60 }); const created = await createIncident(ctx, api.baseUrl, fixture, "terminal-work"); const initial = await ctx.startWorker(); await waitStep(ctx, api.baseUrl, created.incidentId, 0, "SENT", { processes: [initial] }); await ctx.stop(initial); await new Promise((resolve) => setTimeout(resolve, 1_100));
  const barrier = await ctx.barrier({ hold: (value) => value.point === "worker.claimed" && value.aggregateId === created.incidentId }); const late = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const held = await barrier.waitFor((entry) => entry.json?.aggregateId === created.incidentId, { processes: [late] }); await acknowledge(ctx, api.baseUrl, created.incidentId, 0, fixture.responders[0].responderId, "close-work"); await resolveIncident(ctx, api.baseUrl, created.incidentId, fixture.responders[0].responderId, "close-work"); const receiverCount = receivers.reduce((sum, item) => sum + item.ledger.length, 0); barrier.release(held); await new Promise((resolve) => setTimeout(resolve, 300)); const snapshot = await waitTerminalWork(ctx, api.baseUrl, created.incidentId, { processes: [late] }); assert.ok([...resources(snapshot).groupEscalationSteps, ...resources(snapshot).escalationSteps].filter((item) => item.incidentId === created.incidentId && item.stepIndex > 0).every((item) => item.state === "SUPERSEDED")); assert.ok(snapshot.work.filter((item) => item.aggregateId === created.incidentId).every((item) => item.terminal)); assert.equal(receivers.reduce((sum, item) => sum + item.ledger.length, 0), receiverCount, "late worker cannot send after terminal"); return ctx.pass();
});

const C07 = guardedCase("C-07", ["EVENT_TRANSACTIONALITY"], async (ctx) => {
  let outcome = 0; const domain = await ctx.receiver({ path: "/events", behavior: () => outcome++ === 0 ? { status: 500 } : outcome === 2 ? { disconnect: true } : { status: 204 } }); const fixture = ctx.fixtures.event(); await ctx.migrate(); await ctx.seed(fixture.seed); const api = await ctx.startApi(); const created = await createIncident(ctx, api.baseUrl, fixture, "domain-unknown"); const barrier = await ctx.barrier({ hold: (value) => value.point === "dispatcher.response-received" && value.aggregateId === created.incidentId }); const dispatcher = await ctx.startDispatcher({ webhookUrl: domain.url, env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const held = await barrier.waitFor((entry) => entry.json?.aggregateId === created.incidentId, { timeoutMs: 20_000, processes: [dispatcher] }); await ctx.kill(dispatcher); barrier.release(held); const replacement = await ctx.startDispatcher({ webhookUrl: domain.url }); await ctx.waitFor(() => domain.ledger.some(({ acknowledged, responseStatus }) => acknowledged && responseStatus >= 200 && responseStatus < 300), { timeoutMs: 30_000, processes: [replacement], label: "Domain Event ACK after unknown response" }); const matching = domain.ledger.filter((entry) => entry.headers["x-incidentrelay-event-id"] === domain.ledger[0].headers["x-incidentrelay-event-id"]); assert.ok(matching.length >= 2); assert.ok(matching.every((entry) => canonicalJson(entry.json) === canonicalJson(matching[0].json))); assert.equal(new Set(matching.map((entry) => entry.headers["x-incidentrelay-event-type"])).size, 1); assert.notEqual(matching[0].headers["x-incidentrelay-event-id"], matching[0].headers["x-incidentrelay-notification-id"]); return ctx.pass();
});

const C08 = guardedCase("C-08", ["EVENT_TRANSACTIONALITY", "QUORUM_AUTHORITY", "STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  const state = await recoveryFixture(ctx, "quorum-recovery", "worker.before-commit", { group: true }); const rollbackBefore = await ctx.snapshot(state.api.baseUrl); const badAck = await acknowledge(ctx, state.api.baseUrl, state.created.incidentId, 0, ctx.uuid("outsider"), "rollback", { expectSuccess: false }); assert.equal(badAck.status, 409); const rollbackAfter = await ctx.snapshot(state.api.baseUrl); assert.equal(rollbackAfter.events.length, rollbackBefore.events.length, "failed acknowledgement emits no event");
  await ctx.kill(state.worker); state.barrier.release(state.held); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacement = await ctx.startWorker(); const sent = await waitStep(ctx, state.api.baseUrl, state.created.incidentId, 0, "SENT", { processes: [replacement], timeoutMs: 20_000 }); const step = resources(sent).groupEscalationSteps.find((item) => item.incidentId === state.created.incidentId && item.stepIndex === 0); await acknowledge(ctx, state.api.baseUrl, state.created.incidentId, 0, step.responderIds[0], "first-vote"); await acknowledge(ctx, state.api.baseUrl, state.created.incidentId, 0, step.responderIds[1], "winner-vote"); const final = await ctx.snapshot(state.api.baseUrl); const incident = resources(final).incidents.find((item) => item.incidentId === state.created.incidentId); assert.equal(incident.state, "ACKNOWLEDGED"); assert.ok(resources(final).groupEscalationSteps.filter((item) => item.incidentId === state.created.incidentId && item.stepIndex !== incident.acknowledgementStepIndex).every((item) => item.state === "SUPERSEDED")); assert.ok(final.work.filter((item) => item.aggregateId === state.created.incidentId && item.kind === "ESCALATION_STEP").every((item) => item.terminal)); assertEventSequence(final.events.filter((item) => item.aggregateId === state.created.incidentId)); assert.equal(JSON.stringify(final).includes(ctx.barrierToken), false, "snapshot omits fencing secret");
  return ctx.pass({ diagnostics: [diagnostic("IR-C08-ACK-EVENT-TYPE", "SPEC-GAP-04")] });
});

export const C_CASES = [C01, C02, C03, C04, C05, C06, C07, C08];
