import assert from "node:assert/strict";
import { CaseExcluded } from "../lib/execution.mjs";
import { assertEventSequence, assertNotificationIdentity, assertOneActiveDedup, assertWork, byteCompare, canonicalJson } from "../oracles/index.mjs";
import { assertLoad, createIncident, fixedDurationLoad, guardedCase, legacyAcknowledge, resources, resolveIncident, startReceivers, waitSnapshot, waitStep } from "./helpers.mjs";

function recordSet(items) { return new Set(items.map((item) => canonicalJson(item))); }
function assertPreserved(actual, expected, label) { const records = recordSet(actual); for (const item of expected) assert.ok(records.has(canonicalJson(item)), `${label} record changed during migration`); }

const E01 = guardedCase("E-01", ["MIGRATION_COMPATIBILITY"], async (ctx) => {
  if (!ctx.v1Workspace) throw new CaseExcluded("missing_v1_checkpoint");
  const receivers = await startReceivers(ctx, 3); const fixture = ctx.fixtures.migration(receivers.map(({ url }) => url)); const v1 = ctx.forWorkspace(ctx.v1Workspace); await v1.migrate(); await v1.seed(fixture.seed); const apiV1 = await v1.startApi(), workerV1 = await v1.startWorker();
  const acknowledged = await createIncident(ctx, apiV1.baseUrl, fixture, "v1-ack"); await waitStep(ctx, apiV1.baseUrl, acknowledged.incidentId, 0, "SENT", { processes: [workerV1] }); const ackResponse = await legacyAcknowledge(ctx, apiV1.baseUrl, acknowledged.incidentId, fixture.responders[0].responderId, "v1-ack");
  const resolved = await createIncident(ctx, apiV1.baseUrl, fixture, "v1-resolved"); await waitStep(ctx, apiV1.baseUrl, resolved.incidentId, 0, "SENT", { processes: [workerV1] }); await legacyAcknowledge(ctx, apiV1.baseUrl, resolved.incidentId, fixture.responders[0].responderId, "v1-resolved"); await resolveIncident(ctx, apiV1.baseUrl, resolved.incidentId, fixture.responders[0].responderId, "v1-resolved");
  await ctx.stop(workerV1); const open = await createIncident(ctx, apiV1.baseUrl, fixture, "v1-open"); const before = await ctx.snapshot(apiV1.baseUrl); const beforeEvents = [...before.events]; const beforeIncidents = [...resources(before).incidents]; const winningTimes = new Map(beforeIncidents.filter(({ state }) => ["ACKNOWLEDGED", "RESOLVED"].includes(state)).map((item) => [item.incidentId, item.acknowledgedAt])); await ctx.stop(apiV1);
  await ctx.migrate(); const apiFinal = await ctx.startApi(); const after = await ctx.snapshot(apiFinal.baseUrl); assertPreserved(after.events, beforeEvents, "Domain Event"); for (const incident of beforeIncidents) { const migrated = resources(after).incidents.find((item) => item.incidentId === incident.incidentId); assert.ok(migrated); for (const [key, value] of Object.entries(incident)) assert.deepEqual(migrated[key], value, `${incident.incidentId} preserves V1 ${key}`); const records = resources(after).incidentAcknowledgements.filter((item) => item.incidentId === incident.incidentId); assert.equal(records.length, winningTimes.has(incident.incidentId) ? 1 : 0, "only V1 winners synthesize one acknowledgement"); if (records.length) assert.equal(records[0].acknowledgedAt, winningTimes.get(incident.incidentId)); }
  const policies = resources(after).escalationPolicies; assert.ok(policies.every((policy) => policy.steps.every((step) => Array.isArray(step.responderIds) && step.responderIds.length === 1 && step.quorumRequired === 1)), "V1 policies migrate to singleton quorum"); const replay = await ctx.mutate(apiFinal.baseUrl, `/api/v1/incidents/${acknowledged.incidentId}/acknowledge`, ctx.key("legacy-ack:v1-ack"), { responderId: fixture.responders[0].responderId }); assert.equal(replay.status, ackResponse.status); assert.equal(replay.text, ackResponse.text, "saved legacy acknowledgement replay preserved"); assert.equal((await ctx.request(apiFinal.baseUrl, `/api/v1/incidents/${open.incidentId}`)).status, 200); await ctx.migrate(); assert.deepEqual(resources(await ctx.snapshot(apiFinal.baseUrl)).incidentAcknowledgements, resources(after).incidentAcknowledgements, "repeat FINAL migration stable"); return ctx.pass();
});

const E02 = guardedCase("E-02", ["MIGRATION_COMPATIBILITY", "IDEMPOTENCY_CORRECTNESS", "STALE_WORK_OR_LOST_DELIVERY"], async (ctx) => {
  if (!ctx.v1Workspace) throw new CaseExcluded("missing_v1_checkpoint");
  let release = false; const receiver = await ctx.receiver({ path: "/notifications", behavior: () => release ? { status: 204 } : { status: 500 } }); const fixture = ctx.fixtures.migration([receiver.url, receiver.url, receiver.url]); const v1 = ctx.forWorkspace(ctx.v1Workspace); await v1.migrate(); await v1.seed(fixture.seed); const apiV1 = await v1.startApi(); const shield = await ctx.responseShield(apiV1.baseUrl); const body = fixture.incidentBody("saved-replay"), key = fixture.savedReplayKey; shield.dropNextMutation(); await assert.rejects(ctx.mutate(shield.baseUrl, "/api/v1/incidents", key, body)); const captured = shield.captures.find(({ dropped }) => dropped); assert.equal(captured.response.status, 201);
  const workerV1 = await v1.startWorker(); await ctx.waitFor(() => receiver.ledger.length >= 1, { timeoutMs: 15_000, processes: [workerV1], label: "V1 failed notification attempt" }); const before = await ctx.snapshot(apiV1.baseUrl); const incidentId = JSON.parse(captured.response.body).incidentId; const deliveryBefore = resources(before).notificationDeliveries.find((item) => item.incidentId === incidentId && item.stepIndex === 0); assert.ok(deliveryBefore && deliveryBefore.attemptCount >= 1); await ctx.kill(workerV1); await ctx.stop(apiV1);
  await ctx.migrate(); const apiFinal = await ctx.startApi(); const replay = await ctx.mutate(apiFinal.baseUrl, "/api/v1/incidents", key, body); assert.equal(replay.status, captured.response.status); assert.equal(replay.text, captured.response.body, "saved V1 response exact after migration"); let after = await ctx.snapshot(apiFinal.baseUrl); const deliveryMigrated = resources(after).notificationDeliveries.find((item) => item.notificationId === deliveryBefore.notificationId); assert.deepEqual(deliveryMigrated, deliveryBefore, "pending delivery identity body URL and attempt preserved"); release = true; await new Promise((resolve) => setTimeout(resolve, 3_200)); const workerFinal = await ctx.startWorker(); after = await waitStep(ctx, apiFinal.baseUrl, incidentId, 0, "SENT", { processes: [workerFinal], timeoutMs: 20_000 }); const finalDelivery = resources(after).notificationDeliveries.find((item) => item.notificationId === deliveryBefore.notificationId); assert.equal(finalDelivery.state, "DELIVERED"); assert.ok(receiver.ledger.every((entry) => entry.headers["x-incidentrelay-notification-id"] === deliveryBefore.notificationId && canonicalJson(entry.json) === canonicalJson(deliveryBefore.body))); return ctx.pass();
});

const E03 = guardedCase("E-03", ["MIGRATION_COMPATIBILITY", "STALE_WORK_OR_LOST_DELIVERY", "EVENT_TRANSACTIONALITY"], async (ctx) => {
  if (!ctx.v1Workspace) throw new CaseExcluded("missing_v1_checkpoint");
  const business = await startReceivers(ctx, 3); const domain = await ctx.receiver({ path: "/events" }); const fixture = ctx.fixtures.migration(business.map(({ url }) => url)); const v1 = ctx.forWorkspace(ctx.v1Workspace); await v1.migrate(); await v1.seed(fixture.seed); const apiV1 = await v1.startApi(); const created = await createIncident(ctx, apiV1.baseUrl, fixture, "continuity"); const barrier = await ctx.barrier({ hold: (value) => value.aggregateId === created.incidentId && ["worker.claimed", "dispatcher.response-received"].includes(value.point) }); const workerV1 = await v1.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const dispatcherV1 = await v1.startDispatcher({ webhookUrl: domain.url, env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const workerHeld = await barrier.waitFor((entry) => entry.json?.processRole === "worker", { timeoutMs: 20_000, processes: [workerV1] }); const dispatcherHeld = await barrier.waitFor((entry) => entry.json?.processRole === "dispatcher", { timeoutMs: 20_000, processes: [dispatcherV1] }); const before = await ctx.snapshot(apiV1.baseUrl); const leased = before.work.find((item) => item.aggregateId === created.incidentId && item.state === "LEASED"); assert.ok(leased); const eventBefore = before.events.find((item) => item.aggregateId === created.incidentId); assert.ok(eventBefore); await ctx.kill(workerV1); await ctx.kill(dispatcherV1); barrier.release(workerHeld); barrier.release(dispatcherHeld); await ctx.stop(apiV1);
  await ctx.migrate(); const apiFinal = await ctx.startApi(); const migrated = await ctx.snapshot(apiFinal.baseUrl); assertPreserved(migrated.work, before.work, "Work"); assertPreserved(migrated.events, before.events, "Event"); await new Promise((resolve) => setTimeout(resolve, 3_200)); const workerFinal = await ctx.startWorker(), dispatcherFinal = await ctx.startDispatcher({ webhookUrl: domain.url }); const recovered = await waitStep(ctx, apiFinal.baseUrl, created.incidentId, 0, "SENT", { processes: [workerFinal], timeoutMs: 20_000 }); await ctx.waitFor(() => domain.ledger.some((entry) => entry.headers["x-incidentrelay-event-id"] === eventBefore.eventId && entry.acknowledged), { timeoutMs: 20_000, processes: [dispatcherFinal], label: "migrated Event ACK" }); const finalWork = recovered.work.find((item) => item.workId === leased.workId); assert.ok(finalWork.terminal && finalWork.attempt > leased.attempt); assert.equal(recovered.events.filter((item) => item.eventId === eventBefore.eventId).length, 1); assertEventSequence(recovered.events.filter((item) => item.aggregateId === created.incidentId)); return ctx.pass();
});

function performanceSeed(ctx, receiverUrl, asOf) {
  const profile = ctx.fixtures.performance(); const responders = [], services = [], escalationPolicies = [], incidents = [], escalationSteps = [], notificationDeliveries = [];
  const responderGroups = Array.from({ length: profile.serviceCount }, (_, serviceIndex) => Array.from({ length: 10 }, (_, localIndex) => { const responder = { responderId: ctx.uuid(`perf-responder:${serviceIndex}:${localIndex}`), name: `Responder ${serviceIndex}-${localIndex}`, deliveryUrl: receiverUrl }; responders.push(responder); return responder; }));
  const policyByService = Array.from({ length: profile.serviceCount }, (_, serviceIndex) => { const policy = { policyId: ctx.uuid(`perf-policy:${serviceIndex}`), version: 1, steps: responderGroups[serviceIndex].slice(0, 3).map(({ responderId }, stepIndex) => ({ stepIndex, delaySeconds: stepIndex * 10, responderId })), expireAfterSeconds: 7_200 }; escalationPolicies.push(policy); const service = { serviceId: ctx.uuid(`perf-service:${serviceIndex}`), name: `Service ${serviceIndex}`, currentPolicyId: policy.policyId, currentPolicyVersion: 1 }; services.push(service); return policy; });
  const openCreatedAt = new Date(Date.parse(asOf) - 60_000).toISOString(), terminalCreatedAt = new Date(Date.parse(asOf) - 10_800_000).toISOString();
  for (let incidentIndex = 0; incidentIndex < profile.incidentCount; incidentIndex += 1) {
    const serviceIndex = Math.floor(incidentIndex / 100), service = services[serviceIndex], policy = policyByService[serviceIndex], open = incidentIndex < 1_000, createdAt = open ? openCreatedAt : terminalCreatedAt, expiresAt = new Date(Date.parse(createdAt) + policy.expireAfterSeconds * 1_000).toISOString(); const incidentId = ctx.uuid(`perf-incident:${incidentIndex}`);
    incidents.push({ incidentId, serviceId: service.serviceId, dedupKey: `perf-seed-${incidentIndex}`, severity: ["LOW", "MEDIUM", "HIGH", "CRITICAL"][incidentIndex % 4], title: "perf incident", details: "fixed 64-byte ASCII detail", state: open ? "OPEN" : "EXPIRED", policyId: policy.policyId, policyVersion: 1, createdAt, expiresAt, nextEscalationAt: open ? createdAt : null, acknowledgedBy: null, acknowledgedAt: null, resolvedAt: null, sequence: 1 });
    for (const policyStep of policy.steps) { const dueAt = new Date(Date.parse(createdAt) + policyStep.delaySeconds * 1_000).toISOString(), notificationId = ctx.uuid(`perf-notification:${incidentIndex}:${policyStep.stepIndex}`), state = open ? "PENDING" : "SUPERSEDED"; const body = { notificationId, incidentId, serviceId: service.serviceId, stepIndex: policyStep.stepIndex, responderId: policyStep.responderId, severity: incidents.at(-1).severity, title: "perf incident", details: "fixed 64-byte ASCII detail" }; escalationSteps.push({ incidentId, stepIndex: policyStep.stepIndex, responderId: policyStep.responderId, dueAt, state, notificationId, successfulDeliveryAt: null }); notificationDeliveries.push({ notificationId, incidentId, stepIndex: policyStep.stepIndex, responderId: policyStep.responderId, deliveryUrl: receiverUrl, body, state, attemptCount: 0, nextAttemptAt: open ? dueAt : null, successfulDeliveryAt: null }); }
  }
  assert.deepEqual([services.length, responders.length, escalationPolicies.length, incidents.length, escalationSteps.length], [1_000, 10_000, 1_000, 100_000, 300_000]); assert.equal(escalationSteps.filter(({ state, dueAt }) => state === "PENDING" && Date.parse(dueAt) <= Date.parse(asOf)).length, 3_000);
  return { schemaVersion: 1, seedVersion: "perf-v1", services, responders, escalationPolicies, incidents, escalationSteps, notificationDeliveries };
}

async function installPerformanceSeed(ctx, receiverUrl) { await ctx.migrate(); const api = await ctx.startApi(); const asOf = (await ctx.snapshot(api.baseUrl)).asOf; await ctx.stop(api); const seed = performanceSeed(ctx, receiverUrl, asOf); await ctx.seed(seed, { timeoutMs: 300_000 }); return seed; }

const E04 = guardedCase("E-04", ["INCIDENT_TERMINAL_AUTHORITY", "IDEMPOTENCY_CORRECTNESS"], async (ctx) => {
  const receiver = await ctx.receiver({ path: "/notifications" }); const seed = await installPerformanceSeed(ctx, receiver.url); let apis = await Promise.all([ctx.startApi(), ctx.startApi()]); const serviceIds = seed.services.map(({ serviceId }) => serviceId).sort(byteCompare); const known = new Set(); let warmOrdinal = 0, measuredOrdinal = 0;
  const ingest = await fixedDurationLoad(ctx, { warmupMs: 10_000, measureMs: 60_000, concurrency: 64, request: (_ordinal, measured) => { const phase = measured ? "measure" : "warm", ordinal = measured ? measuredOrdinal++ : warmOrdinal++, block = Math.floor(ordinal / 10), slot = ordinal % 10, semanticOrdinal = slot === 9 ? ordinal - 1 : ordinal, serviceId = serviceIds[semanticOrdinal % serviceIds.length], dedupKey = `perf-${phase}-${block}-${slot === 9 ? 8 : slot}`, severity = ["LOW", "MEDIUM", "HIGH", "CRITICAL"][semanticOrdinal % 4], body = { serviceId, dedupKey, severity, title: "perf incident", details: "fixed 64-byte ASCII detail" }; known.add(`${serviceId}\0${dedupKey}`); return ctx.mutate(apis[ordinal % 2].baseUrl, "/api/v1/incidents", ctx.key(`perf-ingest:${phase}:${ordinal}`), body); }, validate: (response) => { assert.ok([200, 201].includes(response.status)); assert.equal(response.json.state, "OPEN"); } }); assertLoad(ingest, { minimumThroughput: 200, maximumP95: 250, acceptedStatuses: [200, 201] }); let after = await ctx.snapshot(apis[0].baseUrl, { timeoutMs: 120_000 }); assertOneActiveDedup(resources(after).incidents); assert.equal(resources(after).incidents.filter(({ dedupKey }) => dedupKey.startsWith("perf-warm-") || dedupKey.startsWith("perf-measure-")).length, known.size, "every ten requests create exactly nine Incidents");
  await ctx.resetDatabase(); const receiver2 = await ctx.receiver({ path: "/notifications" }); const readSeed = await installPerformanceSeed(ctx, receiver2.url); apis = await Promise.all([ctx.startApi(), ctx.startApi()]); const incidentIds = readSeed.incidents.map(({ incidentId }) => incidentId).sort(byteCompare); const beforeRead = await ctx.snapshot(apis[0].baseUrl, { timeoutMs: 120_000 }); const timelineLoad = await fixedDurationLoad(ctx, { warmupMs: 10_000, measureMs: 60_000, concurrency: 64, request: (ordinal) => ctx.request(apis[ordinal % 2].baseUrl, `/api/v1/incidents/${incidentIds[ordinal % incidentIds.length]}/timeline`), validate: (response) => { assert.equal(response.status, 200); assert.ok(Array.isArray(response.json)); response.json.forEach((item, index) => assert.equal(item.sequence, index + 1)); } }); assertLoad(timelineLoad, { minimumThroughput: 250, maximumP95: 150, acceptedStatuses: [200] }); const afterRead = await ctx.snapshot(apis[0].baseUrl, { timeoutMs: 120_000 }); assert.equal(canonicalJson(resources(afterRead)), canonicalJson(resources(beforeRead)), "timeline reads do not alter escalation state"); ctx.mark("perf.http.fixed", { ingest, timeline: timelineLoad }); return ctx.pass();
});

const E05 = guardedCase("E-05", ["STALE_WORK_OR_LOST_DELIVERY", "EVENT_TRANSACTIONALITY"], async (ctx) => {
  const receiver = await ctx.receiver({ path: "/notifications", behavior: () => ({ status: 204 }) }); const seed = await installPerformanceSeed(ctx, receiver.url); const api = await ctx.startApi(); const dueIncidentIds = new Set(seed.incidents.slice(0, 1_000).map(({ incidentId }) => incidentId)); const barrier = await ctx.barrier({ hold: (value) => value.point === "worker.claimed" && dueIncidentIds.has(value.aggregateId) }); const victims = await Promise.all(Array.from({ length: 2 }, () => ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }))); await ctx.waitFor(() => { const claims = barrier.ledger.filter((entry) => entry.json?.point === "worker.claimed" && dueIncidentIds.has(entry.json.aggregateId)); return new Set(claims.map((entry) => entry.json.workId)).size >= 2; }, { timeoutMs: 30_000, processes: victims, label: "two distinct due claims" }); const leased = (await ctx.snapshot(api.baseUrl, { timeoutMs: 120_000 })).work.filter((item) => item.state === "LEASED" && dueIncidentIds.has(item.aggregateId)); assert.ok(leased.length >= 2); await Promise.all(victims.map((worker) => ctx.kill(worker))); barrier.releaseAll(); await new Promise((resolve) => setTimeout(resolve, 3_200)); const started = performance.now(); const replacements = await Promise.all(Array.from({ length: 2 }, () => ctx.startWorker())); const final = await waitSnapshot(ctx, api.baseUrl, (snapshot) => { const steps = [...resources(snapshot).escalationSteps, ...(resources(snapshot).groupEscalationSteps ?? [])].filter((item) => dueIncidentIds.has(item.incidentId)); return steps.length === 3_000 && steps.every((item) => item.state === "SENT") && snapshot.work.filter((item) => item.kind === "ESCALATION_STEP").every((item) => item.terminal); }, { timeoutMs: 45_000, intervalMs: 1_000, processes: replacements, label: "3000 due Step recovery drain" }); const recoveryMs = performance.now() - started; assert.ok(recoveryMs <= 45_000); const deliveries = resources(final).notificationDeliveries.filter((item) => dueIncidentIds.has(item.incidentId)); assert.equal(deliveries.length, 3_000); assert.ok(deliveries.every((item) => item.state === "DELIVERED")); assertNotificationIdentity(deliveries); assert.equal(receiver.ledger.length, 3_000, "one exact successful business notification per due Step"); assertWork(final.work); assertEventSequence(final.events); assert.equal(replacements.some(({ stderr }) => /error|uncaught|fatal/iu.test(stderr)), false, "replacement workers log no error"); const exposed = `${JSON.stringify(final)}\n${replacements.map(({ logs }) => logs).join("\n")}`; assert.equal(exposed.includes(ctx.adminToken) || exposed.includes(ctx.barrierToken), false, "snapshot and logs omit secrets"); ctx.mark("perf.recovery.fixed", { dueSteps: 3_000, killedWorkers: 2, replacements: 2, recoveryMs }); return ctx.pass();
});

export const E_CASES = [E01, E02, E03, E04, E05];
