import {
  assertFrozenTotals, assertPaymentIdentity, assertSeatConservation, checkoutHold, createHold, createWaitlist,
  defineCase, expectError, finalEvidence, liveSeatOwners, prepare, providerReceipt, reconcilePayment,
  startProviderDouble, startSeatWorker, waitForOffer, waitForPayment, waitForSnapshot,
} from "./helpers.mjs";

const B01 = defineCase({
  id: "B-01", fixtureFamily: "SR-F-DURABLE-REPLAY",
  action: "Drop committed Hold and checkout responses, replay each key twenty ways across two API processes, restart one API, and submit changed bodies under the saved keys.",
  oracle: "Every exact replay restores the original status, byte-equivalent JSON, Hold, Order, PaymentIntent, Work, Event, and provider identity; changed bodies conflict without a second effect.",
  async run(ctx) {
    const fixture = ctx.fixtures.payment(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); let api0 = await target.startApi(); const api1 = await target.startApi(); const body = fixture.holdPayload("lost", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`)]); const key = ctx.key("lost-hold"); const shield = await ctx.responseShield(api0.baseUrl); shield.dropNextMutation(); await ctx.mutate(shield.baseUrl, "/api/v1/holds", key, body).catch(() => undefined); ctx.equal(shield.captures.length, 1, "shield captures committed Hold response"); const saved = shield.captures[0].response;
    const replays = await Promise.all(Array.from({ length: 20 }, (_, index) => ctx.mutate(index % 2 ? api1.baseUrl : api0.baseUrl, "/api/v1/holds", key, body))); ctx.ok(replays.every(({ status, json }) => status === saved.status && JSON.stringify(json) === saved.body), "twenty Hold replays restore original response"); const changed = await ctx.mutate(api1.baseUrl, "/api/v1/holds", key, { ...body, customerRef: "changed" }); expectError(ctx, changed, 409, "IDEMPOTENCY_CONFLICT", "changed Hold replay"); const hold = replays[0].json;
    const checkoutKey = ctx.key("lost-checkout"); const checkoutShield = await ctx.responseShield(api0.baseUrl); checkoutShield.dropNextMutation(); await ctx.mutate(checkoutShield.baseUrl, `/api/v1/holds/${hold.holdId}/checkout`, checkoutKey, { providerScenario: "TIMEOUT" }).catch(() => undefined); ctx.equal(checkoutShield.captures.length, 1, "shield captures committed checkout response"); const savedCheckout = checkoutShield.captures[0].response; const checkoutReplays = await Promise.all(Array.from({ length: 20 }, (_, index) => ctx.mutate(index % 2 ? api1.baseUrl : api0.baseUrl, `/api/v1/holds/${hold.holdId}/checkout`, checkoutKey, { providerScenario: "TIMEOUT" }))); ctx.ok(checkoutReplays.every(({ status, json }) => status === savedCheckout.status && JSON.stringify(json) === savedCheckout.body), "twenty checkout replays restore original response"); const checkoutConflict = await ctx.mutate(api1.baseUrl, `/api/v1/holds/${hold.holdId}/checkout`, checkoutKey, { providerScenario: "FAILED" }); expectError(ctx, checkoutConflict, 409, "IDEMPOTENCY_CONFLICT", "changed checkout replay");
    await ctx.stop(api0); api0 = await target.startApi(); const afterRestart = await ctx.mutate(api0.baseUrl, "/api/v1/holds", key, body); ctx.equal(JSON.stringify(afterRestart.json), saved.body, "API restart preserves Hold replay"); const worker = await startSeatWorker(ctx, provider); const paymentId = checkoutReplays[0].json.paymentIntent.paymentIntentId; const unknown = await waitForPayment(ctx, api0.baseUrl, paymentId, "UNKNOWN", [worker]); ctx.equal(provider.charges.size, 1, "replayed checkout produces one provider identity"); ctx.equal(unknown.snapshot.resources.holds.filter(({ customerRef }) => customerRef === body.customerRef).length, 1, "replayed Hold creates one resource"); ctx.equal(unknown.snapshot.resources.orders.filter(({ holdId }) => holdId === hold.holdId).length, 1, "replayed checkout creates one Order"); assertSeatConservation(unknown.snapshot); assertPaymentIdentity(unknown.snapshot, provider.charges);
    return finalEvidence(ctx, { holdId: hold.holdId, paymentIntentId: paymentId, holdReplays: 20, checkoutReplays: 20 });
  },
});

const B02 = defineCase({
  id: "B-02", fixtureFamily: "SR-F-HOT-SEAT-CONTENTION",
  action: "Send sixty-four overlapping two-seat Hold requests through two independently started APIs so every request contains one shared hot Seat and one otherwise-free partner Seat.",
  oracle: "Exactly one all-or-nothing request succeeds; every conflict owns neither its hot nor partner Seat and the committed snapshot has at most one live owner for every Seat.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const hot = fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:B:1`); const partners = fixture.seats.filter(({ row, number }) => row === "B" && number >= 2);
    const attempts = Array.from({ length: 64 }, (_, index) => ({ index, partner: partners[index % partners.length] })); const results = await ctx.concurrent(attempts, 64, ({ index, partner }) => ctx.mutate(apis[index % 2].baseUrl, "/api/v1/holds", ctx.key(`hot:${index}`), fixture.holdPayload(`hot-${index}`, [hot, partner]))); ctx.equal(results.filter(({ status }) => status === 200).length, 1, "one overlapping Hold wins"); ctx.ok(results.every(({ status }) => [200, 409].includes(status)), "contention returns only success or stable conflict"); const snapshot = await ctx.snapshot(apis[0].baseUrl); assertSeatConservation(snapshot); const owners = liveSeatOwners(snapshot); ctx.equal(owners.get(hot.seatId)?.length, 1, "hot Seat has one live owner"); const winnerIndex = results.findIndex(({ status }) => status === 200); const winnerPartner = attempts[winnerIndex].partner.seatId; for (const { index, partner } of attempts) if (index !== winnerIndex && partner.seatId !== winnerPartner) ctx.equal(owners.has(partner.seatId), false, `failed request ${index} leaves partner unowned`);
    return finalEvidence(ctx, { attempts: results.length, winningHoldId: results[winnerIndex].json.holdId, hotSeatId: hot.seatId });
  },
});

const B03 = defineCase({
  id: "B-03", fixtureFamily: "SR-F-PAYMENT-COMMUTATIVITY",
  action: "Drive a TIMEOUT checkout to UNKNOWN, set the Provider double terminal fact, then race a matching public receipt and active reconcile through two APIs while expiry Work remains fenced by grace.",
  oracle: "Receipt and reconcile commute to one Payment and Order terminal result with one provider request and transaction identity; terminal history cannot regress and protected seats never become free during UNKNOWN.",
  async run(ctx) {
    const fixture = ctx.fixtures.payment(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const hold = await createHold(ctx, apis[0].baseUrl, fixture.holdPayload("commute", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`)])); const checkout = await checkoutHold(ctx, apis[0].baseUrl, hold.holdId, "TIMEOUT"); const worker = await startSeatWorker(ctx, provider); const unknown = await waitForPayment(ctx, apis[0].baseUrl, checkout.paymentIntent.paymentIntentId, "UNKNOWN", [worker]); const identity = unknown.payment.providerRequestId; const providerRecord = provider.charges.get(identity); providerRecord.outcome = "SUCCEEDED"; providerRecord.providerTransactionId = `txn-commute-${ctx.key("tx").slice(-12)}`; const receipt = { providerEventId: `event-${ctx.key("receipt").slice(-20)}`, providerRequestId: identity, outcome: "SUCCEEDED", providerTransactionId: providerRecord.providerTransactionId, occurredAt: ctx.at({ seconds: 1 }) };
    const raced = await Promise.all([providerReceipt(ctx, apis[0].baseUrl, receipt, { allowFailure: true, key: ctx.key("receipt") }), reconcilePayment(ctx, apis[1].baseUrl, checkout.paymentIntent.paymentIntentId, { allowFailure: true, key: ctx.key("reconcile") })]); ctx.ok(raced.every(({ status }) => status >= 200 && status < 300), "receipt and reconcile both acknowledge the same fact"); const settled = await waitForPayment(ctx, apis[0].baseUrl, checkout.paymentIntent.paymentIntentId, "SUCCEEDED", [worker]); const order = settled.snapshot.resources.orders.find(({ orderId }) => orderId === checkout.order.orderId); const finalHold = settled.snapshot.resources.holds.find(({ holdId }) => holdId === hold.holdId); ctx.equal(order.state, "CONFIRMED", "successful fact confirms Order"); ctx.equal(finalHold.state, "CONVERTED", "successful fact converts Hold"); ctx.equal(provider.charges.size, 1, "commuting paths preserve one provider identity"); ctx.equal(providerRecord.postCount, 1, "commuting paths do not repeat semantic charge"); assertPaymentIdentity(settled.snapshot, provider.charges); assertSeatConservation(settled.snapshot);
    const lateUnknown = await providerReceipt(ctx, apis[1].baseUrl, { ...receipt, providerEventId: `event-${ctx.key("late").slice(-20)}`, outcome: "FAILED", providerTransactionId: null, occurredAt: ctx.at() }, { allowFailure: true, key: ctx.key("late") }); ctx.equal(lateUnknown.status, 409, "conflicting late result is rejected"); ctx.ok(["PROVIDER_RESULT_CONFLICT", "PROVIDER_TRANSACTION_CONFLICT"].includes(lateUnknown.json?.error?.code), "conflicting late result uses published stable error"); const after = await getOrderLike(ctx, apis[0].baseUrl, order.orderId); ctx.equal(after.state, "CONFIRMED", "late conflict cannot reverse terminal Order");
    return finalEvidence(ctx, { paymentIntentId: checkout.paymentIntent.paymentIntentId, providerRequestId: identity, terminalState: settled.payment.state });
  },
});

async function getOrderLike(ctx, baseUrl, orderId) { const response = await ctx.request(baseUrl, `/api/v1/orders/${orderId}`); ctx.equal(response.status, 200, "get terminal Order status"); return response.json; }

const B04 = defineCase({
  id: "B-04", fixtureFamily: "SR-F-WAITLIST-RELEASE-CONTENTION",
  action: "Occupy the leading contiguous rows, create ordered waiting Entries, then cancel independent Holds across two APIs while four Workers concurrently claim matching work.",
  oracle: "Committed releases preserve FIFO eligibility and deterministic contiguous selection; each Entry has at most one ACTIVE Offer and each Seat has at most one Hold, Order, or Offer owner.",
  async run(ctx) {
    const fixture = ctx.fixtures.waitlist(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const occupiedSeats = [1, 2, 3, 5, 6].map((number) => fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:${number}`)); const blockers = []; for (let index = 0; index < occupiedSeats.length; index += 1) blockers.push(await createHold(ctx, apis[index % 2].baseUrl, fixture.holdPayload(`block-${index}`, [occupiedSeats[index]])));
    const entries = []; for (let index = 0; index < 3; index += 1) entries.push(await createWaitlist(ctx, apis[index % 2].baseUrl, fixture.waitlistPayload(`fifo-${index}`, { seatCount: index === 2 ? 2 : 3 }))); entries.sort((left, right) => left.createdAt.localeCompare(right.createdAt) || left.waitlistEntryId.localeCompare(right.waitlistEntryId));
    const workers = await Promise.all(Array.from({ length: 4 }, () => startSeatWorker(ctx, provider))); const releases = await ctx.concurrent(blockers, blockers.length, (hold, index) => ctx.mutate(apis[index % 2].baseUrl, `/api/v1/holds/${hold.holdId}/cancel`, ctx.key(`release:${index}`), {})); ctx.ok(releases.every(({ status }) => status === 200), "all independent releases commit"); const settled = await waitForSnapshot(ctx, apis[0].baseUrl, (snapshot) => snapshot.resources.seatOffers.filter(({ state }) => state === "ACTIVE").length === entries.length, { label: "all eligible waitlist matches", processes: workers });
    for (const entry of entries) ctx.equal(settled.resources.seatOffers.filter(({ waitlistEntryId, state }) => waitlistEntryId === entry.waitlistEntryId && state === "ACTIVE").length, 1, `${entry.waitlistEntryId} has one active Offer`); const offers = settled.resources.seatOffers.filter(({ state }) => state === "ACTIVE").sort((left, right) => left.createdAt.localeCompare(right.createdAt) || left.seatOfferId.localeCompare(right.seatOfferId)); ctx.equal(offers.map(({ waitlistEntryId }) => waitlistEntryId), entries.map(({ waitlistEntryId }) => waitlistEntryId), "Offer creation respects Entry FIFO"); assertSeatConservation(settled); assertFrozenTotals(settled);
    return finalEvidence(ctx, { entries: entries.map(({ waitlistEntryId }) => waitlistEntryId), offers: offers.map(({ seatOfferId }) => seatOfferId) });
  },
});

const B05 = defineCase({
  id: "B-05", fixtureFamily: "SR-F-OFFER-TERMINAL-RACE",
  action: "Create one ACTIVE Offer, wait until its database-published expiry boundary, then race accept, decline, Entry cancel, and the production expiry Worker through independent API processes.",
  oracle: "Exactly one legal terminal history wins; accept produces at most one Hold, non-accept winners release seats or restore WAITING as specified, and stale operations return only published terminal errors.",
  async run(ctx) {
    const fixture = ctx.fixtures.waitlist(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const worker = await startSeatWorker(ctx, provider); const entry = await createWaitlist(ctx, apis[0].baseUrl, fixture.waitlistPayload("terminal-race", { seatCount: 2 })); const matched = await waitForOffer(ctx, apis[0].baseUrl, entry.waitlistEntryId, [worker]); const waitMs = Math.max(0, Date.parse(matched.offer.expiresAt) - Date.now() - 50); if (waitMs > 0) await new Promise((resolve) => setTimeout(resolve, waitMs));
    const outcomes = await Promise.all([
      ctx.mutate(apis[0].baseUrl, `/api/v1/seat-offers/${matched.offer.seatOfferId}/accept`, ctx.key("race-accept"), {}),
      ctx.mutate(apis[1].baseUrl, `/api/v1/seat-offers/${matched.offer.seatOfferId}/decline`, ctx.key("race-decline"), {}),
      ctx.mutate(apis[0].baseUrl, `/api/v1/waitlist-entries/${entry.waitlistEntryId}/cancel`, ctx.key("race-cancel"), {}),
    ]);
    ctx.ok(outcomes.filter(({ status }) => status >= 200 && status < 300).length <= 1, "at most one public terminal mutation wins"); ctx.ok(outcomes.filter(({ status }) => status < 200 || status >= 300).every(({ status, json }) => status === 409 && ["WAITLIST_ENTRY_TERMINAL", "SEAT_OFFER_TERMINAL", "SEAT_OFFER_EXPIRED", "SEAT_OFFER_OWNERSHIP_CHANGED"].includes(json?.error?.code)), "losers use exact published terminal errors"); const final = await waitForSnapshot(ctx, apis[0].baseUrl, (snapshot) => ["ACCEPTED", "DECLINED", "EXPIRED"].includes(snapshot.resources.seatOffers.find(({ seatOfferId }) => seatOfferId === matched.offer.seatOfferId)?.state), { timeoutMs: 30_000, label: "Offer terminal race closure", processes: [worker] }); const offer = final.resources.seatOffers.find(({ seatOfferId }) => seatOfferId === matched.offer.seatOfferId); ctx.ok(final.resources.holds.filter(({ holdId }) => holdId === offer.holdId).length <= 1, "terminal race creates at most one Hold"); if (offer.state !== "ACCEPTED") ctx.equal(offer.holdId, null, "non-accept terminal has no Hold"); assertSeatConservation(final); assertFrozenTotals(final);
    return finalEvidence(ctx, { seatOfferId: offer.seatOfferId, terminalState: offer.state, successfulMutations: outcomes.filter(({ status }) => status >= 200 && status < 300).length });
  },
});

export const B_CASES = Object.freeze([B01, B02, B03, B04, B05]);
