import {
  assertPaymentIdentity, assertSeatConservation, cancelWaitlist, checkoutHold, createHold, createWaitlist,
  defineCase, finalEvidence, prepare, reconcilePayment, startProviderDouble, startSeatWorker,
  waitForOffer, waitForPayment, waitForSnapshot, waitForWorkDrain,
} from "./helpers.mjs";

const C01 = defineCase({
  id: "C-01", fixtureFamily: "SR-F-HOLD-EXPIRY-RECOVERY",
  action: "Seed a database-time-due HELD Hold, stop its first production Worker at the published worker.claimed barrier, SIGKILL that owner, and start a replacement after lease expiry.",
  oracle: "The replacement reclaims retained HOLD_EXPIRY Work, releases the Seat exactly once, emits at most one expiry transition, and the killed lease token cannot commit after fencing.",
  async run(ctx) {
    const fixture = ctx.fixtures.recovery(); const dueSeat = fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`); const holdId = ctx.uuid("recovery-due-hold"); const seed = structuredClone(fixture.seed); seed.seedVersion = `${ctx.caseId.toLowerCase()}-due`; seed.holds.push({ holdId, tenantId: fixture.tenant.tenantId, eventId: fixture.event.eventId, customerRef: "recovery-due", state: "HELD", expiresAt: "2020-01-01T00:00:00.000Z", paymentGraceExpiresAt: null, totalMinor: 5500, currency: "USD", createdAt: "2019-12-31T23:55:00.000Z", terminalAt: null, sequence: 1 }); seed.holdSeats.push({ holdId, seatId: dueSeat.seatId, priceVersionId: fixture.prices.priceA1.priceVersionId, unitAmountMinor: 5000, feeMinor: 500 });
    const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed }); const api = await target.startApi(); const barrier = await ctx.barrier({ hold: (payload) => payload.point === "worker.claimed" && payload.aggregateId === holdId }); const first = await startSeatWorker(ctx, provider, { env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const claimed = await barrier.waitFor(({ json }) => json?.point === "worker.claimed" && json.aggregateId === holdId, { timeoutMs: 120_000, processes: [first] }); await ctx.kill(first); ctx.equal(claimed.json.aggregateId, holdId, "barrier identifies due Hold Work"); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacement = await startSeatWorker(ctx, provider); const final = await waitForWorkDrain(ctx, api.baseUrl, ({ kind, aggregateId }) => kind === "HOLD_EXPIRY" && aggregateId === holdId, [replacement]); const hold = final.resources.holds.find((item) => item.holdId === holdId); ctx.equal(hold.state, "EXPIRED", "replacement expires Hold"); ctx.equal(final.events.filter((event) => event.aggregateId === holdId && (event.type ?? event.eventType) === "hold.expired").length, 1, "one expiry event"); ctx.equal(final.work.filter(({ kind, aggregateId }) => kind === "HOLD_EXPIRY" && aggregateId === holdId).length, 1, "one retained expiry Work"); ctx.equal(final.resources.holdSeats.filter(({ holdId: value }) => value === holdId).length, 1, "immutable HoldSeat history retained"); assertSeatConservation(final);
    return finalEvidence(ctx, { holdId, killedAttempt: claimed.json.attempt, terminalWorkId: final.work.find(({ aggregateId }) => aggregateId === holdId).workId });
  },
});

const C02 = defineCase({
  id: "C-02", fixtureFamily: "SR-F-PAYMENT-UNKNOWN-RECOVERY",
  action: "Checkout through CONNECTION_RESET, release a claimed capture Worker so the Provider durably records the request, SIGKILL that Worker around the unknown response, then replace and reconcile.",
  oracle: "Recovery uses the original providerRequestId and one canonical charge to converge Payment, Order, Hold, and Seat ownership; stale ownership cannot commit or allocate a replacement identity.",
  async run(ctx) {
    const fixture = ctx.fixtures.recovery(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi(); const hold = await createHold(ctx, api.baseUrl, fixture.holdPayload("connection-reset", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`)])); const checkout = await checkoutHold(ctx, api.baseUrl, hold.holdId, "CONNECTION_RESET"); const paymentId = checkout.paymentIntent.paymentIntentId; const barrier = await ctx.barrier({ hold: (payload) => payload.point === "worker.claimed" && payload.aggregateId === paymentId }); const first = await startSeatWorker(ctx, provider, { env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const claimed = await barrier.waitFor(({ json }) => json?.aggregateId === paymentId, { timeoutMs: 120_000, processes: [first] }); barrier.release(claimed); await ctx.waitFor(() => provider.charges.size === 1, { timeoutMs: 30_000, intervalMs: 10, label: "Provider durable charge", processes: [first] }); await ctx.kill(first); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacement = await startSeatWorker(ctx, provider); const unknown = await waitForPayment(ctx, api.baseUrl, paymentId, "UNKNOWN", [replacement]); const identity = unknown.payment.providerRequestId; ctx.equal(provider.charges.size, 1, "one provider identity after killed response window"); await reconcilePayment(ctx, api.baseUrl, paymentId); const final = await waitForPayment(ctx, api.baseUrl, paymentId, ["SUCCEEDED", "FAILED"], [replacement]); ctx.equal(provider.charges.size, 1, "reconcile preserves provider identity"); ctx.equal(provider.charges.get(identity).postCount, 1, "recovery never repeats semantic POST"); ctx.ok(provider.charges.get(identity).getCount >= 1, "recovery queries durable provider request"); assertPaymentIdentity(final.snapshot, provider.charges); assertSeatConservation(final.snapshot);
    return finalEvidence(ctx, { paymentIntentId: paymentId, providerRequestId: identity, killedAttempt: claimed.json.attempt, terminalState: final.payment.state });
  },
});

const C03 = defineCase({
  id: "C-03", fixtureFamily: "SR-F-WAITLIST-OFFER-RECOVERY",
  action: "SIGKILL a Worker after WAITLIST_MATCH claim, reclaim to one Offer, then hold OFFER_EXPIRY at its claim boundary, kill again, and drain with replacement Workers.",
  oracle: "Recovered selection equals the FIFO contiguous-seat oracle, each Entry has at most one active or terminal Offer, expiry releases ownership and restores only an unexpired Entry, and stale leases commit nothing.",
  async run(ctx) {
    const fixture = ctx.fixtures.recovery(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi(); const entry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("recover", { seatCount: 2, expiresAt: new Date(Date.now() + 60_000).toISOString() })); const matchBarrier = await ctx.barrier({ hold: (payload) => payload.point === "worker.claimed" && payload.aggregateId === entry.waitlistEntryId }); const first = await startSeatWorker(ctx, provider, { env: { TEST_BARRIER_URL: matchBarrier.url, TEST_BARRIER_TOKEN: matchBarrier.token } }); const matchClaim = await matchBarrier.waitFor(({ json }) => json?.aggregateId === entry.waitlistEntryId, { timeoutMs: 120_000, processes: [first] }); await ctx.kill(first); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacement = await startSeatWorker(ctx, provider); const matched = await waitForOffer(ctx, api.baseUrl, entry.waitlistEntryId, [replacement]); ctx.equal(matched.snapshot.resources.seatOffers.filter(({ waitlistEntryId }) => waitlistEntryId === entry.waitlistEntryId).length, 1, "match recovery creates one Offer"); assertSeatConservation(matched.snapshot);
    await ctx.stop(replacement); const expiryBarrier = await ctx.barrier({ hold: (payload) => payload.point === "worker.claimed" && payload.aggregateId === matched.offer.seatOfferId }); const expiryOwner = await startSeatWorker(ctx, provider, { env: { TEST_BARRIER_URL: expiryBarrier.url, TEST_BARRIER_TOKEN: expiryBarrier.token } }); const expiryClaim = await expiryBarrier.waitFor(({ json }) => json?.aggregateId === matched.offer.seatOfferId, { timeoutMs: 150_000, processes: [expiryOwner] }); await ctx.kill(expiryOwner); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacements = await Promise.all([startSeatWorker(ctx, provider), startSeatWorker(ctx, provider)]); const final = await waitForWorkDrain(ctx, api.baseUrl, ({ kind, aggregateId }) => kind === "OFFER_EXPIRY" && aggregateId === matched.offer.seatOfferId, replacements, 120_000); const offer = final.resources.seatOffers.find(({ seatOfferId }) => seatOfferId === matched.offer.seatOfferId); const finalEntry = final.resources.waitlistEntries.find(({ waitlistEntryId }) => waitlistEntryId === entry.waitlistEntryId); ctx.equal(offer.state, "EXPIRED", "replacement expires Offer"); ctx.equal(finalEntry.state, "EXPIRED", "expired Entry cannot revive after Offer expiry"); ctx.equal(final.resources.seatOffers.filter(({ waitlistEntryId }) => waitlistEntryId === entry.waitlistEntryId).length, 1, "expiry recovery does not duplicate Offer"); assertSeatConservation(final);
    return finalEvidence(ctx, { waitlistEntryId: entry.waitlistEntryId, seatOfferId: offer.seatOfferId, killedAttempts: [matchClaim.json.attempt, expiryClaim.json.attempt] });
  },
});

const C04 = defineCase({
  id: "C-04", fixtureFamily: "SR-F-OUTBOX-UNKNOWN-ACK",
  action: "Commit Hold and successful checkout transitions, let the receiver persist the first complete event request while withholding its acknowledgement, SIGKILL Dispatcher, then start a replacement.",
  oracle: "Only committed business effects produce events; unknown-ACK retry preserves Event ID, aggregate sequence, headers, and canonical body, without duplicating Hold, Order, Payment, or unpublished Manager event types.",
  async run(ctx) {
    const fixture = ctx.fixtures.recovery(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi(); const hold = await createHold(ctx, api.baseUrl, fixture.holdPayload("event", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`)])); const checkout = await checkoutHold(ctx, api.baseUrl, hold.holdId, "SUCCEEDED"); const worker = await startSeatWorker(ctx, provider); await waitForPayment(ctx, api.baseUrl, checkout.paymentIntent.paymentIntentId, "SUCCEEDED", [worker]);
    let release; const held = new Promise((resolve) => { release = resolve; }); let first = true; const receiver = await ctx.receiver({ behavior: async () => { if (first) { first = false; await held; return { status: 204 }; } return { status: 204 }; } }); const dispatcher = await target.startDispatcher({ webhookUrl: receiver.url }); await ctx.waitFor(() => receiver.ledger.length >= 1, { timeoutMs: 120_000, label: "receiver persisted unknown-ACK event", processes: [dispatcher] }); const captured = receiver.ledger[0]; await ctx.kill(dispatcher); release(); const replacement = await target.startDispatcher({ webhookUrl: receiver.url }); await ctx.waitFor(() => receiver.ledger.some((entry, index) => index > 0 && entry.json?.eventId === captured.json?.eventId), { timeoutMs: 120_000, label: "stable event retry", processes: [replacement] }); const replay = receiver.ledger.find((entry, index) => index > 0 && entry.json?.eventId === captured.json?.eventId); ctx.equal(replay.raw, captured.raw, "retry preserves canonical event body"); ctx.equal(replay.headers["content-type"], captured.headers["content-type"], "retry preserves content type"); const snapshot = await ctx.snapshot(api.baseUrl); ctx.equal(snapshot.resources.holds.filter(({ holdId }) => holdId === hold.holdId).length, 1, "dispatch retry does not duplicate Hold"); ctx.equal(snapshot.resources.orders.filter(({ orderId }) => orderId === checkout.order.orderId).length, 1, "dispatch retry does not duplicate Order"); ctx.ok(snapshot.events.every((event) => !/^waitlist\.|^offer\.|^seat-offer\./u.test(event.type ?? event.eventType ?? "")), "no unpublished waitlist or Offer event type"); assertSeatConservation(snapshot);
    return finalEvidence(ctx, { eventId: captured.json.eventId, receiverAttempts: receiver.ledger.filter(({ json }) => json?.eventId === captured.json.eventId).length });
  },
});

export const C_CASES = Object.freeze([C01, C02, C03, C04]);
