import {
  assertFrozenTotals, assertPaymentIdentity, assertSeatConservation, assertSnapshot, checkoutHold, countStatuses,
  createHold, defineCase, finalEvidence, formalSeed, prepare, reconcilePayment, requireV1, runFixedLoad,
  startProviderDouble, startSeatWorker, startSeatWorkerFor, waitForPayment, waitForSnapshot,
} from "./helpers.mjs";

const E01 = defineCase({
  id: "E-01", fixtureFamily: "SR-F-V1-FINAL-MIGRATION",
  action: "Build a populated V1 database with live Hold, UNKNOWN checkout, saved Hold replay, Work and Events, stop V1 roles, run FINAL migration, replay the saved mutation, and inspect FINAL snapshot.",
  oracle: "Every V1 identity, frozen price, amount, provider request, saved status/body, pending Work and Event body/sequence survives exactly; new waitlist resources remain empty until their public API is used.",
  async run(ctx) {
    const v1Workspace = requireV1(ctx); const fixture = ctx.fixtures.v1Final(); const provider = await startProviderDouble(ctx); const v1 = await prepare(ctx, { workspace: v1Workspace, seed: fixture.seed }); const v1Api = await v1.startApi(); const body = fixture.holdPayload("migration-replay", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`)]); const replayKey = fixture.savedReplayKey; const held = await ctx.mutate(v1Api.baseUrl, "/api/v1/holds", replayKey, body); ctx.equal(held.status, 200, "V1 saved Hold status"); const savedBody = held.json; const checkout = await checkoutHold(ctx, v1Api.baseUrl, savedBody.holdId, "TIMEOUT", { key: ctx.key("v1-checkout") }); const v1Worker = await startSeatWorkerFor(v1, provider); await waitForPayment(ctx, v1Api.baseUrl, checkout.paymentIntent.paymentIntentId, "UNKNOWN", [v1Worker]); await ctx.stop(v1Worker); const before = assertSnapshot(ctx, await ctx.snapshot(v1Api.baseUrl), { final: false }); await ctx.stop(v1Api);
    const finalTarget = await prepare(ctx, { migrate: true, seed: undefined }); const finalApi = await finalTarget.startApi(); const after = assertSnapshot(ctx, await ctx.snapshot(finalApi.baseUrl)); for (const name of ["tenants", "venues", "events", "zones", "seats", "priceVersions", "holds", "holdSeats", "orders", "orderSeats", "paymentIntents", "providerReceipts"]) ctx.equal(after.resources[name], before.resources[name], `${name} preserved across migration`); ctx.equal(after.work, before.work, "pending and terminal Work identity preserved"); ctx.equal(after.events, before.events, "Event identity, body, and sequence preserved"); ctx.equal(after.resources.waitlistEntries, [], "migration does not invent WaitlistEntries"); ctx.equal(after.resources.seatOffers, [], "migration does not invent SeatOffers"); const replayed = await ctx.mutate(finalApi.baseUrl, "/api/v1/holds", replayKey, body); ctx.equal(replayed.status, held.status, "saved replay status preserved"); ctx.equal(replayed.json, savedBody, "saved replay body preserved"); const replaySnapshot = await ctx.snapshot(finalApi.baseUrl); ctx.equal(replaySnapshot.resources.holds.filter(({ holdId }) => holdId === savedBody.holdId).length, 1, "replay after migration creates no second Hold"); assertSeatConservation(replaySnapshot); assertFrozenTotals(replaySnapshot);
    return finalEvidence(ctx, { holdId: savedBody.holdId, paymentIntentId: checkout.paymentIntent.paymentIntentId, workCount: before.work.length, eventCount: before.events.length });
  },
});

const E02 = defineCase({
  id: "E-02", fixtureFamily: "SR-F-PERF-HOLD-INGEST",
  action: "Seed at least fifty thousand disjoint Seats, start four production APIs and four Workers, then issue exactly fifty thousand public one-seat Hold requests at concurrency ninety-six.",
  oracle: "The fixed workload sustains at least 250 Holds per second with p95 at most 400ms and zero 5xx; all fifty thousand Holds freeze the published price and own distinct Seats after load.",
  async run(ctx) {
    const formal = formalSeed({ version: `${ctx.caseId.toLowerCase()}-formal`, seatCount: 50_000 }); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: formal.seed }); const apis = await Promise.all(Array.from({ length: 4 }, () => target.startApi())); await Promise.all(Array.from({ length: 4 }, () => startSeatWorker(ctx, provider))); const load = await runFixedLoad({ count: 50_000, concurrency: 96, operation: (index) => ctx.mutate(apis[index % 4].baseUrl, "/api/v1/holds", `formal-ingest-${index}`, { tenantId: formal.tenantId, eventId: formal.eventId, customerRef: `formal-${index}`, seatIds: [formal.seatId(index)], ttlSeconds: 900 }) }); ctx.ok(load.throughput >= 250, `seat-hold-ingest throughput ${load.throughput.toFixed(1)}/s`); ctx.ok(load.p95Ms <= 400, `seat-hold-ingest p95 ${load.p95Ms.toFixed(1)}ms`); ctx.equal(countStatuses(load, (status) => status >= 200 && status < 300), 50_000, "all formal Holds succeed"); ctx.equal(countStatuses(load, (status) => status >= 500), 0, "formal ingest has zero 5xx"); const snapshot = await ctx.snapshot(apis[0].baseUrl); const holds = snapshot.resources.holds.filter(({ customerRef }) => customerRef.startsWith("formal-")); const holdIds = new Set(holds.map(({ holdId }) => holdId)); const items = snapshot.resources.holdSeats.filter(({ holdId }) => holdIds.has(holdId)); ctx.equal(holds.length, 50_000, "formal Hold count"); ctx.equal(items.length, 50_000, "formal HoldSeat count"); ctx.equal(new Set(items.map(({ seatId }) => seatId)).size, 50_000, "formal Seats are disjoint"); ctx.ok(items.every(({ priceVersionId, unitAmountMinor, feeMinor }) => priceVersionId === formal.priceVersionId && unitAmountMinor === 5000 && feeMinor === 500), "formal Holds freeze exact price"); ctx.ok(holds.every(({ totalMinor }) => totalMinor === 5500), "formal Hold totals close"); assertSeatConservation(snapshot); assertFrozenTotals(snapshot);
    return finalEvidence(ctx, { scenarioId: "seat-hold-ingest", completed: load.count, throughput: load.throughput, p95Ms: load.p95Ms, statusCounts: Object.fromEntries(load.statuses) });
  },
});

const E03 = defineCase({
  id: "E-03", fixtureFamily: "SR-F-PERF-HOT-CONTENTION",
  action: "Seed one thousand hot Seats, start four production APIs, and issue exactly twenty thousand public one-seat Hold attempts at concurrency one hundred twenty-eight.",
  oracle: "The fixed workload sustains at least 300 attempts per second with p95 at most 500ms, exactly one request owns each hot Seat, expected conflicts are not 5xx, and no partial or process-local owner exists.",
  async run(ctx) {
    const formal = formalSeed({ version: `${ctx.caseId.toLowerCase()}-formal`, seatCount: 1_000 }); const target = await prepare(ctx, { seed: formal.seed }); const apis = await Promise.all(Array.from({ length: 4 }, () => target.startApi())); const load = await runFixedLoad({ count: 20_000, concurrency: 128, operation: (index) => ctx.mutate(apis[index % 4].baseUrl, "/api/v1/holds", `formal-hot-${index}`, { tenantId: formal.tenantId, eventId: formal.eventId, customerRef: `hot-${index}`, seatIds: [formal.seatId(index % 1_000)], ttlSeconds: 900 }) }); ctx.ok(load.throughput >= 300, `hot-seat-contention throughput ${load.throughput.toFixed(1)}/s`); ctx.ok(load.p95Ms <= 500, `hot-seat-contention p95 ${load.p95Ms.toFixed(1)}ms`); ctx.equal(countStatuses(load, (status) => status >= 200 && status < 300), 1_000, "one success per hot Seat"); ctx.equal(countStatuses(load, (status) => status === 409), 19_000, "remaining attempts are expected conflicts"); ctx.equal(countStatuses(load, (status) => status >= 500), 0, "hot contention has zero 5xx"); const snapshot = await ctx.snapshot(apis[0].baseUrl); const hotHolds = snapshot.resources.holds.filter(({ customerRef }) => customerRef.startsWith("hot-")); const ids = new Set(hotHolds.map(({ holdId }) => holdId)); const owned = snapshot.resources.holdSeats.filter(({ holdId }) => ids.has(holdId)); ctx.equal(hotHolds.length, 1_000, "one committed Hold per Seat"); ctx.equal(new Set(owned.map(({ seatId }) => seatId)).size, 1_000, "all hot Seats have exactly one winner"); assertSeatConservation(snapshot); assertFrozenTotals(snapshot);
    return finalEvidence(ctx, { scenarioId: "hot-seat-contention", completed: load.count, throughput: load.throughput, p95Ms: load.p95Ms, statusCounts: Object.fromEntries(load.statuses) });
  },
});

const E04 = defineCase({
  id: "E-04", fixtureFamily: "SR-F-PERF-PAYMENT-RECOVERY",
  action: "Create five thousand 30-second Holds and TIMEOUT checkouts, observe two target payment Work claims through the barrier, SIGKILL both Workers, and drain with four replacements plus public reconcile calls.",
  oracle: "Within 90 seconds after the kills every target Payment, Order, Hold and Work reaches one legal terminal result using one provider identity, with no stale commit, duplicate charge, stranded owner, or omitted expiry.",
  async run(ctx) {
    const count = 5_000; const formal = formalSeed({ version: `${ctx.caseId.toLowerCase()}-formal`, seatCount: count }); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: formal.seed }); const apis = await Promise.all(Array.from({ length: 4 }, () => target.startApi())); const holds = await runFixedLoad({ count, concurrency: 96, operation: (index) => ctx.mutate(apis[index % 4].baseUrl, "/api/v1/holds", `formal-payment-hold-${index}`, { tenantId: formal.tenantId, eventId: formal.eventId, customerRef: `payment-${index}`, seatIds: [formal.seatId(index)], ttlSeconds: 30 }) }); ctx.equal(countStatuses(holds, (status) => status >= 200 && status < 300), count, "all payment recovery Holds commit"); const snapshotAfterHolds = await ctx.snapshot(apis[0].baseUrl); const targetHolds = snapshotAfterHolds.resources.holds.filter(({ customerRef }) => customerRef.startsWith("payment-")); const holdIds = new Set(targetHolds.map(({ holdId }) => holdId)); const checkoutResponses = await ctx.concurrent(targetHolds, 96, (hold, index) => ctx.mutate(apis[index % 4].baseUrl, `/api/v1/holds/${hold.holdId}/checkout`, `formal-payment-checkout-${index}`, { providerScenario: "TIMEOUT" })); ctx.ok(checkoutResponses.every(({ status }) => status === 200), "all payment recovery checkouts commit"); const paymentIds = new Set(checkoutResponses.map(({ json }) => json.paymentIntent.paymentIntentId));
    const barrier = await ctx.barrier({ hold: (payload) => payload.point === "worker.claimed" && paymentIds.has(payload.aggregateId) }); const first = await Promise.all(Array.from({ length: 2 }, () => startSeatWorker(ctx, provider, { env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }))); await ctx.waitFor(() => barrier.ledger.filter(({ json }) => json?.point === "worker.claimed" && paymentIds.has(json.aggregateId)).length >= 2, { timeoutMs: 120_000, label: "two target payment Work claims", processes: first }); await Promise.all(first.map((worker) => ctx.kill(worker))); const startedAt = Date.now(); await new Promise((resolve) => setTimeout(resolve, 3_200)); const replacements = await Promise.all(Array.from({ length: 4 }, () => startSeatWorker(ctx, provider)));
    const unknownSnapshot = await waitForSnapshot(ctx, apis[0].baseUrl, (snapshot) => { const intents = snapshot.resources.paymentIntents.filter(({ paymentIntentId }) => paymentIds.has(paymentIntentId)); return intents.length === count && intents.every(({ state }) => ["UNKNOWN", "SUCCEEDED", "FAILED"].includes(state)); }, { timeoutMs: 75_000, label: "all capture outcomes persisted", processes: replacements }); const unresolved = unknownSnapshot.resources.paymentIntents.filter(({ paymentIntentId, state }) => paymentIds.has(paymentIntentId) && state === "UNKNOWN"); const reconciles = await ctx.concurrent(unresolved, 96, (intent, index) => ctx.mutate(apis[index % 4].baseUrl, `/api/v1/payment-intents/${intent.paymentIntentId}/reconcile`, `formal-reconcile-${index}`, {})); ctx.ok(reconciles.every(({ status }) => status === 200), "all UNKNOWN payments accept public reconcile"); const final = await waitForSnapshot(ctx, apis[0].baseUrl, (snapshot) => { const intents = snapshot.resources.paymentIntents.filter(({ paymentIntentId }) => paymentIds.has(paymentIntentId)); const orders = snapshot.resources.orders.filter(({ paymentIntentId }) => paymentIds.has(paymentIntentId)); const selectedHolds = snapshot.resources.holds.filter(({ holdId }) => holdIds.has(holdId)); const pending = snapshot.work.some(({ kind, aggregateId, terminal }) => !terminal && ((["PAYMENT_CAPTURE", "PAYMENT_RECONCILE"].includes(kind) && paymentIds.has(aggregateId)) || (kind === "HOLD_EXPIRY" && holdIds.has(aggregateId)))); return intents.length === count && intents.every(({ state }) => ["SUCCEEDED", "FAILED"].includes(state)) && orders.length === count && orders.every(({ state }) => ["CONFIRMED", "CANCELLED"].includes(state)) && selectedHolds.length === count && selectedHolds.every(({ state }) => ["CONVERTED", "CANCELLED"].includes(state)) && !pending; }, { timeoutMs: Math.max(1, 90_000 - (Date.now() - startedAt)), intervalMs: 100, label: "payment-expiry-recovery complete drain", processes: replacements }); const durationMs = Date.now() - startedAt; ctx.ok(durationMs <= 90_000, `payment-expiry-recovery closes in ${durationMs}ms`); ctx.equal(provider.charges.size, count, "one provider request per PaymentIntent"); for (const record of provider.charges.values()) ctx.equal(record.postCount, 1, "one semantic charge per provider identity"); assertPaymentIdentity(final, provider.charges); assertSeatConservation(final); assertFrozenTotals(final);
    return finalEvidence(ctx, { scenarioId: "payment-expiry-recovery", completed: count, durationMs, killedWorkers: 2, replacementWorkers: 4, reconciled: unresolved.length });
  },
});

export const E_CASES = Object.freeze([E01, E02, E03, E04]);
