import { candidateAssert as assert } from "../lib/execution.mjs";
import { assertNotificationWire, assertSlidingQuota, assertNotificationIdentity, frozenRecallSet, projectReadings } from "../oracles/index.mjs";
import { faultWorkers, heldWorker, releaseStaleWorker, acceptHandoff, assertSnapshotShape, createAssignment, createConfig, createCustody, createRecall, deviceRequest, diagnostic, guardedCase, ingest, offerHandoff, prepare, publishConfig, quarantineRecall, resourceFrom, resources, semanticError, shipmentAction, successful, waitForWork, waitSnapshot } from "./helpers.mjs";

function rolloutFixture(ctx,count=20_000){const fixture=ctx.fixtures.config(),revision={...fixture.config,configRevisionId:ctx.uuid("rollout-config"),version:2,minTemperatureMilliC:1_500,maxTemperatureMilliC:8_500,publishedAt:ctx.at({days:-1})},devices=[],credentials=[],assignments=[];for(let index=0;index<count;index+=1){const deviceId=ctx.uuid(`rollout-device:${index}`);devices.push({...fixture.device,deviceId,serialNumber:`ROLLOUT-${String(index).padStart(5,"0")}`,currentConfigVersion:1});credentials.push({...fixture.credential,deviceCredentialId:ctx.uuid(`rollout-credential:${index}`),deviceId,secret:ctx.fixtures.secret(`rollout-secret:${index}`)});assignments.push({...fixture.assignment,configAssignmentId:ctx.uuid(`rollout-assignment:${index}`),deviceId,configRevisionId:revision.configRevisionId,state:"PENDING",confirmedAt:null,createdAt:ctx.at({days:-1}),expiresAt:ctx.at({hours:1})});}fixture.seed={...fixture.seed,devices,deviceCredentials:credentials,configRevisions:[fixture.config,revision],configAssignments:assignments};return{...fixture,revision,rollout:{devices,assignments}};}
function recallFixture(ctx,count=2_500){const fixture=ctx.fixtures.recall(),devices=[],credentials=[],assignments=[],shipments=[],legs=[],projections=[];for(let index=0;index<count;index+=1){const deviceId=ctx.uuid(`quarantine-device:${index}`),shipmentId=ctx.uuid(`quarantine-shipment:${index}`);devices.push({...fixture.device,deviceId,serialNumber:`QUARANTINE-${String(index).padStart(5,"0")}`});credentials.push({...fixture.credential,deviceCredentialId:ctx.uuid(`quarantine-credential:${index}`),deviceId,secret:ctx.fixtures.secret(`quarantine-secret:${index}`)});assignments.push({...fixture.assignment,configAssignmentId:ctx.uuid(`quarantine-assignment:${index}`),deviceId});shipments.push({...fixture.shipment,shipmentId,deviceId,externalRef:`QUARANTINE-${index}`});legs.push(...fixture.legs.map((leg)=>({...leg,shipmentLegId:ctx.uuid(`quarantine-leg:${index}:${leg.ordinal}`),shipmentId})));projections.push({...fixture.projection,shipmentId});}const otherDevice=ctx.uuid("quarantine-other-device"),otherShipment=ctx.uuid("quarantine-other-shipment");devices.push({...fixture.device,deviceId:otherDevice,serialNumber:"QUARANTINE-OTHER"});credentials.push({...fixture.credential,deviceCredentialId:ctx.uuid("quarantine-other-credential"),deviceId:otherDevice,secret:ctx.fixtures.secret("quarantine-other-secret")});assignments.push({...fixture.assignment,configAssignmentId:ctx.uuid("quarantine-other-assignment"),deviceId:otherDevice});shipments.push({...fixture.shipment,shipmentId:otherShipment,deviceId:otherDevice,externalRef:"QUARANTINE-OTHER",productLotCode:"LOT-OTHER"});legs.push(...fixture.legs.map((leg)=>({...leg,shipmentLegId:ctx.uuid(`quarantine-other-leg:${leg.ordinal}`),shipmentId:otherShipment})));projections.push({...fixture.projection,shipmentId:otherShipment});fixture.seed={...fixture.seed,devices,deviceCredentials:credentials,configAssignments:assignments,shipments,shipmentLegs:legs,shipmentProjections:projections};fixture.shipment=shipments[0];fixture.custodyBody={...fixture.custodyBody,shipmentId:shipments[0].shipmentId};return{...fixture,recallSet:shipments.filter((item)=>item.productLotCode===fixture.recallBody.productLotCode),otherShipment};}

const C01 = guardedCase("C-01", ["STALE_WORK_AUTHORITY"], async (ctx) => {
  const fixture=ctx.fixtures.recall(),receiver=await ctx.receiver({path:"/events"}),{api,workers,dispatchers}=await prepare(ctx,fixture,{workerCount:2,dispatcherCount:1,webhookUrl:receiver.url}),draft=await createConfig(ctx,api.baseUrl,fixture,"work"),published=successful(await publishConfig(ctx,api.baseUrl,draft.config.configRevisionId,1,"work")),revision=resourceFrom(published.json,"configRevisionId","configRevision");await createAssignment(ctx,api.baseUrl,fixture,revision.configRevisionId,"work");await ingest(ctx,api.baseUrl,fixture,ctx.fixtures.reading(fixture,"work",{sequence:1}),"work");const chain=await createCustody(ctx,api.baseUrl,fixture),recall=await createRecall(ctx,api.baseUrl,fixture);assert.ok(chain.chain.custodyChainId);await quarantineRecall(ctx,api.baseUrl,recall.recall.recallId,recall.recall.revision);const snapshot=await waitSnapshot(ctx,api.baseUrl,(value)=>{const kinds=new Set(value.work.map((item)=>item.kind));return["CONFIG_DELIVER","TELEMETRY_PROJECT","CUSTODY_HANDOFF_EXPIRY","RECALL_PROPAGATE","QUARANTINE_ENFORCE"].every((kind)=>kinds.has(kind));},{processes:[...workers,...dispatchers],timeoutMs:30_000});assert.ok(snapshot.work.length>=5);assert.ok(snapshot.work.every((item)=>typeof item.workId==="string"&&Number.isSafeInteger(item.attempt)&&typeof item.terminal==="boolean"));assertSnapshotShape(await ctx.snapshot(api.baseUrl),{secrets:fixture.carrierDevices.map((item)=>item.secret)});return ctx.pass();
});

const C02 = guardedCase("C-02", ["STALE_WORK_AUTHORITY"], async (ctx) => {
  const fixture=rolloutFixture(ctx),{api}=await prepare(ctx,fixture),faults=await faultWorkers(ctx,"CONFIG_DELIVER"),workers=faults.workers;await waitSnapshot(ctx,api.baseUrl,(snapshot)=>snapshot.work.filter((item)=>item.kind==="CONFIG_DELIVER"&&item.state==="LEASED").length>=2,{processes:workers,timeoutMs:30_000,intervalMs:5});await Promise.all(workers.slice(0,2).map((worker)=>ctx.kill(worker)));const appliedAt=(await ctx.snapshot(api.baseUrl)).asOf,replacementPromise=Promise.all(Array.from({length:2},()=>ctx.startWorker())),staleAckPromise=Promise.all(fixture.rollout.assignments.slice(0,16).map((assignment,index)=>{const device=fixture.rollout.devices[index],credential=fixture.seed.deviceCredentials.find((item)=>item.deviceId===device.deviceId),deviceFixture={...fixture,device,deviceSecret:credential.secret};return deviceRequest(ctx,api.baseUrl,deviceFixture,"POST",`/api/v1/devices/${device.deviceId}/config-acknowledgements`,{body:{configAssignmentId:assignment.configAssignmentId,configVersion:1,appliedAt},key:ctx.key(`stale-rollout-ack:${index}`),secret:credential.secret,deviceId:device.deviceId,expectSuccess:false});})),[replacements,staleAcks]=await Promise.all([replacementPromise,staleAckPromise]);assert.ok(staleAcks.every((response)=>response.status===409),"stale acknowledgements reject during recovery");const final=await waitSnapshot(ctx,api.baseUrl,(snapshot)=>{const selected=snapshot.resources.configAssignments.filter((item)=>item.configRevisionId===fixture.revision.configRevisionId);return selected.length===20_000&&selected.every((item)=>["DELIVERED","CONFIRMED","EXPIRED"].includes(item.state));},{processes:[...workers.slice(2),...replacements],timeoutMs:60_000,intervalMs:1_000});assert.equal(final.resources.devices.some((item)=>item.currentConfigVersion<1),false);const work=final.work.filter((item)=>item.kind==="CONFIG_DELIVER");assert.equal(new Set(work.map((item)=>item.workId)).size,work.length);assert.ok(work.every((item)=>item.attempt>=1));await releaseStaleWorker(ctx,api.baseUrl,faults.stale);return ctx.pass();
});

const C03 = guardedCase("C-03", ["STALE_WORK_AUTHORITY","PROJECTION_AUTHORITY"], async (ctx) => {
  const fixture=ctx.fixtures.telemetry(),{api}=await prepare(ctx,fixture),readings=Array.from({length:1_000},(_,index)=>fixture.reading(`projection-kill-${index+1}`,{sequence:index+1,temperatureMilliC:index%7===0?9_000:5_000})).sort((a,b)=>((a.sequence*37)%1009)-((b.sequence*37)%1009));for(const reading of readings)await ingest(ctx,api.baseUrl,fixture,reading,`projection-kill-${reading.sequence}`);const faults=await faultWorkers(ctx,"TELEMETRY_PROJECT"),workers=faults.workers;await waitForWork(ctx,api.baseUrl,(item)=>item.kind==="TELEMETRY_PROJECT"&&item.state==="LEASED",{processes:workers,intervalMs:5});await Promise.all(workers.slice(0,2).map((worker)=>ctx.kill(worker)));const replacements=await Promise.all(Array.from({length:2},()=>ctx.startWorker())),final=await waitSnapshot(ctx,api.baseUrl,(snapshot)=>{const work=snapshot.work.filter((item)=>item.kind==="TELEMETRY_PROJECT"&&item.aggregateId===fixture.shipment.shipmentId);return snapshot.resources.shipmentProjections.some((item)=>item.shipmentId===fixture.shipment.shipmentId&&item.lastSequence===1_000)&&work.length>0&&work.every((item)=>item.terminal);},{processes:[...workers.slice(2),...replacements],timeoutMs:90_000,intervalMs:500}),projection=final.resources.shipmentProjections.find((item)=>item.shipmentId===fixture.shipment.shipmentId),expected=projectReadings(readings,{sites:fixture.sites}),excursions=final.resources.excursions.filter((item)=>item.shipmentId===fixture.shipment.shipmentId);assert.deepEqual([projection.lastSequence,projection.lastObservedAt,projection.lastLatitudeE6,projection.lastLongitudeE6,projection.lastTemperatureMilliC,projection.currentSiteId,projection.currentLegOrdinal],[expected.lastSequence,expected.lastObservedAt,expected.lastLatitudeE6,expected.lastLongitudeE6,expected.lastTemperatureMilliC,expected.currentSiteId,expected.currentLegOrdinal]);assert.deepEqual(excursions.map(({kind,state,firstSequence,lastSequence,minimumObservedMilliC,maximumObservedMilliC})=>({kind,state,firstSequence,lastSequence,minimumObservedMilliC,maximumObservedMilliC})),expected.excursions);assert.equal(final.resources.telemetryReadings.length,1_000);assert.equal(new Set(final.events.map((item)=>item.eventId)).size,final.events.length);await releaseStaleWorker(ctx,api.baseUrl,faults.stale);return ctx.pass();
});

const C04 = guardedCase("C-04", ["STALE_WORK_AUTHORITY","PROJECTION_AUTHORITY"], async (ctx) => {
  const fixture=ctx.fixtures.telemetry();fixture.seed={...fixture.seed,configRevisions:fixture.seed.configRevisions.map((item)=>({...item,offlineAfterSeconds:2})),devices:fixture.seed.devices.map((item)=>item.deviceId===fixture.device.deviceId?{...item,lastSeenAt:ctx.at({days:-1,seconds:-10})}:item),shipmentProjections:fixture.seed.shipmentProjections.map((item)=>({...item,lastObservedAt:ctx.at({days:-1,seconds:-10})}))};const{api}=await prepare(ctx,fixture),held=await heldWorker(ctx,"DEVICE_OFFLINE_CHECK"),workerA=held.worker;await waitForWork(ctx,api.baseUrl,(item)=>item.kind==="DEVICE_OFFLINE_CHECK"&&item.state==="LEASED",{processes:[workerA],intervalMs:5,timeoutMs:20_000});await new Promise((resolve)=>setTimeout(resolve,3_200));const workerB=await ctx.startWorker(),opened=await waitSnapshot(ctx,api.baseUrl,(snapshot)=>snapshot.resources.excursions.filter((item)=>item.shipmentId===fixture.shipment.shipmentId&&item.kind==="OFFLINE"&&item.state!=="RESOLVED").length===1,{processes:[workerB],timeoutMs:20_000}),excursion=opened.resources.excursions.find((item)=>item.kind==="OFFLINE");await ingest(ctx,api.baseUrl,fixture,fixture.reading("offline-recovery",{sequence:1}),"offline-recovery");await waitSnapshot(ctx,api.baseUrl,(snapshot)=>snapshot.resources.excursions.some((item)=>item.excursionId===excursion.excursionId&&item.state==="RESOLVED"),{processes:[workerB]});await releaseStaleWorker(ctx,api.baseUrl,held);const final=await ctx.snapshot(api.baseUrl);const offline=final.resources.excursions.filter((item)=>item.shipmentId===fixture.shipment.shipmentId&&item.kind==="OFFLINE");assert.equal(offline.length,1);assert.equal(offline[0].state,"RESOLVED");assert.equal(final.resources.shipmentProjections.find((item)=>item.shipmentId===fixture.shipment.shipmentId).lastSequence,1);return ctx.pass();
});

const C05 = guardedCase("C-05", ["STALE_WORK_AUTHORITY","CUSTODY_RECALL_AUTHORITY"], async (ctx) => {
  const fixture=ctx.fixtures.custody(),{api}=await prepare(ctx,fixture),asOf=(await ctx.snapshot(api.baseUrl)).asOf,body={...fixture.custodyBody,steps:fixture.custodyBody.steps.map((step)=>({...step,windowStart:new Date(Date.parse(asOf)-1_000).toISOString(),windowEnd:new Date(Date.parse(asOf)+3_000).toISOString()}))},created=await createCustody(ctx,api.baseUrl,fixture,"expiry",{body}),offered=successful(await offerHandoff(ctx,api.baseUrl,created.chain.custodyChainId,created.chain.revision)),handoff=resourceFrom(offered.json,"custodyHandoffId","handoff"),held=await heldWorker(ctx,"CUSTODY_HANDOFF_EXPIRY"),workerA=held.worker;await waitForWork(ctx,api.baseUrl,(item)=>item.kind==="CUSTODY_HANDOFF_EXPIRY"&&item.state==="LEASED",{processes:[workerA],intervalMs:5,timeoutMs:20_000});await new Promise(resolve=>setTimeout(resolve,3_200));const replacement=await ctx.startWorker(),accept=await acceptHandoff(ctx,api.baseUrl,fixture,handoff,created.chain.revision,"expiry-race",{expectSuccess:false}),final=await waitSnapshot(ctx,api.baseUrl,(snapshot)=>{const chain=snapshot.managerResources.custodyChains.find((item)=>item.custodyChainId===created.chain.custodyChainId);return chain&&["COMPLETED","CANCELLED"].includes(chain.state);},{processes:[replacement],timeoutMs:20_000}),chain=final.managerResources.custodyChains.find((item)=>item.custodyChainId===created.chain.custodyChainId);assert.ok((accept.status===200&&chain.state==="COMPLETED")||(accept.status===409&&chain.state==="CANCELLED"));assert.ok(final.managerResources.custodyHandoffs.filter((item)=>item.custodyChainId===chain.custodyChainId&&item.state==="ACCEPTED").length<=1);await releaseStaleWorker(ctx,api.baseUrl,held);return ctx.pass();
});

const C06 = guardedCase("C-06", ["STALE_WORK_AUTHORITY","CUSTODY_RECALL_AUTHORITY"], async (ctx) => {
  const fixture=recallFixture(ctx),{api}=await prepare(ctx,fixture),expected=frozenRecallSet(resources(await ctx.snapshot(api.baseUrl)).shipments,fixture.tenant.tenantId,fixture.recallBody.productLotCode),recall=await createRecall(ctx,api.baseUrl,fixture);await quarantineRecall(ctx,api.baseUrl,recall.recall.recallId,recall.recall.revision);const faults=await faultWorkers(ctx,"QUARANTINE_ENFORCE"),workers=faults.workers;await waitSnapshot(ctx,api.baseUrl,(snapshot)=>snapshot.work.filter((item)=>["RECALL_PROPAGATE","QUARANTINE_ENFORCE"].includes(item.kind)&&item.state==="LEASED").length>=2,{processes:workers,intervalMs:5,timeoutMs:30_000});await Promise.all(workers.slice(0,2).map((worker)=>ctx.kill(worker)));const replacements=await Promise.all(Array.from({length:2},()=>ctx.startWorker())),final=await waitSnapshot(ctx,api.baseUrl,(snapshot)=>snapshot.managerResources.recallOrders.some((item)=>item.recallId===recall.recall.recallId&&item.state==="CONTAINED"),{processes:[...workers.slice(2),...replacements],timeoutMs:90_000,intervalMs:1_000}),actions=final.managerResources.quarantineActions.filter((item)=>item.recallId===recall.recall.recallId);assert.deepEqual(actions.map((item)=>item.shipmentId).sort(),expected);assert.equal(actions.length,2_500);assert.ok(actions.every((item)=>item.state==="APPLIED"));assert.equal(actions.some((item)=>item.shipmentId===fixture.otherShipment),false);const terminal=await shipmentAction(ctx,api.baseUrl,fixture.shipment.shipmentId,"deliver","quarantined",{expectSuccess:false});semanticError(terminal,409,"SHIPMENT_QUARANTINED");await releaseStaleWorker(ctx,api.baseUrl,faults.stale);return ctx.pass();
});

async function assertDeadLetter(ctx, baseUrl, fixture, previousDispatcher) {
  await ctx.stop(previousDispatcher);
  const receiver = await ctx.receiver({ path: '/dead-letter', behavior: entry => { entry.observedAtMs = performance.now(); return { status: 500 }; } });
  const response = successful(await ctx.mutate(baseUrl, '/api/v1/notification-policies', ctx.key('dead-letter-policy'), {
    tenantId: fixture.tenant.tenantId, eventKinds: ['RECALL_ISSUED'], destination: receiver.url, rateLimitPerMinute: 60, state: 'ACTIVE',
  }));
  const policy = resourceFrom(response.json, 'notificationPolicyId', 'policy');
  await createRecall(ctx, baseUrl, fixture, 'dead-letter', { body: { tenantId: fixture.tenant.tenantId, productLotCode: fixture.shipment.productLotCode, reason: 'Delivery retry verification' } });
  const dispatcher = await ctx.startDispatcher();
  const snapshot = await waitSnapshot(ctx, baseUrl, value => value.resources.notificationDeliveries.some(row => row.notificationPolicyId === policy.notificationPolicyId && row.state === 'DEAD_LETTER'), { processes: [dispatcher], timeoutMs: 90_000 });
  const deliveries = snapshot.resources.notificationDeliveries.filter(row => row.notificationPolicyId === policy.notificationPolicyId);
  assert.equal(deliveries.length, 1);
  assert.deepEqual([deliveries[0].attempts, deliveries[0].nextAttemptAt, deliveries[0].deliveredAt], [6, null, null]);
  assert.equal(receiver.ledger.length, 6, 'six admitted failures, not quota deferrals');
  for (let i = 1; i < 6; i++) assert.ok(receiver.ledger[i].observedAtMs - receiver.ledger[i - 1].observedAtMs >= 2 ** (i - 1) * 1000, 'published retry minimum');
  assertNotificationWire(snapshot, receiver.ledger);
  assertNotificationIdentity(deliveries, receiver.ledger);
}

const C07 = guardedCase("C-07", ["EVENT_DELIVERY_AUTHORITY","TENANT_SECRET_AUTHORITY"], async (ctx) => {
  const receiver=await ctx.receiver({path:"/events",behavior:(_entry,ledger)=>ledger.length===1?{status:204,delayMs:5_000}:ledger.length===2?{status:500}:ledger.length===3?{disconnect:true}:{status:204}}),fixture=ctx.fixtures.notification(receiver.url),{api,workers}=await prepare(ctx,fixture,{workerCount:2});for(const reading of fixture.readings.slice(0,3))await ingest(ctx,api.baseUrl,fixture,reading,`delivery-${reading.sequence}`);const dispatcherA=await ctx.startDispatcher({webhookUrl:receiver.url});await ctx.waitFor(()=>receiver.ledger.length>=1,{processes:[dispatcherA],timeoutMs:20_000,label:"receiver read complete request"});await ctx.kill(dispatcherA);const dispatcherB=await ctx.startDispatcher({webhookUrl:receiver.url});await ctx.waitFor(()=>receiver.ledger.some((entry)=>entry.acknowledged&&entry.responseStatus===204),{processes:[dispatcherB],timeoutMs:30_000,label:"unknown ACK replay delivered"});const snapshot=await ctx.snapshot(api.baseUrl),deliveries=snapshot.resources.notificationDeliveries.filter((item)=>item.notificationPolicyId===fixture.policy.notificationPolicyId);assert.ok(deliveries.length>0);assertNotificationIdentity(deliveries,receiver.ledger);assertNotificationWire(snapshot,receiver.ledger);const ids=new Set(receiver.ledger.map((entry)=>entry.headers["x-coldchain-event-id"]));assert.equal(ids.has(undefined),false);assertSnapshotShape(snapshot,{secrets:fixture.carrierDevices.map((item)=>item.secret)});await assertDeadLetter(ctx,api.baseUrl,fixture,dispatcherB);return ctx.pass();
});

const C08 = guardedCase("C-08", ["EVENT_DELIVERY_AUTHORITY"], async (ctx) => {
  const receiver=await ctx.receiver({path:"/events",behavior:(entry)=>{entry.observedAtMs=performance.now();return{status:204};}}),fixture=ctx.fixtures.notification(receiver.url);fixture.seed={...fixture.seed,notificationPolicies:[{...fixture.policy,rateLimitPerMinute:6},{...fixture.policy,notificationPolicyId:ctx.uuid("quota-policy-2"),rateLimitPerMinute:6}]};const{api,workers}=await prepare(ctx,fixture,{workerCount:2});let sequence=0;for(let cycle=0;cycle<6;cycle+=1){for(const temperatureMilliC of[9_000,9_000,9_000,5_000,5_000,5_000]){sequence+=1;const reading=fixture.reading(`quota-${sequence}`,{sequence,temperatureMilliC});await ingest(ctx,api.baseUrl,fixture,reading,`quota-${sequence}`);}await waitSnapshot(ctx,api.baseUrl,(snapshot)=>snapshot.resources.excursions.filter((item)=>item.shipmentId===fixture.shipment.shipmentId).length>=cycle+1,{processes:workers});}const dispatchers=await Promise.all([ctx.startDispatcher({webhookUrl:receiver.url}),ctx.startDispatcher({webhookUrl:receiver.url})]);await ctx.waitFor(()=>receiver.ledger.length>=6,{processes:dispatchers,timeoutMs:30_000,label:"shared quota deliveries"});await ctx.kill(dispatchers[0]);const replacement=await ctx.startDispatcher({webhookUrl:receiver.url});await new Promise((resolve)=>setTimeout(resolve,61_000));assertSlidingQuota(receiver.ledger.map(entry=>entry.observedAtMs),6,59_900);assert.ok(receiver.ledger.length>6,"quota resumes after the window expires");const first=receiver.ledger[0].observedAtMs,firstMinute=receiver.ledger.filter((entry)=>entry.observedAtMs-first<60_000);assert.ok(firstMinute.length<=6,"tenant aggregate respects published per-minute bound across dispatchers and restart");const snapshot=await ctx.snapshot(api.baseUrl);assert.equal(new Set(snapshot.resources.notificationDeliveries.map((item)=>item.notificationDeliveryId)).size,snapshot.resources.notificationDeliveries.length);assertNotificationIdentity(snapshot.resources.notificationDeliveries,receiver.ledger);assertNotificationWire(snapshot,receiver.ledger);const firstSeen=[...new Set(receiver.ledger.map((entry)=>entry.headers["x-coldchain-event-id"]).filter(Boolean))],observedEvents=firstSeen.map((eventId)=>snapshot.events.find((item)=>item.eventId===eventId)).filter(Boolean);for(const events of Map.groupBy(observedEvents,(item)=>item.aggregateId).values()){const sequences=events.map((item)=>item.sequence);assert.deepEqual(sequences,[...sequences].sort((a,b)=>a-b),"receiver preserves per-aggregate Event order");}await ctx.stop(replacement);return ctx.pass();
});

export const C_CASES=[C01,C02,C03,C04,C05,C06,C07,C08];
