import assert from "node:assert/strict";

import { assertArtifactVersion,assertChunkReceipt,assertPublicError,assertRelease,assertReleaseDetail,assertSnapshot,assertUploadSession,assertVerificationResult,canonical } from "../lib/oracle.mjs";
import { uploadDeclaration } from "../lib/fixtures.mjs";

export function defineCase(id,fixtureFamily,action,oracle,seams,run){return Object.freeze({id,taskId:"artifactvault",fixtureFamily,action,oracle,seams:Object.freeze([...seams]),run});}
export function caseResult(ctx,details={}){return{evidence:[{caseId:ctx.caseId,taskId:"artifactvault",...details}]};}
export function requireStatus(response,status,label="request"){const accepted=Array.isArray(status)?status:[status];assert.ok(accepted.includes(response.status),`${label}: expected ${accepted.join("/")}, got ${response.status}: ${response.text}`);return response.json;}
export function expectError(ctx,response,status,code,options={}){ctx.assert(`${code} exact public error`,()=>assertPublicError(response,status,code),options);return response;}
export function uploadView(json){return json?.uploadSession??json;}
export function verificationView(json){return Object.hasOwn(json??{},"verificationResult")?json.verificationResult:null;}
export async function boot(ctx,options={}){if(options.seed)await ctx.seedBundle(options.seed,{workspace:options.workspace});const apis=[];for(let index=0;index<(options.apiCount??1);index+=1)apis.push(await ctx.startApi({workspace:options.workspace}));return{apis,api:apis[0]};}
export async function snapshot(ctx,url,options={}){const value=await ctx.snapshot(url,options);ctx.assert("verification snapshot exact and sorted",()=>assertSnapshot(value,{final:options.final??true}),options.assertionOptions);return value;}
export function findVersion(state,packageName,version,platform){return state.resources.artifactVersions.find((item)=>item.packageName===packageName&&item.version===version&&(platform===undefined||item.platform===platform));}
export function findUpload(state,uploadId){return state.resources.uploadSessions.find((item)=>item.uploadId===uploadId);}
export function findRelease(state,releaseId){return state.resources.releases?.find((item)=>item.releaseId===releaseId);}
export function workFor(state,kind,aggregateId){return state.work.filter((item)=>item.kind===kind&&(aggregateId===undefined||item.aggregateId===aggregateId));}
export function eventsFor(state,aggregateId){return state.events.filter((item)=>item.aggregateId===aggregateId);}
export async function waitSnapshot(ctx,url,predicate,options={}){return ctx.waitFor(async()=>{const state=await ctx.snapshot(url,{timeoutMs:options.requestTimeoutMs});return predicate(state)?state:undefined;},{label:options.label??"ArtifactVault durable state",timeoutMs:options.timeoutMs??60_000,intervalMs:options.intervalMs??100,processes:options.processes??[]});}
export async function waitUpload(ctx,url,uploadId,states,options={}){const expected=new Set(Array.isArray(states)?states:[states]);return ctx.waitFor(async()=>{const response=await ctx.getUpload(url,uploadId,{timeoutMs:options.requestTimeoutMs});if(response.status!==200)return undefined;const upload=uploadView(response.json);return expected.has(upload.state)?{response,upload,verificationResult:verificationView(response.json)}:undefined;},{label:`upload ${uploadId} ${[...expected].join("/")}`,timeoutMs:options.timeoutMs??60_000,intervalMs:options.intervalMs??100,processes:options.processes??[]});}
export async function createUpload(ctx,url,label,bytes,overrides={},options={}){const declaration=uploadDeclaration(ctx.fixtures,label,bytes,overrides),response=await ctx.createUpload(url,declaration,{key:options.key});ctx.equal("upload create status",response.status,201);const upload=uploadView(response.json);ctx.assert("created UploadSession exact",()=>assertUploadSession(upload));ctx.equal("upload declaration echoed",{packageName:upload.packageName,version:upload.version,mediaType:upload.mediaType,expectedSize:upload.expectedSize,expectedSha256:upload.expectedSha256},declaration);return{declaration,response,upload};}
export async function putSequential(ctx,url,uploadId,bytes,options={}){const size=options.chunkBytes??8*1024*1024,receipts=[];for(let start=0;start<bytes.length;start+=size){const chunk=bytes.subarray(start,Math.min(start+size,bytes.length)),response=await ctx.putChunk(url,uploadId,chunk,start,bytes.length,{key:options.keys?.[receipts.length],timeoutMs:options.timeoutMs});ctx.equal("chunk PUT status",response.status,200);ctx.assert("ChunkReceipt exact",()=>assertChunkReceipt(response.json));ctx.equal("chunk advances durable offset",response.json.nextOffset,start+chunk.length);receipts.push(response);}return receipts;}
export async function completeAndVerify(ctx,url,uploadId,options={}){const complete=await ctx.completeUpload(url,uploadId,{key:options.key});ctx.equal("complete returns 202",complete.status,202);ctx.assert("complete returns exact VERIFYING UploadSession",()=>assertUploadSession(uploadView(complete.json),{manager:options.manager??false}));const worker=options.worker??await ctx.startWorker(options.workerOptions);const settled=await waitUpload(ctx,url,uploadId,options.states??(options.manager?["VERIFIED","REJECTED"]:["COMMITTED","REJECTED"]),{timeoutMs:options.timeoutMs??120_000,processes:[worker]});ctx.assert("terminal VerificationResult exact",()=>assertVerificationResult(settled.verificationResult,{manager:options.manager??false}));if(!options.keepWorker&&!options.worker)await ctx.stop(worker);return{complete,worker,...settled};}
export async function commitStandalone(ctx,url,label,bytes,overrides={},options={}){const created=await createUpload(ctx,url,label,bytes,overrides,options);await putSequential(ctx,url,created.upload.uploadId,bytes,options);const settled=await completeAndVerify(ctx,url,created.upload.uploadId,options);ctx.equal("standalone committed",settled.upload.state,"COMMITTED");const metadata=await ctx.getVersion(url,created.declaration.packageName,created.declaration.version);ctx.equal("committed metadata status",metadata.status,200);ctx.assert("ArtifactVersion exact",()=>assertArtifactVersion(metadata.json));return{...created,...settled,version:metadata.json};}
export function releaseView(json){return json?.release??json;}
export async function createRelease(ctx,url,declaration,options={}){const response=await ctx.createRelease(url,declaration,{key:options.key});ctx.equal("release create status",response.status,200);const release=releaseView(response.json);ctx.assert("DRAFT Release exact",()=>assertRelease(release));ctx.equal("release begins DRAFT",release.state,"DRAFT");return{response,release};}
export async function uploadReleaseMembers(ctx,url,release,bytesByPlatform,options={}){const worker=options.worker??await ctx.startWorker(options.workerOptions);for(const artifact of release.artifacts){const bytes=bytesByPlatform[artifact.platform];assert.ok(Buffer.isBuffer(bytes),`missing bytes for ${artifact.platform}`);await putSequential(ctx,url,artifact.uploadId,bytes,options);await completeAndVerify(ctx,url,artifact.uploadId,{manager:true,worker,keepWorker:true,timeoutMs:options.timeoutMs});}if(!options.keepWorker&&!options.worker)await ctx.stop(worker);const detail=await ctx.getRelease(url,release.packageName,release.version);ctx.equal("release detail status",detail.status,200);ctx.assert("ReleaseDetail exact",()=>assertReleaseDetail(detail.json));return detail.json;}
export async function publishReadyRelease(ctx,url,release,options={}){const response=await ctx.publishRelease(url,release.releaseId,{key:options.key});ctx.equal("publish status",response.status,200);const published=releaseView(response.json);ctx.assert("published Release exact",()=>assertRelease(published));ctx.equal("Release PUBLISHED",published.state,"PUBLISHED");return{response,published};}
export function stableSemantic(ctx,responses,label,options={}){ctx.ok(`${label} has responses`,responses.length>0);ctx.equal(`${label} status stable`,new Set(responses.map((item)=>item.status)).size,1,options);ctx.equal(`${label} body stable`,new Set(responses.map((item)=>canonical(item.json))).size,1,options);return responses[0];}
export function exactBinary(ctx,response,expected,label="content"){ctx.equal(`${label} status`,response.status,200);ctx.equal(`${label} bytes`,response.body,expected);ctx.equal(`${label} Content-Length`,response.headers.get("content-length"),String(expected.length));}
export async function exerciseReleaseUi(ctx,api,{packageName,version,platforms}){await ctx.withPage(api,{width:1280,height:800},async(page)=>{await page.goto("/",{waitUntil:"networkidle"});const releaseNav=page.getByRole("link",{name:/release/i}).or(page.getByRole("button",{name:/release/i}));if(await releaseNav.count())await releaseNav.first().click();const packageInput=page.locator('input[name*="package" i], input[placeholder*="package" i]').first(),versionInput=page.locator('input[name*="version" i], input[placeholder*="version" i]').first();if(await packageInput.count()&&await versionInput.count()){await packageInput.fill(packageName);await versionInput.fill(version);const submit=page.getByRole("button",{name:/view|load|find|search|open|查询|查看/i});if(await submit.count())await submit.first().click();await page.waitForTimeout(250);}const body=(await page.locator("body").innerText()).toLowerCase();for(const platform of platforms)ctx.ok(`UI displays ${platform} platform`,body.includes(platform.toLowerCase()));const select=page.locator("select").filter({has:page.locator("option")}).first();if(await select.count()){for(const platform of platforms){const option=select.locator("option").filter({hasText:platform});if(await option.count())await select.selectOption({label:await option.first().innerText()});}}const links=page.locator('a[href*="/artifacts/"][href*="/content"]');ctx.ok("UI exposes platform content link",await links.count()>0);for(const platform of platforms){const href=await links.filter({hasText:new RegExp(platform,"i")}).first().getAttribute("href").catch(()=>null)??await page.locator(`a[href*="/${platform}/content"]`).first().getAttribute("href").catch(()=>null);ctx.ok(`UI exposes ${platform} content selection`,Boolean(href));const fetched=await page.evaluate(async(url)=>{const response=await fetch(url);return{status:response.status,length:(await response.arrayBuffer()).byteLength};},href);ctx.equal(`UI ${platform} download status`,fetched.status,200);ctx.ok(`UI ${platform} download has bytes`,fetched.length>0);}});}
