import { T,id,ref,record as r,obj,pick,omit,list,union,nullable,name,text,uuid,time,nat,pos,int,empty,page,operation as op,finish,pagination,snapshotSmoke,idem,manager,wire } from './helpers-b.mjs';
const I=n=>id(1,n);
const s={
 Tenant:r('tenantId:uuid name:name createdAt:timestamp'),
 Customer:r('customerId:uuid tenantId:uuid externalRef:name name:name createdAt:timestamp'),
 Plan:r('planId:uuid tenantId:uuid name:name createdAt:timestamp'),
 PriceVersion:r('priceVersionId:uuid tenantId:uuid planId:uuid version:pos currency:currency unitAmountMinor:nat effectiveFrom:timestamp effectiveTo:timestamp|null createdAt:timestamp'),
 Subscription:r('subscriptionId:uuid tenantId:uuid customerId:uuid planId:uuid version:pos quantity:pos periodStart:timestamp periodEnd:timestamp state:ACTIVE|CANCELLED createdAt:timestamp cancelledAt:timestamp|null'),
 ExchangeRateSnapshot:r('exchangeRateSnapshotId:uuid tenantId:uuid baseCurrency:currency quoteCurrency:currency numerator:pos denominator:pos effectiveFrom:timestamp effectiveTo:timestamp|null createdAt:timestamp'),
 LedgerAccount:r('ledgerAccountId:uuid tenantId:uuid currency:currency accountCode:name allowOverdraft:boolean balanceMinor:int createdAt:timestamp'),
 InvoiceLine:r('invoiceLineId:uuid kind:BASE|PRORATION|DISCOUNT|TAX description:string quantity:int unitAmountMinor:nat amountMinor:nat'),
 Invoice:r('invoiceId:uuid tenantId:uuid customerId:uuid subscriptionId:uuid currency:currency periodStart:timestamp periodEnd:timestamp state:DRAFT|OPEN|PAID|PARTIALLY_REFUNDED|REFUNDED|VOID totalMinor:nat paidMinor:nat refundedMinor:nat outstandingMinor:nat priceVersion:int taxVersion:int discountVersion:int exchangeRateSnapshotId:uuid lines:[InvoiceLine] createdAt:timestamp finalizedAt:timestamp|null sequence:pos'),
 PaymentIntent:r('paymentIntentId:uuid invoiceId:uuid amountMinor:nat currency:currency state:CREATED|PROCESSING|SUCCEEDED|FAILED|UNKNOWN providerRequestId:string providerTransactionId:string|null createdAt:timestamp resolvedAt:timestamp|null sequence:pos'),
 Refund:r('refundId:uuid paymentIntentId:uuid amountMinor:nat state:REQUESTED|PROCESSING|SUCCEEDED|FAILED providerTransactionId:string|null createdAt:timestamp resolvedAt:timestamp|null'),
 LedgerEntry:r('ledgerEntryId:uuid postingId:uuid tenantId:uuid currency:currency accountCode:string direction:DEBIT|CREDIT amountMinor:nat referenceType:PAYMENT|REFUND|SETTLEMENT referenceId:uuid createdAt:timestamp'),
 SettlementRun:r('settlementRunId:uuid tenantId:uuid periodStart:timestamp periodEnd:timestamp state:OPEN|SNAPSHOTTING|CALCULATING|POSTING|CLOSED snapshotDigest:sha256|null totalInvoiceMinor:nat totalPaymentMinor:nat totalRefundMinor:nat createdAt:timestamp closedAt:timestamp|null sequence:pos'),
 Dispute:r('disputeId:uuid tenantId:uuid paymentIntentId:uuid externalRef:name amountMinor:pos currency:currency state:OPEN|WON|LOST reservedMinor:nat chargebackPostingId:uuid|null createdAt:timestamp resolvedAt:timestamp|null'),
 Adjustment:r('adjustmentId:uuid tenantId:uuid settlementRunId:uuid originalPostingId:uuid postingId:uuid currency:currency amountMinor:pos direction:DEBIT|CREDIT accountCode:name balancingAccountCode:name reason:name createdAt:timestamp'),
};
s.ManagerLedgerEntry=obj({...s.LedgerEntry.properties,referenceType:{enum:['PAYMENT','REFUND','SETTLEMENT','CHARGEBACK','ADJUSTMENT'],type:'string'}});
const base={tenants:'Tenant',customers:'Customer',plans:'Plan',priceVersions:'PriceVersion',subscriptions:'Subscription',invoices:'Invoice',paymentIntents:'PaymentIntent',refunds:'Refund',exchangeRateSnapshots:'ExchangeRateSnapshot',ledgerAccounts:'LedgerAccount',ledgerEntries:'LedgerEntry',settlementRuns:'SettlementRun'};
export default finish({taskId:'billforge',title:'BillForge',schemas:s,seedTypes:base,resources:{...base,ledgerEntries:'ManagerLedgerEntry',disputes:'Dispute',adjustments:'Adjustment'},importedAt:true,transportErrors:{invalidRequest:{status:400,code:'INVALID_REQUEST'}},
 seedData:{tenants:[{tenantId:I(1),name:'Public workshop',createdAt:T}],customers:[{customerId:I(2),tenantId:I(1),externalRef:'public-customer',name:'Public customer',createdAt:T}],plans:[{planId:I(3),tenantId:I(1),name:'Public fixed plan',createdAt:T}],priceVersions:[{priceVersionId:I(4),tenantId:I(1),planId:I(3),version:1,currency:'USD',unitAmountMinor:2500,effectiveFrom:T,effectiveTo:null,createdAt:T}],subscriptions:[{subscriptionId:I(5),tenantId:I(1),customerId:I(2),planId:I(3),version:1,quantity:1,periodStart:'2035-04-01T00:00:00.000Z',periodEnd:'2035-05-01T00:00:00.000Z',state:'ACTIVE',createdAt:T,cancelledAt:null}],exchangeRateSnapshots:[{exchangeRateSnapshotId:I(6),tenantId:I(1),baseCurrency:'USD',quoteCurrency:'USD',numerator:1,denominator:1,effectiveFrom:T,effectiveTo:null,createdAt:T}],ledgerAccounts:[{ledgerAccountId:I(7),tenantId:I(1),currency:'USD',accountCode:'CustomerReceivable',allowOverdraft:false,balanceMinor:0,createdAt:T},{ledgerAccountId:I(8),tenantId:I(1),currency:'USD',accountCode:'CashClearing',allowOverdraft:false,balanceMinor:0,createdAt:T},{ledgerAccountId:I(9),tenantId:I(1),currency:'USD',accountCode:'RefundExpense',allowOverdraft:false,balanceMinor:0,createdAt:T}]},
 workKinds:['INVOICE_FINALIZATION','PAYMENT_CAPTURE','REFUND_PROCESSING','SETTLEMENT_CLOSE'],eventTypes:['invoice.created','invoice.finalized','payment.succeeded','payment.failed','payment.unknown','refund.succeeded','settlement.closed'],
 operations:[
 op('tenant-create','POST','/api/v1/tenants',r('name:name'),ref('Tenant')),
 op('customer-create','POST','/api/v1/customers',pick(s.Customer,['tenantId','externalRef','name']),ref('Customer')),
 op('plan-create','POST','/api/v1/plans',pick(s.Plan,['tenantId','name']),ref('Plan')),
 op('price-version-create','POST','/api/v1/price-versions',pick(s.PriceVersion,['tenantId','planId','version','currency','unitAmountMinor','effectiveFrom','effectiveTo']),ref('PriceVersion')),
 op('subscription-create','POST','/api/v1/subscriptions',pick(s.Subscription,['tenantId','customerId','planId','quantity','periodStart','periodEnd']),ref('Subscription')),
 op('subscription-change','POST','/api/v1/subscriptions/:subscriptionId/change',r('expectedVersion:pos planId:uuid quantity:pos effectiveAt:timestamp'),ref('Subscription')),
 op('subscription-cancel','POST','/api/v1/subscriptions/:subscriptionId/cancel',r('expectedVersion:pos effectiveAt:timestamp'),ref('Subscription')),
 op('invoice-create','POST','/api/v1/invoices',r('tenantId:uuid customerId:uuid subscriptionId:uuid subscriptionVersion:pos periodStart:timestamp periodEnd:timestamp currency:currency'),ref('Invoice')),
 op('invoice-finalize','POST','/api/v1/invoices/:invoiceId/finalize',empty,ref('Invoice')),
 op('invoice-get','GET','/api/v1/invoices/:invoiceId',null,ref('Invoice')),
 op('invoice-ledger','GET','/api/v1/invoices/:invoiceId/ledger',null,page(ref('ManagerLedgerEntry')),{parameters:pagination}),
 op('payment-intent-create','POST','/api/v1/payment-intents',pick(s.PaymentIntent,['invoiceId','amountMinor','currency']),ref('PaymentIntent')),
 op('payment-intent-reconcile','POST','/api/v1/payment-intents/:paymentIntentId/reconcile',empty,ref('PaymentIntent')),
 op('provider-webhook','POST','/api/v1/provider/webhooks',r('providerEventId:name providerRequestId:name providerTransactionId:name outcome:SUCCEEDED|DECLINED occurredAt:timestamp'),ref('PaymentIntent')),
 op('refund-create','POST','/api/v1/payment-intents/:paymentIntentId/refunds',r('amountMinor:pos'),ref('Refund')),
 op('settlement-create','POST','/api/v1/settlements',pick(s.SettlementRun,['tenantId','periodStart','periodEnd']),ref('SettlementRun')),
 op('settlement-get','GET','/api/v1/settlements/:settlementId',null,ref('SettlementRun')),
 op('dispute-create','POST','/api/v1/disputes',pick(s.Dispute,['tenantId','paymentIntentId','externalRef','amountMinor']),ref('Dispute'),{source:`${manager}; ${wire} (new route and resource)`}),
 op('dispute-resolve','POST','/api/v1/disputes/:disputeId/resolve',r('outcome:WON|LOST'),ref('Dispute'),{source:`${manager}; ${wire} (new route and resource)`}),
 op('adjustment-create','POST','/api/v1/adjustments',pick(s.Adjustment,['tenantId','settlementRunId','originalPostingId','currency','amountMinor','direction','accountCode','balancingAccountCode','reason']),ref('Adjustment'),{source:`${manager}; ${wire} (new route and resource)`}),
 ],
 smoke:[snapshotSmoke([['tenants',{tenantId:I(1)}],['customers',{customerId:I(2),tenantId:I(1)}],['priceVersions',{priceVersionId:I(4),planId:I(3),unitAmountMinor:2500}],['subscriptions',{subscriptionId:I(5),customerId:I(2)}],['exchangeRateSnapshots',{exchangeRateSnapshotId:I(6),numerator:1,denominator:1}],['ledgerAccounts',{ledgerAccountId:I(7),balanceMinor:0}]]),{operationId:'tenant-create',headers:idem('billforge-tenant'),body:{name:'Public second workshop'},expectStatus:200,capture:{tenantId:['tenantId']},expectBody:{name:'Public second workshop'}},snapshotSmoke([['tenants',{tenantId:'${tenantId}',name:'Public second workshop'}]])],
 notes:[
 'V2 wire clarification: V1 names Tenant, Customer, Plan, PriceVersion, Subscription, ExchangeRateSnapshot and LedgerAccount but never defines their fields. Their complete schemas here are new public transport definitions, shared by seed, API and snapshot. Public creation excludes generated IDs/times/state. Exchange rates are exact positive integer ratios; this fixes their representation, not a rounding algorithm.',
 'Unresolved original business specification: tax/discount configuration has neither a public route nor a V1 seed collection; proration units and rounding, tax rounding and discount allocation formulas are not defined. This contract does not manufacture those algorithms or a hidden-rule fixture. Invoice/payment smoke is deliberately excluded until those business choices are separately published.',
 'V2 wire clarification: subscription change/cancel use expectedVersion and effectiveAt; invoice generation names subscriptionVersion and the billing period. Provider webhooks carry providerEventId, providerRequestId, providerTransactionId, outcome and occurredAt and return PaymentIntent; transport failures are not successful webhook outcomes.',
 'Manager only requested impact analysis and a staged plan in its original turn. V2 explicitly publishes new disputes/resolve/adjustments wire interfaces to support the newly requested complete interface scaffold. Their fields and route spelling are not retrospectively claimed as original requirements. CHARGEBACK/ADJUSTMENT extend snapshot ledger referenceType; legacy seed remains unchanged. Dispute reservations, one balanced loss posting and next-period corrections remain business implementation responsibilities.',
 ],
});
