import { ref, str, name, uuid, time, sha, int, nat, pos, nullable, list, obj, enumeration as en, page, pick, empty, T, uid, basic, work, event, seedShape, snapshotShape, operation as op, standardOps, commands, environmentVariables, keyed, admin, source, manager, parameter, pagination, sharedNotes } from './helpers-a.mjs';

const tenantId = uid(4, 1), profileId = uid(4, 2), policyId = uid(4, 3), uploadId = uid(4, 4), assetId = uid(4, 5), aliasId = uid(4, 6), grantId = uid(4, 7);
const publicBytes = 'Public media\n';
const publicDigest = 'a95925ca0003faeae66ebb99e4e7664f80c4a85e5286ee8577b39d8e37575277';
const schemas = {
  ...basic,
  UploadSession: obj({ uploadId: uuid, tenantId: uuid, fileName: name, contentType: name, expectedSize: { ...pos, maximum: 1073741824 }, expectedSha256: sha, partSize: { ...pos, minimum: 8192, maximum: 8388608 }, state: en('OPEN', 'COMPLETING', 'COMPLETED', 'ABORTED', 'EXPIRED', 'FAILED'), expiresAt: time, assetId: nullable(uuid), createdAt: time, completedAt: nullable(time), sequence: nat }),
  UploadPart: obj({ uploadId: uuid, partNumber: pos, start: nat, end: nat, size: pos, sha256: sha, createdAt: time }),
  BlobObject: obj({ blobId: uuid, sha256: sha, size: nat, state: en('STAGING', 'COMMITTED', 'QUARANTINED', 'DELETING', 'DELETED'), createdAt: time, deletedAt: nullable(time) }),
  MediaAsset: obj({ assetId: uuid, tenantId: uuid, sourceBlobId: uuid, fileName: name, contentType: name, size: pos, sha256: sha, state: en('QUARANTINED', 'SCANNING', 'CLEAN', 'PROCESSING', 'READY', 'INFECTED', 'FAILED'), createdAt: time, readyAt: nullable(time), sequence: nat }),
  ScanJob: obj({ scanJobId: uuid, assetId: uuid, state: en('PENDING', 'RUNNING', 'CLEAN', 'INFECTED', 'UNKNOWN', 'FAILED'), attempt: nat, scannerRequestId: str, signature: { type: 'null' }, createdAt: time, finishedAt: nullable(time) }),
  ScanResult: obj({ scanResultId: uuid, scanJobId: uuid, scannerRequestId: str, state: en('CLEAN', 'INFECTED', 'UNKNOWN'), receivedAt: time }),
  TranscodeProfile: obj({ profileId: uuid, tenantId: uuid, name, revision: pos, operation: en('COPY', 'PREFIX'), prefixBase64: nullable({ type: 'string', contentEncoding: 'base64' }), maxAttempts: pos, createdAt: time }),
  TranscodeJob: obj({ transcodeJobId: uuid, assetId: uuid, profileId: uuid, profileRevision: pos, state: en('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'), attempt: nat, renditionId: nullable(uuid), createdAt: time, finishedAt: nullable(time) }),
  Rendition: obj({ renditionId: uuid, assetId: uuid, profileId: uuid, profileRevision: pos, blobId: uuid, size: nat, sha256: sha, state: en('READY', 'FAILED', 'DELETED'), createdAt: time, deletedAt: nullable(time) }),
  AccessGrant: obj({ grantId: uuid, tenantId: uuid, assetId: uuid, renditionId: nullable(uuid), expiresAt: time, state: en('ACTIVE', 'REVOKED', 'EXPIRED'), createdAt: time, revokedAt: nullable(time), publicationRevisionId: nullable(uuid) }),
  Retention: obj({ expiredUploadSeconds: nat, stagingSeconds: nat, infectedSourceSeconds: nat, failedRenditionSeconds: nat, expiredGrantSeconds: nat, unreferencedBlobSeconds: nat }),
  CleanupPolicy: obj({ policyId: uuid, tenantId: uuid, revision: pos, retention: ref('Retention'), createdAt: time }),
  CleanupRun: obj({ cleanupRunId: uuid, tenantId: uuid, policyRevision: pos, cutoffAt: time, state: en('PLANNED', 'RUNNING', 'COMPLETED', 'FAILED'), plannedCount: nat, deletedCount: nat, createdAt: time, finishedAt: nullable(time), sequence: nat }),
  CleanupEntry: obj({ cleanupEntryId: uuid, cleanupRunId: uuid, targetType: en('UPLOAD_PARTS', 'STAGING_BLOB', 'INFECTED_SOURCE', 'FAILED_RENDITION', 'ACCESS_GRANT', 'UNREFERENCED_BLOB'), targetId: uuid, state: en('PLANNED', 'DELETING', 'DELETED', 'SKIPPED', 'FAILED'), reason: nullable(str), createdAt: time, finishedAt: nullable(time) }),
  MediaAlias: obj({ aliasId: uuid, tenantId: uuid, name, requiredProfileIds: list(uuid, { uniqueItems: true }), retentionSeconds: nat, currentRevision: nat, currentPublicationRevisionId: nullable(uuid), createdAt: time }),
  PublicationRevision: obj({ publicationRevisionId: uuid, aliasId: uuid, tenantId: uuid, revision: pos, assetId: uuid, sourceBlobId: uuid, renditionIds: list(uuid, { uniqueItems: true }), createdAt: time, retainUntil: time }),
  ResolvedSource: obj({ assetId: uuid, contentType: name, size: pos, sha256: sha }),
  ResolvedRendition: obj({ renditionId: uuid, profileId: uuid, profileRevision: pos, size: nat, sha256: sha }),
  Work: work(['UPLOAD_EXPIRY', 'VIRUS_SCAN', 'TRANSCODE', 'CLEANUP_DELETE', 'PUBLICATION_SWITCH']),
  DomainEvent: event(['upload.created', 'upload.completed', 'asset.clean', 'asset.infected', 'transcode.succeeded', 'transcode.failed', 'grant.revoked', 'cleanup.started', 'cleanup.completed', 'PUBLICATION_SWITCH'], obj({ uploadId: uuid, assetId: uuid, profileId: uuid, renditionId: uuid, grantId: uuid, cleanupRunId: uuid, aliasId: uuid, publicationRevisionId: uuid, sha256: sha, size: nat, revision: nat }, [])),
};
schemas.CreateProfile = pick(schemas.TranscodeProfile, ['tenantId', 'name', 'operation', 'prefixBase64', 'maxAttempts']);
schemas.CreateUpload = pick(schemas.UploadSession, ['tenantId', 'fileName', 'contentType', 'expectedSize', 'expectedSha256', 'partSize', 'expiresAt']);
schemas.UploadRead = obj({ ...schemas.UploadSession.properties, parts: list(ref('UploadPart')) });
schemas.CreateGrant = obj({ renditionId: nullable(uuid), expiresAt: time, publicationRevisionId: uuid }, ['renditionId', 'expiresAt']);
schemas.GrantResponse = obj({ grant: ref('AccessGrant'), url: str, token: str });
schemas.CleanupRead = obj({ ...schemas.CleanupRun.properties, entries: list(ref('CleanupEntry')) });
schemas.AliasResolution = obj({ aliasId: uuid, publicationRevisionId: uuid, revision: pos, source: ref('ResolvedSource'), renditions: list(ref('ResolvedRendition')) });
const collections = Object.fromEntries(Object.entries({ tenants: 'Tenant', uploadSessions: 'UploadSession', uploadParts: 'UploadPart', blobObjects: 'BlobObject', mediaAssets: 'MediaAsset', scanJobs: 'ScanJob', scanResults: 'ScanResult', transcodeProfiles: 'TranscodeProfile', transcodeJobs: 'TranscodeJob', renditions: 'Rendition', accessGrants: 'AccessGrant', cleanupPolicies: 'CleanupPolicy', cleanupRuns: 'CleanupRun', cleanupEntries: 'CleanupEntry', mediaAliases: 'MediaAlias', publicationRevisions: 'PublicationRevision' }).map(([key, type]) => [key, list(ref(type))]));
schemas.Snapshot = snapshotShape(collections);
const retention = { expiredUploadSeconds: 3600, stagingSeconds: 3600, infectedSourceSeconds: 86400, failedRenditionSeconds: 86400, expiredGrantSeconds: 3600, unreferencedBlobSeconds: 86400 };
const uploadInput = { tenantId, fileName: 'public.txt', contentType: 'text/plain', expectedSize: 13, expectedSha256: publicDigest, partSize: 8192, expiresAt: '2031-04-06T06:07:08.000Z' };
const seed = { schema: seedShape(collections), example: { schemaVersion: 1, seedVersion: 'mediadock-public-v2-1', importedAt: T, tenants: [{ tenantId, name: 'Public Studio' }], uploadSessions: [{ uploadId, ...uploadInput, state: 'OPEN', assetId: null, createdAt: T, completedAt: null, sequence: 0 }], uploadParts: [], blobObjects: [], mediaAssets: [], scanJobs: [], scanResults: [], transcodeProfiles: [{ profileId, tenantId, name: 'Public Original', revision: 1, operation: 'COPY', prefixBase64: null, maxAttempts: 3, createdAt: T }], transcodeJobs: [], renditions: [], accessGrants: [], cleanupPolicies: [{ policyId, tenantId, revision: 1, retention, createdAt: T }], cleanupRuns: [], cleanupEntries: [], mediaAliases: [{ aliasId, tenantId, name: 'Public Front Page', requiredProfileIds: [profileId], retentionSeconds: 86400, currentRevision: 0, currentPublicationRevisionId: null, createdAt: T }], publicationRevisions: [] } };
const binary = { type: 'string', contentMediaType: 'application/octet-stream' };
const mediaParameters = [parameter('token', { type: 'string', minLength: 1 }, 'query', true), parameter('Range', { type: 'string', pattern: '^bytes=(?:[0-9]+-[0-9]*|-[0-9]+)$' }, 'header'), parameter('If-None-Match', str, 'header')];
const operations = [
  op('createTenant', 'POST', '/api/v1/tenants', obj({ name }), ref('Tenant'), { body: { name: 'Another Public Studio' }, headers: keyed('media-example-tenant') }),
  op('createProfile', 'POST', '/api/v1/transcode-profiles', ref('CreateProfile'), ref('TranscodeProfile'), { body: { tenantId, name: 'Public Prefix', operation: 'PREFIX', prefixBase64: 'UHVibGljOiA=', maxAttempts: 3 }, headers: keyed('media-example-profile') }),
  op('createProfileRevision', 'POST', '/api/v1/transcode-profiles/:profileId/revisions', obj({ operation: en('COPY', 'PREFIX'), prefixBase64: nullable({ type: 'string', contentEncoding: 'base64' }), maxAttempts: pos }), ref('TranscodeProfile'), { params: { profileId }, body: { operation: 'COPY', prefixBase64: null, maxAttempts: 4 }, headers: keyed('media-example-profile-revision') }),
  op('createCleanupPolicy', 'POST', '/api/v1/cleanup-policies', obj({ tenantId: uuid, retention: ref('Retention') }), ref('CleanupPolicy'), { body: { tenantId, retention }, headers: keyed('media-example-policy') }),
  op('createUpload', 'POST', '/api/v1/uploads', ref('CreateUpload'), ref('UploadSession'), { body: uploadInput, headers: keyed('media-example-upload') }, source('Multipart upload contract')),
  op('getUpload', 'GET', '/api/v1/uploads/:uploadId', null, ref('UploadRead'), { params: { uploadId } }, source('Multipart upload contract')),
  op('putPart', 'PUT', '/api/v1/uploads/:uploadId/parts/:partNumber', { ...binary, minLength: 1 }, ref('UploadPart'), { params: { uploadId, partNumber: 1 }, body: publicBytes, headers: { ...keyed('media-example-part'), 'Content-Type': 'application/octet-stream', 'Content-Range': 'bytes 0-12/13', 'X-Part-SHA256': publicDigest } }, source('Multipart upload contract'), [parameter('Content-Range', { type: 'string', pattern: '^bytes [0-9]+-[0-9]+/[0-9]+$' }, 'header', true), parameter('X-Part-SHA256', sha, 'header', true)]),
  op('completeUpload', 'POST', '/api/v1/uploads/:uploadId/complete', obj({ parts: list(obj({ partNumber: pos, sha256: sha, size: pos }), { minItems: 1, maxItems: 10000 }) }), ref('UploadSession'), { params: { uploadId }, body: { parts: [{ partNumber: 1, sha256: publicDigest, size: 13 }] }, headers: keyed('media-example-complete') }),
  op('abortUpload', 'POST', '/api/v1/uploads/:uploadId/abort', empty, ref('UploadSession'), { params: { uploadId }, body: {}, headers: keyed('media-example-abort') }, source('Multipart upload contract')),
  op('getAsset', 'GET', '/api/v1/assets/:assetId', null, ref('MediaAsset'), { params: { assetId } }, source('Public HTTP surface')),
  op('listRenditions', 'GET', '/api/v1/assets/:assetId/renditions', null, page(ref('Rendition')), { params: { assetId }, query: { limit: 20 } }, source('Public HTTP surface'), pagination),
  op('createGrant', 'POST', '/api/v1/assets/:assetId/access-grants', ref('CreateGrant'), ref('GrantResponse'), { params: { assetId }, body: { renditionId: null, expiresAt: '2031-04-05T06:17:08.000Z' }, headers: keyed('media-example-grant') }, source('Temporary access contract')),
  op('revokeGrant', 'POST', '/api/v1/access-grants/:grantId/revoke', empty, ref('AccessGrant'), { params: { grantId }, body: {}, headers: keyed('media-example-revoke') }, source('Temporary access contract')),
  { ...op('getMedia', 'GET', '/media/:grantId', null, binary, { params: { grantId }, query: { token: 'public-example-token' }, headers: { Range: 'bytes=0-3' } }, source('Temporary access contract'), mediaParameters), successStatuses: [200, 206, 304], successResponses: { 206: { response: binary }, 304: { description: 'No body; matching ETag' } }, responseHeaders: { 'Content-Type': str, 'Content-Length': str, ETag: str, 'Accept-Ranges': { const: 'bytes' }, 'Content-Range': str } },
  { ...op('headMedia', 'HEAD', '/media/:grantId', null, { type: 'null' }, { params: { grantId }, query: { token: 'public-example-token' } }, source('Temporary access contract'), mediaParameters), successStatuses: [200, 206, 304], successResponses: { 200: { description: 'No body; full representation headers' }, 206: { description: 'No body; range representation headers' }, 304: { description: 'No body; matching ETag' } }, responseHeaders: { 'Content-Type': str, 'Content-Length': str, ETag: str, 'Accept-Ranges': { const: 'bytes' }, 'Content-Range': str } },
  op('recordScanResult', 'POST', '/api/v1/scanner/results', obj({ scanJobId: uuid, scannerRequestId: str, state: en('CLEAN', 'INFECTED', 'UNKNOWN'), signature: nullable(str) }), ref('ScanResult'), { body: { scanJobId: uid(4, 8), scannerRequestId: 'public-scan-request', state: 'CLEAN', signature: null }, headers: keyed('media-example-scan') }),
  op('reconcileScan', 'POST', '/api/v1/scan-jobs/:scanJobId/reconcile', empty, ref('ScanJob'), { params: { scanJobId: uid(4, 8) }, body: {}, headers: keyed('media-example-reconcile') }, source('Virus scan gate')),
  op('createCleanupRun', 'POST', '/api/v1/cleanup-runs', obj({ tenantId: uuid, policyRevision: pos, cutoffAt: time }), ref('CleanupRun'), { body: { tenantId, policyRevision: 1, cutoffAt: T }, headers: keyed('media-example-cleanup') }),
  op('getCleanupRun', 'GET', '/api/v1/cleanup-runs/:cleanupRunId', null, ref('CleanupRead'), { params: { cleanupRunId: uid(4, 9) } }),
  op('createAlias', 'POST', '/api/v1/media-aliases', obj({ tenantId: uuid, name, requiredProfileIds: list(uuid), retentionSeconds: nat }), obj({ alias: ref('MediaAlias') }), { body: { tenantId, name: 'Public Feature', requiredProfileIds: [profileId], retentionSeconds: 86400 }, headers: keyed('media-example-alias') }, manager),
  op('publishAlias', 'POST', '/api/v1/media-aliases/:aliasId/publish', obj({ expectedRevision: nat, assetId: uuid }), obj({ alias: ref('MediaAlias'), revision: ref('PublicationRevision') }), { params: { aliasId }, body: { expectedRevision: 0, assetId }, headers: keyed('media-example-publish') }, manager),
  op('getAlias', 'GET', '/api/v1/media-aliases/:aliasId', null, obj({ alias: ref('MediaAlias'), revisions: list(ref('PublicationRevision')) }), { params: { aliasId } }, manager),
  op('resolveAlias', 'GET', '/api/v1/media-aliases/:aliasId/resolve', null, ref('AliasResolution'), { params: { aliasId } }, manager),
  op('createAliasGrant', 'POST', '/api/v1/media-aliases/:aliasId/access-grants', obj({ renditionId: nullable(uuid), expiresAt: time }), ref('GrantResponse'), { params: { aliasId }, body: { renditionId: null, expiresAt: '2031-04-05T06:17:08.000Z' }, headers: keyed('media-example-alias-grant') }, manager),
  ...standardOps(),
];
export default {
  taskId: 'mediadock', title: 'MediaDock', environmentVariables: [...environmentVariables, 'MANAGED_DATA_ROOT', 'GRANT_SIGNING_KEY'], commands, seed, schemas, operations,
  smoke: [
    { operationId: 'snapshot', headers: admin, expectContains: [{ path: ['resources', 'uploadSessions'], match: { uploadId, state: 'OPEN', expectedSha256: publicDigest } }, { path: ['resources', 'transcodeProfiles'], match: { profileId, operation: 'COPY' } }, { path: ['resources', 'cleanupPolicies'], match: { policyId, revision: 1 } }, { path: ['resources', 'mediaAliases'], match: { aliasId, requiredProfileIds: [profileId] } }] },
    { operationId: 'getUpload', params: { uploadId }, expectBody: { uploadId, tenantId, state: 'OPEN', parts: [] } },
    { operationId: 'createProfile', body: { tenantId, name: 'Smoke Public Copy', operation: 'COPY', prefixBase64: null, maxAttempts: 2 }, headers: keyed('media-smoke-profile'), capture: { newProfileId: ['profileId'] }, expectBody: { tenantId, name: 'Smoke Public Copy', revision: 1, operation: 'COPY', prefixBase64: null } },
    { operationId: 'snapshot', headers: admin, expectContains: [{ path: ['resources', 'transcodeProfiles'], match: { profileId: '${newProfileId}', tenantId, maxAttempts: 2 } }] },
    { operationId: 'createAlias', body: { tenantId, name: 'Smoke Alias', requiredProfileIds: ['${newProfileId}'], retentionSeconds: 120 }, headers: keyed('media-smoke-alias'), capture: { newAliasId: ['alias', 'aliasId'] }, expectBody: { alias: { currentRevision: 0, currentPublicationRevisionId: null } } },
    { operationId: 'getAlias', params: { aliasId: '${newAliasId}' }, expectBody: { alias: { aliasId: '${newAliasId}', name: 'Smoke Alias', requiredProfileIds: ['${newProfileId}'] }, revisions: [] } },
  ],
  notes: [...sharedNotes,
    'V2 public wire clarification: upload parts are numbered from 1 and complete accepts {parts:[{partNumber,sha256,size}]}. Upload GET is the UploadSession fields plus complete sorted parts. Completion returns UploadSession with its assetId; asset and scan state are read through their own public resources. The seed imports metadata only: it cannot create physical bytes, READY assets/renditions or aliases pointing at READY publication content.',
    'V2 public wire clarification: TranscodeProfile creation assigns revision 1 and a fresh profileId; a new revision of an existing profile uses the added POST /api/v1/transcode-profiles/:profileId/revisions route. COPY requires prefixBase64:null; PREFIX requires valid canonical Base64 (empty prefix allowed). Profile revisions are immutable; jobs freeze the revision applicable when the asset passes CLEAN.',
    'V2 public wire clarification: CleanupPolicy is versioned per tenant; POST creates the next revision with the fixed six retention-second fields. CleanupEntry has a stable cleanupEntryId and refers to one public target identity, never a path. Cleanup GET is CleanupRun plus its sorted entries. Tenant ownership and all live references are rechecked transactionally before deletion.',
    'V2 privacy conflict resolution: the original Exact public shapes includes ScanJob.signature, but Virus scan gate forbids public persisted signatures. V2 keeps that field for shape compatibility and requires null in all public outputs and seeds. The scanner result input may carry a signature privately; ScanResult exposes only IDs, state and receivedAt. No scanner payload/signature reaches snapshot/events.',
    'V2 Manager wire clarification: the Manager supplied behavior but no routes or object fields. The declared media-aliases create/publish/get/resolve/access-grants routes and MediaAlias/PublicationRevision schemas are new public wire contracts. requiredProfileIds are frozen, deduplicated and UUID-sorted at creation. Publish CAS checks expectedRevision, increments from 0, captures one READY clean asset and its required READY renditions atomically, and records retainUntil=publication time+alias.retentionSeconds. The current revision is retained regardless of that deadline; old revisions remain retained through the deadline and while any grant or stream references their bytes.',
    'V2 Manager wire clarification: publish returns {alias,revision}; alias GET returns {alias,revisions}; resolve returns one immutable source/rendition digest set and never bytes from mixed revisions. Direct asset grant input may pin publicationRevisionId; alias grant always pins the resolved current publication. AccessGrant adds nullable publicationRevisionId, null only for direct non-publication grants. Publish conflicts use 409 PUBLICATION_REVISION_CONFLICT; missing/ineligible content uses 409 ASSET_QUARANTINED; absent resources/unpublished resolution use 404 NOT_FOUND. PUBLICATION_SWITCH is the exact new Work kind and Event type.',
    'V2 transport clarification: media GET emits raw bytes (not a JSON string or base64); HEAD emits no body with the equivalent headers. Full/range/not-modified success statuses are 200/206/304; Range failure uses 416 with Content-Range bytes */size. ETag is the quoted lowercase SHA-256; media response schemas describe the byte-string seam. Capability HMAC input is UTF-8 grantId + LF + expiresAt and HMAC-SHA256 with GRANT_SIGNING_KEY, encoded unpadded base64url; verification is constant-time. This previously unspecified byte encoding is a public V2 convention.',
    'The public seed includes a tenant, OPEN metadata-only upload, profile, cleanup policy and unpublished alias. The smoke checks these reads and independent profile/alias creation; it does not claim virus scanning, streaming, cleanup, publication CAS, recovery or performance acceptance. All 21 README routes plus the explicit Manager wire routes are declared.',
  ],
};
