import { T,id,ref,record as r,obj,pick,omit,list,map,union,nullable,name,text,uuid,int,nat,pos,empty,page,operation as op,finish,pagination,query,domainEventsOperation,snapshotSmoke,idem,manager,wire } from './helpers-b.mjs';
const I=n=>id(8,n);const amount={...int,not:{const:0}};const reference={...text,maxLength:120,pattern:'^(?:\\S(?:.*\\S)?)?$'};
const s={
 StatementLine:r('statementLineId:uuid batchId:uuid externalId:name bookedAt:date currency:currency state:UNMATCHED|MATCHED|IGNORED revision:pos',{amountMinor:amount,reference}),
 LedgerEntry:r('ledgerEntryId:uuid postedAt:date currency:currency state:UNMATCHED|MATCHED revision:pos',{amountMinor:amount,reference}),
 Match:r('matchId:uuid statementLineId:uuid ledgerEntryId:uuid state:PROPOSED|CONFIRMED|REJECTED|REVERSED score:int reasons:[string] createdAt:timestamp confirmedAt:timestamp|null reversedAt:timestamp|null sequence:pos'),
 StatementBatch:r('batchId:uuid source:name batchKey:name digest:sha256 lineCount:nat createdAt:timestamp',{state:{const:'IMPORTED'}}),
 MatchGroup:r('matchGroupId:uuid matchId:uuid|null statementLineId:uuid|null ledgerEntryId:uuid|null currency:currency statementTotalMinor:int ledgerTotalMinor:int state:PROPOSED|CONFIRMED|REJECTED|REVERSED createdAt:timestamp confirmedAt:timestamp|null reversedAt:timestamp|null sequence:pos',{statementLineIds:list(uuid,{minItems:1,maxItems:20,uniqueItems:true}),ledgerEntryIds:list(uuid,{minItems:1,maxItems:20,uniqueItems:true})}),
};
s.SeedStatementLine=omit(s.StatementLine,['batchId','revision']);s.SeedStatementBatch=obj({...pick(s.StatementBatch,['batchId','source','batchKey','digest','createdAt']).properties,lines:list(ref('SeedStatementLine'))});
const batchInput=r('source:name batchKey:name',{lines:list(pick(s.StatementLine,['externalId','bookedAt','currency','amountMinor','reference']),{minItems:1})});
const batchOutput=obj({statementBatch:ref('StatementBatch'),statementLines:list(ref('StatementLine'))});
const revisionMap=map(pos,uuid.pattern);
export default finish({taskId:'reconcilehub',title:'ReconcileHub',schemas:s,seedTypes:{ledgerEntries:'LedgerEntry',statementBatches:'SeedStatementBatch',matches:'Match'},resources:{statementBatches:'StatementBatch',statementLines:'StatementLine',ledgerEntries:'LedgerEntry',matches:'Match',matchGroups:'MatchGroup'},emptyEventPayload:true,environmentVariables:['CHROMIUM_PATH','MANAGED_DATA_ROOT'],
 seedData:{ledgerEntries:[{ledgerEntryId:I(1),postedAt:'2035-04-03',currency:'EUR',amountMinor:137,reference:'PUBLIC-LEDGER-1',state:'UNMATCHED',revision:1}]},
 workKinds:['MATCH_SUGGESTION'],eventTypes:['statement-batch.imported','match.proposed','match.confirmed','match.rejected','match.reversed','statement-line.ignored'],
 operations:[op('matches-list','GET','/api/v1/matches',null,page(ref('Match')),{parameters:pagination}),op('match-get','GET','/api/v1/matches/:matchId',null,ref('Match')),
 op('statement-batch-create','POST','/api/v1/statement-batches',batchInput,batchOutput,{status:202,example:{body:{source:'public-source',batchKey:'public-batch',lines:[{externalId:'public-line-1',bookedAt:'2035-04-03',currency:'USD',amountMinor:211,reference:'PUBLIC-LINE-1'}]}}}),
 op('match-create','POST','/api/v1/matches',pick(s.Match,['statementLineId','ledgerEntryId']),ref('Match'),{status:201}),op('match-confirm','POST','/api/v1/matches/:matchId/confirm',r('expectedLineRevision:pos expectedLedgerRevision:pos'),ref('Match')),op('match-reject','POST','/api/v1/matches/:matchId/reject',r('reason:name'),ref('Match')),op('match-reverse','POST','/api/v1/matches/:matchId/reverse',r('reason:name'),ref('Match')),
 op('statement-line-ignore','POST','/api/v1/statement-lines/:statementLineId/ignore',r('expectedRevision:pos reason:name'),ref('StatementLine')),
 op('reconciliation-work','GET','/api/v1/reconciliation-work',null,obj({statementLines:list(ref('StatementLine')),ledgerEntries:list(ref('LedgerEntry')),suggestions:list(ref('Match')),nextCursor:nullable(text)}),{parameters:[query('state',{const:'UNMATCHED'}),...pagination]}),
 op('match-group-create','POST','/api/v1/match-groups',pick(s.MatchGroup,['statementLineIds','ledgerEntryIds']),ref('MatchGroup'),{status:201,source:manager}),op('match-group-get','GET','/api/v1/match-groups/:matchGroupId',null,ref('MatchGroup'),{source:manager}),
 op('match-group-confirm','POST','/api/v1/match-groups/:matchGroupId/confirm',obj({expectedStatementLineRevisions:revisionMap,expectedLedgerEntryRevisions:revisionMap}),ref('MatchGroup'),{source:manager,example:{body:{expectedStatementLineRevisions:{[I(2)]:1},expectedLedgerEntryRevisions:{[I(1)]:1}}}}),op('match-group-reverse','POST','/api/v1/match-groups/:matchGroupId/reverse',r('reason:name'),ref('MatchGroup'),{source:manager}),domainEventsOperation()],
 smoke:[snapshotSmoke([['ledgerEntries',{ledgerEntryId:I(1),amountMinor:137,currency:'EUR'}]]),{operationId:'statement-batch-create',headers:idem('statement-batch'),body:{source:'public-source',batchKey:'public-batch',lines:[{externalId:'public-line-1',bookedAt:'2035-04-03',currency:'USD',amountMinor:211,reference:'PUBLIC-LINE-1'}]},expectStatus:202,capture:{batchId:['statementBatch','batchId'],lineId:['statementLines',0,'statementLineId']}},snapshotSmoke([['statementBatches',{batchId:'${batchId}',lineCount:1}],['statementLines',{statementLineId:'${lineId}',batchId:'${batchId}',externalId:'public-line-1'}]])],
 notes:['V2 wire clarification: batch import returns {statementBatch,statementLines}; reconciliation work returns {statementLines,ledgerEntries,suggestions,nextCursor}. Revision maps use UUID keys and positive integer values.','The seed contains one legal unmatched ledger row; the public write smoke imports a nonmatching-currency statement row. No private matching score, candidate or reconciliation answer is embedded.'],
});
