import { ref, str, name, uuid, time, sha, int, nat, pos, bool, nullable, list, obj, enumeration as en, page, pick, empty, T, uid, basic, work, event, seedShape, snapshotShape, operation as op, standardOps, commands, environmentVariables, keyed, admin, source, manager, pagination, sharedNotes } from './helpers-a.mjs';

const tenantId = uid(2, 1), ruleSetId = uid(2, 2), versionId = uid(2, 3), ruleId = uid(2, 4), evaluationId = uid(2, 5), comparisonRunId = uid(2, 6);
const decision = en('ALLOW', 'DENY', 'REVIEW');
const safeJson = { anyOf: [{ type: 'null' }, bool, str, int, list(ref('JsonValue')), { type: 'object', additionalProperties: ref('JsonValue') }] };
const schemas = {
  ...basic, JsonValue: safeJson,
  Facts: { type: 'object', additionalProperties: ref('JsonValue') },
  Expression: { oneOf: [obj({ all: list(ref('Expression'), { minItems: 1, maxItems: 100 }) }), obj({ any: list(ref('Expression'), { minItems: 1, maxItems: 100 }) }), obj({ not: ref('Expression') }), obj({ op: en('eq', 'neq', 'lt', 'lte', 'gt', 'gte', 'in', 'exists'), path: { type: 'string', pattern: '^\\$\\.[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*$' }, value: ref('JsonValue') })] },
  Effect: obj({ decision: nullable(decision), tags: list(str) }),
  RuleSet: obj({ ruleSetId: uuid, tenantId: uuid, name, currentRevision: nat, currentPublishedVersionId: nullable(uuid), publicationRevision: nat, createdAt: time }),
  RuleSetVersion: obj({ ruleSetVersionId: uuid, ruleSetId: uuid, tenantId: uuid, revision: pos, state: en('DRAFT', 'PUBLISHED', 'RETIRED'), defaultDecision: decision, rulesDigest: sha, publishedAt: nullable(time) }),
  Rule: obj({ ruleId: uuid, ruleSetVersionId: uuid, priority: int, name, condition: ref('Expression'), effect: ref('Effect'), terminal: bool }),
  Evaluation: obj({ evaluationId: uuid, tenantId: uuid, ruleSetId: uuid, ruleSetVersionId: uuid, factsDigest: sha, state: en('PENDING', 'RUNNING', 'COMPLETED', 'FAILED'), decision: nullable(decision), tags: list(str), matchedRuleIds: list(uuid), explanationDigest: nullable(sha), createdAt: time, completedAt: nullable(time), sequence: nat }),
  ExplanationNode: obj({ evaluationId: uuid, ordinal: nat, ruleId: uuid, path: str, result: en(true, false, 'SKIPPED'), reason: str }),
  ReplayRun: obj({ replayRunId: uuid, evaluationId: uuid, state: en('PENDING', 'RUNNING', 'MATCHED', 'DIVERGED', 'FAILED'), resultDigest: nullable(sha), createdAt: time, completedAt: nullable(time) }),
  ConflictReport: obj({ conflictReportId: uuid, ruleSetVersionId: uuid, priority: int, ruleId: uuid, code: str, message: str }),
  ComparisonRun: obj({ comparisonRunId: uuid, tenantId: uuid, ruleSetId: uuid, baselineVersionId: uuid, candidateVersionId: uuid, evaluationIds: list(uuid, { minItems: 1, maxItems: 100000, uniqueItems: true }), corpusDigest: sha, state: en('PENDING', 'RUNNING', 'COMPLETED', 'CANCELLED', 'FAILED'), revision: nat, resultCounts: obj({ MATCH: nat, DIFF: nat, ERROR: nat }), createdAt: time, startedAt: nullable(time), completedAt: nullable(time), cancelledAt: nullable(time), promotedAt: nullable(time) }),
  ComparisonSide: obj({ decision, tags: list(str), explanationDigest: sha }),
  ComparisonResult: obj({ comparisonRunId: uuid, evaluationId: uuid, ordinal: nat, status: en('MATCH', 'DIFF', 'ERROR'), baseline: nullable(ref('ComparisonSide')), candidate: nullable(ref('ComparisonSide')), errorCode: nullable(str), resultDigest: sha }),
  Work: work(['EVALUATION_EXECUTE', 'EVALUATION_REPLAY', 'COMPARISON_EXECUTE']),
  DomainEvent: event(['rule_version.published', 'evaluation.completed', 'evaluation.failed', 'replay.matched', 'replay.diverged', 'comparison.started', 'comparison.completed', 'comparison.cancelled', 'comparison.promoted'], obj({ ruleSetId: uuid, ruleSetVersionId: uuid, evaluationId: uuid, replayRunId: uuid, comparisonRunId: uuid, factsDigest: sha, explanationDigest: sha, resultDigest: sha, corpusDigest: sha, revision: nat }, [])),
};
schemas.RuleInput = pick(schemas.Rule, ['ruleId', 'priority', 'name', 'condition', 'effect', 'terminal']);
schemas.CreateVersion = obj({ defaultDecision: decision, rules: list(ref('RuleInput'), { maxItems: 5000 }) });
schemas.CreateEvaluation = obj({ tenantId: uuid, ruleSetId: uuid, ruleSetVersionId: uuid, facts: ref('Facts') });
const collections = Object.fromEntries(Object.entries({ tenants: 'Tenant', ruleSets: 'RuleSet', ruleSetVersions: 'RuleSetVersion', rules: 'Rule', evaluations: 'Evaluation', explanationNodes: 'ExplanationNode', replayRuns: 'ReplayRun', conflictReports: 'ConflictReport', comparisonRuns: 'ComparisonRun', comparisonResults: 'ComparisonResult' }).map(([key, type]) => [key, list(ref(type))]));
schemas.Snapshot = snapshotShape(collections);
const rule = { ruleId, ruleSetVersionId: versionId, priority: 10, name: 'Public named document', condition: { op: 'eq', path: '$.kind', value: 'document' }, effect: { decision: 'ALLOW', tags: ['document'] }, terminal: true };
const ruleInput = Object.fromEntries(Object.entries(rule).filter(([key]) => key !== 'ruleSetVersionId'));
const seed = { schema: seedShape({ ...collections, evaluationInputs: list(obj({ evaluationId: uuid, facts: ref('Facts') })) }), example: { schemaVersion: 1, seedVersion: 'rulebench-public-v2-1', importedAt: T, tenants: [{ tenantId, name: 'Public Decisions' }], ruleSets: [{ ruleSetId, tenantId, name: 'Public Document Policy', currentRevision: 1, currentPublishedVersionId: versionId, publicationRevision: 1, createdAt: T }], ruleSetVersions: [{ ruleSetVersionId: versionId, ruleSetId, tenantId, revision: 1, state: 'PUBLISHED', defaultDecision: 'REVIEW', rulesDigest: '149e4702f4442f81404bf78e510280b36625fdaac687bb00de2cce999ada68b4', publishedAt: T }], rules: [rule], evaluations: [], evaluationInputs: [], explanationNodes: [], replayRuns: [], conflictReports: [], comparisonRuns: [], comparisonResults: [] } };
const operations = [
  op('createTenant', 'POST', '/api/v1/tenants', obj({ name }), ref('Tenant'), { body: { name: 'Another Public Tenant' }, headers: keyed('rule-example-tenant') }),
  op('createRuleSet', 'POST', '/api/v1/rule-sets', obj({ tenantId: uuid, name }), ref('RuleSet'), { body: { tenantId, name: 'Another Public RuleSet' }, headers: keyed('rule-example-set') }),
  op('createVersion', 'POST', '/api/v1/rule-sets/:ruleSetId/versions', ref('CreateVersion'), ref('RuleSetVersion'), { params: { ruleSetId }, body: { defaultDecision: 'REVIEW', rules: [{ ...ruleInput, ruleId: uid(2, 10) }] }, headers: keyed('rule-example-version') }),
  ...['validate', 'publish'].map(action => op(`${action}Version`, 'POST', `/api/v1/rule-set-versions/:versionId/${action}`, empty, ref('RuleSetVersion'), { params: { versionId }, body: {}, headers: keyed(`rule-example-${action}`) }, source('Rule language and deterministic semantics'))),
  op('getConflicts', 'GET', '/api/v1/rule-set-versions/:versionId/conflicts', null, page(ref('ConflictReport')), { params: { versionId }, query: { limit: 20 } }, source('Public HTTP surface'), pagination),
  op('createEvaluation', 'POST', '/api/v1/evaluations', ref('CreateEvaluation'), ref('Evaluation'), { body: { tenantId, ruleSetId, ruleSetVersionId: versionId, facts: { kind: 'document' } }, headers: keyed('rule-example-evaluation') }),
  op('getEvaluation', 'GET', '/api/v1/evaluations/:evaluationId', null, ref('Evaluation'), { params: { evaluationId } }, source('Public HTTP surface')),
  op('getExplanation', 'GET', '/api/v1/evaluations/:evaluationId/explanation', null, page(ref('ExplanationNode')), { params: { evaluationId }, query: { limit: 20 } }, source('Public HTTP surface'), pagination),
  op('createReplay', 'POST', '/api/v1/evaluations/:evaluationId/replay', empty, ref('ReplayRun'), { params: { evaluationId }, body: {}, headers: keyed('rule-example-replay') }, source('Required behavior and invariants')),
  op('getReplay', 'GET', '/api/v1/replay-runs/:replayRunId', null, ref('ReplayRun'), { params: { replayRunId: uid(2, 7) } }, source('Public HTTP surface')),
  op('createComparison', 'POST', '/api/v1/comparison-runs', obj({ tenantId: uuid, ruleSetId: uuid, baselineVersionId: uuid, candidateVersionId: uuid, evaluationIds: list(uuid, { minItems: 1, maxItems: 100000 }) }), obj({ run: ref('ComparisonRun') }), { body: { tenantId, ruleSetId, baselineVersionId: versionId, candidateVersionId: uid(2, 8), evaluationIds: [evaluationId] }, headers: keyed('rule-example-comparison') }, manager),
  ...['start', 'cancel', 'promote'].map(action => op(`${action}Comparison`, 'POST', `/api/v1/comparison-runs/:comparisonRunId/${action}`, obj({ expectedRevision: nat }), obj({ run: ref('ComparisonRun'), ...(action === 'promote' ? { ruleSet: ref('RuleSet') } : {}) }), { params: { comparisonRunId }, body: { expectedRevision: 0 }, headers: keyed(`rule-example-comparison-${action}`) }, manager)),
  op('getComparison', 'GET', '/api/v1/comparison-runs/:comparisonRunId', null, obj({ run: ref('ComparisonRun'), results: list(ref('ComparisonResult')) }), { params: { comparisonRunId } }, manager),
  ...standardOps(),
];
export default {
  taskId: 'rulebench', title: 'RuleBench', environmentVariables, commands, seed, schemas, operations,
  smoke: [
    { operationId: 'snapshot', headers: admin, expectContains: [{ path: ['resources', 'ruleSets'], match: { ruleSetId, currentPublishedVersionId: versionId } }, { path: ['resources', 'ruleSetVersions'], match: { ruleSetVersionId: versionId, state: 'PUBLISHED' } }, { path: ['resources', 'rules'], match: rule }] },
    { operationId: 'createEvaluation', body: { tenantId, ruleSetId, ruleSetVersionId: versionId, facts: { kind: 'document' } }, headers: keyed('rule-smoke-evaluation'), capture: { newEvaluationId: ['evaluationId'] }, expectBody: { tenantId, ruleSetId, ruleSetVersionId: versionId, factsDigest: '34444fe0e6bdbf3927a579fe3286859d204ea0882a381b7769ffd4905551d24f' } },
    { operationId: 'getEvaluation', params: { evaluationId: '${newEvaluationId}' }, expectBody: { evaluationId: '${newEvaluationId}', tenantId, ruleSetVersionId: versionId, factsDigest: '34444fe0e6bdbf3927a579fe3286859d204ea0882a381b7769ffd4905551d24f' } },
    { operationId: 'createRuleSet', body: { tenantId, name: 'Smoke Created RuleSet' }, headers: keyed('rule-smoke-set'), capture: { newRuleSetId: ['ruleSetId'] }, expectBody: { currentRevision: 0, currentPublishedVersionId: null, publicationRevision: 0 } },
    { operationId: 'snapshot', headers: admin, expectContains: [{ path: ['resources', 'ruleSets'], match: { ruleSetId: '${newRuleSetId}', tenantId, name: 'Smoke Created RuleSet' } }] },
  ],
  notes: [...sharedNotes,
    'V2 public wire clarification: RuleSet is the exact declared schema, with currentRevision the highest allocated version revision; new sets initialize currentRevision=0, currentPublishedVersionId=null and publicationRevision=0. Publishing a version changes its state and the current published pointer atomically; promotion changes only the pointer and publicationRevision. CreateVersion accepts {defaultDecision,rules}; each RuleInput supplies its ruleId, and the server supplies ruleSetVersionId and the next revision.',
    'V2 public wire clarification: rulesDigest is SHA-256 of RFC 8785-compatible canonical JSON of the complete Rule objects sorted by (priority,ruleId); factsDigest is SHA-256 of canonical facts. Explanation digest is SHA-256 of the ordered complete ExplanationNode array. Replay resultDigest is SHA-256 of canonical {decision,tags,matchedRuleIds,explanationDigest}; comparison corpus/result digests retain the Manager definitions. These byte definitions were absent from the original V1 prose and are now public, not inferred from an oracle.',
    'V2 public wire clarification: ConflictReport is one declared conflict row; /conflicts returns its paginated rows sorted by (priority,ruleId,code,conflictReportId). Validate returns the current RuleSetVersion on success and persists deterministic reports for inspection; semantic conflicts return RULE_CONFLICT. Explanation ordinal is zero-based and contiguous. A pending explanation is an empty page, never fabricated terminal nodes.',
    'V2 language clarification: exists requires a boolean value, true tests presence and false tests absence; eq/neq compare canonical JSON without coercion; ordering requires safe integers on both sides; in requires an array value. Missing never equals null and non-exists comparisons with missing yield false. Runtime expression depth and 256 KiB facts limit remain business checks beyond structural schema.',
    'V2 public wire clarification: seed adds comparisonRuns/comparisonResults and seed-only evaluationInputs:[{evaluationId,facts}]. Each imported Evaluation requires exactly one matching input with the declared factsDigest; orphan inputs are invalid. Inputs are stored privately for replay/comparison and never added to public Evaluation or snapshots. This resolves the original omission of restorable facts without exposing them through reads. The independent populated published-rule seed uses empty evaluationInputs and creates its evaluation through real HTTP.',
    'The smoke checks actual acceptance, frozen version and digest, plus persisted write/read. It does not claim asynchronous terminal decision, replay, Shadow ComparisonRun or recovery acceptance. All 14 README routes and 5 Manager routes are declared.',
  ],
};
