import {
  crashDispatcherAfterResponse, crashWorkerAt, createExport, createGrant, defineCase, downloadGrant,
  expectError, finalEvidence, getEvents, prepare, sha256, startPreparedApi, waitForDrain, waitForExport,
} from "./helpers.mjs";

async function generationRecovery(ctx, point, label) {
  const fixture = ctx.fixtures.recovery(); const target = await prepare(ctx, { fixture, label }); const api = await target.startApi(); const created = await createExport(ctx, api.baseUrl, { subjectId: fixture.owner.subjectId, scope: ["activity", "profile"], format: "JSONL" }, { key: ctx.key(`${label}:create`) }); const crashed = await crashWorkerAt(ctx, api.baseUrl, point, ({ aggregateId, kind }) => aggregateId === created.exportId && kind === "EXPORT_GENERATION"); const heldView = await ctx.request(api.baseUrl, `/api/v1/exports/${created.exportId}`); ctx.equal(heldView.status, 200, `${label} public read during crash window`); ctx.ok(heldView.json.state !== "READY", `${label} does not expose READY before recovery`, { hardCapIds: ["PUBLICATION_ATOMICITY"] }); const denied = await createGrant(ctx, api.baseUrl, created.exportId, { expiresInSeconds: 300 }, { allowFailure: true, key: ctx.key(`${label}:premature-grant`) }); expectError(ctx, denied, 409, "EXPORT_NOT_READY", `${label} staged bytes inaccessible`); const replacement = await ctx.startWorker(); const ready = await waitForExport(ctx, api.baseUrl, created.exportId, "READY", [replacement], { timeoutMs: 180_000 }); const grant = await createGrant(ctx, api.baseUrl, ready.exportId, { expiresInSeconds: 300 }, { key: ctx.key(`${label}:grant`) }); const bytes = await downloadGrant(ctx, api.baseUrl, grant.grantId); ctx.equal(bytes.status, 200, `${label} recovered bytes status`); ctx.equal(sha256(bytes.body), ready.object.sha256, `${label} recovered bytes digest`); const snapshot = await ctx.snapshot(api.baseUrl); ctx.equal(snapshot.work.filter(({ aggregateId, kind }) => aggregateId === ready.exportId && kind === "EXPORT_GENERATION").length, 1, `${label} one operation identity`); ctx.equal(snapshot.events.filter(({ aggregateId, type }) => aggregateId === ready.exportId && type === "export.ready").length, 1, `${label} one ready Event`); return { ready, crashed, snapshot, bytes };
}

const C01 = defineCase({
  id: "C-01", fixtureFamily: "EV-F-RECOVERY",
  action: "SIGKILL a generation worker after public lease claim, wait for persisted lease expiry, recover with a replacement, then test a held stale owner.",
  oracle: "Require one operation identity, bounded attempts, complete bytes and event once, while a stale fencing token cannot publish after replacement ownership.",
  async run(ctx) {
    const recovered = await generationRecovery(ctx, "worker.claimed", "claimed-kill"); ctx.ok(recovered.snapshot.work.find(({ aggregateId }) => aggregateId === recovered.ready.exportId).attempt >= 2, "replacement increments persisted attempt");
    await ctx.resetDatabase(); const fixture = ctx.fixtures.recovery(); const target = await prepare(ctx, { fixture, label: "stale-held" }); const api = await target.startApi(); const created = await createExport(ctx, api.baseUrl, { subjectId: fixture.owner.subjectId, scope: ["files"], format: "CSV" }, { key: ctx.key("stale-create") }); const barrier = await ctx.barrier({ hold: ({ point, aggregateId }) => point === "worker.before-commit" && aggregateId === created.exportId }); const stale = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const entry = await barrier.waitFor(({ json }) => json?.aggregateId === created.exportId && json?.point === "worker.before-commit", { timeoutMs: 180_000, processes: [stale] }); await new Promise((resolveWait) => setTimeout(resolveWait, 3_500)); const replacement = await ctx.startWorker(); const ready = await waitForExport(ctx, api.baseUrl, created.exportId, "READY", [replacement], { timeoutMs: 180_000 }); barrier.release(entry); await new Promise((resolveWait) => setTimeout(resolveWait, 250)); const snapshot = await ctx.snapshot(api.baseUrl); ctx.equal(snapshot.events.filter(({ aggregateId, type }) => aggregateId === ready.exportId && type === "export.ready").length, 1, "released stale owner cannot double-publish"); ctx.equal(snapshot.work.filter(({ aggregateId }) => aggregateId === ready.exportId).length, 1, "stale race keeps one Work identity");
    return finalEvidence(ctx, { killedWorkId: recovered.crashed.work.workId, staleWorkId: entry.json.workId, recoveredAttempt: recovered.snapshot.work.find(({ aggregateId }) => aggregateId === recovered.ready.exportId).attempt });
  },
});

const C02 = defineCase({
  id: "C-02", fixtureFamily: "EV-F-RECOVERY",
  action: "SIGKILL independent workers at worker.effect-complete and worker.before-commit, inspect public visibility, then recover each Export with a replacement.",
  oracle: "Staging bytes are never Grant-readable and READY appears only with complete immutable bytes, exact metadata, one Work, and one event.",
  async run(ctx) {
    const effect = await generationRecovery(ctx, "worker.effect-complete", "effect-complete"); await ctx.resetDatabase(); const beforeCommit = await generationRecovery(ctx, "worker.before-commit", "before-commit"); ctx.equal(effect.ready.object.sha256, sha256(effect.bytes.body), "effect-complete recovery digest closes"); ctx.equal(beforeCommit.ready.object.sha256, sha256(beforeCommit.bytes.body), "before-commit recovery digest closes"); return finalEvidence(ctx, { points: [effect.crashed.entry.json.point, beforeCommit.crashed.entry.json.point], digests: [effect.ready.object.sha256, beforeCommit.ready.object.sha256] });
  },
});

async function cleanupRecovery(ctx, point, label) {
  const fixture = ctx.fixtures.lifecycle(); const target = await prepare(ctx, { fixture, label }); const api = await target.startApi(); const live = fixture.exports.find((item) => item.state === "READY" && item.retentionUntil > "2030-01-01T00:00:00.000Z"); const expired = fixture.exports.find((item) => item.state === "READY" && item.retentionUntil < "2030-01-01T00:00:00.000Z"); const grant = await createGrant(ctx, api.baseUrl, live.exportId, { expiresInSeconds: 300 }, { key: ctx.key(`${label}:control-grant`) }); const before = await downloadGrant(ctx, api.baseUrl, grant.grantId); const crashed = await crashWorkerAt(ctx, api.baseUrl, point, ({ aggregateId, kind }) => aggregateId === expired.exportId && kind === "EXPORT_CLEANUP"); const replacement = await ctx.startWorker(); const snapshot = await waitForDrain(ctx, api.baseUrl, { processes: [replacement], predicate: ({ aggregateId, kind }) => aggregateId === expired.exportId && kind === "EXPORT_CLEANUP" }); const proofs = snapshot.resources.deletionProofs.filter(({ exportId }) => exportId === expired.exportId); ctx.equal(proofs.length, 1, `${label} one Deletion Proof`); ctx.equal(proofs[0].objectSha256, expired.object.sha256, `${label} proof deleted digest`); const after = await downloadGrant(ctx, api.baseUrl, grant.grantId); ctx.equal(after.status, 200, `${label} live control readable`); ctx.equal(after.body, before.body, `${label} live control bytes unchanged`); ctx.equal(snapshot.events.filter(({ aggregateId, type }) => aggregateId === expired.exportId && type === "export.deleted").length, 1, `${label} one deletion Event`); return { crashed, snapshot, proof: proofs[0] };
}

const C03 = defineCase({
  id: "C-03", fixtureFamily: "EV-F-RECOVERY+LIFECYCLE",
  action: "SIGKILL cleanup workers after physical effect and before database commit in isolated databases, then recover and read every live control.",
  oracle: "Every deleted object converges to one EXPIRED resource, proof, and event while ineligible objects remain byte-readable and retries cannot double-delete.",
  async run(ctx) {
    const effect = await cleanupRecovery(ctx, "worker.effect-complete", "cleanup-effect"); await ctx.resetDatabase(); const commit = await cleanupRecovery(ctx, "worker.before-commit", "cleanup-commit"); return finalEvidence(ctx, { points: [effect.crashed.entry.json.point, commit.crashed.entry.json.point], proofDigests: [effect.proof.proofDigest, commit.proof.proofDigest] });
  },
});

const C04 = defineCase({
  id: "C-04", fixtureFamily: "EV-F-RECOVERY",
  action: "Create committed Export events, acknowledge one webhook through a dispatcher barrier, SIGKILL before ACK commit, and recover delivery with a replacement dispatcher.",
  oracle: "Match receiver deliveries by eventId and canonical body, require contiguous aggregate sequence, no rollback event, and no invented Manager event type.",
  async run(ctx) {
    const fixture = ctx.fixtures.recovery(); const api = await startPreparedApi(ctx, { fixture }); const created = await createExport(ctx, api.baseUrl, { subjectId: fixture.owner.subjectId, scope: ["activity"], format: "JSONL" }); const worker = await ctx.startWorker(); const ready = await waitForExport(ctx, api.baseUrl, created.exportId, "READY", [worker]); const receiver = await ctx.receiver({ behavior: () => ({ status: 204 }) }); const crashed = await crashDispatcherAfterResponse(ctx, receiver); ctx.ok(receiver.ledger.length >= 1, "receiver observes pre-crash delivery"); const original = receiver.ledger.at(-1); const replacement = await ctx.startDispatcher({ webhookUrl: receiver.url }); const duplicate = await ctx.waitFor(() => receiver.ledger.find((entry, index) => index > receiver.ledger.indexOf(original) && entry.json?.eventId === original.json?.eventId), { timeoutMs: 120_000, label: "same event redelivery after unknown ACK", processes: [replacement] }); ctx.equal(duplicate.raw, original.raw, "redelivery body is byte-stable"); ctx.equal(duplicate.json.eventId, original.json.eventId, "redelivery event identity stable"); const events = await getEvents(ctx, api.baseUrl, ready.exportId); ctx.equal(events.map(({ type }) => type), ["export.requested", "export.ready"], "published transition event sequence"); ctx.ok(events.every(({ type }) => ["export.requested", "export.ready", "export.failed", "export.cancelled", "export.expired", "export.deleted", "download-grant.revoked"].includes(type)), "no unpublished Manager Event type"); const before = await ctx.snapshot(api.baseUrl); const invalid = await createExport(ctx, api.baseUrl, { subjectId: fixture.owner.subjectId, scope: [], format: "JSONL" }, { allowFailure: true, contractExpectation: "invalid", key: ctx.key("invalid") }); expectError(ctx, invalid, 400, "INVALID_EXPORT_SCOPE", "rolled-back invalid request"); const after = await ctx.snapshot(api.baseUrl); ctx.equal(after.events.length, before.events.length, "rollback emits no Event");
    return finalEvidence(ctx, { eventId: original.json.eventId, deliveries: receiver.ledger.filter(({ json }) => json?.eventId === original.json.eventId).length, barrierWorkId: crashed.entry.json.workId });
  },
});

export const C_CASES = Object.freeze([C01, C02, C03, C04]);
