import assert from "node:assert/strict";

import {
  EXPORT_KEYS, FINAL_RESOURCE_KEYS, SHARDED_EXPORT_KEYS, assertSnapshot, cancelExport, checkField, chooseOption,
  clickControl, createExport, createGrant, defineCase, downloadGrant, expectError, expectSuccess, fillField,
  finalEvidence, getEvents, launchBrowser, prepare, sha256, startPreparedApi, waitForDrain, waitForExport,
} from "./helpers.mjs";

async function browserCreate(page, subjectId, { scopes = ["profile"], format = "JSONL" } = {}) {
  await fillField(page, [/subject id/iu, /subject/iu], subjectId); for (const scope of scopes) await checkField(page, [new RegExp(`^${scope}$`, "iu"), new RegExp(scope, "iu")]); await chooseOption(page, [/format/iu], format); await clickControl(page, [/create export/iu, /request export/iu, /创建.*导出/u]);
}
async function findLatestExport(ctx, baseUrl, subjectId, state) { return ctx.waitFor(async () => { const response = await ctx.request(baseUrl, "/api/v1/exports?limit=100"); const items = response.json?.items; const matches = Array.isArray(items) ? items.filter((item) => item.subjectId === subjectId && (!state || item.state === state)) : []; return matches.at(-1) ?? false; }, { timeoutMs: 180_000, intervalMs: 100, label: `browser-created Export ${state ?? ""}` }); }

const D01 = defineCase({
  id: "D-01", fixtureFamily: "EV-F-BROWSER-V1",
  action: "Use production Chromium and only labelled visible controls to create, observe, download, revoke, cancel, refresh, and revisit V1 Exports.",
  oracle: "Cross-check visible terminal and error states against public HTTP, immutable response bytes, and snapshot state while retaining keyboard and mobile usability.",
  async run(ctx) {
    const fixture = ctx.fixtures.bytes(); const api = await startPreparedApi(ctx, { fixture }); const worker = await ctx.startWorker(); const { page } = await launchBrowser(ctx, api.baseUrl); await browserCreate(page, fixture.owner.subjectId, { scopes: ["profile"], format: "JSONL" }); const created = await findLatestExport(ctx, api.baseUrl, fixture.owner.subjectId); const ready = await waitForExport(ctx, api.baseUrl, created.exportId, "READY", [worker]); await page.reload({ waitUntil: "networkidle" }); ctx.ok(await page.getByText(ready.exportId, { exact: false }).first().isVisible(), "browser displays created Export identity"); ctx.ok(await page.getByText(/ready/iu).first().isVisible(), "browser displays READY state");
    await clickControl(page, [/create.*grant/iu, /download grant/iu, /生成.*下载/u]); const grant = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(api.baseUrl); return snapshot.resources.downloadGrants.find(({ exportId }) => exportId === ready.exportId) ?? false; }, { timeoutMs: 30_000, label: "browser-created Download Grant" }); const full = await downloadGrant(ctx, api.baseUrl, grant.grantId); ctx.equal(full.status, 200, "browser-created Grant downloads"); ctx.equal(sha256(full.body), ready.object.sha256, "browser Grant exact immutable bytes"); await clickControl(page, [/revoke/iu, /撤销/u]); await ctx.waitFor(async () => { const response = await downloadGrant(ctx, api.baseUrl, grant.grantId); return response.status === 410 ? response : false; }, { timeoutMs: 30_000, label: "browser revoke visible through API" });
    await page.setViewportSize({ width: 390, height: 844 }); await page.reload({ waitUntil: "domcontentloaded" }); ctx.ok((await page.locator("body").evaluate((node) => node.scrollWidth)) <= 410, "mobile UI has no material horizontal overflow"); await page.keyboard.press("Tab"); ctx.ok(await page.locator(":focus").count() === 1, "keyboard focus enters a visible semantic control");
    await ctx.stop(worker); await browserCreate(page, fixture.owner.subjectId, { scopes: ["files"], format: "CSV" }); const second = await findLatestExport(ctx, api.baseUrl, fixture.owner.subjectId, "REQUESTED"); await clickControl(page, [/cancel/iu, /取消/u]); const cancelled = await waitForExport(ctx, api.baseUrl, second.exportId, "CANCELLED"); ctx.equal(cancelled.object, null, "browser cancellation publishes no object");
    return finalEvidence(ctx, { readyExportId: ready.exportId, grantId: grant.grantId, cancelledExportId: cancelled.exportId });
  },
});

const D02 = defineCase({
  id: "D-02", fixtureFamily: "EV-F-BROWSER-SHARD",
  action: "Use production Chromium to request a 100003-record Export, observe ordered Shard progress, select one Shard and the Manifest, and refresh.",
  oracle: "Compare every visible ordinal, section, range, count, state, and downloaded target digest with public API bytes while preserving the legacy flow.",
  async run(ctx) {
    const worked = ctx.fixtures.shard().workedExample; const owner = { subjectId: ctx.uuid("d02-subject"), name: "Browser Shards", currentDatasetRevision: 1 }; const records = worked.sections.flatMap((section) => section.recordIds.map((recordId, index) => ({ recordId, scope: section.name, data: { index, section: section.name } }))); const seed = { schemaVersion: 1, seedVersion: "d02-browser-shards", subjects: [owner], datasetRevisions: [{ subjectId: owner.subjectId, revision: 1, committedAt: ctx.at({ minutes: -1 }), records }], exports: [] }; const target = await prepare(ctx, { seed }); const api = await target.startApi(); const workers = [await ctx.startWorker(), await ctx.startWorker()]; const { page } = await launchBrowser(ctx, api.baseUrl); await browserCreate(page, owner.subjectId, { scopes: ["profile", "activity"], format: "JSONL" }); const created = await findLatestExport(ctx, api.baseUrl, owner.subjectId); const ready = await waitForExport(ctx, api.baseUrl, created.exportId, "READY", workers, { timeoutMs: 300_000 }); ctx.ok(Array.isArray(ready.shards) && ready.shards.length === 3, "browser request produces worked-example Shards"); await page.reload({ waitUntil: "networkidle" });
    for (const shard of ready.shards) { ctx.ok(await page.getByText(String(shard.ordinal), { exact: true }).first().isVisible(), `visible Shard ordinal ${shard.ordinal}`); ctx.ok(await page.getByText(shard.section, { exact: false }).first().isVisible(), `visible Shard section ${shard.section}`); ctx.ok(await page.getByText(String(shard.recordCount), { exact: true }).first().isVisible(), `visible Shard count ${shard.recordCount}`); }
    ctx.ok(await page.getByText(/manifest/iu).first().isVisible(), "visible Manifest after all Shards verify"); await clickControl(page, [/manifest.*grant/iu, /download.*manifest/iu, /下载.*manifest/iu]); const manifestGrant = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(api.baseUrl); return snapshot.resources.shardedDownloadGrants.find(({ exportId, target }) => exportId === ready.exportId && target === "MANIFEST") ?? false; }, { timeoutMs: 30_000, label: "browser-created Manifest Grant" }); const manifestBytes = await downloadGrant(ctx, api.baseUrl, manifestGrant.grantId); ctx.equal(manifestBytes.status, 200, "browser Manifest Grant downloads"); ctx.equal(sha256(manifestBytes.body), ready.manifest.canonicalDigest, "browser Manifest digest"); await page.reload({ waitUntil: "networkidle" }); ctx.ok(await page.getByText(ready.exportId, { exact: false }).first().isVisible(), "refresh restores sharded Export state");
    return finalEvidence(ctx, { exportId: ready.exportId, shardCount: ready.shards.length, manifestGrantId: manifestGrant.grantId });
  },
});

function resolveRef(document, value) { if (!value?.$ref) return value; const parts = value.$ref.replace(/^#\//u, "").split("/"); return parts.reduce((current, part) => current?.[part.replaceAll("~1", "/").replaceAll("~0", "~")], document); }
function schemaAt(document, path, method, status) { const response = resolveRef(document, document.paths?.[path]?.[method]?.responses?.[String(status)]); return resolveRef(document, response?.content?.["application/json"]?.schema); }
function propertySets(document, schema) { const resolved = resolveRef(document, schema); if (!resolved) return []; if (resolved.properties) return [new Set(Object.keys(resolved.properties))]; const branches = resolved.oneOf ?? resolved.anyOf ?? resolved.allOf ?? []; if (resolved.allOf) { const merged = new Set(); for (const branch of branches) for (const set of propertySets(document, branch)) for (const key of set) merged.add(key); return [merged]; } return branches.flatMap((branch) => propertySets(document, branch)); }

const D03 = defineCase({
  id: "D-03", fixtureFamily: "EV-F-CONTRACT-SNAPSHOT",
  action: "Fetch canonical OpenAPI, execute representative legacy reads, and inspect a populated FINAL verification snapshot from one public point in time.",
  oracle: "Validate frozen routes, statuses, closed schema alternatives, exact resource union, shapes, sorts, Work enum, events, and recursive secret omission.",
  async run(ctx) {
    const fixture = ctx.fixtures.lifecycle(); const api = await startPreparedApi(ctx, { fixture }); const response = await ctx.request(api.baseUrl, "/openapi.json"); const openapi = expectSuccess(ctx, response, "OpenAPI"); ctx.equal(openapi.openapi, "3.1.0", "OpenAPI version"); const required = [["/api/v1/exports", "get"], ["/api/v1/exports", "post"], ["/api/v1/exports/{exportId}", "get"], ["/api/v1/exports/{exportId}/cancel", "post"], ["/api/v1/exports/{exportId}/download-grants", "post"], ["/api/v1/download-grants/{grantId}/revoke", "post"], ["/api/v1/download-grants/{grantId}/content", "get"], ["/api/v1/exports/{exportId}/sections", "get"], ["/api/v1/domain-events", "get"], ["/api/v1/verification-snapshot", "get"]]; for (const [path, method] of required) ctx.ok(openapi.paths?.[path]?.[method], `OpenAPI publishes ${method.toUpperCase()} ${path}`);
    const createSets = propertySets(openapi, schemaAt(openapi, "/api/v1/exports", "post", 202)); ctx.ok(createSets.some((keys) => EXPORT_KEYS.every((key) => keys.has(key))), "OpenAPI publishes legacy Export fields"); ctx.ok(createSets.some((keys) => SHARDED_EXPORT_KEYS.every((key) => keys.has(key))), "OpenAPI publishes sharded Export fields"); const managerCodes = JSON.stringify(openapi); for (const code of ["EXPORT_SHARD_LIMIT_EXCEEDED", "EXPORT_SHARD_NOT_READY", "INVALID_EXPORT_DOWNLOAD_TARGET"]) ctx.ok(managerCodes.includes(code), `OpenAPI publishes ${code}`);
    const legacy = fixture.exports.find((item) => item.state === "READY" && item.retentionUntil > "2030-01-01T00:00:00.000Z"); const legacyRead = expectSuccess(ctx, await ctx.request(api.baseUrl, `/api/v1/exports/${legacy.exportId}`), "legacy Export runtime body"); ctx.equal(Object.keys(legacyRead).sort(), [...EXPORT_KEYS].sort(), "legacy body stays exact V1 shape under EV-GAP-01"); const snapshot = assertSnapshot(ctx, await ctx.snapshot(api.baseUrl), { final: true }); ctx.equal(Object.keys(snapshot.resources).sort(), [...FINAL_RESOURCE_KEYS].sort(), "FINAL snapshot exact union"); ctx.equal(new Set(snapshot.work.map(({ kind }) => kind)).isSubsetOf(new Set(["EXPORT_GENERATION", "EXPORT_CLEANUP"])), true, "FINAL Work enum unchanged");
    return finalEvidence(ctx, { pathCount: required.length, resourceKeys: Object.keys(snapshot.resources) });
  },
});

const D04 = defineCase({
  id: "D-04", fixtureFamily: "EV-F-TRACE",
  action: "Trace one successful request through sections, bytes, Grant and events, one cancellation chain, one cleanup proof, and one atomically rejected request.",
  oracle: "Join only public IDs and independently recomputed digests, require no orphan or duplicate identity, and scan responses, snapshot, logs, and errors for secrets.",
  async run(ctx) {
    const fixture = ctx.fixtures.lifecycle(); const api = await startPreparedApi(ctx, { fixture }); const fresh = ctx.fixtures.bytes(); const created = await createExport(ctx, api.baseUrl, { subjectId: fixture.owner.subjectId, scope: ["profile"], format: "JSONL" }, { key: ctx.key("trace-success") }); const worker = await ctx.startWorker(); const ready = await waitForExport(ctx, api.baseUrl, created.exportId, "READY", [worker]); const grant = await createGrant(ctx, api.baseUrl, ready.exportId, { expiresInSeconds: 300 }, { key: ctx.key("trace-grant") }); const bytes = await downloadGrant(ctx, api.baseUrl, grant.grantId); ctx.equal(sha256(bytes.body), ready.object.sha256, "request-to-byte digest closes"); const events = await getEvents(ctx, api.baseUrl, ready.exportId); ctx.equal(events.at(-1).sequence, ready.sequence, "resource and Event sequence close"); const snapshotBefore = await ctx.snapshot(api.baseUrl); ctx.equal(snapshotBefore.resources.downloadGrants.filter(({ grantId }) => grantId === grant.grantId).length, 1, "Grant appears once in snapshot"); ctx.equal(snapshotBefore.resources.exportSections.filter(({ exportId }) => exportId === ready.exportId).every(({ state }) => state === "VERIFIED"), true, "all success sections verified");
    const cancelledRequest = await createExport(ctx, api.baseUrl, { subjectId: fixture.owner.subjectId, scope: ["files"], format: "CSV" }, { key: ctx.key("trace-cancel") }); const cancelled = await cancelExport(ctx, api.baseUrl, cancelledRequest.exportId, "trace", { key: ctx.key("trace-cancel-action") }); ctx.equal(cancelled.object, null, "cancel chain has no object"); const invalidKey = ctx.key("trace-invalid"); const beforeInvalid = await ctx.snapshot(api.baseUrl); const invalid = await createExport(ctx, api.baseUrl, { subjectId: fixture.owner.subjectId, scope: ["unknown"], format: "JSONL" }, { allowFailure: true, key: invalidKey }); expectError(ctx, invalid, 400, "INVALID_EXPORT_SCOPE", "trace invalid scope"); const afterInvalid = await ctx.snapshot(api.baseUrl); ctx.equal(afterInvalid.resources.exports.length, beforeInvalid.resources.exports.length, "failed chain leaves no Export"); ctx.equal(afterInvalid.work.length, beforeInvalid.work.length, "failed chain leaves no Work"); ctx.equal(afterInvalid.events.length, beforeInvalid.events.length, "failed chain leaves no Event"); const workers = [worker, await ctx.startWorker()]; const final = await waitForDrain(ctx, api.baseUrl, { processes: workers, predicate: ({ kind }) => kind === "EXPORT_CLEANUP" }); const expired = fixture.exports.find((item) => item.state === "READY" && item.retentionUntil < "2030-01-01T00:00:00.000Z"); ctx.equal(final.resources.deletionProofs.filter(({ exportId }) => exportId === expired.exportId).length, 1, "cleanup chain closes with one Proof"); const serialized = JSON.stringify({ responses: [created, ready, cancelled, invalid.json], snapshot: final, logs: api.logs }); ctx.ok(!new RegExp(`${ctx.adminToken}|${invalidKey}|postgres(?:ql)?:\\/\\/|/(?:Users|home|tmp)/`, "u").test(serialized), "trace surfaces omit credentials, idempotency keys, and private paths");
    return finalEvidence(ctx, { successExportId: ready.exportId, cancelledExportId: cancelled.exportId, deletedExportId: expired.exportId });
  },
});

export const D_CASES = Object.freeze([D01, D02, D03, D04]);
