import {
  ASSIGNMENT_KEYS, PLAN_CHANGE_KEYS, PLAN_REVISION_KEYS, POOL_KEYS, PROVIDER_EVENT_KEYS, REFUND_KEYS,
  SUBSCRIPTION_KEYS, VIEW_KEYS, activateSubscription, assertPoolClosure, assertSnapshot, assignSeat,
  changePlan, checkEntitlement, clickControl, createPool, createRefund, createRevision,
  defineCase, exactKeys, fillField, finalEvidence, getSubscription, launchBrowser, prepare, publishRevision,
  waitForSubscription,
} from "./helpers.mjs";

function dereference(document, schema) {
  if (!schema?.$ref) return schema ?? {}; let value = document; for (const part of schema.$ref.replace(/^#\//u, "").split("/")) value = value?.[part.replaceAll("~1", "/").replaceAll("~0", "~")]; return value ?? {};
}

function responseSchema(document, operation, status = "200") {
  const response = operation.responses?.[status] ?? operation.responses?.[Number(status)]; const value = dereference(document, response); const content = value.content?.["application/json"] ?? Object.values(value.content ?? {})[0]; return dereference(document, content?.schema);
}

function requestSchema(document, operation) {
  const body = dereference(document, operation.requestBody); const content = body.content?.["application/json"] ?? Object.values(body.content ?? {})[0]; return dereference(document, content?.schema);
}

function schemaBranches(document, schema) { const value = dereference(document, schema); const variants = value.allOf ?? value.anyOf ?? value.oneOf; return variants ? variants.map((branch) => dereference(document, branch)) : [value]; }

function objectKeys(document, schema) { const keys = new Set(); const visit = (value) => { const resolved = dereference(document, value); for (const key of Object.keys(resolved.properties ?? {})) keys.add(key); for (const branch of resolved.allOf ?? []) visit(branch); }; visit(schema); return [...keys].sort(); }

function isClosed(document, schema) { const value = dereference(document, schema); return value.additionalProperties === false || value.unevaluatedProperties === false || schemaBranches(document, value).some((branch) => branch.additionalProperties === false || branch.unevaluatedProperties === false); }

function propertySchema(document, schema, name) { const value = dereference(document, schema); if (value.properties?.[name]) return dereference(document, value.properties[name]); for (const branch of value.allOf ?? []) { const found = propertySchema(document, branch, name); if (found) return found; } }

function allowsNull(document, schema) { const value = dereference(document, schema); if (value.nullable === true || (Array.isArray(value.type) && value.type.includes("null")) || value.type === "null") return true; return [...(value.anyOf ?? []), ...(value.oneOf ?? [])].some((branch) => allowsNull(document, branch)); }

function assertNullable(ctx, document, schema, names, label) { for (const name of names) { const property = propertySchema(document, schema, name); ctx.ok(property && allowsNull(document, property), `${label}.${name} is nullable`); } }

function parameterNames(document, path, operation) { return [...(document.paths[path].parameters ?? []), ...(operation.parameters ?? [])].map((parameter) => dereference(document, parameter).name).sort(); }

function enumValues(value, result = new Set()) { if (Array.isArray(value)) for (const item of value) enumValues(item, result); else if (value && typeof value === "object") { if (Array.isArray(value.enum)) for (const item of value.enum) result.add(item); for (const child of Object.values(value)) enumValues(child, result); } return result; }

function assertOperation(ctx, document, method, path, requestKeys, responseKeys) {
  const operation = document.paths?.[path]?.[method.toLowerCase()]; ctx.ok(operation && typeof operation === "object", `${method} ${path} exists in OpenAPI`); if (requestKeys) { const schema = requestSchema(document, operation); ctx.equal(objectKeys(document, schema), [...requestKeys].sort(), `${method} ${path} request fields`); ctx.ok(isClosed(document, schema), `${method} ${path} request is closed`); } if (responseKeys) { const schema = responseSchema(document, operation); ctx.equal(objectKeys(document, schema), [...responseKeys].sort(), `${method} ${path} success fields`); ctx.ok(isClosed(document, schema), `${method} ${path} success is closed`); } return operation;
}

async function settleUi(page) { await page.waitForLoadState("networkidle", { timeout: 10_000 }).catch(() => undefined); await page.waitForTimeout(150); }

async function visibleAction(page, names) { await clickControl(page, names); await settleUi(page); }

async function fill(page, labels, value) { await fillField(page, labels, value); }

const L01 = defineCase({
  id: "LAYER-01", fixtureFamily: "EH-F-LAYER-OPENAPI",
  action: "Read OpenAPI 3.1 and execute representative V1 and organization Pool requests against the same production API surface.",
  oracle: "Every published method, path, closed request, response, nullability and error envelope matches runtime, while the legacy Subscription wire remains unpolluted.",
  async run(ctx) {
    const fixture = ctx.fixtures.layer(); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi(); const response = await ctx.request(api.baseUrl, "/openapi.json"); ctx.equal(response.status, 200, "OpenAPI status"); const document = response.json; ctx.equal(document.openapi, "3.1.0", "OpenAPI 3.1 version");
    assertOperation(ctx, document, "POST", "/api/v1/tenants", ["name"], ["tenantId", "name"]); assertOperation(ctx, document, "POST", "/api/v1/plans", ["tenantId", "name"], ["planId", "tenantId", "name"]); const revisionOperation = assertOperation(ctx, document, "POST", "/api/v1/plans/{planId}/revisions", ["priceMinor", "currency", "interval", "features", "trialDays", "graceDays", "refundDays"], PLAN_REVISION_KEYS); assertOperation(ctx, document, "POST", "/api/v1/plan-revisions/{planRevisionId}/publish", null, PLAN_REVISION_KEYS);
    const subscriptionOperation = assertOperation(ctx, document, "POST", "/api/v1/subscriptions", ["tenantId", "subjectId", "planRevisionId", "startTrial", "subscriptionKind"], SUBSCRIPTION_KEYS); assertOperation(ctx, document, "GET", "/api/v1/subscriptions/{subscriptionId}", null, SUBSCRIPTION_KEYS); assertOperation(ctx, document, "POST", "/api/v1/subscriptions/{subscriptionId}/change-plan", ["toPlanRevisionId", "expectedPlanRevisionId", "kind"], PLAN_CHANGE_KEYS); assertOperation(ctx, document, "POST", "/api/v1/subscriptions/{subscriptionId}/cancel", ["cancelAtPeriodEnd"], SUBSCRIPTION_KEYS); const refundOperation = assertOperation(ctx, document, "POST", "/api/v1/subscriptions/{subscriptionId}/refunds", ["amountMinor"], REFUND_KEYS); assertOperation(ctx, document, "POST", "/api/v1/provider/events", PROVIDER_EVENT_KEYS, PROVIDER_EVENT_KEYS); assertOperation(ctx, document, "POST", "/api/v1/refunds/{refundId}/reconcile", null, REFUND_KEYS); const checkOperation = assertOperation(ctx, document, "GET", "/api/v1/entitlements/check", null, VIEW_KEYS);
    assertOperation(ctx, document, "POST", "/api/v1/entitlement-pools", ["tenantId", "subscriptionId", "feature", "seatLimit"], POOL_KEYS); const assignmentOperation = assertOperation(ctx, document, "POST", "/api/v1/entitlement-pools/{poolId}/assignments", ["subjectId", "expectedPoolVersion"], ["pool", "assignment"]); assertOperation(ctx, document, "POST", "/api/v1/entitlement-pools/{poolId}/assignments/{subjectId}/revoke", ["expectedPoolVersion"], ["pool", "assignment"]); const listOperation = assertOperation(ctx, document, "GET", "/api/v1/entitlement-pools/{poolId}/assignments", null, ["items", "nextCursor"]); ctx.equal(parameterNames(document, "/api/v1/entitlements/check", checkOperation), ["feature", "knownRevocationVersion", "subjectId", "tenantId"], "entitlement check query parameters"); ctx.equal(parameterNames(document, "/api/v1/entitlement-pools/{poolId}/assignments", listOperation), ["cursor", "limit", "poolId"], "assignment list path and query parameters");
    assertNullable(ctx, document, responseSchema(document, revisionOperation), ["publishedAt"], "PlanRevision"); assertNullable(ctx, document, responseSchema(document, subscriptionOperation), ["trialEndsAt", "pendingPlanRevisionId", "terminalAt"], "Subscription"); assertNullable(ctx, document, responseSchema(document, refundOperation), ["resolvedAt"], "Refund"); assertNullable(ctx, document, responseSchema(document, checkOperation), ["limit", "subscriptionId"], "EntitlementView"); const assignmentSchema = propertySchema(document, responseSchema(document, assignmentOperation), "assignment"); assertNullable(ctx, document, assignmentSchema, ["terminalAt"], "SeatAssignment"); assertNullable(ctx, document, responseSchema(document, listOperation), ["nextCursor"], "SeatAssignmentList");
    for (const path of ["/api/v1/entitlements", "/api/v1/audit", "/api/v1/verification-snapshot"]) ctx.ok(document.paths?.[path]?.get, `GET ${path} exists`); ctx.ok(document.paths?.["/api/v1/admin/expire-due"]?.post, "POST expire-due exists");
    const errorSchema = Object.values(document.components?.schemas ?? {}).find((schema) => objectKeys(document, schema).join(",") === "error"); ctx.ok(errorSchema, "OpenAPI publishes standard error envelope"); const errorInner = propertySchema(document, errorSchema, "error"); ctx.equal(objectKeys(document, errorInner), ["code", "details", "message"], "error object fields"); ctx.ok(isClosed(document, errorSchema) && isClosed(document, errorInner), "error envelope and error object are closed"); const publishedCodes = enumValues(document); for (const code of ["INVALID_SUBSCRIPTION", "INVALID_PLAN_CHANGE", "INVALID_REFUND", "INVALID_REQUEST", "MALFORMED_JSON", "TRIAL_ALREADY_CONSUMED", "PLAN_REVISION_CHANGED", "SUBSCRIPTION_TERMINAL", "PENDING_PROVIDER_RESULT", "REFUND_LIMIT_EXCEEDED", "REVOCATION_FENCE_STALE", "IDEMPOTENCY_CONFLICT", "NOT_FOUND", "ORGANIZATION_SUBSCRIPTION_REQUIRED", "POOL_VERSION_CHANGED", "POOL_CAPACITY_EXCEEDED", "POOL_OVER_LIMIT", "POOL_TERMINAL", "SEAT_ALREADY_ASSIGNED"]) ctx.ok(publishedCodes.has(code), `OpenAPI enumerates ${code}`);
    const activated = await activateSubscription(ctx, api, { tenantId: fixture.tenant.tenantId, subjectId: "openapi-org", planRevisionId: fixture.revisions.proV1.planRevisionId, startTrial: true, subscriptionKind: "ORGANIZATION" }, { key: ctx.key("openapi-org") }); ctx.equal(Object.keys(activated.created).sort(), [...SUBSCRIPTION_KEYS].sort(), "runtime Subscription stays V1 wire"); const pool = await createPool(ctx, api.baseUrl, { tenantId: fixture.tenant.tenantId, subscriptionId: activated.active.subscriptionId, feature: "reports", seatLimit: 2 }, { key: ctx.key("openapi-pool") }); const assigned = await assignSeat(ctx, api.baseUrl, pool.poolId, { subjectId: "openapi-seat", expectedPoolVersion: 0 }, { key: ctx.key("openapi-seat") }); exactKeys(assigned.pool, POOL_KEYS, "runtime Pool"); exactKeys(assigned.assignment, ASSIGNMENT_KEYS, "runtime SeatAssignment"); const view = await checkEntitlement(ctx, api.baseUrl, { tenantId: fixture.tenant.tenantId, subjectId: "openapi-seat", feature: "reports", knownRevocationVersion: 0 }); exactKeys(view, VIEW_KEYS, "runtime EntitlementView"); assertSnapshot(ctx, await ctx.snapshot(api.baseUrl));
    return finalEvidence(ctx, { openApiPaths: Object.keys(document.paths).length, subscriptionId: activated.active.subscriptionId, poolId: pool.poolId });
  },
});

const L02 = defineCase({
  id: "LAYER-02", fixtureFamily: "EH-F-LAYER-INDIVIDUAL-UI",
  action: "Drive the production React UI through visible controls to publish a revision, start a personal trial, change plans, refund and reconcile, check access, cancel, refresh, and inspect audit.",
  oracle: "UI-visible lifecycle results agree with public HTTP and snapshot Grant, Refund, access and fence state, without mocked endpoints, private calls, or exposed provider credentials.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); const dev = await target.startDev(); const worker = await target.startWorker(); const { page } = await launchBrowser(ctx, dev.baseUrl); await visibleAction(page, [/plans?/iu, /catalog/iu]); await visibleAction(page, [/publish(?: revision)?/iu]); const published = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(dev.baseUrl); return snapshot.resources.planRevisions.find(({ planRevisionId, state }) => planRevisionId === fixture.revisions.draft.planRevisionId && state === "PUBLISHED") ? snapshot : false; }, { timeoutMs: 30_000, label: "UI revision publication" }); ctx.ok(published, "UI publishes draft revision");
    await visibleAction(page, [/subscriptions?/iu, /start trial/iu]); await fill(page, [/tenant(?: id)?/iu], fixture.tenant.tenantId); await fill(page, [/subject(?: id)?/iu], "ui-personal"); await fill(page, [/plan revision(?: id)?/iu, /revision(?: id)?/iu], fixture.revisions.basicV1.planRevisionId); await fill(page, [/provider request(?: id)?/iu], "ui-personal-start"); await visibleAction(page, [/start trial/iu, /create subscription/iu, /^start$/iu]); const started = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(dev.baseUrl); return snapshot.resources.subscriptions.find(({ subjectId }) => subjectId === "ui-personal") ?? false; }, { timeoutMs: 30_000, label: "UI personal subscription" }); const active = await waitForSubscription(ctx, dev.baseUrl, started.subscriptionId, ["TRIALING", "ACTIVE"], [worker]);
    await visibleAction(page, [/change plan/iu, /upgrade/iu]); await fill(page, [/subscription(?: id)?/iu], active.subscriptionId); await fill(page, [/target.*revision/iu, /to plan revision/iu], fixture.revisions.proV1.planRevisionId); await fill(page, [/expected sequence/iu], active.sequence); await visibleAction(page, [/apply change/iu, /upgrade/iu, /change plan/iu]); const upgraded = await ctx.waitFor(async () => { const value = await getSubscription(ctx, dev.baseUrl, active.subscriptionId); return value.planRevisionId === fixture.revisions.proV1.planRevisionId ? value : false; }, { timeoutMs: 120_000, label: "UI upgrade", processes: [worker] });
    await visibleAction(page, [/refunds?/iu]); await fill(page, [/subscription(?: id)?/iu], upgraded.subscriptionId); await fill(page, [/amount(?: minor)?/iu], 500); await fill(page, [/currency/iu], "USD"); await fill(page, [/provider request(?: id)?/iu], "ui-partial-refund"); await visibleAction(page, [/create refund/iu, /^refund$/iu]); const refund = await ctx.waitFor(async () => (await ctx.snapshot(dev.baseUrl)).resources.refunds.find(({ providerRequestId }) => providerRequestId === "ui-partial-refund") ?? false, { timeoutMs: 30_000, label: "UI Refund" }); await visibleAction(page, [/reconcile/iu]); await fill(page, [/refund(?: id)?/iu], refund.refundId); await visibleAction(page, [/run reconcile/iu, /^reconcile$/iu]);
    await visibleAction(page, [/entitlements?/iu, /access check/iu]); await fill(page, [/tenant(?: id)?/iu], fixture.tenant.tenantId); await fill(page, [/subject(?: id)?/iu], "ui-personal"); await fill(page, [/feature/iu], "reports"); await fill(page, [/known revocation version/iu], upgraded.revocationVersion); await visibleAction(page, [/check (?:access|entitlement)/iu, /^check$/iu]); await settleUi(page); ctx.ok(await page.getByText(/ENABLED|DISABLED/iu).first().isVisible(), "UI renders entitlement decision");
    const latest = await getSubscription(ctx, dev.baseUrl, upgraded.subscriptionId); await visibleAction(page, [/cancel/iu]); await fill(page, [/subscription(?: id)?/iu], latest.subscriptionId); await fill(page, [/expected sequence/iu], latest.sequence); await visibleAction(page, [/confirm cancel/iu, /^cancel subscription$/iu, /^cancel$/iu]); const cancelled = await waitForSubscription(ctx, dev.baseUrl, latest.subscriptionId, "CANCELLED", [worker]); await page.reload({ waitUntil: "networkidle" }); await visibleAction(page, [/audit/iu]); ctx.ok(await page.locator("body").innerText().then((text) => text.includes(fixture.tenant.tenantId)), "refreshed audit UI shows tenant history"); const snapshot = assertSnapshot(ctx, await ctx.snapshot(dev.baseUrl)); const grants = snapshot.resources.entitlementGrants.filter(({ subscriptionId }) => subscriptionId === latest.subscriptionId); ctx.ok(grants.length > 0 && grants.every(({ validUntil }) => validUntil !== null), "UI cancellation closes all Grants"); const decision = await checkEntitlement(ctx, dev.baseUrl, { tenantId: fixture.tenant.tenantId, subjectId: "ui-personal", feature: "reports", knownRevocationVersion: 0 }); ctx.equal(decision.state, "DISABLED", "HTTP agrees with UI cancellation"); ctx.ok(decision.revocationVersion >= cancelled.revocationVersion, "HTTP returns terminal fence");
    return finalEvidence(ctx, { subscriptionId: latest.subscriptionId, refundId: refund.refundId, auditRows: snapshot.resources.auditEntries.length });
  },
});

const L03 = defineCase({
  id: "LAYER-03", fixtureFamily: "EH-F-LAYER-POOL-UI",
  action: "Use visible production UI controls to create an organization subscription and Pool, fill capacity, lower its limit, explicitly revoke seats, terminate, and refresh history.",
  oracle: "Rendered Pool version, state and Seat history match HTTP and snapshot; capacity never oversells, limit reduction never auto-evicts, and terminal revocation closes every subject.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); const setupApi = await target.startApi(); const draft = await createRevision(ctx, setupApi.baseUrl, fixture.plans.proPlan.planId, { priceMinor: 5000, currency: "USD", interval: "MONTH", features: { reports: { limit: 3 }, exports: { limit: 1 } }, trialDays: 14, graceDays: 3, refundDays: 7 }, { key: ctx.key("ui-lower") }); const lower = await publishRevision(ctx, setupApi.baseUrl, draft.planRevisionId, { key: ctx.key("ui-publish-lower") }); await ctx.stop(setupApi); const dev = await target.startDev(); const worker = await target.startWorker(); const { page } = await launchBrowser(ctx, dev.baseUrl);
    await visibleAction(page, [/subscriptions?/iu]); await fill(page, [/tenant(?: id)?/iu], fixture.tenant.tenantId); await fill(page, [/subject(?: id)?/iu], "ui-org-owner"); await fill(page, [/plan revision(?: id)?/iu, /revision(?: id)?/iu], fixture.revisions.proV1.planRevisionId); await fill(page, [/provider request(?: id)?/iu], "ui-org-start"); const kind = page.getByLabel(/subscription kind/iu); if (await kind.count()) await kind.selectOption("ORGANIZATION"); else await visibleAction(page, [/organization/iu]); await visibleAction(page, [/start trial/iu, /create subscription/iu, /^start$/iu]); const owner = await ctx.waitFor(async () => (await ctx.snapshot(dev.baseUrl)).resources.subscriptions.find(({ subjectId }) => subjectId === "ui-org-owner") ?? false, { timeoutMs: 30_000, label: "UI organization subscription" }); const active = await waitForSubscription(ctx, dev.baseUrl, owner.subscriptionId, ["TRIALING", "ACTIVE"], [worker]);
    await visibleAction(page, [/pools?/iu, /seat management/iu]); await fill(page, [/tenant(?: id)?/iu], fixture.tenant.tenantId); await fill(page, [/subscription(?: id)?/iu], active.subscriptionId); await fill(page, [/feature/iu], "reports"); await fill(page, [/seat limit/iu], 5); await visibleAction(page, [/create pool/iu]); let snapshot = await ctx.waitFor(async () => { const value = await ctx.snapshot(dev.baseUrl); return value.resources.entitlementPools.find(({ subscriptionId }) => subscriptionId === active.subscriptionId) ? value : false; }, { timeoutMs: 30_000, label: "UI Pool" }); let pool = snapshot.resources.entitlementPools.find(({ subscriptionId }) => subscriptionId === active.subscriptionId);
    for (let index = 0; index < 5; index += 1) { await visibleAction(page, [/assign seat/iu, /new assignment/iu]); await fill(page, [/pool(?: id)?/iu], pool.poolId); await fill(page, [/subject(?: id)?/iu], `ui-seat-${index}`); await fill(page, [/expected pool version/iu], index); await visibleAction(page, [/confirm assign/iu, /^assign$/iu, /^assign seat$/iu]); await ctx.waitFor(async () => (await ctx.snapshot(dev.baseUrl)).resources.seatAssignments.filter(({ poolId, state }) => poolId === pool.poolId && state === "ACTIVE").length === index + 1, { timeoutMs: 15_000, label: `UI seat ${index}` }); }
    const before = await getSubscription(ctx, dev.baseUrl, active.subscriptionId); await visibleAction(page, [/change plan/iu, /upgrade/iu]); await fill(page, [/subscription(?: id)?/iu], active.subscriptionId); await fill(page, [/target.*revision/iu, /to plan revision/iu], lower.planRevisionId); await fill(page, [/expected sequence/iu], before.sequence); await visibleAction(page, [/apply change/iu, /upgrade/iu, /change plan/iu]); snapshot = await ctx.waitFor(async () => { const value = await ctx.snapshot(dev.baseUrl); const current = value.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); return current?.state === "OVER_LIMIT" && current.seatLimit === 3 ? value : false; }, { timeoutMs: 120_000, label: "UI Pool OVER_LIMIT", processes: [worker] }); pool = snapshot.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); ctx.equal(snapshot.resources.seatAssignments.filter(({ poolId, state }) => poolId === pool.poolId && state === "ACTIVE").length, 5, "UI limit reduction does not evict");
    for (let index = 0; index < 2; index += 1) { await visibleAction(page, [/revoke seat/iu]); await fill(page, [/pool(?: id)?/iu], pool.poolId); await fill(page, [/subject(?: id)?/iu], `ui-seat-${index}`); await fill(page, [/expected pool version/iu], pool.version); await visibleAction(page, [/confirm revoke/iu, /^revoke$/iu, /^revoke seat$/iu]); snapshot = await ctx.waitFor(async () => { const value = await ctx.snapshot(dev.baseUrl); const current = value.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); return current?.version === pool.version + 1 ? value : false; }, { timeoutMs: 15_000, label: `UI revoke ${index}` }); pool = snapshot.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); }
    ctx.equal(pool.state, "ACTIVE", "UI explicit revokes restore ACTIVE"); const latest = await getSubscription(ctx, dev.baseUrl, active.subscriptionId); await visibleAction(page, [/cancel/iu]); await fill(page, [/subscription(?: id)?/iu], latest.subscriptionId); await fill(page, [/expected sequence/iu], latest.sequence); await visibleAction(page, [/confirm cancel/iu, /^cancel subscription$/iu, /^cancel$/iu]); snapshot = await ctx.waitFor(async () => { const value = await ctx.snapshot(dev.baseUrl); return value.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId)?.state === "REVOKED" ? value : false; }, { timeoutMs: 120_000, label: "UI terminal Pool", processes: [worker] }); await page.reload({ waitUntil: "networkidle" }); ctx.ok(await page.locator("body").innerText().then((text) => /REVOKED|EXPIRED/iu.test(text)), "refreshed UI renders terminal Pool or Seat history"); const finalPool = snapshot.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); const history = snapshot.resources.seatAssignments.filter(({ poolId }) => poolId === pool.poolId); assertPoolClosure(finalPool, history); ctx.ok(history.every(({ state }) => state !== "ACTIVE"), "terminal UI flow closes all seats");
    return finalEvidence(ctx, { subscriptionId: active.subscriptionId, poolId: pool.poolId, history: history.length });
  },
});

const L04 = defineCase({
  id: "LAYER-04", fixtureFamily: "EH-F-LAYER-SNAPSHOT-CLOSURE",
  action: "Capture authenticated FINAL snapshots while public refund, plan-change and Pool mutations execute concurrently, then compare point-in-time access closure and canonical ordering.",
  oracle: "Every snapshot is one exact V1-plus-Pool resource union with internally closed Subscription, Grant, Refund, fence, Pool, Seat, Work and Event data and no private leakage.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const org = await activateSubscription(ctx, apis[0], { tenantId: fixture.tenant.tenantId, subjectId: "snapshot-owner", planRevisionId: fixture.revisions.proV1.planRevisionId, startTrial: true, subscriptionKind: "ORGANIZATION" }, { key: ctx.key("snapshot-owner") }); const pool = await createPool(ctx, apis[0].baseUrl, { tenantId: fixture.tenant.tenantId, subscriptionId: org.active.subscriptionId, feature: "reports", seatLimit: 3 }, { key: ctx.key("snapshot-pool") }); await assignSeat(ctx, apis[0].baseUrl, pool.poolId, { subjectId: "snapshot-seat", expectedPoolVersion: 0 }, { key: ctx.key("snapshot-seat") }); const current = await getSubscription(ctx, apis[0].baseUrl, org.active.subscriptionId);
    const mutations = [changePlan(ctx, apis[0].baseUrl, current.subscriptionId, { toPlanRevisionId: fixture.revisions.proLow.planRevisionId, expectedPlanRevisionId: current.planRevisionId, kind: "DOWNGRADE" }, { allowFailure: true, key: ctx.key("snapshot-change") }), createRefund(ctx, apis[1].baseUrl, current.subscriptionId, { amountMinor: 200 }, { allowFailure: true, key: ctx.key("snapshot-refund") }), assignSeat(ctx, apis[1].baseUrl, pool.poolId, { subjectId: "snapshot-seat-two", expectedPoolVersion: 1 }, { allowFailure: true, key: ctx.key("snapshot-seat-two") })]; const captures = await Promise.all([ctx.snapshot(apis[0].baseUrl), ctx.snapshot(apis[1].baseUrl), ...mutations]); const snapshots = captures.slice(0, 2); for (const snapshot of snapshots) { assertSnapshot(ctx, snapshot); const ownPool = snapshot.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); if (ownPool) assertPoolClosure(ownPool, snapshot.resources.seatAssignments.filter(({ poolId }) => poolId === pool.poolId)); const subscription = snapshot.resources.subscriptions.find(({ subscriptionId }) => subscriptionId === current.subscriptionId); const fence = snapshot.resources.revocationFences.find(({ tenantId, subjectId }) => tenantId === fixture.tenant.tenantId && subjectId === current.subjectId); if (subscription && fence) ctx.ok(fence.revocationVersion >= subscription.revocationVersion, "snapshot fence covers Subscription revocationVersion"); }
    const final = assertSnapshot(ctx, await ctx.snapshot(apis[0].baseUrl)); const view = await checkEntitlement(ctx, apis[1].baseUrl, { tenantId: fixture.tenant.tenantId, subjectId: "snapshot-seat", feature: "reports", knownRevocationVersion: 0 }); const finalPool = final.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); ctx.equal(view.state, ["REVOKED", "EXPIRED"].includes(finalPool.state) ? "DISABLED" : "ENABLED", "public access agrees with FINAL Pool closure");
    return finalEvidence(ctx, { snapshots: snapshots.length + 1, poolId: pool.poolId, accessState: view.state });
  },
});

export const D_CASES = Object.freeze([L01, L02, L03, L04]);
