import {
  acceptOffer, assertFrozenTotals, assertOfferSelection, assertPaymentIdentity, assertSeatConservation,
  cancelWaitlist, checkoutHold, createHold, createWaitlist, declineOffer, defineCase, expectError,
  finalEvidence, getOffer, liveSeatOwners, prepare, reconcilePayment, startProviderDouble, startSeatWorker,
  waitForOffer, waitForPayment, waitForSnapshot,
} from "./helpers.mjs";

const A01 = defineCase({
  id: "A-01", fixtureFamily: "SR-F-CONTRACT-HOLD",
  action: "Create boundary multi-seat Holds through the public API, publish a later price, and issue duplicate, partial-conflict, cross-event, and TTL-invalid requests.",
  oracle: "Every successful Hold owns the complete sorted set at one database boundary with frozen prices and exact integer total; every rejection leaves Hold, owner, Work, and Event ledgers unchanged.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi();
    const seats = [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`), fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:2`), fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:3`)];
    const hold = await createHold(ctx, api.baseUrl, fixture.holdPayload("atomic", seats, { ttlSeconds: 30 }), { key: ctx.key("atomic-hold") });
    const created = await ctx.snapshot(api.baseUrl); const items = created.resources.holdSeats.filter(({ holdId }) => holdId === hold.holdId);
    ctx.equal(items.map(({ seatId }) => seatId), seats.map(({ seatId }) => seatId).sort(), "HoldSeat set is complete and sorted"); ctx.ok(items.every(({ priceVersionId }) => priceVersionId === fixture.prices.priceA1.priceVersionId), "Hold freezes active PriceVersion"); ctx.equal(hold.totalMinor, items.reduce((sum, item) => sum + item.unitAmountMinor + item.feeMinor, 0), "Hold total closes frozen items"); ctx.ok(Date.parse(hold.expiresAt) - Date.parse(hold.createdAt) >= 29_000 && Date.parse(hold.expiresAt) - Date.parse(hold.createdAt) <= 31_000, "TTL is based on database time"); assertSeatConservation(created);
    const beforeInvalid = await ctx.snapshot(api.baseUrl);
    for (const [label, body, status, code] of [
      ["duplicate", fixture.holdPayload("duplicate", [seats[0], seats[0]]), 400, "HOLD_INVALID"],
      ["ttl-low", fixture.holdPayload("ttl-low", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:5`)], { ttlSeconds: 29 }), 400, "HOLD_INVALID"],
      ["ttl-high", fixture.holdPayload("ttl-high", [fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:5`)], { ttlSeconds: 901 }), 400, "HOLD_INVALID"],
      ["partial-conflict", fixture.holdPayload("partial", [seats[0], fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:5`)]), 409, "SEAT_UNAVAILABLE"],
      ["cross-event", fixture.holdPayload("cross-event", [seats[0], fixture.seed.seats.find(({ eventId }) => eventId === fixture.otherEvent.eventId)]), 400, "HOLD_INVALID"],
    ]) {
      const response = await createHold(ctx, api.baseUrl, body, { allowFailure: true, key: ctx.key(label), ...(["duplicate", "ttl-low", "ttl-high"].includes(label) ? { contractExpectation: "invalid" } : {}) }); expectError(ctx, response, status, code, label); if (label === "partial-conflict") ctx.ok(JSON.stringify(response.json.error.details).includes(seats[0].seatId), "conflict reports unavailable requested Seat");
    }
    const afterInvalid = await ctx.snapshot(api.baseUrl); for (const name of ["holds", "holdSeats"]) ctx.equal(afterInvalid.resources[name], beforeInvalid.resources[name], `${name} unchanged by rejected Hold requests`); ctx.equal(afterInvalid.work, beforeInvalid.work, "Work unchanged by rejected Hold requests"); ctx.equal(afterInvalid.events, beforeInvalid.events, "Events unchanged by rejected Hold requests");
    const activate = await ctx.mutate(api.baseUrl, `/api/v1/price-versions/${fixture.prices.priceA2.priceVersionId}/activate`, ctx.key("activate-v2"), { expectedActivePriceVersionId: fixture.prices.priceA1.priceVersionId }); ctx.equal(activate.status, 200, "later price activation"); const afterPrice = await ctx.snapshot(api.baseUrl); const frozen = afterPrice.resources.holdSeats.filter(({ holdId }) => holdId === hold.holdId); ctx.ok(frozen.every(({ priceVersionId, unitAmountMinor, feeMinor }) => priceVersionId === fixture.prices.priceA1.priceVersionId && unitAmountMinor === fixture.prices.priceA1.unitAmountMinor && feeMinor === fixture.prices.priceA1.feeMinor), "later publication cannot reprice an existing Hold"); assertFrozenTotals(afterPrice);
    return finalEvidence(ctx, { holdId: hold.holdId, frozenSeatCount: items.length, rejectedRequests: 5 });
  },
});

const A02 = defineCase({
  id: "A-02", fixtureFamily: "SR-F-PAYMENT-UNKNOWN",
  action: "Create and checkout a frozen Hold against the deterministic Provider TIMEOUT path, observe UNKNOWN, then reconcile through the original provider request identity.",
  oracle: "Checkout commits one Order, PaymentIntent, and capture Work before provider I/O; UNKNOWN protects seats and reconciliation queries the same identity without a second semantic charge.",
  async run(ctx) {
    const fixture = ctx.fixtures.payment(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi();
    const seat = fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`); const hold = await createHold(ctx, api.baseUrl, fixture.holdPayload("unknown", [seat]), { key: ctx.key("unknown-hold") }); const checkout = await checkoutHold(ctx, api.baseUrl, hold.holdId, "TIMEOUT", { key: ctx.key("unknown-checkout") }); ctx.equal(checkout.order.totalMinor, hold.totalMinor, "Order freezes Hold total"); ctx.equal(checkout.paymentIntent.amountMinor, hold.totalMinor, "PaymentIntent freezes Hold total");
    const worker = await startSeatWorker(ctx, provider); const unknown = await waitForPayment(ctx, api.baseUrl, checkout.paymentIntent.paymentIntentId, "UNKNOWN", [worker]); const unknownOrder = unknown.snapshot.resources.orders.find(({ orderId }) => orderId === checkout.order.orderId); const unknownHold = unknown.snapshot.resources.holds.find(({ holdId }) => holdId === hold.holdId); ctx.equal(unknownOrder.state, "PAYMENT_UNKNOWN", "UNKNOWN is not decline"); ctx.equal(unknownHold.state, "CHECKOUT", "UNKNOWN retains Hold fence"); ctx.ok(Date.parse(unknownHold.paymentGraceExpiresAt) > Date.parse(unknown.snapshot.asOf), "UNKNOWN publishes a future grace fence"); const identity = unknown.payment.providerRequestId; ctx.equal(provider.charges.get(identity)?.postCount, 1, "one semantic provider charge");
    await reconcilePayment(ctx, api.baseUrl, checkout.paymentIntent.paymentIntentId, { key: ctx.key("unknown-reconcile") }); const final = await waitForPayment(ctx, api.baseUrl, checkout.paymentIntent.paymentIntentId, ["SUCCEEDED", "FAILED"], [worker]); ctx.equal(provider.charges.size, 1, "reconcile does not allocate a new provider identity"); ctx.ok(provider.charges.get(identity).getCount >= 1, "reconcile queries original provider identity"); ctx.equal(provider.charges.get(identity).postCount, 1, "reconcile does not issue a second semantic charge"); assertPaymentIdentity(final.snapshot, provider.charges); assertSeatConservation(final.snapshot); assertFrozenTotals(final.snapshot);
    return finalEvidence(ctx, { paymentIntentId: checkout.paymentIntent.paymentIntentId, providerRequestId: identity, terminalState: final.payment.state });
  },
});

const A03 = defineCase({
  id: "A-03", fixtureFamily: "SR-F-EXPIRY-CONSERVATION",
  action: "Seed an already-due live Hold, create and confirm a distinct paid Order, then drain expiry Work and inspect authoritative seat ownership and immutable histories.",
  oracle: "Database-time expiry releases only the due live Hold exactly once while a confirmed Order keeps its seats, terminal states never regress, and no Seat has two live owners.",
  async run(ctx) {
    const fixture = ctx.fixtures.payment(); const dueSeat = fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:1`); const dueHoldId = ctx.uuid("due-hold"); const seed = structuredClone(fixture.seed); seed.seedVersion = `${ctx.caseId.toLowerCase()}-due`; seed.holds.push({ holdId: dueHoldId, tenantId: fixture.tenant.tenantId, eventId: fixture.event.eventId, customerRef: "due", state: "HELD", expiresAt: "2020-01-01T00:00:00.000Z", paymentGraceExpiresAt: null, totalMinor: 5500, currency: "USD", createdAt: "2019-12-31T23:55:00.000Z", terminalAt: null, sequence: 1 }); seed.holdSeats.push({ holdId: dueHoldId, seatId: dueSeat.seatId, priceVersionId: fixture.prices.priceA1.priceVersionId, unitAmountMinor: 5000, feeMinor: 500 });
    const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed }); const api = await target.startApi(); const paidSeat = fixture.byPosition.get(`${fixture.zones.zoneA.zoneId}:A:2`); const paidHold = await createHold(ctx, api.baseUrl, fixture.holdPayload("paid", [paidSeat])); const checkout = await checkoutHold(ctx, api.baseUrl, paidHold.holdId, "SUCCEEDED"); const worker = await startSeatWorker(ctx, provider);
    const final = await waitForSnapshot(ctx, api.baseUrl, (snapshot) => snapshot.resources.holds.find(({ holdId }) => holdId === dueHoldId)?.state === "EXPIRED" && snapshot.resources.orders.find(({ orderId }) => orderId === checkout.order.orderId)?.state === "CONFIRMED", { label: "due Hold expiry and paid Order confirmation", processes: [worker] }); const due = final.resources.holds.find(({ holdId }) => holdId === dueHoldId); const paidOrder = final.resources.orders.find(({ orderId }) => orderId === checkout.order.orderId); ctx.equal(due.state, "EXPIRED", "due Hold reaches EXPIRED"); ctx.equal(paidOrder.state, "CONFIRMED", "paid Order reaches CONFIRMED"); const owners = liveSeatOwners(final); ctx.equal(owners.has(dueSeat.seatId), false, "expired Hold seat is released"); ctx.equal(owners.get(paidSeat.seatId), [{ kind: "order", ownerId: paidOrder.orderId }], "confirmed Order retains ownership"); assertSeatConservation(final); assertFrozenTotals(final);
    const replayed = await waitForSnapshot(ctx, api.baseUrl, (snapshot) => snapshot.work.filter(({ kind, aggregateId }) => kind === "HOLD_EXPIRY" && aggregateId === dueHoldId).every(({ terminal }) => terminal), { label: "expiry Work retained terminal", processes: [worker] }); ctx.equal(replayed.resources.holds.find(({ holdId }) => holdId === dueHoldId).state, "EXPIRED", "terminal Hold does not regress");
    return finalEvidence(ctx, { expiredHoldId: dueHoldId, confirmedOrderId: paidOrder.orderId });
  },
});

const A04 = defineCase({
  id: "A-04", fixtureFamily: "SR-F-WAITLIST-FIFO-CONTIGUOUS",
  action: "Create ordered eligible and over-cap WaitlistEntries against rows with gaps, then run production matching and inspect the exact selected seat sets in public snapshot.",
  oracle: "Eligible Entries are processed by createdAt and identity; selection uses the lexicographically first same-zone same-row strictly contiguous set, while insufficient or over-cap entries remain WAITING with no partial Offer.",
  async run(ctx) {
    const fixture = ctx.fixtures.waitlist(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi();
    const created = [await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("first"), { key: ctx.key("wait-first") }), await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("second"), { key: ctx.key("wait-second") })]; const [first, second] = created.sort((left, right) => left.createdAt.localeCompare(right.createdAt) || left.waitlistEntryId.localeCompare(right.waitlistEntryId)); const overCap = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("over-cap", { seatCount: 2, maxUnitTotalMinor: 100 }), { key: ctx.key("wait-over-cap") }); const worker = await startSeatWorker(ctx, provider);
    const settled = await waitForSnapshot(ctx, api.baseUrl, (snapshot) => snapshot.resources.seatOffers.filter(({ state }) => state === "ACTIVE").length >= 2, { label: "two FIFO Offers", processes: [worker] }); const seatById = new Map(settled.resources.seats.map((seat) => [seat.seatId, seat])); const priceByZone = new Map(settled.resources.priceVersions.filter(({ state }) => state === "ACTIVE").map((price) => [price.zoneId, price])); const ownerIds = new Set(); const expectedFirst = selectWaitlistSeats({ seats: settled.resources.seats, activePriceByZone: priceByZone, liveOwnerSeatIds: ownerIds, seatCount: first.seatCount, allowedZoneIds: first.allowedZoneIds, maxUnitTotalMinor: first.maxUnitTotalMinor }); const firstOffer = assertOfferSelection(settled, first, expectedFirst); firstOffer.items.forEach(({ seatId }) => ownerIds.add(seatId)); const expectedSecond = selectWaitlistSeats({ seats: settled.resources.seats, activePriceByZone: priceByZone, liveOwnerSeatIds: ownerIds, seatCount: second.seatCount, allowedZoneIds: second.allowedZoneIds, maxUnitTotalMinor: second.maxUnitTotalMinor }); const secondOffer = assertOfferSelection(settled, second, expectedSecond);
    ctx.equal(firstOffer.items.map(({ seatId }) => seatById.get(seatId).number).sort((left, right) => left - right), [1, 2, 3], "worked example selects A1-A3"); ctx.equal(firstOffer.items.map(({ seatId }) => seatById.get(seatId).row), ["A", "A", "A"], "worked example remains in row A"); ctx.equal(secondOffer.items.map(({ seatId }) => seatById.get(seatId).row), ["B", "B", "B"], "gapped remainder is not combined across rows"); const capEntry = settled.resources.waitlistEntries.find(({ waitlistEntryId }) => waitlistEntryId === overCap.waitlistEntryId); ctx.equal(capEntry.state, "WAITING", "over-cap Entry remains WAITING"); ctx.equal(settled.resources.seatOffers.filter(({ waitlistEntryId }) => waitlistEntryId === overCap.waitlistEntryId).length, 0, "over-cap Entry creates no partial Offer"); assertSeatConservation(settled);
    return finalEvidence(ctx, { entryOrder: [first.waitlistEntryId, second.waitlistEntryId], offers: [firstOffer.seatOfferId, secondOffer.seatOfferId] });
  },
});

const A05 = defineCase({
  id: "A-05", fixtureFamily: "SR-F-OFFER-LIFECYCLE",
  action: "Match several WaitlistEntries, read each SeatOffer publicly, activate a later price, then accept, decline, cancel, and naturally expire independent Offers.",
  oracle: "Offer creation freezes all seats and exact amounts for 120 seconds; accept creates one 300-second HELD Hold from the frozen items, while decline, cancel, and expiry release atomically with published terminal states.",
  async run(ctx) {
    const fixture = ctx.fixtures.waitlist(); const provider = await startProviderDouble(ctx); const target = await prepare(ctx, { seed: fixture.seed }); const api = await target.startApi(); const worker = await startSeatWorker(ctx, provider);
    const acceptedEntry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("accept", { seatCount: 2 })); const acceptedMatch = await waitForOffer(ctx, api.baseUrl, acceptedEntry.waitlistEntryId, [worker]); const publicOffer = await getOffer(ctx, api.baseUrl, acceptedMatch.offer.seatOfferId); ctx.equal(publicOffer, acceptedMatch.offer, "GET returns exact authoritative Offer"); ctx.equal(Date.parse(publicOffer.expiresAt) - Date.parse(publicOffer.createdAt), 120_000, "Offer lifetime is exact");
    const activate = await ctx.mutate(api.baseUrl, `/api/v1/price-versions/${fixture.prices.priceA2.priceVersionId}/activate`, ctx.key("offer-later-price"), { expectedActivePriceVersionId: fixture.prices.priceA1.priceVersionId }); ctx.equal(activate.status, 200, "later price activates"); const stillFrozen = await getOffer(ctx, api.baseUrl, publicOffer.seatOfferId); ctx.equal(stillFrozen.items, publicOffer.items, "Offer items do not reprice"); const accepted = await acceptOffer(ctx, api.baseUrl, publicOffer.seatOfferId); ctx.equal(accepted.offer.state, "ACCEPTED", "accept terminal Offer"); ctx.equal(accepted.hold.state, "HELD", "accept creates normal Hold"); ctx.equal(Date.parse(accepted.hold.expiresAt) - Date.parse(accepted.hold.createdAt), 300_000, "accepted Hold lifetime");
    const afterAccept = await ctx.snapshot(api.baseUrl); const acceptedItems = afterAccept.resources.holdSeats.filter(({ holdId }) => holdId === accepted.hold.holdId); ctx.equal(acceptedItems.map(({ seatId, priceVersionId, unitAmountMinor, feeMinor }) => ({ seatId, priceVersionId, unitAmountMinor, feeMinor })), publicOffer.items, "accepted Hold copies frozen Offer items"); ctx.equal(afterAccept.resources.waitlistEntries.find(({ waitlistEntryId }) => waitlistEntryId === acceptedEntry.waitlistEntryId).state, "FULFILLED", "accept fulfills Entry");
    const declinedEntry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("decline", { seatCount: 2 })); const declinedMatch = await waitForOffer(ctx, api.baseUrl, declinedEntry.waitlistEntryId, [worker]); const declined = await declineOffer(ctx, api.baseUrl, declinedMatch.offer.seatOfferId); ctx.equal(declined.state, "DECLINED", "decline terminal Offer"); const afterDecline = await ctx.snapshot(api.baseUrl); ctx.equal(afterDecline.resources.waitlistEntries.find(({ waitlistEntryId }) => waitlistEntryId === declinedEntry.waitlistEntryId).state, "DECLINED", "decline terminal Entry");
    const cancelledEntry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("cancel", { seatCount: 2 })); const cancelledMatch = await waitForOffer(ctx, api.baseUrl, cancelledEntry.waitlistEntryId, [worker]); const cancelled = await cancelWaitlist(ctx, api.baseUrl, cancelledEntry.waitlistEntryId); ctx.equal(cancelled.state, "CANCELLED", "cancel terminal Entry"); const cancelledSnapshot = await ctx.snapshot(api.baseUrl); ctx.equal(cancelledSnapshot.resources.seatOffers.find(({ seatOfferId }) => seatOfferId === cancelledMatch.offer.seatOfferId).state !== "ACTIVE", true, "cancel releases active Offer");
    const expiringEntry = await createWaitlist(ctx, api.baseUrl, fixture.waitlistPayload("expiry", { seatCount: 1 })); const expiringMatch = await waitForOffer(ctx, api.baseUrl, expiringEntry.waitlistEntryId, [worker]); const expired = await waitForSnapshot(ctx, api.baseUrl, (snapshot) => snapshot.resources.seatOffers.find(({ seatOfferId }) => seatOfferId === expiringMatch.offer.seatOfferId)?.state === "EXPIRED", { timeoutMs: 150_000, label: "natural 120-second Offer expiry", processes: [worker] }); const expiryEntryState = expired.resources.waitlistEntries.find(({ waitlistEntryId }) => waitlistEntryId === expiringEntry.waitlistEntryId).state; ctx.ok(["WAITING", "OFFERED"].includes(expiryEntryState), "Offer expiry restores eligibility before any immediate rematch"); assertSeatConservation(expired); assertFrozenTotals(expired);
    return finalEvidence(ctx, { acceptedOfferId: accepted.offer.seatOfferId, declinedOfferId: declined.seatOfferId, expiredOfferId: expiringMatch.offer.seatOfferId });
  },
});

export const A_CASES = Object.freeze([A01, A02, A03, A04, A05]);
