import { createHash } from "node:crypto";
function digest(seed, label) { return createHash("sha256").update(`${seed}\0${label}`).digest(); }
function uuidFrom(bytes) { const hex = bytes.toString("hex"); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-a${hex.slice(17, 20)}-${hex.slice(20, 32)}`; }
export function createFixtureFactory({ evaluationSeed, caseId, baseTime }) { const seed = `${evaluationSeed}\0${caseId}`, epoch = Date.parse(baseTime); if (!Number.isFinite(epoch))
    throw new TypeError("baseTime must be ISO"); return Object.freeze({ seed, uuid: (label) => uuidFrom(digest(seed, `uuid:${label}`)), key: (label) => `co-${String(label).replace(/[^a-z0-9-]/giu, "-").slice(0, 70)}-${digest(seed, `key:${label}`).toString("hex").slice(0, 18)}`, at: ({ milliseconds = 0, seconds = 0 } = {}) => new Date(epoch + milliseconds + seconds * 1000).toISOString(), salt: (label) => `salt-${digest(seed, `salt:${label}`).toString("hex").slice(0, 24)}` }); }
export function canonical(value) { if (Array.isArray(value))
    return `[${value.map(canonical).join(",")}]`; if (value && typeof value === "object") {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;
} const encoded = JSON.stringify(value); if (encoded === undefined)
    throw new TypeError("unsupported JSON value"); return encoded; }
export function sha256(value) { return createHash("sha256").update(value).digest("hex"); }
export function documentDigest(document) { return sha256(Buffer.from(canonical(document))); }
export function assignmentBucket({ tenantId, applicationId, environmentId, releaseId, audienceSalt, clientId }) { const input = `${tenantId}:${applicationId}:${environmentId}:${releaseId}:${audienceSalt}:${clientId}`, hash = createHash("sha256").update(input).digest(); return Number(hash.readBigUInt64BE(0) % 10000n); }
export function baseCatalog(fixtures, label = "base") {
    const tenant = { tenantId: fixtures.uuid(`${label}:tenant`), name: `Tenant ${label}` }, application = { applicationId: fixtures.uuid(`${label}:application`), tenantId: tenant.tenantId, key: `app-${label}`.toLowerCase().replace(/[^a-z0-9._-]/gu, "-"), name: `Application ${label}` }, keys = ["development", "staging", "production"], environments = keys.map((key, index) => ({ environmentId: fixtures.uuid(`${label}:env:${key}`), applicationId: application.applicationId, key, generation: 1, activeReleaseId: fixtures.uuid(`${label}:release:${key}:1`), createdAt: fixtures.at({ seconds: index }) })), configRevisions = environments.map((environment, index) => { const document = { feature: "stable", environment: environment.key, limits: { requests: 100 + index } }; return { revisionId: fixtures.uuid(`${label}:revision:${environment.key}:1`), environmentId: environment.environmentId, revision: 1, parentRevisionId: null, state: "PUBLISHED", document, documentDigest: documentDigest(document), schemaRevision: 1, createdAt: fixtures.at({ seconds: 10 + index }), publishedAt: fixtures.at({ seconds: 20 + index }) }; }), releases = environments.map((environment, index) => ({ releaseId: environment.activeReleaseId, environmentId: environment.environmentId, revisionId: configRevisions[index].revisionId, previousReleaseId: null, state: "ACTIVE", rolloutBasisPoints: 10000, audienceSalt: fixtures.salt(`${label}:${environment.key}:1`), generation: 1, createdAt: fixtures.at({ seconds: 30 + index }), activatedAt: fixtures.at({ seconds: 40 + index }), terminalAt: null }));
    return { tenant, application, environments, configRevisions, releases };
}
export function v1Seed(fixtures, label = "seed", options = {}) { const catalog = options.catalog ?? baseCatalog(fixtures, label), clientCount = options.clientCount ?? 0, invalidations = options.invalidations ?? []; return { schemaVersion: 1, seedVersion: options.seedVersion ?? `${label}-${sha256(Buffer.from(fixtures.seed)).slice(0, 12)}`, tenants: [catalog.tenant], applications: [catalog.application], environments: catalog.environments, configRevisions: catalog.configRevisions, releases: catalog.releases, clientObservations: Array.from({ length: clientCount }, (_, index) => ({ clientId: `client-${String(index).padStart(6, "0")}`, environmentId: catalog.environments[0].environmentId, lastGeneration: 1, lastReleaseId: catalog.environments[0].activeReleaseId, lastSeenAt: fixtures.at({ seconds: 100 + index % 60 }) })), invalidations, auditEntries: [] }; }
export function emptySeed(fixtures, label = "empty") { return { schemaVersion: 1, seedVersion: `${label}-${sha256(Buffer.from(fixtures.seed)).slice(0, 12)}`, tenants: [], applications: [], environments: [], configRevisions: [], releases: [], clientObservations: [], invalidations: [], auditEntries: [] }; }
export function revisionBody(catalog, document, options = {}) { const environment = options.environment ?? catalog.environments[0], parent = options.parentRevisionId === undefined ? catalog.configRevisions.find(({ environmentId }) => environmentId === environment.environmentId)?.revisionId : options.parentRevisionId; return { environmentId: environment.environmentId, parentRevisionId: parent ?? null, schemaRevision: options.schemaRevision ?? 1, document }; }
export function publishBody(options = {}) { return { rolloutBasisPoints: options.rolloutBasisPoints ?? 10000, audienceSalt: options.audienceSalt ?? "hidden-publish-salt", expectedGeneration: options.expectedGeneration ?? 1, startAt: options.startAt ?? "2000-01-01T00:00:00.000Z" }; }
export function rolloutBody(expectedGeneration, rolloutBasisPoints) { return { rolloutBasisPoints, expectedGeneration, audienceSalt: "hidden-rollout-salt" }; }
export function observationBody({ clientId, environmentId, lastGeneration, lastReleaseId }) { return { clientId, environmentId, lastGeneration, lastReleaseId }; }
export function trainBody(catalog, options = {}) { const environments = options.environments ?? catalog.environments; return { tenantId: catalog.tenant.tenantId, applicationId: catalog.application.applicationId, name: options.name ?? "promotion-train", revisionId: options.revisionId ?? catalog.configRevisions[0].revisionId, stages: environments.map((environment, index) => ({ environmentId: environment.environmentId, rolloutBasisPoints: options.rolloutBasisPoints?.[index] ?? [2500, 5000, 10000][index] })) }; }
export function performanceContract() { return Object.freeze({ fetch: { clientCount: 50000, concurrency: 128, durationSeconds: 60, currentEtagPercent: 80, stalePercent: 20, targetPerSecond: 800, p95Ms: 150 }, contention: { environmentCount: 100, apiCount: 2, concurrency: 64, attempts: 10000, targetPerSecond: 100, p95Ms: 500 }, invalidation: { count: 100000, killedWorkers: 2, replacementWorkers: 4, maximumSeconds: 90, convergenceSeconds: 5 } }); }
export function performanceCatalog(fixtures, count = 100) { const tenant = { tenantId: fixtures.uuid("perf:tenant"), name: "Performance Tenant" }, applications = [], environments = [], configRevisions = [], releases = []; for (let index = 0; index < count; index += 1) {
    const application = { applicationId: fixtures.uuid(`perf:app:${index}`), tenantId: tenant.tenantId, key: `perf-${String(index).padStart(3, "0")}`, name: `Performance ${index}` }, environment = { environmentId: fixtures.uuid(`perf:env:${index}`), applicationId: application.applicationId, key: "production", generation: 1, activeReleaseId: fixtures.uuid(`perf:release:${index}`), createdAt: fixtures.at({ seconds: index }) }, document = { index, enabled: true }, revision = { revisionId: fixtures.uuid(`perf:revision:${index}`), environmentId: environment.environmentId, revision: 1, parentRevisionId: null, state: "PUBLISHED", document, documentDigest: documentDigest(document), schemaRevision: 1, createdAt: fixtures.at({ seconds: 200 + index }), publishedAt: fixtures.at({ seconds: 300 + index }) }, release = { releaseId: environment.activeReleaseId, environmentId: environment.environmentId, revisionId: revision.revisionId, previousReleaseId: null, state: "ACTIVE", rolloutBasisPoints: 10000, audienceSalt: fixtures.salt(`perf:${index}`), generation: 1, createdAt: fixtures.at({ seconds: 400 + index }), activatedAt: fixtures.at({ seconds: 500 + index }), terminalAt: null };
    applications.push(application);
    environments.push(environment);
    configRevisions.push(revision);
    releases.push(release);
} return { tenant, applications, environments, configRevisions, releases }; }
export function performanceSeed(fixtures, { environmentCount = 100, clientCount = 0, invalidationCount = 0, label = "perf" } = {}) { const catalog = performanceCatalog(fixtures, environmentCount), invalidations = Array.from({ length: invalidationCount }, (_, index) => { const environment = catalog.environments[index % environmentCount]; return { invalidationId: fixtures.uuid(`${label}:invalidation:${index}`), environmentId: environment.environmentId, generation: 1, releaseId: environment.activeReleaseId, eventId: fixtures.uuid(`${label}:event:${index}`), state: "PENDING", createdAt: fixtures.at({ seconds: index % 60 }), deliveredAt: null }; }); return { catalog, seed: { schemaVersion: 1, seedVersion: `${label}-${sha256(Buffer.from(fixtures.seed)).slice(0, 12)}`, tenants: [catalog.tenant], applications: catalog.applications, environments: catalog.environments, configRevisions: catalog.configRevisions, releases: catalog.releases, clientObservations: Array.from({ length: clientCount }, (_, index) => ({ clientId: `client-${String(index).padStart(6, "0")}`, environmentId: catalog.environments[0].environmentId, lastGeneration: 1, lastReleaseId: catalog.environments[0].activeReleaseId, lastSeenAt: fixtures.at({ seconds: index % 60 }) })), invalidations, auditEntries: [] } }; }
export function contentionSeed(fixtures, { environmentCount = 100, label = "contention" } = {}) { const tenant = { tenantId: fixtures.uuid(`${label}:tenant`), name: "Contention Tenant" }, catalogs = Array.from({ length: environmentCount }, (_, index) => { const catalog = baseCatalog(fixtures, `${label}-${String(index).padStart(3, "0")}`); catalog.tenant = tenant; catalog.application.tenantId = tenant.tenantId; return catalog; }), applications = catalogs.map(({ application }) => application), environments = catalogs.flatMap(({ environments }) => environments), configRevisions = catalogs.flatMap(({ configRevisions }) => configRevisions), releases = catalogs.flatMap(({ releases }) => releases); return { catalogs, seed: { schemaVersion: 1, seedVersion: `${label}-${sha256(Buffer.from(fixtures.seed)).slice(0, 12)}`, tenants: [tenant], applications, environments, configRevisions, releases, clientObservations: [], invalidations: [], auditEntries: [] } }; }
