import assert from "node:assert/strict";
import { publishBody, revisionBody } from "../lib/fixtures.mjs";
import { assertClientConfig, assertPromotionTrain, assertPublicError, assertRevision, assertSnapshot, documentDigest } from "../lib/oracle.mjs";
export function defineCase(id, fixtureFamily, action, oracle, seams, run) { return Object.freeze({ id, taskId: "configorbit", fixtureFamily, action, oracle, seams: Object.freeze([...seams]), run }); }
export function caseResult(ctx, details = {}, diagnostics = []) { return { evidence: [{ caseId: ctx.caseId, taskId: "configorbit", ...details }], ...(diagnostics.length ? { diagnostics } : {}) }; }
export function requireStatus(response, status, label = "request") { const values = Array.isArray(status) ? status : [status]; assert.ok(values.includes(response.status), `${label}: expected ${values.join("/")}, got ${response.status}: ${response.text}`); return response.json; }
export function expectError(ctx, response, status, code, options = {}) { ctx.assert(`${code} exact error`, () => assertPublicError(response, status, code), options); return response; }
export async function boot(ctx, options = {}) { const catalog = options.catalog ?? ctx.catalog(options.label ?? ctx.caseId.toLowerCase()); if (options.seed !== false)
    await ctx.seed(options.seed ?? ctx.seedFor(options.label ?? ctx.caseId.toLowerCase(), { catalog, ...options.seedOptions }), { workspace: options.workspace }); const apis = []; for (let index = 0; index < (options.apiCount ?? 1); index += 1)
    apis.push(await ctx.startApi({ workspace: options.workspace })); return { catalog, apis, api: apis[0] }; }
export async function snapshot(ctx, url, options = {}) { const value = await ctx.snapshot(url, options); ctx.assert("snapshot exact sorted union", () => assertSnapshot(value, { final: options.final ?? true }), options.assertionOptions); return value; }
export function environmentFrom(state, id) { return state.resources.environments.find(({ environmentId }) => environmentId === id); }
export function revisionFrom(state, id) { return state.resources.configRevisions.find(({ revisionId }) => revisionId === id); }
export function releaseFrom(state, id) { return state.resources.releases.find(({ releaseId }) => releaseId === id); }
export function trainFrom(state, id) { return state.resources.promotionTrains?.find(({ trainId }) => trainId === id); }
export function stagesFor(state, id) { return (state.resources.promotionStages ?? []).filter(({ trainId }) => trainId === id).sort((a, b) => a.position - b.position); }
export function workFor(state, kind, aggregateId) { return state.work.filter((item) => item.kind === kind && (aggregateId === undefined || item.aggregateId === aggregateId)); }
export function eventsFor(state, aggregateId) { return state.events.filter((item) => item.aggregateId === aggregateId); }
export async function waitSnapshot(ctx, url, predicate, options = {}) { return ctx.waitFor(async () => { const state = await ctx.snapshot(url, { timeoutMs: options.requestTimeoutMs }); return predicate(state) ? state : undefined; }, { label: options.label ?? "ConfigOrbit durable state", timeoutMs: options.timeoutMs ?? 60000, intervalMs: options.intervalMs ?? 100, processes: options.processes ?? [] }); }
export async function createDraft(ctx, url, catalog, document, options = {}) { const body = revisionBody(catalog, document, options), response = await ctx.createRevision(url, body, { key: options.key }); ctx.equal("revision create status", response.status, 200); ctx.assert("ConfigRevision create exact", () => assertRevision(response.json)); ctx.equal("draft document digest", response.json.documentDigest, documentDigest(document)); ctx.equal("new revision DRAFT", response.json.state, "DRAFT"); return { body, response, revision: response.json }; }
export async function publishDraft(ctx, url, revision, options = {}) { const body = publishBody(options), response = await ctx.publishRevision(url, revision.revisionId, body, { key: options.key }); ctx.equal("publish status", response.status, 200); return { body, response }; }
export async function waitGeneration(ctx, url, environmentId, generation, options = {}) { return waitSnapshot(ctx, url, (state) => environmentFrom(state, environmentId)?.generation === generation, { ...options, label: options.label ?? `environment generation ${generation}` }); }
export async function fetchClient(ctx, url, catalog, clientId, options = {}) { const environment = options.environment ?? catalog.environments[0], query = { tenantId: catalog.tenant.tenantId, applicationKey: catalog.application.key, environmentKey: environment.key, clientId, ...(options.knownGeneration === undefined ? {} : { knownGeneration: String(options.knownGeneration) }) }, response = await ctx.clientConfig(url, query, { headers: options.headers }); if (response.status === 200)
    ctx.assert("client-config exact", () => assertClientConfig(response.json)); return response; }
export async function createTrain(ctx, url, catalog, options = {}) { const body = ctx.trainBody(catalog, options), response = await ctx.createTrain(url, body, { key: options.key }); ctx.equal("Train create status", response.status, 200); ctx.assert("PromotionTrain exact", () => assertPromotionTrain(response.json)); ctx.equal("Train starts DRAFT", response.json.state, "DRAFT"); return { body, response, train: response.json }; }
export function stableSemantic(ctx, responses, label, options = {}) { ctx.ok(`${label} has responses`, responses.length > 0); ctx.equal(`${label} status stable`, new Set(responses.map(({ status }) => status)).size, 1, options); ctx.equal(`${label} semantic body stable`, new Set(responses.map(({ json }) => ctx.canonical(json))).size, 1, options); return responses[0]; }
export async function resetBoot(ctx, options = {}) { await ctx.resetDatabase(); await ctx.migrate(); return boot(ctx, options); }
export async function browserControls(ctx, api, operation) { return ctx.withPage(api, { width: 1280, height: 800 }, async (page) => { await page.goto("/", { waitUntil: "networkidle" }); ctx.ok("production UI exposes visible controls", await page.locator("a,button,input,textarea,select").count() > 0); if (operation)
    await operation(page); }); }
