import { observationBody, rolloutBody, publishBody as publicationBody } from "../lib/fixtures.mjs";
import { assertGenerationClosure, assertPromotionTrain } from "../lib/oracle.mjs";
import { boot, caseResult, createDraft, createTrain, defineCase, environmentFrom, expectError, fetchClient, publishDraft, snapshot, stableSemantic, stagesFor, trainFrom, waitGeneration, waitSnapshot } from "./helpers.mjs";
async function unknownReplay(ctx, apis, path, key, body, conflictBody) { const shield = await ctx.responseShield(apis[0].baseUrl); shield.dropNextMutation(); await ctx.mutate(shield.baseUrl, path, key, body).catch(() => undefined); await ctx.waitFor(() => shield.captures.find(({ dropped }) => dropped), { label: `dropped ${path} response` }); const committed = await ctx.snapshot(apis[0].baseUrl), responses = await Promise.all(Array.from({ length: 20 }, (_, index) => ctx.mutate(apis[index % 2].baseUrl, path, key, body))), first = stableSemantic(ctx, responses, path, { hardCapIds: ["IDEMPOTENCY_CORRECTNESS"] }); expectError(ctx, await ctx.mutate(apis[1].baseUrl, path, key, conflictBody), 409, "IDEMPOTENCY_CONFLICT", { hardCapIds: ["IDEMPOTENCY_CORRECTNESS"] }); const replayed = await ctx.snapshot(apis[0].baseUrl); ctx.equal(`${path} replay and conflict have zero additional durable effect`, { resources: replayed.resources, work: replayed.work, events: replayed.events }, { resources: committed.resources, work: committed.work, events: committed.events }, { hardCapIds: ["IDEMPOTENCY_CORRECTNESS"] }); return first; }
const RACE01 = defineCase("RACE-01", "three unknown mutation responses", "Drop committed publish, rollout and current-stage Train rollback responses then replay 20-way across two APIs", "Saved responses and all generation Release invalidation audit Event and Work effects occur once", ["response shield", "two APIs", "restart"], async (ctx) => {
    const { apis, catalog } = await boot(ctx, { apiCount: 2 }), environment = catalog.environments[0], draft = await createDraft(ctx, apis[0].baseUrl, catalog, { race: "publish" }), publishKey = ctx.key("unknown-publish"), publishBody = publicationBody({ rolloutBasisPoints: 10000, audienceSalt: "race-publish", expectedGeneration: 1 });
    await unknownReplay(ctx, apis, `/api/v1/config-revisions/${draft.revision.revisionId}/publish`, publishKey, publishBody, { ...publishBody, rolloutBasisPoints: 9999 });
    let state = await waitGeneration(ctx, apis[0].baseUrl, environment.environmentId, 2);
    ctx.equal("publish has one generation-2 Release", state.resources.releases.filter(({ environmentId, generation }) => environmentId === environment.environmentId && generation === 2).length, 1, { hardCapIds: ["IDEMPOTENCY_CORRECTNESS"] });
    await ctx.stop(apis[1]);
    apis[1] = await ctx.startApi();
    const rolloutKey = ctx.key("unknown-rollout"), rollout = rolloutBody(2, 5000);
    await unknownReplay(ctx, apis, `/api/v1/environments/${environment.environmentId}/rollout`, rolloutKey, rollout, { ...rollout, rolloutBasisPoints: 5001 });
    state = await waitGeneration(ctx, apis[0].baseUrl, environment.environmentId, 3);
    ctx.equal("rollout has one generation-3 Release", state.resources.releases.filter(({ environmentId, generation }) => environmentId === environment.environmentId && generation === 3).length, 1, { hardCapIds: ["IDEMPOTENCY_CORRECTNESS"] });
    const created = await createTrain(ctx, apis[0].baseUrl, catalog, { name: "replay-rollback" });
    await ctx.startTrain(apis[0].baseUrl, created.train.trainId);
    let worker = await ctx.startWorker();
    state = await waitSnapshot(ctx, apis[0].baseUrl, (value) => trainFrom(value, created.train.trainId)?.state === "RUNNING" && stagesFor(value, created.train.trainId)[0]?.state === "ACTIVE", { label: "replay Train active", processes: [worker] });
    await ctx.stop(worker);
    const expectedGeneration = environmentFrom(state, environment.environmentId).generation, rollbackKey = ctx.key("unknown-train-rollback"), rollbackBody = { expectedStage: 0, expectedEnvironmentGeneration: expectedGeneration };
    const rollbackResponse = await unknownReplay(ctx, apis, `/api/v1/promotion-trains/${created.train.trainId}/rollback`, rollbackKey, rollbackBody, { ...rollbackBody, expectedStage: 1 });
    ctx.assert("Train rollback replay exact response", () => assertPromotionTrain(rollbackResponse.json));
    worker = await ctx.startWorker();
    const final = await waitSnapshot(ctx, apis[0].baseUrl, (value) => trainFrom(value, created.train.trainId)?.state === "ROLLED_BACK", { label: "replayed Train rollback terminal", processes: [worker] });
    await ctx.stop(worker);
    ctx.equal("Train rollback advances one generation", environmentFrom(final, environment.environmentId).generation, expectedGeneration + 1);
    ctx.equal("one compensating Release", final.resources.releases.filter(({ environmentId, generation }) => environmentId === environment.environmentId && generation === expectedGeneration + 1).length, 1, { hardCapIds: ["IDEMPOTENCY_CORRECTNESS"] });
    ctx.assert("replay generation closure", () => assertGenerationClosure(final));
    return caseResult(ctx, { publishReplay: 20, rolloutReplay: 20, rollbackReplay: 20 });
});
const RACE02 = defineCase("RACE-02", "shared generation and Stage hotspot", "Race 16 rollout and 16 current-Stage Train rollback requests across two APIs", "Only one successor generation and Release wins; every loser has a published CAS conflict", ["two APIs", "32 concurrent requests", "snapshot"], async (ctx) => { const { apis, catalog } = await boot(ctx, { apiCount: 2 }), environment = catalog.environments[0], created = await createTrain(ctx, apis[0].baseUrl, catalog, { name: "generation-race" }); await ctx.startTrain(apis[0].baseUrl, created.train.trainId); const workers = await Promise.all([ctx.startWorker(), ctx.startWorker()]); let state = await waitSnapshot(ctx, apis[0].baseUrl, (value) => trainFrom(value, created.train.trainId)?.state === "RUNNING" && stagesFor(value, created.train.trainId)[0]?.state === "ACTIVE", { label: "race Train active", processes: workers }); for (const worker of workers)
    await ctx.stop(worker); const generation = environmentFrom(state, environment.environmentId).generation, responses = await Promise.all(Array.from({ length: 32 }, (_, index) => index % 2 === 0 ? ctx.rollout(apis[index % 2].baseUrl, environment.environmentId, rolloutBody(generation, 5000), { key: ctx.key(`hot-rollout-${index}`) }) : ctx.rollbackTrain(apis[index % 2].baseUrl, created.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: generation }, { key: ctx.key(`hot-rollback-${index}`) }))); ctx.equal("exactly one hotspot mutation succeeds", responses.filter(({ status }) => status === 200).length, 1, { hardCapIds: ["GENERATION_AUTHORITY"] }); for (const response of responses.filter(({ status }) => status !== 200)) {
    ctx.equal("loser is semantic conflict", response.status, 409);
    ctx.ok("loser code is a published CAS error", ["ENVIRONMENT_GENERATION_CHANGED", "PROMOTION_STAGE_CHANGED"].includes(response.json?.error?.code));
} state = await snapshot(ctx, apis[0].baseUrl); ctx.equal("hotspot advances one generation", environmentFrom(state, environment.environmentId).generation, generation + 1, { hardCapIds: ["GENERATION_AUTHORITY"] }); ctx.equal("one successor Release", state.resources.releases.filter(({ environmentId, generation: releaseGeneration }) => environmentId === environment.environmentId && releaseGeneration === generation + 1).length, 1, { hardCapIds: ["GENERATION_AUTHORITY"] }); ctx.assert("hotspot generation closure", () => assertGenerationClosure(state)); return caseResult(ctx, { accepted: 1, conflicts: 31 }); });
async function crashClaimed(ctx, kind, prepare, index) { await ctx.resetDatabase(); await ctx.migrate(); const { api, catalog } = await boot(ctx, { label: `race-03-${index}` }), prepared = await prepare(api, catalog), before = await ctx.snapshot(api.baseUrl), work = before.work.find((item) => item.kind === kind && !item.terminal && (prepared.aggregateId === undefined || item.aggregateId === prepared.aggregateId)); ctx.ok(`${kind} pending Work exists`, work); const barrier = ctx.workerBarrier(({ workId }) => workId === work.workId), stale = await ctx.startWorkerAtBarrier(barrier), held = await barrier.waitFor((entry) => entry.json.workId === work.workId, { timeoutMs: 30000, processes: [stale] }); await ctx.kill(stale); await ctx.sleep(3200); const replacement = await ctx.startWorker(), after = await waitSnapshot(ctx, api.baseUrl, (state) => state.work.find(({ workId }) => workId === work.workId)?.terminal === true, { label: `${kind} replacement drain`, timeoutMs: 60000, processes: [replacement] }); await ctx.stop(replacement); const terminal = after.work.find(({ workId }) => workId === work.workId); ctx.ok(`${kind} replacement increments attempt`, terminal.attempt > held.json.attempt, undefined, { hardCapIds: ["WORK_RECOVERY_CORRECTNESS"] }); ctx.assert(`${kind} generation closure`, () => assertGenerationClosure(after)); return { kind, workId: work.workId, attempt: terminal.attempt }; }
const RACE03 = defineCase("RACE-03", "three claimed Work recovery paths", "SIGKILL claimed RELEASE_ACTIVATE, CACHE_INVALIDATE and current-environment PROMOTION_ROLLBACK Work then reclaim", "Every Work drains once and stale owners cannot duplicate generation or Stage effects", ["worker.claimed", "SIGKILL", "lease expiry"], async (ctx) => { const results = []; results.push(await crashClaimed(ctx, "RELEASE_ACTIVATE", async (api, catalog) => { const draft = await createDraft(ctx, api.baseUrl, catalog, { activate: true }); await publishDraft(ctx, api.baseUrl, draft.revision, { rolloutBasisPoints: 10000, audienceSalt: "activate" }); return {}; }, 1)); results.push(await crashClaimed(ctx, "CACHE_INVALIDATE", async (api, catalog) => { const draft = await createDraft(ctx, api.baseUrl, catalog, { invalidate: true }); await publishDraft(ctx, api.baseUrl, draft.revision, { rolloutBasisPoints: 10000, audienceSalt: "invalidate" }); return {}; }, 2)); results.push(await crashClaimed(ctx, "PROMOTION_ROLLBACK", async (api, catalog) => { const created = await createTrain(ctx, api.baseUrl, catalog, { name: "rollback-work" }); await ctx.startTrain(api.baseUrl, created.train.trainId); const starter = await ctx.startWorker(), running = await waitSnapshot(ctx, api.baseUrl, (state) => trainFrom(state, created.train.trainId)?.state === "RUNNING" && stagesFor(state, created.train.trainId)[0]?.state === "ACTIVE", { label: "rollback Work Train active", processes: [starter] }); await ctx.stop(starter); const generation = environmentFrom(running, catalog.environments[0].environmentId).generation; await ctx.rollbackTrain(api.baseUrl, created.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: generation }); return { aggregateId: created.train.trainId }; }, 3)); return caseResult(ctx, { recovered: results }); });
const RACE04 = defineCase("RACE-04", "unknown webhook ACK and client observation reorder", "Hold the first receiver response after full body, kill dispatcher, restart, then apply generation 3/2/3 observations", "Retry bytes and Event identity stay exact while observation and fetch remain monotonic", ["receiver ledger", "dispatcher SIGKILL", "client-config"], async (ctx) => {
    const { api, catalog } = await boot(ctx), environment = catalog.environments[0], draft = await createDraft(ctx, api.baseUrl, catalog, { outbox: true });
    await publishDraft(ctx, api.baseUrl, draft.revision, { rolloutBasisPoints: 10000, audienceSalt: "outbox" });
    const worker = await ctx.startWorker();
    await waitSnapshot(ctx, api.baseUrl, (state) => state.events.length > 0 && state.resources.invalidations.length > 0, { label: "committed outbox Event", processes: [worker] });
    await ctx.stop(worker);
    const receiver = await ctx.receiver((entry) => entry.attempt === 1 ? { status: 204, delayMs: 60000 } : { status: 204 }), dispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url });
    await ctx.waitFor(() => receiver.ledger.length >= 1, { label: "receiver persisted first Event", processes: [dispatcher] });
    await ctx.kill(dispatcher);
    const replacement = await ctx.startDispatcher({ webhookUrl: receiver.url });
    await ctx.waitFor(() => receiver.ledger.length >= 2, { label: "replacement Event retry", timeoutMs: 30000, processes: [replacement] });
    await ctx.stop(replacement);
    const [first, second] = receiver.ledger;
    ctx.equal("Event retry raw body byte-identical", second.raw, first.raw, { hardCapIds: ["WORK_RECOVERY_CORRECTNESS"] });
    ctx.equal("Event retry eventId stable", second.json?.eventId, first.json?.eventId);
    ctx.equal("Event retry semantic body stable", second.json, first.json);
    await ctx.rollout(api.baseUrl, environment.environmentId, rolloutBody(2, 10000));
    const latest = await ctx.waitFor(async () => { const response = await fetchClient(ctx, api.baseUrl, catalog, "outbox-client", { environment, knownGeneration: 0 }); return response.status === 200 && response.json.generation === 3 ? response : undefined; }, { label: "generation 3 client convergence", timeoutMs: 5000, intervalMs: 50 });
    for (const generation of [3, 2, 3]) {
        const releaseId = generation === 3 ? latest.json.releaseId : catalog.environments[0].activeReleaseId, response = await ctx.observeClient(api.baseUrl, observationBody({ clientId: "outbox-client", environmentId: environment.environmentId, lastGeneration: generation, lastReleaseId: releaseId }));
        ctx.equal("reordered observation accepted", response.status, 200);
    }
    const state = await snapshot(ctx, api.baseUrl), observation = state.resources.clientObservations.find(({ clientId }) => clientId === "outbox-client");
    ctx.equal("reordered invalidation cannot decrease generation", observation.lastGeneration, 3, { hardCapIds: ["CLIENT_GENERATION_FENCE"] });
    ctx.equal("latest fetch remains generation 3", (await fetchClient(ctx, api.baseUrl, catalog, "outbox-client", { environment, knownGeneration: 2 })).json.generation, 3);
    for (const aggregateId of new Set(state.events.map(({ aggregateId }) => aggregateId))) {
        const events = state.events.filter((item) => item.aggregateId === aggregateId);
        ctx.equal("aggregate Event sequence remains continuous", events.map(({ sequence }) => sequence), events.map((_, index) => index + 1));
    }
    return caseResult(ctx, { deliveryAttempts: 2, finalObservation: 3 });
});
export const RACE_CASES = Object.freeze([RACE01, RACE02, RACE03, RACE04]);
