import { v1Seed } from "../lib/fixtures.mjs";
import { assertGenerationClosure, assertPromotionTrain } from "../lib/oracle.mjs";
import { boot, browserControls, caseResult, createTrain, defineCase, environmentFrom, expectError, snapshot, stagesFor, trainFrom, waitSnapshot } from "./helpers.mjs";
async function startRunning(ctx, url, train, catalog, options = {}) { const response = await ctx.startTrain(url, train.trainId, { key: options.key }); ctx.equal("Train start status", response.status, 200); ctx.assert("Train start exact response", () => assertPromotionTrain(response.json)); const worker = options.worker ?? await ctx.startWorker(), state = await waitSnapshot(ctx, url, (value) => trainFrom(value, train.trainId)?.state === "RUNNING" && stagesFor(value, train.trainId).filter(({ state: stageState }) => stageState === "ACTIVE").length === 1, { label: "Train RUNNING with one ACTIVE Stage", processes: [worker], timeoutMs: 60000 }); if (!options.worker)
    await ctx.stop(worker); return { response, state }; }
const TRAIN01 = defineCase("TRAIN-01", "three-stage Train fixture matrix", "Create valid and invalid stage lists, start and rollback without calling an unpublished update route", "Train digest, order, positions, environment bindings, rollout values and salt remain frozen", ["public Train mutations", "snapshot"], async (ctx) => {
    const catalog = ctx.catalog("train-01"), foreign = ctx.catalog("train-01-foreign"), seed = structuredClone(v1Seed(ctx.fixtures, "train-01", { catalog }));
    foreign.tenant = catalog.tenant;
    foreign.application.tenantId = catalog.tenant.tenantId;
    seed.applications.push(foreign.application);
    seed.environments.push(...foreign.environments);
    seed.configRevisions.push(...foreign.configRevisions);
    seed.releases.push(...foreign.releases);
    const { api } = await boot(ctx, { catalog, seed }), valid = await createTrain(ctx, api.baseUrl, catalog, { name: "frozen-train" }), createdState = await snapshot(ctx, api.baseUrl), frozenStages = stagesFor(createdState, valid.train.trainId).map(({ position, environmentId, rolloutBasisPoints }) => ({ position, environmentId, rolloutBasisPoints }));
    ctx.equal("stage positions start at zero", frozenStages.map(({ position }) => position), [0, 1, 2]);
    ctx.equal("stage environment order frozen", frozenStages.map(({ environmentId }) => environmentId), catalog.environments.map(({ environmentId }) => environmentId));
    ctx.equal("Train revision digest frozen from source", valid.train.revisionDigest, catalog.configRevisions[0].documentDigest);
    const invalidBodies = [{ ...valid.body, stages: [valid.body.stages[0], valid.body.stages[0]] }, { ...valid.body, stages: [...valid.body.stages].reverse() }, { ...valid.body, stages: valid.body.stages.map((item, index) => index === 1 ? { ...item, rolloutBasisPoints: 10001 } : item) }, { ...valid.body, stages: valid.body.stages.map((item, index) => index === 1 ? { ...item, environmentId: foreign.environments[1].environmentId } : item) }];
    for (let index = 0; index < invalidBodies.length; index += 1) {
        const response = await ctx.createTrain(api.baseUrl, invalidBodies[index], { key: ctx.key(`invalid-train-${index}`), ...(index === 2 ? { contractExpectation: "invalid" } : {}) });
        ctx.equal("invalid Train rejected", response.status, 400);
    }
    const rejected = await snapshot(ctx, api.baseUrl);
    ctx.equal("invalid Trains create no partial Train", rejected.resources.promotionTrains.length, 1);
    ctx.equal("invalid Trains create no partial Stages", rejected.resources.promotionStages.length, 3);
    const running = await startRunning(ctx, api.baseUrl, valid.train, catalog), generation = environmentFrom(running.state, catalog.environments[0].environmentId).generation, rolled = await ctx.rollbackTrain(api.baseUrl, valid.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: generation });
    ctx.equal("Train rollback status", rolled.status, 200);
    ctx.assert("Train rollback exact response", () => assertPromotionTrain(rolled.json));
    const worker = await ctx.startWorker(), final = await waitSnapshot(ctx, api.baseUrl, (state) => trainFrom(state, valid.train.trainId)?.state === "ROLLED_BACK", { label: "Train terminal rollback", processes: [worker] });
    await ctx.stop(worker);
    ctx.equal("frozen stages survive mutations", stagesFor(final, valid.train.trainId).map(({ position, environmentId, rolloutBasisPoints }) => ({ position, environmentId, rolloutBasisPoints })), frozenStages);
    ctx.equal("Train digest remains frozen", trainFrom(final, valid.train.trainId).revisionDigest, valid.train.revisionDigest);
    ctx.equal("audience salt remains frozen", trainFrom(final, valid.train.trainId).audienceSalt, valid.train.audienceSalt);
    return caseResult(ctx, { trainId: valid.train.trainId });
});
const TRAIN02 = defineCase("TRAIN-02", "DRAFT three-stage Train", "Start once and replay start while observing every environment and Work", "Exactly stage zero is ACTIVE and only development receives one normal generation effect", ["public start", "worker", "snapshot"], async (ctx) => { const { api, catalog } = await boot(ctx), created = await createTrain(ctx, api.baseUrl, catalog, { name: "single-stage" }), key = ctx.key("start-replay"), first = await ctx.startTrain(api.baseUrl, created.train.trainId, { key }), replay = await ctx.startTrain(api.baseUrl, created.train.trainId, { key }); ctx.equal("start replay exact status", replay.status, first.status); ctx.equal("start replay exact semantic body", replay.json, first.json); const worker = await ctx.startWorker(), state = await waitSnapshot(ctx, api.baseUrl, (value) => trainFrom(value, created.train.trainId)?.state === "RUNNING" && stagesFor(value, created.train.trainId).some(({ position, state: stageState }) => position === 0 && stageState === "ACTIVE"), { label: "first PromotionStage ACTIVE", processes: [worker] }); await ctx.stop(worker); const stages = stagesFor(state, created.train.trainId); ctx.equal("one ACTIVE Stage", stages.filter(({ state: stageState }) => stageState === "ACTIVE").length, 1, { hardCapIds: ["GENERATION_AUTHORITY"] }); ctx.equal("later Stages remain PENDING", stages.slice(1).map(({ state: stageState }) => stageState), ["PENDING", "PENDING"]); ctx.equal("development generation advances once", environmentFrom(state, catalog.environments[0].environmentId).generation, 2); ctx.equal("staging unchanged", environmentFrom(state, catalog.environments[1].environmentId).generation, 1); ctx.equal("production unchanged", environmentFrom(state, catalog.environments[2].environmentId).generation, 1); ctx.ok("normal Release exists", state.resources.releases.some(({ environmentId, generation }) => environmentId === catalog.environments[0].environmentId && generation === 2)); ctx.ok("normal Invalidation exists", state.resources.invalidations.some(({ environmentId, generation }) => environmentId === catalog.environments[0].environmentId && generation === 2)); ctx.assert("generation closure", () => assertGenerationClosure(state)); return caseResult(ctx, { trainId: created.train.trainId }); });
const TRAIN03 = defineCase("TRAIN-03", "current advance CAS rejection and snapshot refresh", "Submit publicly invalid stage and generation preconditions, verify zero effects, restart the API and reload the same Train and Stages through snapshot", "Rejected advance calls preserve all current resources, Work and Events; refresh is observable without inventing a Train GET or cross-environment revision identity", ["public advance rejection", "snapshot", "API restart"], async (ctx) => {
    const { api, catalog } = await boot(ctx);
    const created = await createTrain(ctx, api.baseUrl, catalog, { name: "advance-preconditions" });
    const running = await startRunning(ctx, api.baseUrl, created.train, catalog);
    const active = stagesFor(running.state, created.train.trainId).find(({ state }) => state === "ACTIVE");
    ctx.equal("current stage is zero", active.position, 0);
    const generation = environmentFrom(running.state, active.environmentId).generation;
    const wrongStage = await ctx.advanceTrain(api.baseUrl, created.train.trainId, { expectedStage: 1, expectedEnvironmentGeneration: generation }, { key: ctx.key("advance-wrong-stage") });
    expectError(ctx, wrongStage, 409, "PROMOTION_STAGE_CHANGED", { hardCapIds: ["GENERATION_AUTHORITY"] });
    // Zero is below every initialized environment generation; this does not choose
    // between the unspecified current/next-environment interpretation.
    const wrongGeneration = await ctx.advanceTrain(api.baseUrl, created.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: 0 }, { key: ctx.key("advance-wrong-generation") });
    expectError(ctx, wrongGeneration, 409, "ENVIRONMENT_GENERATION_CHANGED", { hardCapIds: ["GENERATION_AUTHORITY"] });
    const rejected = await snapshot(ctx, api.baseUrl);
    ctx.equal("rejected advance changes no resources", rejected.resources, running.state.resources);
    ctx.equal("rejected advance creates no Work", rejected.work, running.state.work);
    ctx.equal("rejected advance creates no Event", rejected.events, running.state.events);
    await ctx.kill(api);
    const restarted = await ctx.startApi(), refreshed = await snapshot(ctx, restarted.baseUrl);
    ctx.equal("snapshot refresh preserves current Train", trainFrom(refreshed, created.train.trainId), trainFrom(rejected, created.train.trainId));
    ctx.equal("snapshot refresh preserves every frozen Stage", stagesFor(refreshed, created.train.trainId), stagesFor(rejected, created.train.trainId));
    ctx.assert("current generation closure after rejection and restart", () => assertGenerationClosure(refreshed));
    return caseResult(ctx, { policyRevision: "learning-final-system-2026-09-08.1", trainId: created.train.trainId, rejectedAdvanceCalls: 2, killedApis: 1, positiveCrossEnvironmentAdvanceCovered: false });
});
const TRAIN04 = defineCase("TRAIN-04", "development current-stage rollback", "Start the source-environment Stage then roll it back under expectedStage and generation", "Only development receives a compensating Release and all other generations remain unchanged", ["public rollback", "worker", "OpenAPI", "Chromium"], async (ctx) => { const { api, catalog } = await boot(ctx), created = await createTrain(ctx, api.baseUrl, catalog, { name: "compensation" }), running = await startRunning(ctx, api.baseUrl, created.train, catalog), before = running.state, development = catalog.environments[0], expectedGeneration = environmentFrom(before, development.environmentId).generation, response = await ctx.rollbackTrain(api.baseUrl, created.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: expectedGeneration }); ctx.equal("Train rollback response status", response.status, 200); ctx.assert("Train rollback response exact", () => assertPromotionTrain(response.json)); const worker = await ctx.startWorker(), after = await waitSnapshot(ctx, api.baseUrl, (state) => trainFrom(state, created.train.trainId)?.state === "ROLLED_BACK", { label: "compensating rollback", processes: [worker] }); await ctx.stop(worker); ctx.equal("development compensation increments generation", environmentFrom(after, development.environmentId).generation, expectedGeneration + 1, { hardCapIds: ["GENERATION_AUTHORITY"] }); for (const environment of catalog.environments.slice(1))
    ctx.equal(`${environment.key} generation unchanged`, environmentFrom(after, environment.environmentId).generation, 1, { hardCapIds: ["GENERATION_AUTHORITY"] }); ctx.equal("current Stage ROLLED_BACK", stagesFor(after, created.train.trainId)[0].state, "ROLLED_BACK"); ctx.assert("compensation generation closure", () => assertGenerationClosure(after)); const openapi = await ctx.readOpenApi(api.baseUrl); ctx.ok("rollback operation published", Object.hasOwn(openapi.paths, "/api/v1/promotion-trains/{trainId}/rollback")); await browserControls(ctx, api); return caseResult(ctx, { trainId: created.train.trainId, environmentId: development.environmentId }); });
const TRAIN05 = defineCase("TRAIN-05", "reachable ROLLED_BACK Train", "Attempt start, advance and rollback after terminal plus missing/stale operations", "Every reachable failure has exact code/envelope and terminal snapshot cannot revive", ["public Train mutations", "snapshot"], async (ctx) => { const { api, catalog } = await boot(ctx), created = await createTrain(ctx, api.baseUrl, catalog, { name: "terminal-wire" }), running = await startRunning(ctx, api.baseUrl, created.train, catalog), generation = environmentFrom(running.state, catalog.environments[0].environmentId).generation; expectError(ctx, await ctx.rollbackTrain(api.baseUrl, created.train.trainId, { expectedStage: 1, expectedEnvironmentGeneration: generation }), 409, "PROMOTION_STAGE_CHANGED", { hardCapIds: ["GENERATION_AUTHORITY"] }); expectError(ctx, await ctx.rollbackTrain(api.baseUrl, created.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: generation - 1 }), 409, "ENVIRONMENT_GENERATION_CHANGED", { hardCapIds: ["GENERATION_AUTHORITY"] }); const afterStale = await snapshot(ctx, api.baseUrl); ctx.equal("stale operations leave Train unchanged", trainFrom(afterStale, created.train.trainId), trainFrom(running.state, created.train.trainId)); ctx.equal("stale operations leave Stages unchanged", stagesFor(afterStale, created.train.trainId), stagesFor(running.state, created.train.trainId)); await ctx.rollbackTrain(api.baseUrl, created.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: generation }); const worker = await ctx.startWorker(), terminal = await waitSnapshot(ctx, api.baseUrl, (state) => trainFrom(state, created.train.trainId)?.state === "ROLLED_BACK", { label: "terminal Train", processes: [worker] }); await ctx.stop(worker); for (const response of [await ctx.startTrain(api.baseUrl, created.train.trainId), await ctx.advanceTrain(api.baseUrl, created.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: generation }), await ctx.rollbackTrain(api.baseUrl, created.train.trainId, { expectedStage: 0, expectedEnvironmentGeneration: generation })])
    expectError(ctx, response, 409, "PROMOTION_TRAIN_TERMINAL", { hardCapIds: ["GENERATION_AUTHORITY"] }); expectError(ctx, await ctx.startTrain(api.baseUrl, ctx.fixtures.uuid("missing-train")), 404, "NOT_FOUND"); const after = await snapshot(ctx, api.baseUrl); ctx.equal("terminal Train state unchanged", trainFrom(after, created.train.trainId), trainFrom(terminal, created.train.trainId), { hardCapIds: ["GENERATION_AUTHORITY"] }); ctx.equal("terminal Stage state unchanged", stagesFor(after, created.train.trainId), stagesFor(terminal, created.train.trainId)); return caseResult(ctx, { trainId: created.train.trainId }); });
export const TRAIN_CASES = Object.freeze([TRAIN01, TRAIN02, TRAIN03, TRAIN04, TRAIN05]);
