import {
  activateSubscription, assertDeniedEverywhere, assertGrantIntervals, assertPoolClosure, assertRefundConservation,
  assertSnapshot, assignSeat, cancelSubscription, changePlan, checkEntitlement, createPool, createRefund,
  createRevision, createSubscription, defineCase, expectError, finalEvidence, getSubscription, prepare,
  providerEvent, publishRevision, revokeSeat, waitForSubscription,
} from "./helpers.mjs";

function trialBody(fixture, subjectId, planRevisionId, providerRequestId, subscriptionKind) {
  return { tenantId: fixture.tenant.tenantId, subjectId, planRevisionId, startMode: "TRIAL", providerRequestId, ...(subscriptionKind ? { subscriptionKind } : {}) };
}

async function startOrganization(ctx, target, api, fixture, label, seatLimit) {
  const activated = await activateSubscription(ctx, api, trialBody(fixture, `${label}-owner`, fixture.revisions.proV1.planRevisionId, `${label}-start`, "ORGANIZATION"), { key: ctx.key(`${label}:subscription`) });
  const pool = await createPool(ctx, api.baseUrl, { tenantId: fixture.tenant.tenantId, subscriptionId: activated.active.subscriptionId, feature: "reports", seatLimit }, { key: ctx.key(`${label}:pool`) });
  return { target, api, ...activated, pool };
}

const D01 = defineCase({
  id: "DATA-01", fixtureFamily: "EH-F-DATA-TRIAL-FROZEN",
  action: "Race one subject across two published revisions and API processes, terminate the winner, retry the Plan family trial, and publish later terms.",
  oracle: "Exactly one durable trial identity and Subscription may exist, while the winning period and Grant retain their original revision terms after later publication.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const subjectId = "one-trial-subject";
    const requests = [fixture.revisions.basicV1, fixture.revisions.basicV2].map((revision, index) => ctx.mutate(apis[index].baseUrl, "/api/v1/subscriptions", ctx.key(`trial-race:${index}`), trialBody(fixture, subjectId, revision.planRevisionId, `trial-race-${index}`)));
    const raced = await Promise.all(requests); ctx.equal(raced.filter(({ status }) => status === 200).length, 1, "one concurrent trial succeeds", { hardCapIds: ["TRIAL_UNIQUENESS"] }); for (const response of raced.filter(({ status }) => status !== 200)) expectError(ctx, response, 409, "TRIAL_ALREADY_CONSUMED", "losing concurrent trial", { hardCapIds: ["TRIAL_UNIQUENESS"] });
    const winner = raced.find(({ status }) => status === 200).json; const worker = await target.startWorker(); const active = await waitForSubscription(ctx, apis[0].baseUrl, winner.subscriptionId, ["TRIALING", "ACTIVE"], [worker]); const initial = await ctx.snapshot(apis[0].baseUrl); const originalSubscription = initial.resources.subscriptions.find(({ subscriptionId }) => subscriptionId === winner.subscriptionId); const originalGrants = initial.resources.entitlementGrants.filter(({ subscriptionId }) => subscriptionId === winner.subscriptionId); const winningRevision = initial.resources.planRevisions.find(({ planRevisionId }) => planRevisionId === active.planRevisionId); ctx.equal(originalGrants.find(({ feature }) => feature === "reports")?.limit, winningRevision.features.reports, "Grant freezes winning revision feature limit"); ctx.equal((Date.parse(active.trialEndsAt) - Date.parse(active.periodStart)) / 86_400_000, winningRevision.trialDays, "trial end freezes winning revision duration"); ctx.equal(initial.resources.subscriptions.filter(({ tenantId, subjectId: value }) => tenantId === fixture.tenant.tenantId && value === subjectId).length, 1, "one Subscription persisted", { hardCapIds: ["TRIAL_UNIQUENESS"] }); ctx.equal(initial.resources.trialConsumptions.filter(({ tenantId, subjectId: value, planId }) => tenantId === fixture.tenant.tenantId && value === subjectId && planId === fixture.plans.basicPlan.planId).length, 1, "one Plan-family trial consumption", { hardCapIds: ["TRIAL_UNIQUENESS"] });
    const draft = await createRevision(ctx, apis[0].baseUrl, fixture.plans.basicPlan.planId, { priceMinor: 9999, currency: "EUR", interval: "YEAR", features: { reports: 99, exports: 8 }, trialDays: 60, graceDays: 30, refundDays: 1 }, { key: ctx.key("later-terms") }); const later = await publishRevision(ctx, apis[0].baseUrl, draft.planRevisionId, { key: ctx.key("publish-later-terms") }); const afterPublication = await ctx.snapshot(apis[1].baseUrl); ctx.equal(afterPublication.resources.subscriptions.find(({ subscriptionId }) => subscriptionId === winner.subscriptionId), originalSubscription, "later publication does not rewrite frozen Subscription period", { hardCapIds: ["GRANT_INTERVAL_AUTHORITY"] }); ctx.equal(afterPublication.resources.entitlementGrants.filter(({ subscriptionId }) => subscriptionId === winner.subscriptionId), originalGrants, "later publication does not rewrite historical Grants", { hardCapIds: ["GRANT_INTERVAL_AUTHORITY"] });
    const current = await getSubscription(ctx, apis[0].baseUrl, winner.subscriptionId); await cancelSubscription(ctx, apis[0].baseUrl, current.subscriptionId, current.sequence, { key: ctx.key("terminal-cancel") }); const retry = await createSubscription(ctx, apis[1].baseUrl, trialBody(fixture, subjectId, later.planRevisionId, "trial-after-terminal"), { allowFailure: true, key: ctx.key("trial-after-terminal") }); expectError(ctx, retry, 409, "TRIAL_ALREADY_CONSUMED", "terminal state does not restore trial", { hardCapIds: ["TRIAL_UNIQUENESS"] }); const final = assertSnapshot(ctx, await ctx.snapshot(apis[0].baseUrl)); ctx.equal(final.resources.trialConsumptions.filter(({ subjectId: value }) => value === subjectId).length, 1, "trial identity remains unique");
    return finalEvidence(ctx, { subjectId, subscriptionId: winner.subscriptionId, frozenRevisionId: active.planRevisionId });
  },
});

const D02 = defineCase({
  id: "DATA-02", fixtureFamily: "EH-F-DATA-GRANT-AUTHORITY",
  action: "Apply an immediate upgrade, race competing downgrades, cancel through one API, and query current and stale revocation fences through both APIs.",
  oracle: "Grant intervals remain adjoining, one pending downgrade authority survives, cancellation advances the fence once, and stale knowledge never re-enables access.",
  async run(ctx) {
    const fixture = ctx.fixtures.data(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const worker = await target.startWorker(); const upgrade = await changePlan(ctx, apis[0].baseUrl, fixture.active.subscriptionId, { toPlanRevisionId: fixture.revisions.proV1.planRevisionId, expectedSequence: fixture.active.sequence }, { key: ctx.key("upgrade") }); ctx.equal(upgrade.kind, "UPGRADE", "higher price is immediate upgrade"); const upgraded = await ctx.waitFor(async () => { const value = await getSubscription(ctx, apis[1].baseUrl, fixture.active.subscriptionId); return value.planRevisionId === fixture.revisions.proV1.planRevisionId ? value : false; }, { timeoutMs: 120_000, label: "upgrade applied", processes: [worker] });
    const downgradeBodies = [fixture.revisions.basicV1, fixture.revisions.proLow].map(({ planRevisionId }) => ({ toPlanRevisionId: planRevisionId, expectedSequence: upgraded.sequence })); const changes = await Promise.all(downgradeBodies.map((body, index) => ctx.mutate(apis[index].baseUrl, `/api/v1/subscriptions/${upgraded.subscriptionId}/change-plan`, ctx.key(`downgrade:${index}`), body))); ctx.equal(changes.filter(({ status }) => status === 200).length, 1, "only one same-sequence downgrade wins", { hardCapIds: ["GRANT_INTERVAL_AUTHORITY"] }); ctx.ok(changes.every(({ status }) => [200, 400, 409].includes(status)), "downgrade race has only published outcomes");
    const beforeCancel = await getSubscription(ctx, apis[0].baseUrl, upgraded.subscriptionId); const cancelled = await cancelSubscription(ctx, apis[1].baseUrl, beforeCancel.subscriptionId, beforeCancel.sequence, { key: ctx.key("cancel") }); await assertDeniedEverywhere(ctx, apis, { tenantId: fixture.tenant.tenantId, subjectId: fixture.active.subjectId, feature: "reports", knownRevocationVersion: 0 }, cancelled.revocationVersion, [worker]); const repeated = await Promise.all([0, cancelled.revocationVersion - 1, cancelled.revocationVersion].map((knownRevocationVersion, index) => checkEntitlement(ctx, apis[index % 2].baseUrl, { tenantId: fixture.tenant.tenantId, subjectId: fixture.active.subjectId, feature: "reports", knownRevocationVersion }))); ctx.ok(repeated.every(({ state, revocationVersion }) => state === "DISABLED" && revocationVersion >= cancelled.revocationVersion), "older propagation and stale known fences cannot re-enable", { hardCapIds: ["REVOCATION_FAIL_CLOSED"] });
    const snapshot = assertSnapshot(ctx, await ctx.snapshot(apis[0].baseUrl)); const grants = snapshot.resources.entitlementGrants.filter(({ subscriptionId }) => subscriptionId === upgraded.subscriptionId); assertGrantIntervals(grants); ctx.ok(grants.every(({ validUntil }) => validUntil !== null), "terminal cancellation closes every Grant"); ctx.ok(snapshot.resources.planChanges.filter(({ subscriptionId, state }) => subscriptionId === upgraded.subscriptionId && state === "SCHEDULED").length <= 1, "at most one pending downgrade authority");
    return finalEvidence(ctx, { subscriptionId: upgraded.subscriptionId, grantCount: grants.length, revocationVersion: cancelled.revocationVersion });
  },
});

const D03 = defineCase({
  id: "DATA-03", fixtureFamily: "EH-F-DATA-REFUND-CONSERVATION",
  action: "Concurrently reserve partial and UNKNOWN refunds, deliver reordered outcomes, reject the remaining amount plus one, and converge a full frozen-period refund.",
  oracle: "Successful and unresolved amounts never exceed the frozen charge, partial success retains access, UNKNOWN blocks excess, and exact full success atomically revokes.",
  async run(ctx) {
    const fixture = ctx.fixtures.data(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const partial = await createRefund(ctx, apis[0].baseUrl, fixture.active.subscriptionId, { amountMinor: 400, currency: "USD", providerRequestId: "partial-400" }, { key: ctx.key("partial") }); const unknown = await createRefund(ctx, apis[1].baseUrl, fixture.active.subscriptionId, { amountMinor: 600, currency: "USD", providerRequestId: "unknown-600" }, { key: ctx.key("unknown") }); await Promise.all([providerEvent(ctx, apis[0].baseUrl, { providerEventId: "partial-success", providerRequestId: partial.providerRequestId, kind: "REFUND", outcome: "SUCCEEDED", occurredAt: ctx.at() }, { key: ctx.key("partial-success") }), providerEvent(ctx, apis[1].baseUrl, { providerEventId: "unknown-first", providerRequestId: unknown.providerRequestId, kind: "REFUND", outcome: "UNKNOWN", occurredAt: ctx.at({ seconds: 2 }) }, { key: ctx.key("unknown-first") })]); const worker = await target.startWorker(); const reserved = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(apis[0].baseUrl); const values = snapshot.resources.refunds.filter(({ subscriptionId }) => subscriptionId === fixture.active.subscriptionId); return values.some(({ state }) => state === "SUCCEEDED") && values.some(({ state }) => state === "UNKNOWN") ? snapshot : false; }, { timeoutMs: 120_000, label: "partial and UNKNOWN refund states", processes: [worker] }); assertRefundConservation(reserved.resources.subscriptions, reserved.resources.planRevisions, reserved.resources.refunds); const view = await checkEntitlement(ctx, apis[1].baseUrl, { tenantId: fixture.tenant.tenantId, subjectId: fixture.active.subjectId, feature: "reports", knownRevocationVersion: 0 }); ctx.equal(view.state, "ENABLED", "partial plus unresolved refund retains access"); const excess = await createRefund(ctx, apis[0].baseUrl, fixture.active.subscriptionId, { amountMinor: 1, currency: "USD", providerRequestId: "excess-one" }, { allowFailure: true, key: ctx.key("excess-one") }); expectError(ctx, excess, 409, "REFUND_LIMIT_EXCEEDED", "reserved amount plus one", { hardCapIds: ["REFUND_CONSERVATION"] });
    await providerEvent(ctx, apis[1].baseUrl, { providerEventId: "unknown-success", providerRequestId: unknown.providerRequestId, kind: "REFUND", outcome: "SUCCEEDED", occurredAt: ctx.at({ seconds: 1 }) }, { key: ctx.key("unknown-success") }); const final = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(apis[0].baseUrl); return snapshot.resources.subscriptions.find(({ subscriptionId }) => subscriptionId === fixture.active.subscriptionId)?.state === "REFUNDED" ? snapshot : false; }, { timeoutMs: 120_000, label: "full refund convergence", processes: [worker] }); assertRefundConservation(final.resources.subscriptions, final.resources.planRevisions, final.resources.refunds); const disabled = await checkEntitlement(ctx, apis[0].baseUrl, { tenantId: fixture.tenant.tenantId, subjectId: fixture.active.subjectId, feature: "reports", knownRevocationVersion: 0 }); ctx.equal(disabled.state, "DISABLED", "full refund atomically disables access", { hardCapIds: ["REFUND_CONSERVATION"] }); const replayedOld = await providerEvent(ctx, apis[0].baseUrl, { providerEventId: "unknown-late-replay", providerRequestId: unknown.providerRequestId, kind: "REFUND", outcome: "UNKNOWN", occurredAt: ctx.at() }, { key: ctx.key("unknown-late-replay") }); ctx.equal(replayedOld.outcome, "UNKNOWN", "reordered callback is durably recorded"); const after = await getSubscription(ctx, apis[1].baseUrl, fixture.active.subscriptionId); ctx.equal(after.state, "REFUNDED", "reordered UNKNOWN cannot reverse final refund");
    return finalEvidence(ctx, { subscriptionId: fixture.active.subscriptionId, reservedAmount: 1000, finalState: after.state });
  },
});

const D04 = defineCase({
  id: "DATA-04", fixtureFamily: "EH-F-DATA-POOL-CONCURRENCY",
  action: "Fill four of five seats, race thirty-two final-seat assignments, lower the feature limit, race explicit revocations, and recover legal capacity.",
  oracle: "Exactly one final seat wins, successful mutations advance a gapless Pool version, lowering never evicts, OVER_LIMIT blocks assignment, and explicit revocation restores ACTIVE.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); const apis = [await target.startApi(), await target.startApi()]; const org = await startOrganization(ctx, target, apis[0], fixture, "capacity", 5); let version = 0; for (let index = 0; index < 4; index += 1) { const value = await assignSeat(ctx, apis[index % 2].baseUrl, org.pool.poolId, { subjectId: `member-${index}`, expectedPoolVersion: version }, { key: ctx.key(`member:${index}`) }); version = value.pool.version; }
    const contenders = Array.from({ length: 32 }, (_, index) => index); const raced = await ctx.concurrent(contenders, 32, (index) => ctx.mutate(apis[index % 2].baseUrl, `/api/v1/entitlement-pools/${org.pool.poolId}/assignments`, ctx.key(`last-seat:${index}`), { subjectId: `last-${index}`, expectedPoolVersion: version })); ctx.equal(raced.filter(({ status }) => status === 200).length, 1, "one final seat wins", { hardCapIds: ["POOL_CAPACITY_AUTHORITY"] }); ctx.ok(raced.every(({ status }) => [200, 409].includes(status)), "last-seat race has only success or stable conflict"); const filled = await ctx.snapshot(apis[0].baseUrl); let pool = filled.resources.entitlementPools.find(({ poolId }) => poolId === org.pool.poolId); let active = filled.resources.seatAssignments.filter(({ poolId, state }) => poolId === org.pool.poolId && state === "ACTIVE"); ctx.equal(active.length, 5, "Pool is exactly full"); ctx.equal(pool.version, 5, "four sequential plus one raced mutation create gapless version");
    const lowerDraft = await createRevision(ctx, apis[0].baseUrl, fixture.plans.proPlan.planId, { priceMinor: 4000, currency: "USD", interval: "MONTH", features: { reports: 3, exports: 1 }, trialDays: 14, graceDays: 3, refundDays: 7 }, { key: ctx.key("lower-limit") }); const lower = await publishRevision(ctx, apis[0].baseUrl, lowerDraft.planRevisionId, { key: ctx.key("publish-lower") }); const subscription = await waitForSubscription(ctx, apis[0].baseUrl, org.active.subscriptionId, ["TRIALING", "ACTIVE"], org.workers); await changePlan(ctx, apis[0].baseUrl, subscription.subscriptionId, { toPlanRevisionId: lower.planRevisionId, expectedSequence: subscription.sequence }, { key: ctx.key("limit-upgrade") }); const over = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(apis[1].baseUrl); const current = snapshot.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); return current?.state === "OVER_LIMIT" && current.seatLimit === 3 ? snapshot : false; }, { timeoutMs: 120_000, label: "Pool limit reconciliation", processes: org.workers }); pool = over.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId); active = over.resources.seatAssignments.filter(({ poolId, state }) => poolId === pool.poolId && state === "ACTIVE"); ctx.equal(active.length, 5, "limit reduction does not arbitrarily evict", { hardCapIds: ["POOL_CAPACITY_AUTHORITY"] }); const denied = await assignSeat(ctx, apis[0].baseUrl, pool.poolId, { subjectId: "blocked-over-limit", expectedPoolVersion: pool.version }, { allowFailure: true, key: ctx.key("blocked-over-limit") }); expectError(ctx, denied, 409, "POOL_OVER_LIMIT", "assignment while OVER_LIMIT", { hardCapIds: ["POOL_CAPACITY_AUTHORITY"] });
    const firstVersion = pool.version; const pair = await Promise.all(active.slice(0, 2).map(({ subjectId }, index) => ctx.mutate(apis[index].baseUrl, `/api/v1/entitlement-pools/${pool.poolId}/assignments/${encodeURIComponent(subjectId)}/revoke`, ctx.key(`concurrent-revoke:${subjectId}`), { expectedPoolVersion: firstVersion }))); ctx.equal(pair.filter(({ status }) => status === 200).length, 1, "one same-version revoke wins"); const one = pair.find(({ status }) => status === 200).json; const remainingSubject = active.slice(0, 2).find(({ subjectId }) => subjectId !== one.assignment.subjectId).subjectId; const second = await revokeSeat(ctx, apis[1].baseUrl, pool.poolId, remainingSubject, one.pool.version, { key: ctx.key("retry-second-revoke") }); ctx.equal(second.pool.version, firstVersion + 2, "two successful revokes advance exactly two versions"); ctx.equal(second.pool.state, "ACTIVE", "Pool returns ACTIVE at seatLimit"); const final = assertSnapshot(ctx, await ctx.snapshot(apis[0].baseUrl)); assertPoolClosure(final.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId), final.resources.seatAssignments.filter(({ poolId }) => poolId === pool.poolId));
    return finalEvidence(ctx, { poolId: pool.poolId, finalVersion: second.pool.version, activeSeats: 3 });
  },
});

const D05 = defineCase({
  id: "DATA-05", fixtureFamily: "EH-F-DATA-DURABLE-REPLAY",
  action: "Drop a committed response, replay subscription, refund, seat assignment and revocation twenty ways across APIs and restart, then race terminal cancellation.",
  oracle: "Every operation restores one saved semantic result and identity, changed bodies conflict, provider precedence is stable, and terminal contention cannot duplicate effects or revive access.",
  async run(ctx) {
    const fixture = ctx.fixtures.contract(); const target = await prepare(ctx, { seed: fixture.seed }); let api0 = await target.startApi(); const api1 = await target.startApi(); const body = trialBody(fixture, "replay-org-owner", fixture.revisions.proV1.planRevisionId, "replay-start", "ORGANIZATION"); const key = ctx.key("lost-subscription"); const shield = await ctx.responseShield(api0.baseUrl); shield.dropNextMutation(); await ctx.mutate(shield.baseUrl, "/api/v1/subscriptions", key, body).catch(() => undefined); ctx.equal(shield.captures.length, 1, "shield captured committed response"); const saved = JSON.parse(shield.captures[0].response.body); const replayed = await Promise.all(Array.from({ length: 20 }, (_, index) => ctx.mutate((index % 2 ? api1 : api0).baseUrl, "/api/v1/subscriptions", key, body))); ctx.ok(replayed.every(({ status, json }) => status === shield.captures[0].response.status && JSON.stringify(json) === JSON.stringify(saved)), "twenty subscription replays restore saved status and JSON", { hardCapIds: ["DURABLE_IDEMPOTENCY"] }); const conflict = await createSubscription(ctx, api1.baseUrl, { ...body, subjectId: "changed" }, { allowFailure: true, key }); expectError(ctx, conflict, 409, "IDEMPOTENCY_CONFLICT", "same key changed subscription body", { hardCapIds: ["DURABLE_IDEMPOTENCY"] }); await ctx.stop(api0); api0 = await target.startApi(); const afterRestart = await createSubscription(ctx, api0.baseUrl, body, { key }); ctx.equal(afterRestart, saved, "restart preserves subscription replay"); const worker = await target.startWorker(); const active = await waitForSubscription(ctx, api0.baseUrl, saved.subscriptionId, ["TRIALING", "ACTIVE"], [worker]);
    const refundBody = { amountMinor: 300, currency: "USD", providerRequestId: "replay-refund" }; const refundKey = ctx.key("refund-replay"); const refund = await createRefund(ctx, api0.baseUrl, active.subscriptionId, refundBody, { key: refundKey }); const refundReplays = await Promise.all(Array.from({ length: 20 }, (_, index) => createRefund(ctx, (index % 2 ? api1 : api0).baseUrl, active.subscriptionId, refundBody, { key: refundKey }))); ctx.ok(refundReplays.every((value) => JSON.stringify(value) === JSON.stringify(refund)), "refund identity replays twenty ways"); await providerEvent(ctx, api0.baseUrl, { providerEventId: "refund-unknown", providerRequestId: refund.providerRequestId, kind: "REFUND", outcome: "UNKNOWN", occurredAt: ctx.at({ seconds: 1 }) }, { key: ctx.key("refund-unknown") }); await providerEvent(ctx, api1.baseUrl, { providerEventId: "refund-success", providerRequestId: refund.providerRequestId, kind: "REFUND", outcome: "SUCCEEDED", occurredAt: ctx.at({ seconds: 2 }) }, { key: ctx.key("refund-success") }); await providerEvent(ctx, api0.baseUrl, { providerEventId: "refund-late-unknown", providerRequestId: refund.providerRequestId, kind: "REFUND", outcome: "UNKNOWN", occurredAt: ctx.at() }, { key: ctx.key("refund-late-unknown") });
    const pool = await createPool(ctx, api0.baseUrl, { tenantId: fixture.tenant.tenantId, subscriptionId: active.subscriptionId, feature: "reports", seatLimit: 2 }, { key: ctx.key("pool") }); const assignBody = { subjectId: "seat-replay", expectedPoolVersion: 0 }; const assignKey = ctx.key("assign-replay"); const assigned = await assignSeat(ctx, api0.baseUrl, pool.poolId, assignBody, { key: assignKey }); const assignments = await Promise.all(Array.from({ length: 20 }, (_, index) => assignSeat(ctx, (index % 2 ? api1 : api0).baseUrl, pool.poolId, assignBody, { key: assignKey }))); ctx.ok(assignments.every((value) => JSON.stringify(value) === JSON.stringify(assigned)), "seat assignment restores saved response"); const revokeKey = ctx.key("revoke-replay"); const revoked = await revokeSeat(ctx, api0.baseUrl, pool.poolId, "seat-replay", assigned.pool.version, { key: revokeKey }); const revokes = await Promise.all(Array.from({ length: 20 }, (_, index) => revokeSeat(ctx, (index % 2 ? api1 : api0).baseUrl, pool.poolId, "seat-replay", assigned.pool.version, { key: revokeKey }))); ctx.ok(revokes.every((value) => JSON.stringify(value) === JSON.stringify(revoked)), "seat revocation restores saved response");
    const current = await getSubscription(ctx, api0.baseUrl, active.subscriptionId); await cancelSubscription(ctx, api1.baseUrl, current.subscriptionId, current.sequence, { key: ctx.key("terminal-cancel") }); const denied = await assignSeat(ctx, api0.baseUrl, pool.poolId, { subjectId: "after-terminal", expectedPoolVersion: revoked.pool.version }, { allowFailure: true, key: ctx.key("after-terminal") }); ctx.ok(denied.status === 409, "terminal Pool rejects later seat mutation"); const final = await ctx.waitFor(async () => { const snapshot = await ctx.snapshot(api0.baseUrl); return snapshot.resources.entitlementPools.find(({ poolId }) => poolId === pool.poolId)?.state === "REVOKED" ? snapshot : false; }, { timeoutMs: 120_000, label: "terminal replay closure", processes: [worker] }); ctx.equal(final.resources.subscriptions.filter(({ subjectId }) => subjectId === body.subjectId).length, 1, "replay creates one Subscription", { hardCapIds: ["DURABLE_IDEMPOTENCY"] }); ctx.equal(final.resources.refunds.filter(({ providerRequestId }) => providerRequestId === refund.providerRequestId).length, 1, "replay creates one Refund"); ctx.equal(final.resources.seatAssignments.filter(({ poolId, subjectId }) => poolId === pool.poolId && subjectId === "seat-replay").length, 1, "replay creates one SeatAssignment");
    return finalEvidence(ctx, { subscriptionId: active.subscriptionId, refundId: refund.refundId, poolId: pool.poolId });
  },
});

export const B_CASES = Object.freeze([D01, D02, D03, D04, D05]);
