import assert from "node:assert/strict";
import { createWriteStream } from "node:fs";
import { once } from "node:events";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";

import { CaseExcluded, CaseFailure } from "../lib/execution.mjs";
import { assertEventSequence, assertFenceMonotonic, assertGrantIntervals, assertPoolClosure, assertRefundConservation, assertSorted, canonicalJson, percentile } from "../oracles/index.mjs";

export { assertGrantIntervals, assertPoolClosure, assertRefundConservation } from "../oracles/index.mjs";

const builds = new Map();
export const PLAN_REVISION_KEYS = Object.freeze(["planRevisionId", "planId", "revision", "state", "priceMinor", "currency", "interval", "features", "trialDays", "graceDays", "refundDays", "createdAt", "publishedAt"]);
export const SUBSCRIPTION_KEYS = Object.freeze(["subscriptionId", "tenantId", "subjectId", "planRevisionId", "state", "periodStart", "periodEnd", "trialEndsAt", "cancelAtPeriodEnd", "pendingPlanRevisionId", "revocationVersion", "createdAt", "terminalAt", "sequence"]);
export const PLAN_CHANGE_KEYS = Object.freeze(["changeId", "subscriptionId", "fromPlanRevisionId", "toPlanRevisionId", "kind", "state", "effectiveAt", "amountMinor", "createdAt"]);
export const REFUND_KEYS = Object.freeze(["refundId", "subscriptionId", "providerRequestId", "amountMinor", "currency", "state", "createdAt", "resolvedAt"]);
export const PROVIDER_EVENT_KEYS = Object.freeze(["providerEventId", "providerRequestId", "kind", "outcome", "occurredAt"]);
export const GRANT_KEYS = Object.freeze(["grantId", "subscriptionId", "feature", "limit", "validFrom", "validUntil", "grantRevision"]);
export const VIEW_KEYS = Object.freeze(["tenantId", "subjectId", "feature", "state", "limit", "subscriptionId", "revocationVersion", "evaluatedAt"]);
export const POOL_KEYS = Object.freeze(["poolId", "tenantId", "subscriptionId", "feature", "seatLimit", "state", "version", "periodStart", "periodEnd", "createdAt"]);
export const ASSIGNMENT_KEYS = Object.freeze(["poolId", "subjectId", "state", "assignedAt", "terminalAt"]);
export const V1_RESOURCE_KEYS = Object.freeze(["tenants", "plans", "planRevisions", "subscriptions", "trialConsumptions", "planChanges", "refunds", "providerEvents", "entitlementGrants", "revocationFences", "auditEntries"]);
export const FINAL_RESOURCE_KEYS = Object.freeze([...V1_RESOURCE_KEYS, "entitlementPools", "seatAssignments"]);
export const WORK_KINDS = Object.freeze(["SUBSCRIPTION_ACTIVATE", "PLAN_CHANGE_APPLY", "SUBSCRIPTION_EXPIRE", "REFUND_RECONCILE", "ENTITLEMENT_REVOKE", "EVENT_DELIVERY", "POOL_RECONCILE", "POOL_REVOKE"]);

const CASE_HARD_CAPS = Object.freeze({
  "CONTRACT-01": ["TRIAL_UNIQUENESS", "GRANT_INTERVAL_AUTHORITY"], "CONTRACT-02": ["GRANT_INTERVAL_AUTHORITY", "REVOCATION_FAIL_CLOSED"], "CONTRACT-03": ["REFUND_CONSERVATION"], "CONTRACT-04": ["POOL_CAPACITY_AUTHORITY"], "CONTRACT-05": ["POOL_CAPACITY_AUTHORITY", "REVOCATION_FAIL_CLOSED"],
  "DATA-01": ["TRIAL_UNIQUENESS", "GRANT_INTERVAL_AUTHORITY"], "DATA-02": ["GRANT_INTERVAL_AUTHORITY", "REVOCATION_FAIL_CLOSED"], "DATA-03": ["REFUND_CONSERVATION"], "DATA-04": ["POOL_CAPACITY_AUTHORITY"], "DATA-05": ["DURABLE_IDEMPOTENCY", "REFUND_CONSERVATION", "POOL_CAPACITY_AUTHORITY"],
  "RECOVERY-01": ["STALE_WORK_OR_LOST_WORK", "GRANT_INTERVAL_AUTHORITY", "REVOCATION_FAIL_CLOSED"], "RECOVERY-02": ["STALE_WORK_OR_LOST_WORK", "REFUND_CONSERVATION"], "RECOVERY-03": ["STALE_WORK_OR_LOST_WORK", "POOL_CAPACITY_AUTHORITY", "REVOCATION_FAIL_CLOSED"], "RECOVERY-04": ["STALE_WORK_OR_LOST_WORK", "REVOCATION_FAIL_CLOSED"],
  "LAYER-02": ["GRANT_INTERVAL_AUTHORITY", "REVOCATION_FAIL_CLOSED"], "LAYER-03": ["POOL_CAPACITY_AUTHORITY", "REVOCATION_FAIL_CLOSED"], "LAYER-04": ["REFUND_CONSERVATION", "POOL_CAPACITY_AUTHORITY"], "OPERATE-01": ["REVOCATION_FAIL_CLOSED"], "OPERATE-02": ["GRANT_INTERVAL_AUTHORITY", "REFUND_CONSERVATION"], "OPERATE-03": ["STALE_WORK_OR_LOST_WORK", "REVOCATION_FAIL_CLOSED"], "OPERATE-04": ["MIGRATION_COMPATIBILITY"],
});

export function defineCase({ id, fixtureFamily, action, oracle, run }) { if (!/^(?:CONTRACT|DATA|RECOVERY|LAYER|OPERATE)-\d{2}$/u.test(id) || !/^EH-F-/u.test(fixtureFamily ?? "") || typeof action !== "string" || action.length < 24 || typeof oracle !== "string" || oracle.length < 24 || typeof run !== "function" || run.length < 1) throw new TypeError("invalid EntitlementHub case definition"); const hardCaps = CASE_HARD_CAPS[id] ?? []; return Object.freeze({ taskId: "entitlementhub", id, fixtureFamily, action, oracle, async run(ctx) { try { return await run(ctx); } catch (error) { if (error && typeof error === "object") error.hardCapIds = [...new Set([...(error.hardCapIds ?? []), ...hardCaps])]; throw error; } } }); }
export function guardedCase(definition, hardCapIds = []) { return defineCase({ ...definition, async run(ctx) { try { return await definition.run(ctx); } catch (error) { if (error && typeof error === "object") error.hardCapIds = [...new Set([...(error.hardCapIds ?? []), ...hardCapIds])]; throw error; } } }); }
export function exactKeys(value, keys, label) { assert.ok(value && typeof value === "object" && !Array.isArray(value), `${label} must be an object`); assert.deepEqual(Object.keys(value).sort(), [...keys].sort(), `${label} fields`); return value; }
export function expectStatus(ctx, response, status, label, options = {}) { ctx.equal(response.status, status, `${label} status`, options); return response.json; }
export function expectSuccess(ctx, response, label, status = 200, options = {}) { const value = expectStatus(ctx, response, status, label, options); ctx.ok(value && typeof value === "object", `${label} JSON`, options); return value; }
export function expectError(ctx, response, status, code, label, options = {}) { expectStatus(ctx, response, status, label, options); exactKeys(response.json, ["error"], `${label} envelope`); exactKeys(response.json.error, ["code", "message", "details"], `${label} error`); ctx.equal(response.json.error.code, code, `${label} code`, options); return response.json.error; }

export function assertPlanRevision(value) { exactKeys(value, PLAN_REVISION_KEYS, "PlanRevision"); assert.match(value.planRevisionId, /^[0-9a-f-]{36}$/u); assert.ok(Number.isSafeInteger(value.priceMinor) && value.priceMinor >= 0); assert.ok(["DRAFT", "PUBLISHED", "RETIRED"].includes(value.state)); assert.ok(["MONTH", "YEAR"].includes(value.interval)); return value; }
export function assertSubscription(value) { exactKeys(value, SUBSCRIPTION_KEYS, "Subscription"); assert.match(value.subscriptionId, /^[0-9a-f-]{36}$/u); assert.ok(["PENDING", "TRIALING", "ACTIVE", "FAILED", "PAST_DUE", "CANCELLED", "EXPIRED", "REFUNDED"].includes(value.state)); assert.ok(Number.isSafeInteger(value.revocationVersion) && value.revocationVersion >= 0); assert.ok(Number.isSafeInteger(value.sequence) && value.sequence > 0); return value; }
export function assertPlanChange(value) { exactKeys(value, PLAN_CHANGE_KEYS, "PlanChange"); assert.ok(["UPGRADE", "DOWNGRADE"].includes(value.kind)); assert.ok(["REQUESTED", "APPLIED", "SCHEDULED", "REJECTED", "CANCELLED"].includes(value.state)); assert.ok(Number.isSafeInteger(value.amountMinor)); return value; }
export function assertRefund(value) { exactKeys(value, REFUND_KEYS, "Refund"); assert.ok(["REQUESTED", "SUCCEEDED", "FAILED", "UNKNOWN"].includes(value.state)); assert.ok(Number.isSafeInteger(value.amountMinor) && value.amountMinor > 0); return value; }
export function assertProviderEvent(value) { exactKeys(value, PROVIDER_EVENT_KEYS, "ProviderEvent"); assert.ok(["SUBSCRIPTION", "REFUND"].includes(value.kind)); assert.ok(["SUCCEEDED", "FAILED", "UNKNOWN"].includes(value.outcome)); return value; }
export function assertGrant(value) { exactKeys(value, GRANT_KEYS, "EntitlementGrant"); assert.ok(Number.isSafeInteger(value.grantRevision) && value.grantRevision > 0); assert.ok(value.limit === null || Number.isSafeInteger(value.limit)); return value; }
export function assertView(value) { exactKeys(value, VIEW_KEYS, "EntitlementView"); assert.ok(["ENABLED", "DISABLED"].includes(value.state)); assert.ok(Number.isSafeInteger(value.revocationVersion) && value.revocationVersion >= 0); return value; }
export function assertPool(value) { exactKeys(value, POOL_KEYS, "EntitlementPool"); assert.ok(["ACTIVE", "OVER_LIMIT", "REVOKED", "EXPIRED"].includes(value.state)); assert.ok(Number.isSafeInteger(value.seatLimit) && value.seatLimit > 0); assert.ok(Number.isSafeInteger(value.version) && value.version >= 0); return value; }
export function assertAssignment(value) { exactKeys(value, ASSIGNMENT_KEYS, "SeatAssignment"); assert.ok(["ACTIVE", "REVOKED", "EXPIRED"].includes(value.state)); return value; }

async function build(ctx, workspace) { const target = ctx.forWorkspace(workspace); if (!builds.has(target.workspace)) builds.set(target.workspace, target.npm("build")); await builds.get(target.workspace); }
export async function prepare(ctx, options = {}) { const workspace = options.workspace ?? ctx.workspace; const target = ctx.forWorkspace(workspace); if (options.build !== false) await build(ctx, workspace); if (options.migrate !== false) await target.migrate(); if (options.seed) await target.seed(options.seed); ctx.mark("candidate-prepared", { workspace: target.workspace, seeded: Boolean(options.seed) }); return target; }
export async function startPreparedApi(ctx, options = {}) { return (await prepare(ctx, options)).startApi(options.api ?? {}); }

export async function createTenant(ctx, baseUrl, body, options = {}) { const response = await ctx.mutate(baseUrl, "/api/v1/tenants", options.key ?? ctx.key(`tenant:${body.name}`), body); if (options.allowFailure) return response; const value = expectSuccess(ctx, response, options.label ?? "create Tenant"); exactKeys(value, ["tenantId", "name"], "Tenant"); return value; }
export async function createPlan(ctx, baseUrl, body, options = {}) { const response = await ctx.mutate(baseUrl, "/api/v1/plans", options.key ?? ctx.key(`plan:${body.tenantId}:${body.key}`), body); if (options.allowFailure) return response; const value = expectSuccess(ctx, response, options.label ?? "create Plan"); exactKeys(value, ["planId", "tenantId", "key", "name"], "Plan"); return value; }
export async function createRevision(ctx, baseUrl, planId, body, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/plans/${planId}/revisions`, options.key ?? ctx.key(`revision:${planId}:${body.priceMinor}`), body); if (options.allowFailure) return response; return assertPlanRevision(expectSuccess(ctx, response, options.label ?? "create PlanRevision")); }
export async function publishRevision(ctx, baseUrl, planRevisionId, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/plan-revisions/${planRevisionId}/publish`, options.key ?? ctx.key(`publish:${planRevisionId}`), {}); if (options.allowFailure) return response; return assertPlanRevision(expectSuccess(ctx, response, options.label ?? "publish PlanRevision")); }
export async function createSubscription(ctx, baseUrl, body, options = {}) { const response = await ctx.mutate(baseUrl, "/api/v1/subscriptions", options.key ?? ctx.key(`subscription:${body.tenantId}:${body.subjectId}:${body.planRevisionId}`), body); if (options.allowFailure) return response; return assertSubscription(expectSuccess(ctx, response, options.label ?? "create Subscription")); }
export async function getSubscription(ctx, baseUrl, id) { return assertSubscription(expectSuccess(ctx, await ctx.request(baseUrl, `/api/v1/subscriptions/${id}`), "get Subscription")); }
export async function changePlan(ctx, baseUrl, id, body, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/subscriptions/${id}/change-plan`, options.key ?? ctx.key(`change:${id}:${body.toPlanRevisionId}`), body); if (options.allowFailure) return response; return assertPlanChange(expectSuccess(ctx, response, options.label ?? "change Plan")); }
export async function cancelSubscription(ctx, baseUrl, id, expectedSequence, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/subscriptions/${id}/cancel`, options.key ?? ctx.key(`cancel:${id}`), { expectedSequence }); if (options.allowFailure) return response; return assertSubscription(expectSuccess(ctx, response, options.label ?? "cancel Subscription")); }
export async function createRefund(ctx, baseUrl, id, body, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/subscriptions/${id}/refunds`, options.key ?? ctx.key(`refund:${id}:${body.providerRequestId}`), body); if (options.allowFailure) return response; return assertRefund(expectSuccess(ctx, response, options.label ?? "create Refund")); }
export async function providerEvent(ctx, baseUrl, body, options = {}) { const response = await ctx.mutate(baseUrl, "/api/v1/provider/events", options.key ?? ctx.key(`provider:${body.providerEventId}`), body); if (options.allowFailure) return response; return assertProviderEvent(expectSuccess(ctx, response, options.label ?? "record ProviderEvent")); }
export async function reconcileRefund(ctx, baseUrl, refundId, body = {}, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/refunds/${refundId}/reconcile`, options.key ?? ctx.key(`reconcile:${refundId}`), body); if (options.allowFailure) return response; return assertRefund(expectSuccess(ctx, response, options.label ?? "reconcile Refund")); }
export async function checkEntitlement(ctx, baseUrl, { tenantId, subjectId, feature, knownRevocationVersion }) { const query = new URLSearchParams({ tenantId, subjectId, feature, ...(knownRevocationVersion === undefined ? {} : { knownRevocationVersion: String(knownRevocationVersion) }) }); return assertView(expectSuccess(ctx, await ctx.request(baseUrl, `/api/v1/entitlements/check?${query}`), "check Entitlement")); }
export async function createPool(ctx, baseUrl, body, options = {}) { const response = await ctx.mutate(baseUrl, "/api/v1/entitlement-pools", options.key ?? ctx.key(`pool:${body.subscriptionId}:${body.feature}`), body); if (options.allowFailure) return response; return assertPool(expectSuccess(ctx, response, options.label ?? "create EntitlementPool")); }
export async function assignSeat(ctx, baseUrl, poolId, body, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/entitlement-pools/${poolId}/assignments`, options.key ?? ctx.key(`seat:${poolId}:${body.subjectId}`), body); if (options.allowFailure) return response; const value = expectSuccess(ctx, response, options.label ?? "assign Seat"); exactKeys(value, ["pool", "assignment"], "assignment response"); assertPool(value.pool); assertAssignment(value.assignment); return value; }
export async function revokeSeat(ctx, baseUrl, poolId, subjectId, expectedPoolVersion, options = {}) { const response = await ctx.mutate(baseUrl, `/api/v1/entitlement-pools/${poolId}/assignments/${encodeURIComponent(subjectId)}/revoke`, options.key ?? ctx.key(`seat-revoke:${poolId}:${subjectId}`), { expectedPoolVersion }); if (options.allowFailure) return response; const value = expectSuccess(ctx, response, options.label ?? "revoke Seat"); exactKeys(value, ["pool", "assignment"], "revoke response"); assertPool(value.pool); assertAssignment(value.assignment); return value; }
export async function listSeats(ctx, baseUrl, poolId, suffix = "") { const value = expectSuccess(ctx, await ctx.request(baseUrl, `/api/v1/entitlement-pools/${poolId}/assignments${suffix}`), "list SeatAssignments"); exactKeys(value, ["items", "nextCursor"], "SeatAssignment list"); value.items.forEach(assertAssignment); return value; }

export async function waitForSubscription(ctx, baseUrl, id, states, processes = [], timeoutMs = 120_000) { const expected = new Set(Array.isArray(states) ? states : [states]); return ctx.waitFor(async () => { const response = await ctx.request(baseUrl, `/api/v1/subscriptions/${id}`); return response.status === 200 && expected.has(response.json?.state) ? response.json : false; }, { timeoutMs, intervalMs: 100, label: `Subscription ${id} ${[...expected].join("/")}`, processes }); }
export async function waitForDrain(ctx, baseUrl, options = {}) { return ctx.waitFor(async () => { const snapshot = await ctx.snapshot(baseUrl); return snapshot.work.filter(options.predicate ?? (() => true)).every(({ terminal }) => terminal) ? snapshot : false; }, { timeoutMs: options.timeoutMs ?? 120_000, intervalMs: 100, label: options.label ?? "EntitlementHub Work drain", processes: options.processes }); }
export async function activateSubscription(ctx, api, body, options = {}) { const created = await createSubscription(ctx, api.baseUrl, body, options); const workers = options.workers ?? [await ctx.startWorker()]; const active = await waitForSubscription(ctx, api.baseUrl, created.subscriptionId, ["TRIALING", "ACTIVE"], workers); return { created, active, workers }; }

function resources(snapshot, name) { const value = snapshot.resources?.[name]; assert.ok(Array.isArray(value), `${name} snapshot resource`); return value; }
export function assertSnapshot(ctx, snapshot, { final = true } = {}) { exactKeys(snapshot, ["asOf", "resources", "work", "events"], "verification snapshot"); ctx.equal(Object.keys(snapshot.resources).sort(), [...(final ? FINAL_RESOURCE_KEYS : V1_RESOURCE_KEYS)].sort(), `${final ? "FINAL" : "V1"} resource union`); resources(snapshot, "planRevisions").forEach(assertPlanRevision); resources(snapshot, "subscriptions").forEach(assertSubscription); resources(snapshot, "planChanges").forEach(assertPlanChange); resources(snapshot, "refunds").forEach(assertRefund); resources(snapshot, "providerEvents").forEach(assertProviderEvent); resources(snapshot, "entitlementGrants").forEach(assertGrant); assertSorted(resources(snapshot, "tenants"), ["tenantId"]); assertSorted(resources(snapshot, "plans"), ["planId"]); assertSorted(resources(snapshot, "planRevisions"), ["planId", "revision"]); assertSorted(resources(snapshot, "subscriptions"), ["subscriptionId"]); assertSorted(resources(snapshot, "trialConsumptions"), ["tenantId", "subjectId", "planId"]); assertSorted(resources(snapshot, "planChanges"), ["changeId"]); assertSorted(resources(snapshot, "refunds"), ["refundId"]); assertSorted(resources(snapshot, "providerEvents"), ["providerEventId"]); assertSorted(resources(snapshot, "entitlementGrants"), ["subscriptionId", "feature", "grantRevision"]); assertSorted(resources(snapshot, "revocationFences"), ["tenantId", "subjectId"]); assertSorted(resources(snapshot, "auditEntries"), ["tenantId", "sequence"]); if (final) { resources(snapshot, "entitlementPools").forEach(assertPool); resources(snapshot, "seatAssignments").forEach(assertAssignment); assertSorted(resources(snapshot, "entitlementPools"), ["poolId"]); assertSorted(resources(snapshot, "seatAssignments"), ["poolId", "subjectId"]); for (const pool of resources(snapshot, "entitlementPools")) assertPoolClosure(pool, resources(snapshot, "seatAssignments").filter(({ poolId }) => poolId === pool.poolId)); } assertGrantIntervals(resources(snapshot, "entitlementGrants")); assertRefundConservation(resources(snapshot, "subscriptions"), resources(snapshot, "planRevisions"), resources(snapshot, "refunds")); assertFenceMonotonic(resources(snapshot, "revocationFences")); for (const work of snapshot.work) { ctx.ok(WORK_KINDS.includes(work.kind), `published Work kind ${work.kind}`); ctx.equal(work.terminal, ["SUCCEEDED", "FAILED", "CANCELLED"].includes(work.state), `${work.workId} terminal flag`); } if (snapshot.events.every((event) => Number.isSafeInteger(event.sequence) && typeof event.aggregateId === "string")) { assertSorted(snapshot.events, ["aggregateId", "sequence", "eventId"]); assertEventSequence(snapshot.events); } const serialized = canonicalJson(snapshot); ctx.ok(!/(?:providerToken|accessToken|leaseToken|idempotencyKey|postgres(?:ql)?:\/\/|\/(?:Users|home|tmp)\/|inProcessCache)/iu.test(serialized), "snapshot omits secrets, paths, and cache contents"); return snapshot; }

export async function crashClaimedWork(ctx, baseUrl, predicate) { const barrier = await ctx.barrier({ hold: (payload) => payload.point === "worker.claimed" && predicate(payload) }); const worker = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const entry = await barrier.waitFor(({ json }) => json?.point === "worker.claimed" && predicate(json), { timeoutMs: 120_000, processes: [worker] }); await ctx.kill(worker); return { barrier, entry, worker }; }
export async function assertDeniedEverywhere(ctx, apis, query, minimumVersion, processes = []) { const started = Date.now(); const views = await ctx.waitFor(async () => { const values = await Promise.all(apis.map((api) => checkEntitlement(ctx, api.baseUrl, query))); return values.every((view) => view.state === "DISABLED" && view.revocationVersion >= minimumVersion) ? values : false; }, { timeoutMs: 2_000, intervalMs: 25, label: "cross-process revocation convergence", processes }); ctx.ok(Date.now() - started <= 2_000, "revocation visible within two seconds", { hardCapIds: ["REVOCATION_FAIL_CLOSED"] }); return views; }

export async function launchBrowser(ctx, baseUrl, viewport = { width: 1280, height: 800 }) { const chromium = await ctx.loadChromium(); const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH ?? "/usr/bin/chromium", args: ["--no-sandbox"] }); ctx.defer(() => browser.close()); const browserContext = await browser.newContext({ viewport }); const page = await browserContext.newPage(); await page.goto(baseUrl, { waitUntil: "domcontentloaded", timeout: 30_000 }); return { browser, browserContext, page }; }
async function firstVisible(locator) { for (let index = 0; index < await locator.count(); index += 1) { const item = locator.nth(index); if (await item.isVisible().catch(() => false)) return item; } }
export async function fillField(page, labels, value) { for (const label of labels) { const item = await firstVisible(page.getByLabel(label)); if (item) { await item.fill(String(value)); return; } } throw new Error(`missing labelled field ${labels.join("/")}`); }
export async function chooseOption(page, labels, value) { for (const label of labels) { const item = await firstVisible(page.getByLabel(label)); if (item) { await item.selectOption({ label: value }).catch(() => item.selectOption(value)); return; } } throw new Error(`missing select ${labels.join("/")}`); }
export async function clickControl(page, names) { for (const name of names) for (const role of ["button", "link", "tab", "option"]) { const item = await firstVisible(page.getByRole(role, { name })); if (item) { await item.click(); return; } } throw new Error(`missing visible control ${names.join("/")}`); }

export async function runWindow({ clients, seconds, operation }) { const latencies = []; const statuses = new Map(); let completed = 0; const started = performance.now(); const deadline = started + seconds * 1000; await Promise.all(Array.from({ length: clients }, async (_, client) => { while (performance.now() < deadline) { const index = completed++; const callStarted = performance.now(); const response = await operation(index, client); latencies.push(performance.now() - callStarted); statuses.set(response.status, (statuses.get(response.status) ?? 0) + 1); } })); const durationSeconds = (performance.now() - started) / 1000; return { completed, durationSeconds, throughput: completed / durationSeconds, p95Ms: percentile(latencies, 0.95), statuses }; }
export function requireV1(ctx) { if (!ctx.v1Workspace) throw new CaseExcluded("missing_v1_checkpoint"); return ctx.v1Workspace; }
export function finalEvidence(ctx, values = {}) { return ctx.pass({ evidence: [{ kind: "entitlementhub-case-summary", ...values }] }); }
export function candidateFailure(message, failureCodeSuffix = "ASSERTION_FAILED", hardCapIds = []) { throw new CaseFailure(message, { failureCodeSuffix, hardCapIds }); }

function integerUuid(kind, index) { return `${kind.toString(16).padStart(8, "0")}-0000-4000-8000-${index.toString(16).padStart(12, "0")}`; }
async function writeChunk(stream, value) { if (!stream.write(value)) await once(stream, "drain"); }
export async function writeFormalSeed(ctx, scenario) {
  const counts = { "entitlement-decision-read": 100_000, "upgrade-refund-race": 20_000, "expiry-revocation-recovery": 50_000 }; const count = counts[scenario]; if (!count) throw new TypeError(`unknown formal scenario ${scenario}`); const root = ctx.tempPath(`formal-${scenario}`); await mkdir(root, { recursive: true }); const path = resolve(root, "seed.json"); const stream = createWriteStream(path, { encoding: "utf8", mode: 0o600 }); const tenantId = integerUuid(1, 1); const basicPlanId = integerUuid(2, 1); const proPlanId = integerUuid(2, 2); const basicRevisionId = integerUuid(3, 1); const proRevisionId = integerUuid(3, 2);
  const basic = { planRevisionId: basicRevisionId, planId: basicPlanId, revision: 1, state: "PUBLISHED", priceMinor: 1000, currency: "USD", interval: "MONTH", features: { reports: 1 }, trialDays: 14, graceDays: 3, refundDays: 7, createdAt: "2019-01-01T00:00:00.000Z", publishedAt: "2019-01-02T00:00:00.000Z" }; const pro = { planRevisionId: proRevisionId, planId: proPlanId, revision: 1, state: "PUBLISHED", priceMinor: 3000, currency: "USD", interval: "MONTH", features: { reports: 10, exports: 5 }, trialDays: 14, graceDays: 3, refundDays: 7, createdAt: "2019-01-01T00:00:00.000Z", publishedAt: "2019-01-02T00:00:00.000Z" };
  await writeChunk(stream, JSON.stringify({ schemaVersion: 1, seedVersion: scenario, tenants: [{ tenantId, name: "Formal Tenant" }], plans: [{ planId: basicPlanId, tenantId, key: "basic", name: "Basic" }, { planId: proPlanId, tenantId, key: "pro", name: "Pro" }], planRevisions: [basic, pro], subscriptions: [] }).slice(0, -2));
  for (let index = 0; index < count; index += 1) { if (index) await writeChunk(stream, ","); const due = scenario === "expiry-revocation-recovery"; const planRevisionId = scenario === "upgrade-refund-race" && index % 2 ? proRevisionId : basicRevisionId; await writeChunk(stream, JSON.stringify({ subscriptionId: integerUuid(10, index + 1), tenantId, subjectId: `formal-subject-${index}`, planRevisionId, state: "ACTIVE", periodStart: due ? "2019-12-01T00:00:00.000Z" : "2025-01-01T00:00:00.000Z", periodEnd: due ? "2020-01-01T00:00:00.000Z" : "2040-01-01T00:00:00.000Z", trialEndsAt: null, cancelAtPeriodEnd: false, pendingPlanRevisionId: null, revocationVersion: 1, createdAt: due ? "2019-12-01T00:00:00.000Z" : "2025-01-01T00:00:00.000Z", terminalAt: null, sequence: 1 })); }
  await writeChunk(stream, '],"trialConsumptions":[],"planChanges":[],"refunds":[],"providerEvents":[],"entitlementGrants":[');
  for (let index = 0; index < count; index += 1) { if (index) await writeChunk(stream, ","); const proSubject = scenario === "upgrade-refund-race" && index % 2; await writeChunk(stream, JSON.stringify({ grantId: integerUuid(11, index + 1), subscriptionId: integerUuid(10, index + 1), feature: "reports", limit: proSubject ? 10 : 1, validFrom: scenario === "expiry-revocation-recovery" ? "2019-12-01T00:00:00.000Z" : "2025-01-01T00:00:00.000Z", validUntil: null, grantRevision: 1 })); }
  await writeChunk(stream, '],"revocationFences":['); for (let index = 0; index < count; index += 1) { if (index) await writeChunk(stream, ","); await writeChunk(stream, JSON.stringify({ tenantId, subjectId: `formal-subject-${index}`, version: 1, updatedAt: scenario === "expiry-revocation-recovery" ? "2019-12-01T00:00:00.000Z" : "2025-01-01T00:00:00.000Z" })); } await writeChunk(stream, '],"auditEntries":[]}'); stream.end(); await once(stream, "finish"); return { path, count, tenantId, basicRevisionId, proRevisionId };
}
