import { checkStandaloneStepEvents } from "./observations.mjs";
import { assertDomainEvent, assertEventSequence, assertRolloutAuthority, assertWork, snapshotDigest } from "../oracles/index.mjs";
import {
  activate, artifactFor, blocked, boot, caseResult, createReadyCandidate, createRevision, defineCase,
  progressiveActivate, snapshot, waitSnapshot,
} from "./helpers.mjs";

const c01 = defineCase("C-01", "FF-F-WORK lifecycle/retention fixture", "Create and drain FLAG_COMPILATION plus ROLLOUT_DEADLINE work while observing lease and terminal snapshots", "Every Work has the exact FINAL schema, legal lease fields/attempt/terminal relation and terminal rows remain retained", ["public mutation HTTP", "Compilation/deadline workers", "verification snapshot"], async (ctx) => {
  const family = ctx.fixtures.work(); const { api } = await boot(ctx, { family }); const candidate = await createReadyCandidate(ctx, api.baseUrl, family, { label: "c01" }); const rollout = await progressiveActivate(ctx, api.baseUrl, candidate.revision.revisionId, 1, [{ candidateExposureBasisPoints: 10_000, minimumEvaluationCount: 2, maximumFailureBasisPoints: 0, observationSeconds: 1 }], { key: ctx.key("c01-rollout") }); await ctx.sleep(1_100); const workers = [await ctx.startWorker(), await ctx.startWorker()]; const final = await waitSnapshot(ctx, api.baseUrl, (state) => state.work.some(({ kind }) => kind === "FLAG_COMPILATION") && state.work.some(({ kind }) => kind === "ROLLOUT_DEADLINE") && state.work.every(({ terminal }) => terminal) ? state : undefined, { label: "both Work kinds drained", processes: workers }); ctx.assert("FINAL Work schema", () => assertWork(final.work, { final: true })); ctx.equal(new Set(final.work.map(({ kind }) => kind)), new Set(["FLAG_COMPILATION", "ROLLOUT_DEADLINE"]), "exact Work kind union"); ctx.ok(final.work.every(({ terminal, state }) => terminal === ["SUCCEEDED", "FAILED", "CANCELLED"].includes(state)), "terminal relation exact"); const retainedIds = final.work.map(({ workId }) => workId); await ctx.stop(workers[0]); const replay = await snapshot(ctx, api.baseUrl); ctx.equal(replay.work.map(({ workId }) => workId), retainedIds, "terminal Work retained"); return caseResult(ctx, { rolloutId: rollout.json.rolloutId, workKinds: [...new Set(final.work.map(({ kind }) => kind))] });
});

const c02 = defineCase("C-02", "FF-F-WORK claimed crash fixture", "Hold due Compilation and deadline Work at worker.claimed, SIGKILL owners, wait expiry and reclaim with replacements", "Attempts increase, each effect commits once, stale owners cannot commit and no transaction remains open at the held barrier", ["worker recovery barrier", "SIGKILL", "replacement workers", "verification snapshot"], async (ctx) => {
  const family = ctx.fixtures.work(); const { api } = await boot(ctx, { family }); const ready = await createReadyCandidate(ctx, api.baseUrl, family, { label: "c02-ready" }); const rollout = await progressiveActivate(ctx, api.baseUrl, ready.revision.revisionId, 1, [{ candidateExposureBasisPoints: 10_000, minimumEvaluationCount: 2, maximumFailureBasisPoints: 0, observationSeconds: 1 }], { key: ctx.key("c02-rollout") }); await createRevision(ctx, api.baseUrl, family.stringFlag.flagId, family.revisionBody(family.stringFlag, "c02-pending"), { key: ctx.key("c02-pending") }); await ctx.sleep(1_100); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && point === "worker.claimed" }); const owners = [await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }), await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } })]; const claims = await ctx.waitFor(() => { const values = barrier.ledger.filter(({ json }) => json.point === "worker.claimed"); return new Set(values.map(({ json }) => json.workId)).size >= 2 ? values.slice(0, 2) : undefined; }, { label: "two claimed kinds", processes: owners }); const held = await snapshot(ctx, api.baseUrl); ctx.assert("held Work schemas", () => assertWork(held.work, { final: true })); await Promise.all(owners.map((owner) => ctx.kill(owner))); hold = false; await ctx.sleep(3_300); const replacements = [await ctx.startWorker(), await ctx.startWorker()]; const final = await waitSnapshot(ctx, api.baseUrl, (state) => claims.every(({ json }) => state.work.find(({ workId }) => workId === json.workId)?.terminal) ? state : undefined, { label: "claimed replacements drain", processes: replacements }); for (const { json } of claims) ctx.ok(final.work.find(({ workId }) => workId === json.workId).attempt > json.attempt, `${json.workId} attempt increased`); ctx.equal(final.resources.flagSnapshots.map(({ revisionId }) => revisionId).length, new Set(final.resources.flagSnapshots.map(({ revisionId }) => revisionId)).size, "Snapshot effect once"); ctx.equal(final.resources.progressiveRollouts.filter(({ rolloutId }) => rolloutId === rollout.json.rolloutId).length, 1, "deadline effect once"); return caseResult(ctx, { claimedWorkIds: claims.map(({ json }) => json.workId) });
});

const c03 = defineCase("C-03", "FF-F-WORK effect-complete crash fixture", "SIGKILL Compilation and deadline workers after deterministic effect calculation but before commit, then replace them", "Effects are safely recomputed and Snapshot/Rollout/Work/Event identities do not duplicate or hang", ["worker.effect-complete barrier", "SIGKILL", "replacement workers", "verification snapshot"], async (ctx) => {
  const result = await crashBothKinds(ctx, "worker.effect-complete", "c03"); ctx.equal(result.final.resources.flagSnapshots.map(({ revisionId }) => revisionId).length, new Set(result.final.resources.flagSnapshots.map(({ revisionId }) => revisionId)).size, "no duplicate Snapshot"); ctx.assert("recovered Event sequence", () => assertEventSequence(result.final.events)); ctx.ok(result.final.work.every(({ terminal }) => terminal), "no permanent Work"); return caseResult(ctx, { recoveredWorkIds: result.entries.map(({ json }) => json.workId) });
});

const c04 = defineCase("C-04", "FF-F-WORK before-commit crash fixture", "SIGKILL workers at worker.before-commit for Compilation and deadline resolution and recover with replacements", "Each transaction is absent or fully present once with no digest/Snapshot, counter/state or Event fragment", ["worker.before-commit barrier", "SIGKILL", "replacement workers", "verification snapshot"], async (ctx) => {
  const result = await crashBothKinds(ctx, "worker.before-commit", "c04"); for (const revision of result.final.resources.flagRevisions) { const artifact = artifactFor(result.final, revision.revisionId); if (["READY", "ACTIVE", "SUPERSEDED"].includes(revision.state)) { ctx.ok(artifact, `${revision.revisionId} committed Snapshot`); ctx.equal(revision.snapshotDigest, snapshotDigest(artifact), `${revision.revisionId} digest/Snapshot atomic`); } if (revision.state === "REJECTED") ctx.ok(!artifact, `${revision.revisionId} rejected without Snapshot`); } for (const rollout of result.final.resources.progressiveRollouts) { const step = rollout.steps[rollout.currentStepIndex]; ctx.ok(rollout.state !== "RUNNING" || step.state === "OBSERVING", "rollout state/counter transaction complete"); } ctx.assert("transactional Event sequence", () => assertEventSequence(result.final.events)); return caseResult(ctx, { point: "worker.before-commit", work: result.final.work.length });
});

const c05 = defineCase("C-05", "FF-F-WORK expired lease fencing fixture", "Pause worker A beyond lease expiry, let B reclaim and commit, then release A", "The stale owner/token cannot overwrite Revision, Rollout, Work or Events after B completes", ["worker barrier", "lease expiry", "two workers", "verification snapshot"], async (ctx) => {
  const family = ctx.fixtures.work(); const { api } = await boot(ctx, { family }); const response = await createRevision(ctx, api.baseUrl, family.stringFlag.flagId, family.revisionBody(family.stringFlag, "c05"), { key: ctx.key("c05") }); let hold = true; const barrier = await ctx.barrier({ hold: ({ processRole, point }) => hold && processRole === "worker" && point === "worker.claimed" }); const stale = await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const claim = await barrier.waitFor(({ json }) => json.point === "worker.claimed", { processes: [stale] }); await ctx.sleep(3_300); const winner = await ctx.startWorker(); const committed = await waitSnapshot(ctx, api.baseUrl, (state) => state.resources.flagRevisions.find(({ revisionId }) => revisionId === response.json.revisionId)?.state === "READY" ? state : undefined, { label: "replacement fenced commit", processes: [winner] }); hold = false; barrier.releaseAll(); await ctx.sleep(500); const after = await snapshot(ctx, api.baseUrl); ctx.equal(ctx.canonical(after.resources), ctx.canonical(committed.resources), "stale owner cannot overwrite resources", { hardCapIds: ["STALE_WORK_OR_LOST_WORK"] }); ctx.equal(ctx.canonical(after.events), ctx.canonical(committed.events), "stale owner cannot append Event"); const work = after.work.find(({ workId }) => workId === claim.json.workId); ctx.ok(work.attempt > claim.json.attempt && work.terminal, "winner attempt owns terminal Work"); return caseResult(ctx, { workId: work.workId, staleAttempt: claim.json.attempt, finalAttempt: work.attempt });
});

const c06 = defineCase("C-06", "FF-F-WORK obsolete-work convergence fixture", "Make pending Compilation stale and a RUNNING rollout STALE through newer activation, then drain old Work", "Obsolete Work terminates without reviving Revision/Rollout or changing newer routing/counters", ["public activation HTTP", "Compilation/deadline workers", "verification snapshot"], async (ctx) => {
  const family = ctx.fixtures.work(); const { api } = await boot(ctx, { family }); const winner = await createReadyCandidate(ctx, api.baseUrl, family, { label: "c06-winner" }); const staleRevision = await createRevision(ctx, api.baseUrl, family.stringFlag.flagId, family.revisionBody(family.stringFlag, "c06-stale"), { key: ctx.key("c06-stale") }); await activate(ctx, api.baseUrl, winner.revision.revisionId, 1, { key: ctx.key("c06-winner") }); const rolloutCandidate = await createReadyCandidate(ctx, api.baseUrl, family, { label: "c06-rollout", overrides: { expectedActiveRevision: winner.revision.revision } }); const immediate = await createReadyCandidate(ctx, api.baseUrl, family, { label: "c06-immediate", overrides: { expectedActiveRevision: winner.revision.revision } }); const rollout = await progressiveActivate(ctx, api.baseUrl, rolloutCandidate.revision.revisionId, winner.revision.revision, [{ candidateExposureBasisPoints: 10_000, minimumEvaluationCount: 100, maximumFailureBasisPoints: 10_000, observationSeconds: 1 }], { key: ctx.key("c06-rollout") }); await activate(ctx, api.baseUrl, immediate.revision.revisionId, winner.revision.revision, { key: ctx.key("c06-immediate") }); await ctx.sleep(1_100); const workers = [await ctx.startWorker(), await ctx.startWorker()]; const final = await waitSnapshot(ctx, api.baseUrl, (state) => state.work.every(({ terminal }) => terminal) && state.resources.flagRevisions.find(({ revisionId }) => revisionId === staleRevision.json.revisionId)?.state === "REJECTED" && state.resources.progressiveRollouts.find(({ rolloutId }) => rolloutId === rollout.json.rolloutId)?.state === "STALE" ? state : undefined, { label: "obsolete Work convergence", processes: workers }); ctx.equal(final.resources.flagRevisions.find(({ revisionId }) => revisionId === immediate.revision.revisionId).state, "ACTIVE", "newer activation remains active"); ctx.equal(final.resources.progressiveRollouts.find(({ rolloutId }) => rolloutId === rollout.json.rolloutId).state, "STALE", "rollout not revived"); ctx.equal(final.work.filter(({ terminal }) => !terminal).length, 0, "no immortal backlog"); return caseResult(ctx, { staleRevisionId: staleRevision.json.revisionId, staleRolloutId: rollout.json.rolloutId });
});

const c07 = defineCase("C-07", "FF-F-EVENT unknown-ACK fixture", "Persist an exact event request, pause dispatcher after receiver response, SIGKILL, exercise 500/disconnect and retry with replacement", "Retries preserve eventId/type/body and successful per-aggregate order; ACK never invents a new event identity", ["webhook receiver", "dispatcher.response-received barrier", "SIGKILL", "replacement dispatcher"], async (ctx) => {
  const family = ctx.fixtures.event(); const { api } = await boot(ctx, { family }); const candidate = await createReadyCandidate(ctx, api.baseUrl, family, { label: "c07" }); await activate(ctx, api.baseUrl, candidate.revision.revisionId, 1, { key: ctx.key("c07-activate") }); let mode = "success"; const receiver = await ctx.receiver({ behavior: () => mode === "success" ? { status: 204 } : mode === "disconnect" ? { disconnect: true } : { status: 500 } }); const barrier = await ctx.barrier({ hold: ({ processRole, point }) => processRole === "dispatcher" && point === "dispatcher.response-received" }); const dispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url, env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const paused = await barrier.waitFor(({ json }) => json.point === "dispatcher.response-received", { processes: [dispatcher] }); await ctx.kill(dispatcher); mode = "failure"; const retrying = await ctx.startDispatcher({ webhookUrl: receiver.url }); await ctx.waitFor(() => receiver.ledger.length >= 2 ? receiver.ledger : undefined, { label: "500 retry", processes: [retrying] }); mode = "disconnect"; await ctx.waitFor(() => receiver.ledger.length >= 3 ? receiver.ledger : undefined, { label: "disconnect retry", processes: [retrying] }); mode = "success"; const delivered = await ctx.waitFor(() => receiver.ledger.filter(({ acknowledged }) => acknowledged).length >= 1 ? receiver.ledger : undefined, { label: "replacement ACK", timeoutMs: 120_000, processes: [retrying] }); const same = delivered.filter(({ headers }) => headers["x-flagfoundry-event-id"] === paused.json.aggregateId || headers["x-flagfoundry-event-id"]); const byId = new Map(); for (const entry of delivered) { const id = entry.headers["x-flagfoundry-event-id"]; if (!id) continue; const prior = byId.get(id); if (prior) { ctx.equal(entry.raw, prior.raw, `${id} retry body stable`); ctx.equal(entry.headers["x-flagfoundry-event-type"], prior.headers["x-flagfoundry-event-type"], `${id} type stable`); } else byId.set(id, entry); } ctx.ok(same.length > 0, "dispatcher sent public event headers"); const state = await snapshot(ctx, api.baseUrl); ctx.equal(new Set(state.events.map(({ eventId }) => eventId)).size, state.events.length, "no new event identity on ACK", { hardCapIds: ["EVENT_TRANSACTIONALITY"] }); return caseResult(ctx, { requests: delivered.length, eventIds: [...byId.keys()] });
});

const c08 = defineCase("C-08", "FF-F-EVENT transactional transition/recovery fixture", "Crash Compilation and rollout-deadline commits, activate a recovered Revision and dispatch all published V1 transitions", "The four literal V1 events are transactionally paired, rollback has none, aggregate sequences are contiguous and Manager adds no invented event", ["worker/dispatcher barriers", "SIGKILL", "public transitions", "verification snapshot"], async (ctx) => {
  const result = await crashBothKinds(ctx, "worker.before-commit", "c08"); const family = result.family; const ready = result.final.resources.flagRevisions.find(({ state }) => state === "READY"); if (ready) await activate(ctx, result.api.baseUrl, ready.revisionId, 1, { key: ctx.key("c08-activate") }); for (const worker of result.replacements) await ctx.stop(worker); await checkStandaloneStepEvents(ctx, result.api.baseUrl, family); const state = await snapshot(ctx, result.api.baseUrl); ctx.assert("all events exact V1", () => state.events.forEach(assertDomainEvent)); ctx.assert("contiguous event sequences", () => assertEventSequence(state.events)); const allowed = new Set(["flag.compilation-started", "flag.revision-rejected", "flag.revision-activated", "flag.revision-superseded"]); ctx.ok(state.events.every(({ type }) => allowed.has(type)), "no invented Manager event"); for (const event of state.events) { if (event.type === "flag.compilation-started") ctx.ok(state.resources.flagRevisions.some(({ revisionId }) => revisionId === event.aggregateId), "compilation Event has committed Revision"); if (event.type === "flag.revision-rejected") ctx.equal(state.resources.flagRevisions.find(({ revisionId }) => revisionId === event.aggregateId)?.state, "REJECTED", "rejection Event paired"); }
  const receiver = await ctx.receiver(); const dispatcher = await ctx.startDispatcher({ webhookUrl: receiver.url }); await ctx.waitFor(() => receiver.ledger.filter(({ acknowledged }) => acknowledged).length >= state.events.length ? receiver.ledger : undefined, { label: "transactional events delivered", timeoutMs: 120_000, processes: [dispatcher] }); return caseResult(ctx, { eventTypes: [...new Set(state.events.map(({ type }) => type))], family: family.fixtureFamily });
});

async function crashBothKinds(ctx, point, label) {
  const family = ctx.fixtures.work(); const { api } = await boot(ctx, { family }); const candidate = await createReadyCandidate(ctx, api.baseUrl, family, { label: `${label}-ready` }); const rollout = await progressiveActivate(ctx, api.baseUrl, candidate.revision.revisionId, 1, [{ candidateExposureBasisPoints: 10_000, minimumEvaluationCount: 2, maximumFailureBasisPoints: 0, observationSeconds: 1 }], { key: ctx.key(`${label}-rollout`) }); await createRevision(ctx, api.baseUrl, family.stringFlag.flagId, family.revisionBody(family.stringFlag, `${label}-pending`, { expectedActiveRevision: 1 }), { key: ctx.key(`${label}-pending`) }); await ctx.sleep(1_100); const barrier = await ctx.barrier({ hold: ({ processRole, point: actual }) => processRole === "worker" && actual === point }); const owners = [await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }), await ctx.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } })]; const entries = await ctx.waitFor(() => { const matches = barrier.ledger.filter(({ json }) => json.point === point); return new Set(matches.map(({ json }) => json.workId)).size >= 2 ? matches.slice(0, 2) : undefined; }, { label: `${point} two kinds`, timeoutMs: 120_000, processes: owners }); const before = await snapshot(ctx, api.baseUrl); await Promise.all(owners.map((owner) => ctx.kill(owner))); await ctx.sleep(3_300); const replacements = [await ctx.startWorker(), await ctx.startWorker()]; const final = await waitSnapshot(ctx, api.baseUrl, (state) => entries.every(({ json }) => state.work.find(({ workId }) => workId === json.workId)?.terminal) ? state : undefined, { label: `${point} recovered`, processes: replacements }); for (const entry of entries) ctx.ok(final.work.find(({ workId }) => workId === entry.json.workId).attempt > entry.json.attempt, `${entry.json.workId} reclaimed`); ctx.assert("recovered deadline keeps prior ACTIVE and candidate READY", () => assertRolloutAuthority(final, rollout.json.rolloutId, { expectedState: "ROLLED_BACK" }), { hardCapIds: ["ROLLOUT_AUTHORITY", "STALE_WORK_OR_LOST_WORK"] }); return { family, api, rollout, entries, before, final, replacements };
}

export const C_CASES = Object.freeze([c01, c02, c03, c04, c05, c06, c07, c08]);
