// Policy revision: learning-final-system-2026-09-08.1. One FINAL submission; current public operations, persistence and restart recovery, not a historical binary upgrade.
import assert from "node:assert/strict";

import { documentDigest } from "../oracles/index.mjs";
import {
  applyChange, assertBranch, assertChange, assertDocument, assertRevision, assertSnapshot, createDocument,
  expectError, finalEvidence, getJson, guardedCase, prepare, resource, runWindow,
  waitForDrain, writeMillionOperationSeed,
} from "./helpers.mjs";

const E01 = guardedCase({
  id: "E-01",
  fixtureFamily: "MB-F-base-system-FINAL-reinitialization",
  action: "Create base-system history, conflict, saved replay and leased Snapshot Work, then reinitialize the same database to FINAL.",
  oracle: "Compare current Document and Branch identities, immutable revisions, saved response and reclaimed Snapshot Work across FINAL restart.",
  async run(ctx) {
    const initialRuntime = ctx; await initialRuntime.npm("build"); await initialRuntime.migrate(); let api = await initialRuntime.startApi(); const a = ctx.fixtures.block("e01:a", "a"); const b = ctx.fixtures.block("e01:b", "b"); const document = await createDocument(ctx, api.baseUrl, { title: "base-system reinitialization", blocks: [a, b] }, { key: ctx.key("e01:document") }); const body = { clientId: ctx.uuid("e01:client"), clientSequence: 1, baseRevision: 0, operations: [{ op: "REPLACE", blockId: a.blockId, expectedText: "a", newText: "a1" }] }; const savedKey = ctx.key("e01:saved"); const saved = await applyChange(ctx, api.baseUrl, document.documentId, body, { key: savedKey }); const conflicting = await applyChange(ctx, api.baseUrl, document.documentId, { clientId: ctx.uuid("e01:conflict-client"), clientSequence: 1, baseRevision: 0, operations: [{ op: "REPLACE", blockId: a.blockId, expectedText: "a", newText: "bad" }] }, { key: ctx.key("e01:conflict"), allowFailure: true }); expectError(ctx, conflicting, 409, "CHANGE_CONFLICT", "base-system conflict");
    const barrier = await ctx.barrier({ hold: ({ point }) => point === "worker.claimed" }); const worker = await initialRuntime.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }); const held = await barrier.waitFor(({ json }) => json?.point === "worker.claimed" && json?.aggregateId === document.documentId, { timeoutMs: 120_000, processes: [worker] }); const before = await ctx.snapshot(api.baseUrl); const beforeBranches = await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/branches`, "current Branches before restart"); const legacyDocument = assertDocument(await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}`, "base-system Document")); const legacyRevision = assertRevision(await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/revisions/1`, "base-system revision"), { legacy: true });
    await ctx.kill(worker); await ctx.kill(api); const final = await prepare(ctx); await final.migrate(); api = await final.startApi(); const migratedDocument = assertDocument(await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}`, "retained legacy Document")); ctx.equal(migratedDocument, legacyDocument, "legacy Document body survives reinitialization", { hardCapIds: ["MIGRATION_COMPATIBILITY"] }); const migratedRevision = assertRevision(await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/revisions/1`, "retained legacy revision"), { legacy: true }); ctx.equal(migratedRevision, legacyRevision, "legacy revision body survives reinitialization", { hardCapIds: ["MIGRATION_COMPATIBILITY"] }); const replay = await applyChange(ctx, api.baseUrl, document.documentId, body, { key: savedKey }); ctx.equal(replay, saved, "saved idempotency response is byte-semantic stable", { hardCapIds: ["MIGRATION_COMPATIBILITY", "CLIENT_IDENTITY"] });
    const branches = await getJson(ctx, api.baseUrl, `/api/v1/documents/${document.documentId}/branches`, "retained Branches"); ctx.equal(branches, beforeBranches, "current Branch identities remain exact across restart"); for (const branch of branches) assertBranch(branch); const replacement = await final.startWorker(); const after = assertSnapshot(ctx, await waitForDrain(ctx, api.baseUrl, { processes: [replacement], timeoutMs: 120_000 })); const migratedChanges = resource(after, "changes").filter(({ documentId }) => documentId === document.documentId); for (const change of resource(before, "changes")) ctx.equal(migratedChanges.find(({ changeId }) => changeId === change.changeId), change, "current Change identity and Branch association retained"); const migratedRevisions = resource(after, "documentRevisions").filter(({ documentId }) => documentId === document.documentId); for (const revision of resource(before, "documentRevisions")) ctx.equal(migratedRevisions.find((item) => item.documentId === revision.documentId && item.revision === revision.revision && item.branchId === revision.branchId), revision, "immutable current revision retains Branch association"); const beforeEvents = new Map(before.events.map((event) => [event.eventId, event])); for (const [eventId, event] of beforeEvents) ctx.equal(after.events.find((item) => item.eventId === eventId), event, `Event ${eventId} survives reinitialization`, { hardCapIds: ["MIGRATION_COMPATIBILITY"] }); const migratedWork = after.work.find(({ workId }) => workId === held.json.workId); ctx.ok(migratedWork?.terminal && migratedWork.attempt >= 2, "pending base-system Work preserves identity and is reclaimed");
    return finalEvidence(ctx, { branchIds: branches.map(({ branchId }) => branchId), changes: migratedChanges.length, preservedEvents: beforeEvents.size, reclaimedWorkId: migratedWork.workId });
  },
}, ["MIGRATION_COMPATIBILITY"]);

async function createLoadDocuments(ctx, apis, prefix, count) {
  return ctx.concurrent(Array.from({ length: count }, (_, index) => index), Math.min(64, count), async (index) => { const block = ctx.fixtures.block(`${prefix}:block:${index}`, "x".repeat(64)); const document = await createDocument(ctx, apis[index % apis.length].baseUrl, { title: `${prefix}-${index}`, blocks: [block] }, { key: ctx.key(`${prefix}:document:${index}`) }); return { document, block, revision: 0, text: block.text, sequence: 0, clientId: ctx.uuid(`${prefix}:client:${index}`) }; });
}

async function changeLoad(ctx, apis, states, seconds, prefix) {
  return runWindow({ clients: 64, seconds, operation: async (index, client) => { const state = states[client]; const next = `${prefix}-${String(state.sequence + 1).padStart(12, "0")}`.padEnd(64, "x").slice(0, 64); const response = await ctx.mutate(apis[client % apis.length].baseUrl, `/api/v1/documents/${state.document.documentId}/changes`, ctx.key(`${prefix}:${client}:${state.sequence + 1}`), { clientId: state.clientId, clientSequence: state.sequence + 1, baseRevision: state.revision, operations: [{ op: "REPLACE", blockId: state.block.blockId, expectedText: state.text, newText: next }] }); if (response.status === 201) { assertChange(response.json, { legacy: true }); state.sequence += 1; state.revision = response.json.revision; state.text = next; } return response; } });
}

const E02 = guardedCase({
  id: "E-02",
  fixtureFamily: "MB-F-PERF-CHANGE-APPLY",
  action: "Run disjoint 64-client ten-second warm-up and sixty-second non-overlapping Change measurement sets.",
  oracle: "Recompute every final Document digest, client sequence, gapless revision and Event count after measuring full bodies.",
  async run(ctx) {
    const target = await prepare(ctx); const apis = [await target.startApi(), await target.startApi()]; const warm = await createLoadDocuments(ctx, apis, "warm", 64); const measured = await createLoadDocuments(ctx, apis, "measured", 64); const warmResult = await changeLoad(ctx, apis, warm, 10, "warm-change"); ctx.ok((warmResult.statuses.get(500) ?? 0) === 0, "warm-up has no unexpected 5xx"); const result = await changeLoad(ctx, apis, measured, 60, "measured-change"); const successes = result.statuses.get(201) ?? 0; ctx.equal(successes, result.completed, "every measured Change is APPLIED"); ctx.ok(result.throughput >= 300, `Change throughput ${result.throughput.toFixed(2)} >= 300`); ctx.ok(result.p95Ms <= 250, `Change p95 ${result.p95Ms.toFixed(2)} <= 250ms`);
    for (const state of measured) { const current = assertDocument(await getJson(ctx, apis[0].baseUrl, `/api/v1/documents/${state.document.documentId}`, "post-load Document")); ctx.equal(current.headRevision, state.revision, "post-load revision is gapless", { hardCapIds: ["DOCUMENT_ATOMICITY"] }); ctx.equal(current.canonicalDigest, documentDigest(current.documentId, current.headRevision, current.blocks), "post-load digest closes"); }
    const snapshot = await ctx.snapshot(apis[0].baseUrl, { timeoutMs: 120_000 }); const measuredIds = new Set(measured.map(({ document }) => document.documentId)); const changes = resource(snapshot, "changes").filter(({ documentId, state }) => measuredIds.has(documentId) && state === "APPLIED"); ctx.equal(changes.length, successes, "post-load Change count equals successful responses", { hardCapIds: ["DOCUMENT_ATOMICITY"] }); ctx.equal(snapshot.events.filter(({ aggregateId, type }) => measuredIds.has(aggregateId) && type === "document.changed").length, successes, "post-load event count equals successful Changes");
    return finalEvidence(ctx, { durationSeconds: result.durationSeconds, successes, throughput: result.throughput, p95Ms: result.p95Ms });
  },
}, ["DOCUMENT_ATOMICITY"]);

async function seedRevisionRead(ctx, apis) {
  const states = await createLoadDocuments(ctx, apis, "revision-read", 64); const identities = [];
  for (const state of states) { identities.push({ documentId: state.document.documentId, revision: 0 }); for (let revision = 1; revision <= 10; revision += 1) { const next = `revision-${revision}`; await applyChange(ctx, apis[revision % apis.length].baseUrl, state.document.documentId, { clientId: state.clientId, clientSequence: revision, baseRevision: revision - 1, operations: [{ op: "REPLACE", blockId: state.block.blockId, expectedText: state.text, newText: next }] }, { key: ctx.key(`revision-read:${state.document.documentId}:${revision}`) }); state.text = next; identities.push({ documentId: state.document.documentId, revision }); } }
  return identities.sort((left, right) => Buffer.from(left.documentId).compare(Buffer.from(right.documentId)) || left.revision - right.revision);
}

async function revisionReadLoad(ctx, apis, identities, seconds) { let mismatches = 0; return { result: await runWindow({ clients: 64, seconds, operation: async (index, client) => { const identity = identities[(index + client) % identities.length]; const response = await ctx.request(apis[client % apis.length].baseUrl, `/api/v1/documents/${identity.documentId}/revisions/${identity.revision}`); if (response.status === 200) { try { const revision = assertRevision(response.json, { legacy: true }); if (revision.documentId !== identity.documentId || revision.revision !== identity.revision || revision.canonicalDigest !== documentDigest(revision.documentId, revision.revision, revision.blocks)) mismatches += 1; } catch { mismatches += 1; } } return response; } }), get mismatches() { return mismatches; } }; }

const E03 = guardedCase({
  id: "E-03",
  fixtureFamily: "MB-F-PERF-REVISION-READ",
  action: "Round-robin every seeded immutable revision with exactly 64 clients for ten warm-up and sixty measured seconds.",
  oracle: "Recompute every response digest and provenance identity so current-head substitution cannot satisfy the workload.",
  async run(ctx) {
    const target = await prepare(ctx); const apis = [await target.startApi(), await target.startApi()]; const identities = await seedRevisionRead(ctx, apis); const warm = await revisionReadLoad(ctx, apis, identities, 10); ctx.equal(warm.mismatches, 0, "warm-up revision bodies are valid"); const measured = await revisionReadLoad(ctx, apis, identities, 60); const successes = measured.result.statuses.get(200) ?? 0; ctx.equal(successes, measured.result.completed, "every measured revision read succeeds"); ctx.equal(measured.mismatches, 0, "no measured digest or provenance mismatch"); ctx.ok(measured.result.throughput >= 400, `revision throughput ${measured.result.throughput.toFixed(2)} >= 400`); ctx.ok(measured.result.p95Ms <= 120, `revision p95 ${measured.result.p95Ms.toFixed(2)} <= 120ms`);
    return finalEvidence(ctx, { identities: identities.length, successes, throughput: measured.result.throughput, p95Ms: measured.result.p95Ms });
  },
}, ["SNAPSHOT_INTEGRITY"]);

const E04 = guardedCase({
  id: "E-04",
  fixtureFamily: "MB-F-PERF-MILLION-SNAPSHOT",
  action: "Import exactly ten thousand Documents and one million Changes, kill two claimed workers, then start two replacements.",
  oracle: "Stream-audit ten thousand terminal Work and Snapshots covering exactly one million retained operations with matching digests.",
  async run(ctx) {
    const target = await prepare(ctx); const seedPath = await writeMillionOperationSeed(ctx); await target.seedFile(seedPath, { timeoutMs: 1_800_000 }); const api = await target.startApi(); const barrier = await ctx.barrier({ hold: ({ point }) => point === "worker.claimed" }); const originals = [await target.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } }), await target.startWorker({ env: { TEST_BARRIER_URL: barrier.url, TEST_BARRIER_TOKEN: barrier.token } })]; await ctx.waitFor(() => new Set(barrier.ledger.filter(({ json }) => json?.point === "worker.claimed").map(({ json }) => json.workId)).size >= 2, { timeoutMs: 120_000, label: "two distinct claimed Snapshot tasks", processes: originals }); const claimed = barrier.ledger.filter(({ json }) => json?.point === "worker.claimed").slice(0, 2).map(({ json }) => json); await Promise.all(originals.map((worker) => ctx.kill(worker))); const leaseDeadline = Math.max(...(await ctx.snapshot(api.baseUrl, { timeoutMs: 120_000 })).work.filter(({ workId }) => claimed.some((item) => item.workId === workId)).map(({ leaseExpiresAt }) => Date.parse(leaseExpiresAt))); await ctx.waitFor(() => Date.now() > leaseDeadline, { timeoutMs: 10_000, intervalMs: 50, label: "captured worker leases to expire" }); const startedAt = performance.now(); const replacements = [await target.startWorker(), await target.startWorker()]; const snapshot = await waitForDrain(ctx, api.baseUrl, { processes: replacements, timeoutMs: 120_000, intervalMs: 5_000, requestTimeoutMs: 120_000, label: "million-operation compaction" }); const elapsedMs = performance.now() - startedAt; ctx.ok(elapsedMs <= 120_000, `compaction recovery ${elapsedMs.toFixed(0)}ms <= 120000ms`); assertSnapshot(ctx, snapshot); const snapshots = resource(snapshot, "documentSnapshots"); ctx.equal(snapshots.length, 10_000, "exactly ten thousand verified Snapshots", { hardCapIds: ["SNAPSHOT_INTEGRITY"] }); const changes = resource(snapshot, "changes"); ctx.equal(changes.length, 1_000_000, "all one million Changes remain retained", { hardCapIds: ["SNAPSHOT_INTEGRITY"] }); ctx.equal(changes.reduce((sum, change) => sum + change.operations.length, 0), 1_000_000, "Snapshots cover one million operations"); ctx.equal(snapshot.work.filter(({ terminal }) => !terminal).length, 0, "no Snapshot Work remains nonterminal"); for (const item of claimed) { const work = snapshot.work.find(({ workId }) => workId === item.workId); ctx.ok(work?.terminal && work.attempt >= 2, `claimed Work ${item.workId} is fenced and reclaimed`); }
    return finalEvidence(ctx, { elapsedMs, documents: 10_000, operations: 1_000_000, snapshots: snapshots.length, workers: 2 });
  },
}, ["SNAPSHOT_INTEGRITY"]);

export const E_CASES = Object.freeze([E01, E02, E03, E04]);
